const $=s=>document.querySelector(s),main=$('#main'),nav=$('#mainNav'),toc=$('#tocBox'),searchInput=$('#searchInput');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
let manifest;const packs=new Map(),articles=new Map();
async function packed(name){const r=await fetch(`data/${name}`);if(!r.ok)throw Error(`${name}: ${r.status}`);const raw=atob((await r.text()).trim()),u8=Uint8Array.from(raw,c=>c.charCodeAt(0));if(!window.DecompressionStream)throw Error('Navigateur trop ancien pour lire les données compressées.');const stream=new Blob([u8]).stream().pipeThrough(new DecompressionStream('gzip'));return JSON.parse(await new Response(stream).text())}
async function loadPack(name){if(packs.has(name))return packs.get(name);const p=packed(name).then(rows=>{rows.forEach(a=>articles.set(a.id,a));return rows});packs.set(name,p);return p}
const meta=id=>manifest.articles.find(a=>a.id===id);async function article(id){if(articles.has(id))return articles.get(id);const m=meta(id);if(!m)return null;await loadPack(m.file);return articles.get(id)||null}
async function allArticles(){await Promise.all([...new Set(manifest.articles.map(a=>a.file))].map(loadPack));return [...articles.values()]}
const status=s=>manifest.statusLabels[s]||s||'';const badgeClass=s=>s==='canon_recent'?'canon':s==='source_detaillee'?'source':s==='obsolete'?'obsolete':'';
function navHtml(active){const count={};manifest.articles.forEach(a=>count[a.category]=(count[a.category]||0)+1);nav.innerHTML=`<a class="${active==='home'?'active':''}" href="#/home">Accueil du Compendium</a><hr>${manifest.categories.map(c=>`<a class="${active===c?'active':''}" href="#/category/${encodeURIComponent(c)}"><span>${esc(c)}</span><span class="count">${count[c]||0}</span></a>`).join('')}<hr><a class="${active==='search'?'active':''}" href="#/search">Recherche globale</a><a href="../character-builder/">Créer un personnage</a><a href="../">Portail TUC</a>`}
function flat(a){const x=[a.title,...(a.tags||[])];for(const s of a.sections||[]){x.push(s.title||'');for(const b of s.blocks||[]){if(b.type==='p')x.push(b.text);else if(b.type==='table')for(const r of b.rows||[])x.push(...r)}}return x.join(' ')}
const terms=['Grande Californie','Los Angeles','LAUS','CBII','CNAD','Pègre','Crawlers','Underlife','corporations','Neurodive','Voile','Hologramme','Ombremonde','Vampires','Garous','Mages','Aseryns','Exilés','Extrals','Angelus','Daemons','Chasseurs','Fléaux','Revenants'];
function linkify(v){let out=esc(v);for(const t of terms){const rx=new RegExp(`\\b(${t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')})\\b`,'gi');out=out.replace(rx,m=>`<a class="wiki-link" href="#/search?q=${encodeURIComponent(t)}">${m}</a>`)}return out}
function block(b){if(b.type==='table')return `<div class="doc-table-wrap"><table class="doc-table">${(b.rows||[]).map(r=>`<tr>${r.map(c=>`<td>${linkify(c)}</td>`).join('')}</tr>`).join('')}</table></div>`;const st=(b.style||'').toLowerCase(),cl=st.includes('list')?' list':st.includes('lore')?' lore':st.includes('spec')?' spec':'';return `<p class="body-p${cl}">${linkify(b.text||'')}</p>`}
function section(s){const lv=Math.max(2,Math.min(5,+s.level||3)),body=(s.blocks||[]).map(block).join('');if(s.status==='obsolete')return `<section id="${esc(s.id)}" class="section obsolete-block"><strong>${esc(s.title)} — obsolète / ne pas utiliser</strong>${body}</section>`;const html=`<section id="${esc(s.id)}" class="section"><h${lv}>${esc(s.title)}</h${lv}>${body}</section>`;return s.audience==='mj'?`<details class="mj-block"><summary>${esc(s.title)}</summary><div class="mj-inner">${html}</div></details>`:html}
function badges(a){return `<div class="meta"><span class="badge ${badgeClass(a.status)}">${esc(status(a.status))}</span>${a.audience==='mj'?'<span class="badge mj">Contenu MJ</span>':''}${(a.tags||[]).slice(0,5).map(t=>`<span class="badge">${esc(t)}</span>`).join('')}</div>`}
function pageHead(a){return `<div class="page-head"><div class="eyebrow">${esc(a.category)}</div><h1>${esc(a.title)}</h1>${badges(a)}</div>`}
function sourceBox(a){return `<div class="source-box"><strong>Source :</strong> ${esc(a.source)}<br>${a.status==='source_detaillee'?'Lore détaillé servant de matière encyclopédique ; les décisions récentes priment uniquement lorsqu’elles ont réellement statué autrement.':'Corpus récent servant de contrôle canonique actuel.'}</div>`}
function related(a){const txt=norm(flat(a)),same=manifest.articles.filter(x=>x.id!==a.id&&x.audience!=='mj').map(x=>{let n=x.category===a.category?.25:0;const t=norm(x.title).replace(/^\d+\s+/,'');if(t.length>4&&txt.includes(t))n+=5;for(const z of x.tags||[])if((a.tags||[]).map(norm).includes(norm(z)))n++;return[n,x]}).filter(x=>x[0]>1).sort((a,b)=>b[0]-a[0]).slice(0,8).map(x=>x[1]);return same.length?`<section class="related"><h2>Voir aussi</h2><div class="related-links">${same.map(x=>`<a href="#/article/${encodeURIComponent(x.id)}">${esc(x.title)}</a>`).join('')}</div></section>`:''}
function home(){navHtml('home');toc.innerHTML='';const c={};manifest.articles.forEach(a=>c[a.category]=(c[a.category]||0)+1);main.innerHTML=`<div class="page-head"><div class="eyebrow">BASE DOCUMENTAIRE TUC</div><h1>Compendium</h1><p>Une base navigable construite à partir du lore détaillé, puis contrôlée et corrigée par les livres cross-audités récents lorsqu’une décision a été statuée depuis.</p></div><div class="notice"><strong>Première tranche :</strong> le moteur documentaire est en place. Les documents sont découpés en blocs stables pour pouvoir les enrichir, les relier et arbitrer les conflits sans réécrire toute la base.</div><div class="category-grid">${manifest.categories.map(k=>`<a class="category-card" href="#/category/${encodeURIComponent(k)}"><strong>${esc(k)}</strong><p>${k==='Règles'?'Résolution, profil, combat, santé et stress.':k==='Réalité'?'Grande Californie, institutions, organisations et société visible.':k==='Vérité'?'Voile, Ombremonde, peuples, chasse et surnaturel.':k==='Organisations'?'Gouvernement, agences et dossiers détaillés de factions.':'Profils de jeu, PNJ et créatures.'}</p><span class="count">${c[k]||0} entrées →</span></a>`).join('')}</div>`}
function category(k){navHtml(k);toc.innerHTML='';const a=manifest.articles.filter(x=>x.category===k);main.innerHTML=`<div class="page-head"><div class="eyebrow">COMPENDIUM</div><h1>${esc(k)}</h1><p>${a.length} entrées dans cette première tranche.</p></div><div class="article-list">${a.map(x=>`<a class="article-card" href="#/article/${encodeURIComponent(x.id)}"><h3>${esc(x.title)}</h3><p>${esc(x.source)} · ${esc(status(x.status))}${x.audience==='mj'?' · MJ':''}</p></a>`).join('')}</div>`}
async function showArticle(id,anchor){const a=await article(id);if(!a){main.innerHTML='<div class="empty">Article introuvable.</div>';return}navHtml(a.category);toc.innerHTML=`<div class="toc-title">Sur cette page</div><div class="toc-links">${(a.sections||[]).filter(s=>s.title).slice(0,80).map(s=>`<a href="#${esc(s.id)}">${esc(s.title)}</a>`).join('')}</div>`;const body=`${sourceBox(a)}${(a.sections||[]).map(section).join('')}${related(a)}`;main.innerHTML=a.audience==='mj'?`${pageHead(a)}<details class="mj-block"><summary>Afficher le contenu MJ de cette page</summary><div class="mj-inner">${body}</div></details>`:`${pageHead(a)}${body}`;if(anchor)setTimeout(()=>document.getElementById(anchor)?.scrollIntoView(),30)}
function excerpt(a,q){const nq=norm(q);for(const s of a.sections||[])for(const b of s.blocks||[])if(b.type==='p'&&norm(b.text).includes(nq))return{s,text:b.text};return{s:null,text:flat(a).slice(0,220)}}
async function search(q=''){navHtml('search');toc.innerHTML='';searchInput.value=q;main.innerHTML=`<div class="page-head"><div class="eyebrow">RECHERCHE GLOBALE</div><h1>${q?esc(q):'Rechercher dans TUC'}</h1><p>Recherche dans les titres, paragraphes et tableaux des sources intégrées.</p></div>${q?'<div class="loading">Recherche…</div>':'<div class="empty">Saisissez un terme dans la barre supérieure.</div>'}`;if(!q)return;const words=norm(q).split(' ').filter(Boolean),all=await allArticles(),res=[];for(const a of all){const txt=norm(flat(a));if(!words.every(w=>txt.includes(w)))continue;let score=words.reduce((n,w)=>n+(norm(a.title).includes(w)?8:0)+(norm((a.tags||[]).join(' ')).includes(w)?3:0),0);res.push([score,a])}res.sort((a,b)=>b[0]-a[0]||a[1].title.localeCompare(b[1].title,'fr'));main.innerHTML=`<div class="page-head"><div class="eyebrow">RECHERCHE GLOBALE</div><h1>${esc(q)}</h1><p>${res.length} résultat${res.length>1?'s':''}.</p></div><div class="search-results">${res.slice(0,120).map(([,a])=>{const ex=excerpt(a,q),href=`#/article/${encodeURIComponent(a.id)}${ex.s?'@'+encodeURIComponent(ex.s.id):''}`;return `<a class="search-result" href="${href}"><div class="crumb">${esc(a.category)} · ${a.audience==='mj'?'MJ · ':''}${esc(status(a.status))}</div><h3>${esc(a.title)}</h3><p>${esc(ex.text.slice(0,280))}</p></a>`}).join('')||'<div class="empty">Aucun résultat.</div>'}</div>`}
async function router(){const r=location.hash.slice(1)||'/home';if(r.startsWith('/article/')){let x=decodeURIComponent(r.slice(9)),anchor='';if(x.includes('@'))[x,anchor]=x.split('@',2);return showArticle(x,anchor)}if(r.startsWith('/category/'))return category(decodeURIComponent(r.slice(10)));if(r.startsWith('/search'))return search(new URLSearchParams(r.split('?')[1]||'').get('q')||'');return home()}
$('#globalSearch').addEventListener('submit',e=>{e.preventDefault();location.hash=`/search?q=${encodeURIComponent(searchInput.value.trim())}`});window.addEventListener('hashchange',router);
(async()=>{manifest=await packed('manifest.json.gz.b64');await router()})().catch(e=>{console.error(e);main.innerHTML=`<div class="empty">Impossible de charger le Compendium : ${esc(e.message)}</div>`});
