const $=s=>document.querySelector(s);const main=$('#main'),toc=$('#tocBox'),nav=$('#mainNav'),searchInput=$('#searchInput');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
let manifest=null;const fileCache=new Map(),articleCache=new Map();
const statusClass=s=>s==='canon_recent'?'canon':s==='source_detaillee'?'source':s==='obsolete'?'obsolete':'';
const statusLabel=s=>manifest?.statusLabels?.[s]||s||'';
function routeTo(x){location.hash=x.startsWith('#')?x:'#'+x}
function articleMeta(id){return manifest.articles.find(a=>a.id===id)}
async function loadPacked(file){const r=await fetch(`data/${file}`);if(!r.ok)throw new Error(file);const b64=(await r.text()).trim();const bin=atob(b64),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);if(!('DecompressionStream' in window))throw new Error('Ce navigateur ne prend pas en charge la décompression du Compendium.');const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));return JSON.parse(await new Response(stream).text())}
async function loadFile(file){if(fileCache.has(file))return fileCache.get(file);const p=loadPacked(file);fileCache.set(file,p);const data=await p;data.forEach(a=>articleCache.set(a.id,a));return data}
async function loadArticle(id){if(articleCache.has(id))return articleCache.get(id);const m=articleMeta(id);if(!m)return null;await loadFile(m.file);return articleCache.get(id)||null}
async function loadAll(){await Promise.all(Object.values(manifest.sets).flat().map(loadFile));return [...articleCache.values()]}
function renderNav(active=''){const counts={};manifest.articles.forEach(a=>counts[a.category]=(counts[a.category]||0)+1);nav.innerHTML=`<a href="#/home" class="${active==='home'?'active':''}">Accueil</a><hr>${manifest.categories.map(c=>`<a href="#/category/${encodeURIComponent(c)}" class="${active===c?'active':''}"><span>${esc(c)}</span><span class="count">${counts[c]||0}</span></a>`).join('')}<hr><a href="#/search" class="${active==='search'?'active':''}">Recherche globale</a>`}
function metaBadges(a){return `<div class="meta"><span class="badge ${statusClass(a.status)}">${esc(statusLabel(a.status))}</span>${a.audience==='mj'?'<span class="badge mj">Contenu MJ</span>':''}${(a.tags||[]).filter(Boolean).slice(0,5).map(t=>`<span class="badge">${esc(t)}</span>`).join('')}</div>`}
function setToc(html=''){toc.innerHTML=html}
function flattenText(a){const bits=[a.title,...(a.tags||[])];for(const s of a.sections||[]){bits.push(s.title||'');for(const b of s.blocks||[]){if(b.type==='p')bits.push(b.text);else if(b.type==='table')b.rows.forEach(r=>bits.push(...r))}}return bits.join(' ')}
const linkTerms=['Grande Californie','Los Angeles','LAUS','CBII','CNAD','Pègre','Crawlers','Underlife','corporations','Neurodive','Voile','Hologramme','Ombremonde','Vampires','Garous','Mages','Aseryns','Exilés','Extrals','Angelus','Daemons','Chasseurs','Fléaux','Revenants'];
function linkify(raw){let out=esc(raw);for(const term of linkTerms){const re=new RegExp(`\\b(${term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')})\\b`,'gi');out=out.replace(re,m=>`<a class="wiki-link" href="#/search?q=${encodeURIComponent(term)}">${m}</a>`)}return out}
function blockHtml(b){if(b.type==='table'){return `<div class="doc-table-wrap"><table class="doc-table"><tbody>${b.rows.map(r=>`<tr>${r.map(c=>`<td>${linkify(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}const style=(b.style||'').toLowerCase();const cls=style.includes('list')?' list':style.includes('spec')?' spec':style.includes('callout')?' callout':style.includes('lore')?' lore':'';return `<p class="body-p${cls}">${linkify(b.text)}</p>`}
function sectionHtml(s){const lv=Math.min(5,Math.max(2,Number(s.level)||3)),content=(s.blocks||[]).map(blockHtml).join('');if(s.status==='obsolete')return `<section id="${esc(s.id)}" class="section"><div class="obsolete-block"><strong>${esc(s.title)} — source explicitement signalée comme obsolète</strong><div>${content}</div></div></section>`;const inner=`<section id="${esc(s.id)}" class="section"><h${lv}>${esc(s.title)}</h${lv}>${content}</section>`;if(s.audience==='mj')return `<details class="mj-block"><summary>${esc(s.title)}</summary><div class="mj-inner">${inner}</div></details>`;return inner}
function articleSnippet(a,limit=180){let t=flattenText(a).replace(/\s+/g,' ').trim();if(t.toLowerCase().startsWith(a.title.toLowerCase()))t=t.slice(a.title.length).trim();return t.slice(0,limit)+(t.length>limit?'…':'')}
function relatedTo(a){const text=norm(flattenText(a));const candidates=manifest.articles.filter(x=>x.id!==a.id&&x.audience!=='mj');let scored=[];for(const x of candidates){let score=0;const title=norm(x.title).replace(/^\d+\s+/,'');if(title.length>4&&text.includes(title))score+=5;for(const t of x.tags||[])if((a.tags||[]).map(norm).includes(norm(t)))score++;if(x.category===a.category)score+=.25;if(score>1)scored.push([score,x])}return scored.sort((a,b)=>b[0]-a[0]||a[1].title.localeCompare(b[1].title,'fr')).slice(0,8).map(x=>x[1])}
async function showHome(){renderNav('home');setToc('');const counts={};manifest.articles.forEach(a=>counts[a.category]=(counts[a.category]||0)+1);main.innerHTML=`<div class="page-head"><div class="eyebrow">BASE DOCUMENTAIRE TUC</div><h1>Compendium</h1><p>Le texte détaillé du monde, mis en pages web et relié aux synthèses les plus récentes. Cette première version privilégie la fidélité aux sources : on découpe, indexe et relie d’abord ; les arbitrages et enrichissements éditoriaux viennent ensuite.</p></div><div class="notice"><strong>Hiérarchie éditoriale :</strong> les dossiers détaillés sont la base du lore. Les livres récents contrôlent les décisions, terminologies et mécaniques statuées. Une contradiction non résolue doit être signalée et arbitrée, jamais gommée silencieusement.</div><div class="category-grid">${manifest.categories.map(c=>`<a class="category-card" href="#/category/${encodeURIComponent(c)}"><strong>${esc(c)}</strong><p>${c==='Règles'?'Le socle commun : résolution, profil, combat, santé et stress.':c==='Réalité'?'La Grande Californie de 2035, technologie, économie et vie quotidienne.':c==='Vérité'?'Le Voile, les peuples, traditions, Fléaux et mondes cachés.':c==='Organisations'?'Institutions, Pègre, Crawlers, agences, LAUS et corporations.':'Profils de PNJ, créatures et outils de scénario issus de la V17.'}</p><span class="count">${counts[c]||0} entrées →</span></a>`).join('')}</div>`}
async function showCategory(cat){renderNav(cat);setToc('');const list=manifest.articles.filter(a=>a.category===cat);main.innerHTML=`<div class="page-head"><div class="eyebrow">COMPENDIUM · ${esc(cat)}</div><h1>${esc(cat)}</h1><p>${list.length} entrées actuellement indexées. Les contenus MJ sont signalés et fermés par défaut lorsqu’ils sont ouverts depuis une page.</p></div><div class="article-list">${list.map(a=>`<a class="article-card" href="#/article/${encodeURIComponent(a.id)}"><h3>${esc(a.title)}</h3><p>${esc(a.source)} · ${esc(statusLabel(a.status))}${a.audience==='mj'?' · MJ':''}</p></a>`).join('')}</div>`}
async function showArticle(id,anchor=''){const a=await loadArticle(id);if(!a){main.innerHTML='<div class="empty">Article introuvable.</div>';return}renderNav(a.category);const secs=a.sections||[];setToc(`<div class="toc-title">Sur cette page</div><div class="toc-links">${secs.filter(s=>s.title).slice(0,80).map(s=>`<a href="#${esc(s.id)}">${esc(s.title)}</a>`).join('')}</div>`);const core=`<div class="page-head"><div class="eyebrow">${esc(a.category)}</div><h1>${esc(a.title)}</h1>${metaBadges(a)}</div><div class="source-box"><strong>Source :</strong> ${esc(a.source)}<br>${a.status==='source_detaillee'?'Lore détaillé servant de matière encyclopédique. Les décisions plus récentes sont à appliquer lorsqu’un conflit explicite est identifié.':'Corpus récent de contrôle / état canonique actuel.'}</div>${secs.map(sectionHtml).join('')}`;const related=relatedTo(a);const body=`${core}${related.length?`<section class="related"><h2>Voir aussi</h2><div class="related-links">${related.map(r=>`<a href="#/article/${encodeURIComponent(r.id)}">${esc(r.title)}</a>`).join('')}</div></section>`:''}`;main.innerHTML=a.audience==='mj'?`<div class="page-head"><div class="eyebrow">${esc(a.category)}</div><h1>${esc(a.title)}</h1>${metaBadges(a)}</div><details class="mj-block"><summary>Afficher le contenu MJ de cette page</summary><div class="mj-inner">${core.replace(/^<div class="page-head">[\s\S]*?<\/div><div class="source-box">/,'<div class="source-box">')}</div></details>`:body;if(anchor)setTimeout(()=>document.getElementById(anchor)?.scrollIntoView(),30)}
function excerptFor(a,q){const nq=norm(q),parts=[];for(const s of a.sections||[]){for(const b of s.blocks||[]){if(b.type==='p'&&norm(b.text).includes(nq)){parts.push({sec:s,text:b.text});break}}if(parts.length)break}if(!parts.length)return {sec:null,text:articleSnippet(a)};const p=parts[0].text,idx=norm(p).indexOf(nq);return {sec:parts[0].sec,text:p.slice(Math.max(0,idx-80),Math.min(p.length,idx+210))}}
function highlight(t,q){const safe=esc(t);const words=norm(q).split(' ').filter(x=>x.length>1);let out=safe;for(const w of words){const re=new RegExp(`(${w.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')})`,'ig');out=out.replace(re,'<mark>$1</mark>')}return out}
async function showSearch(q=''){renderNav('search');searchInput.value=q;setToc('');main.innerHTML=`<div class="page-head"><div class="eyebrow">RECHERCHE GLOBALE</div><h1>Rechercher dans TUC</h1><p>La recherche porte sur les titres, sous-titres, paragraphes et tableaux de toutes les sources déjà intégrées.</p></div><div class="loading">${q?'Indexation et recherche…':'Saisissez un terme dans la barre supérieure.'}</div>`;if(!q)return;const all=await loadAll(),nq=norm(q),terms=nq.split(' ').filter(Boolean);const scored=[];for(const a of all){const text=norm(flattenText(a));if(!terms.every(t=>text.includes(t)))continue;let score=terms.reduce((n,t)=>n+(norm(a.title).includes(t)?8:0)+(norm((a.tags||[]).join(' ')).includes(t)?3:0),0);score+=Math.min(10,terms.reduce((n,t)=>n+(text.match(new RegExp(t,'g'))||[]).length,0)*.15);scored.push([score,a])}scored.sort((x,y)=>y[0]-x[0]||x[1].title.localeCompare(y[1].title,'fr'));const results=scored.slice(0,120);main.innerHTML=`<div class="page-head"><div class="eyebrow">RECHERCHE GLOBALE</div><h1>${esc(q)}</h1><p>${scored.length} résultat${scored.length>1?'s':''}${scored.length>120?' · 120 premiers affichés':''}.</p></div><div class="search-results">${results.map(([score,a])=>{const ex=excerptFor(a,q);const href=`#/article/${encodeURIComponent(a.id)}${ex.sec?'@'+encodeURIComponent(ex.sec.id):''}`;return `<a class="search-result" href="${href}"><div class="crumb">${esc(a.category)} · ${a.audience==='mj'?'MJ · ':''}${esc(statusLabel(a.status))}</div><h3>${highlight(a.title,q)}</h3><p>${highlight(ex.text,q)}</p></a>`}).join('')||'<div class="empty">Aucun résultat. Essayez un terme plus court ou sans accent.</div>'}</div>`}
async function router(){if(!manifest)return;const raw=location.hash.slice(1)||'/home';if(raw.startsWith('/article/')){let x=decodeURIComponent(raw.slice(9)),anchor='';if(x.includes('@'))[x,anchor]=x.split('@',2);return showArticle(x,anchor)}if(raw.startsWith('/category/'))return showCategory(decodeURIComponent(raw.slice(10)));if(raw.startsWith('/search')){const q=new URLSearchParams(raw.split('?')[1]||'').get('q')||'';return showSearch(q)}return showHome()}
$('#globalSearch').addEventListener('submit',e=>{e.preventDefault();const q=searchInput.value.trim();routeTo(`/search?q=${encodeURIComponent(q)}`)});window.addEventListener('hashchange',router);
(async()=>{manifest=await loadPacked('manifest.json.gz.b64');renderNav();await router()})().catch(e=>{console.error(e);main.innerHTML=`<div class="empty">Impossible de charger le Compendium : ${esc(e.message)}</div>`});
