const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let DB=null;
const slugFromHash=()=>decodeURIComponent(location.hash.replace(/^#\/?/,''))||'pegre-californienne';
async function decodePreview(){const b64=window.PEGRE_PREVIEW_GZ||'';if(!b64)throw new Error('Paquet de données absent.');if(typeof DecompressionStream==='undefined')throw new Error('Ce navigateur ne prend pas en charge DecompressionStream.');const raw=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));const stream=new Blob([raw]).stream().pipeThrough(new DecompressionStream('gzip'));const text=await new Response(stream).text();const data=JSON.parse(text);if(!Array.isArray(data.pages))throw new Error('Le paquet ne contient pas de collection pages.');if(data.pages.length!==18)throw new Error(`Contrôle de recette échoué : ${data.pages.length} pages au lieu de 18.`);const embedded=data.embeddedAssets||data.assets||{};window.PEGRE_PREVIEW_ASSETS=embedded;window.PEGRE_PREVIEW_DIAGNOSTICS={ok:true,pages:data.pages.length,bytes:raw.byteLength,assets:Object.keys(embedded).length};return data}
function renderNav(){const nav=$('#nav');nav.innerHTML='';let g='';for(const p of DB.pages){if(p.group!==g){g=p.group;const h=document.createElement('div');h.className='nav-group';h.textContent=g;nav.appendChild(h)}const a=document.createElement('a');a.href='#/'+encodeURIComponent(p.id);a.dataset.id=p.id;a.innerHTML=`<span>${esc(p.title)}</span>`;nav.appendChild(a)}}
function assetKey(v){return String(v||'').split('/').pop().replace(/\.[^.]+$/,'')}
function assetSrc(v){const embedded=DB.embeddedAssets||{};const key=assetKey(v);return embedded[key]||(DB.assets&&DB.assets[v])||v}
function render(){let id=slugFromHash();let p=DB.pages.find(x=>x.id===id)||DB.pages[0];document.title=`${p.title} · Preview TUC`;document.querySelectorAll('#nav a').forEach(a=>a.classList.toggle('active',a.dataset.id===p.id));const hasVisual=p.visuals?.length;const visuals=hasVisual?`<div class="preview-visuals">${p.visuals.map((v,i)=>`<img loading="lazy" src="${esc(assetSrc(v))}" alt="Illustration source ${i+1} — ${esc(p.title)}">`).join('')}</div>`:'';const flags=(p.flags||[]).map(x=>`<div class="flag-box"><strong>À statuer avant intégration</strong><br>${esc(x)}</div>`).join('');const scheme=p.structure?.length?`<section class="scheme"><h2>Schéma de structure · synthèse de la source</h2><div class="scheme-flow">${p.structure.map((n,i)=>`<div class="scheme-node"><strong>${i+1}. ${esc(n.label)}</strong><span>${esc(n.note)}</span></div>`).join('')}</div></section>`:'';const sections=(p.sections||[]).map(s=>`<section class="preview-section section"><h2>${esc(s.title)}</h2>${(s.blocks||[]).map(b=>`<p class="body-p${b.type==='list'?' list':''}">${esc(b.text)}</p>`).join('')}</section>`).join('');const diag=window.PEGRE_PREVIEW_DIAGNOSTICS;$('#content').innerHTML=`<header class="page-head preview-hero${hasVisual?'':' no-visual'}"><div><div class="eyebrow">${esc(p.group)} · preview recette</div><h1>${esc(p.title)}</h1><p>${esc(p.summary)}</p><div class="preview-meta"><span class="badge source">${esc(p.source)}</span><span class="badge">${esc(p.target)}</span><span class="badge canon">Lore non-personnage</span><span class="badge canon">${diag.pages} pages vérifiées</span><span class="badge canon">${diag.assets} visuels embarqués</span></div></div>${visuals}</header>${flags}${scheme}${sections}<div class="preview-foot">Source de travail : ${esc(DB.source)} · Les biographies/profils individuels ont été exclus de cette preview. Les illustrations affichées proviennent du document source et sont embarquées dans le paquet de recette.</div>`;window.scrollTo({top:0,behavior:'instant'})}
function applyFilter(){const q=$('#filter').value.trim().toLowerCase();document.querySelectorAll('#nav a').forEach(a=>{const p=DB.pages.find(x=>x.id===a.dataset.id);a.classList.toggle('hidden-nav',!!q&&!`${p.title} ${p.group} ${p.summary}`.toLowerCase().includes(q))})}
async function init(){try{DB=await decodePreview();renderNav();render();$('#filter').addEventListener('input',applyFilter);window.addEventListener('hashchange',render)}catch(err){console.error(err);window.PEGRE_PREVIEW_DIAGNOSTICS={ok:false,error:String(err)};$('#content').innerHTML=`<div class="notice"><strong>Preview non valide.</strong><br>${esc(err.message||err)}</div>`}}
init();
