import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
const list=JSON.parse(readFileSync('/tmp/compact-talents-paths.json','utf8'));
const filename='apps/web/package.json',pkg=JSON.parse(readFileSync(filename,'utf8'));
assert.equal(pkg.scripts['test:reality-talents'],'node tests/reality-talents-integration.mjs');
pkg.scripts['test:reality-talents']+=' && node tests/reality-talents-compact.mjs';
writeFileSync(filename,JSON.stringify(pkg,null,2)+'\n');list.push(filename);
const file='apps/web/src/components/builder/CharacterSummary.vue';let s=readFileSync(file,'utf8');
s=s.replace('<dt>{{ context.label }} · bonus de Talent +{{ context.bonus }}</dt><dd>{{ context.total }}</dd>','<span>{{ context.label }} · bonus de Talent +{{ context.bonus }}</span><strong>{{ context.total }}</strong>');
s=s.replace('.skill-context-total{display:flex;','.sheet-skill-groups dl > div{flex-wrap:wrap}\n.skill-context-total{flex-basis:100%;display:flex;').replace('.skill-context-total dt{','.skill-context-total span{').replace('.skill-context-total dd{','.skill-context-total strong{');
writeFileSync(file,s);writeFileSync('/tmp/compact-talents-paths.json',JSON.stringify([...new Set(list)]));
