import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {build} from 'esbuild';
import {parse,compileScript} from '@vue/compiler-sfc';
import {JSDOM,VirtualConsole} from 'jsdom';
const root=fileURLToPath(new URL('../',import.meta.url));
const bundle=await build({stdin:{resolveDir:root,loader:'ts',contents:`import {createApp,h} from 'vue';import Combat from './src/components/CampaignCombat.vue';const app=createApp({render:()=>h(Combat,{campaignId:'camp',room:window.room})});app.mount('#app');window.stop=()=>app.unmount();`},bundle:true,write:false,format:'iife',platform:'browser',define:{'process.env.NODE_ENV':'"test"',__VUE_OPTIONS_API__:'true',__VUE_PROD_DEVTOOLS__:'false'},plugins:[{name:'vue',setup(b){b.onLoad({filter:/\.vue$/},async({path:filename})=>{const {descriptor}=parse(await readFile(filename,'utf8'));return {contents:compileScript(descriptor,{id:'lightning-test',inlineTemplate:true}).content,loader:'ts',resolveDir:path.dirname(filename)};});}}]});
const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));vc.on('error',e=>errors.push(String(e)));
const dom=new JSDOM('<div id="app"></div>',{url:'https://test.invalid',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc}),w=dom.window,d=w.document;
w.Headers=Headers;w.room={canManage:false,characters:[{id:'caster',name:'Caster'},{id:'target',name:'Aseryn'}],combatants:[],events:[],combat:{active:true}};
const polls=[],requests=[];w.setInterval=f=>{polls.push(f);return polls.length;};w.clearInterval=()=>{};
const attack={id:'lightning',attackMode:'foudre',damageType:'electricite',total:30,damage:7,bonusDamage:0,penetration:0,target:{id:'target',name:'Aseryn',version:5,paratonnerre:{available:true},edge:2,pa:3,defense:10,occultDefense:12,canDefend:true,protections:[],armor:50,bodyArmor:20,reductions:{electricite:3},guard:true}};
const snapshot={pending:[],attackers:[{id:'caster',name:'Caster',ready:true,options:[{id:'foudre',label:'Foudre aseryne',group:'Foudre',damage:7,attackMode:'foudre',damageType:'electricite',condition:'Cible à 20 m maximum',modifier:10,components:{attributeName:'Volonté',attribute:5,skillName:'Maîtrise spirituelle',rank:5,bonus:0}}]}],canManage:false};
let lose=false;
w.fetch=async(url,opts)=>{if(!opts?.body)return {ok:true,status:200,json:async()=>structuredClone(snapshot)};const b=JSON.parse(opts.body);requests.push(b);if(lose){lose=false;throw new Error('Lost response');}return {ok:true,status:200,json:async()=>({ok:true})};};
const wait=()=>new Promise(r=>setTimeout(r,5));async function until(check){for(let i=0;i<100;i++){if(check())return;await wait();}assert(check(),'UI did not settle');}
async function set(selector,value){const el=d.querySelector(selector);assert(el,selector);el.value=String(value);el.dispatchEvent(new w.Event(el.tagName==='SELECT'?'change':'input',{bubbles:true}));await wait();}
async function check(selector){const el=d.querySelector(selector);assert(el,selector);el.checked=true;el.dispatchEvent(new w.Event('change',{bubbles:true}));await wait();}
const button=(text)=>{const el=[...d.querySelectorAll('button')].find(b=>b.textContent.includes(text));assert(el,text);return el;};
async function refresh(){for(const p of polls)await p();await wait();}
w.eval(bundle.outputFiles[0].text);await until(()=>d.querySelector('[aria-label="Arme / attaque"]'));
await set('[aria-label="Arme / attaque"]','foudre');await set('[aria-label="Cible de l’attaque"]','target');await set('[aria-label="Distance de la cible de Foudre"]',21);await check('.attack-context input');assert(button('Lancer l’attaque').disabled);await set('[aria-label="Distance de la cible de Foudre"]',20);assert(button('Lancer l’attaque').disabled,'Changing distance requires fresh confirmation');await check('.attack-context input');button('Lancer l’attaque').click();await until(()=>requests.length===1);assert.equal(requests[0].distance,20);assert.equal(requests[0].contextConfirmed,true);assert.equal(requests[0].targetId,'target');
snapshot.pending=[structuredClone(attack)];await refresh();await until(()=>d.querySelector('.lightning-reaction'));
assert(button('Défense passive').disabled);await set('[aria-label="Défense pertinente contre la Foudre"]','occult');assert(button('Défense passive').disabled);await check('.foudre-defense input');button('Défense passive').click();await until(()=>requests.at(-1).action==='defend');assert.equal(requests.at(-1).defenseKind,'occult');assert.equal(requests.at(-1).contextConfirmed,true);
await set('[aria-label="Destination de Paratonnerre"]','Conducteur sûr');await check('.lightning-reaction input[type="checkbox"]');const checks=d.querySelectorAll('.lightning-reaction input[type="checkbox"]');checks[1].checked=true;checks[1].dispatchEvent(new w.Event('change',{bubbles:true}));await wait();
lose=true;button('Détourner la décharge').click();await until(()=>d.querySelector('[role="alert"]'));const request=requests.at(-1);assert.equal(request.action,'paratonnerre');assert.equal(request.actorVersion,5);assert.equal(request.safeDestinationConfirmed,true);button('Réessayer cette action').click();await until(()=>requests.length>=4);assert.deepEqual(requests.at(-1),request);await until(()=>!d.querySelector('.lightning-reaction').disabled);
snapshot.pending[0].target.paratonnerre.available=false;snapshot.pending[0].electricDiversion={eventId:'reaction',modifier:10,dice:[1],total:11,narrativeFailure:true,success:false};await refresh();button('Forcer ce Paratonnerre').click();await until(()=>requests.at(-1).action==='paratonnerre-force');assert.equal(requests.at(-1).actorVersion,5);
snapshot.pending[0].electricDiversion={eventId:'reaction',modifier:10,dice:[10,10],total:30,edgeForced:true,success:true};snapshot.pending[0].defense={label:'Décharge détournée',active:false,modifier:10,total:10};await refresh();assert.match(d.querySelector('.damage-preview').textContent,/0 dégâts/);assert.equal(d.querySelector('.pending-attack input[type="checkbox"]')?.disabled,true,'Ordinary armor is unavailable for Foudre');assert.equal(button('Appliquer 0').disabled,false);
snapshot.pending[0].electricDiversion=undefined;await refresh();assert.match(d.querySelector('.damage-preview').textContent,/18 dégâts/,'20 margin + 7 DGT - 3 electric protection - 6 Rune, ordinary armor ignored');
assert.deepEqual(errors,[]);w.stop();w.close();console.log('LIGHTNING DOM OK — range and fresh context, relevant defense, private personal reaction, exact retry, Edge after result, electric preview and diverted impact');
