<script setup lang="ts">
import {computed,onUnmounted,ref,watch} from 'vue';
import {effectScopes,validateEffectDraft,type LiveEffect,type LiveEffectDraft,type EffectScope} from '../../../api/src/rules/live-effects';
import {terraUmbraCreationRules} from '../../../api/src/rules/terra-umbra-creation';
import {api,ApiError} from '../lib/api';

const props=defineProps<{campaignId:string;room:any}>(),emit=defineEmits<{changed:[]}>();
type Actor={id:string;name:string;isCharacter:boolean;[key:string]:any};
type Snapshot={version:number;effects:LiveEffect[];activation:number;activationOpen:boolean;effectArmor:number};
const actors=computed<Actor[]>(()=>[...(props.room.characters??[]).map((a:any)=>({...a,isCharacter:true})),...(props.room.combatants??[]).map((a:any)=>({...a,isCharacter:false}))]);
const actorId=ref(''),sourceId=ref(''),snapshot=ref<Snapshot|null>(null),busy=ref(false),loading=ref(false),error=ref(''),notice=ref(''),pending=ref<Record<string,any>|null>(null);
const selected=computed(()=>actors.value.find(a=>a.id===actorId.value)),blocked=computed(()=>busy.value||loading.value||!snapshot.value||!!pending.value);
let alive=true,loadSequence=0,npcMinimumVersion=0;

const scopeNames:Record<EffectScope,string>={physical:'Tests physiques',mental:'Tests mentaux',social:'Tests sociaux',intellectual:'Tests intellectuels',visual:'Tests visuels',skill:'Compétence précise','defense-physical':'Défense physique','defense-neuro':'Défense Neuro','defense-occult':'Défense occulte',armor:'Armure',damage:'Dégâts',reduction:'Réduction de dégâts','pa-physical':'Limite de PA physiques',regeneration:'Régénération contrariée',condition:'État suivi'};
const periodNames:Record<string,string>={'round-start':'Début de round','round-end':'Fin de round','activation-start':'Début d’activation','activation-end':'Fin d’activation'};
const skills=terraUmbraCreationRules.skills;
const name=ref(''),kind=ref<LiveEffectDraft['kind']>('modifier'),scope=ref<EffectScope>('physical'),skill=ref(skills[0].id),amount=ref(3),stackKey=ref(''),duration=ref<LiveEffectDraft['duration']['unit']>('scene'),durationValue=ref(1),period=ref('round-end'),delay=ref(1),ticks=ref<number|null>(null),ignoreArmor=ref(true),damageType=ref('physique'),healingKind=ref<'regeneration'|'external'>('external'),zone=ref(''),contextConfirmed=ref(false),armor=ref(0);
const periodic=computed(()=>kind.value==='damage'||kind.value==='healing');
const scopes=computed(()=>kind.value==='condition'?(['condition','pa-physical','regeneration'] as EffectScope[]):periodic.value?(['condition'] as EffectScope[]):effectScopes.filter(s=>!['condition','pa-physical','regeneration'].includes(s)));
watch(kind,value=>{scope.value=value==='condition'||periodic.value?'condition':'physical';amount.value=value==='condition'?0:3;if(value==='healing')healingKind.value='external';contextConfirmed.value=false;});
watch(scope,()=>{contextConfirmed.value=false;});
const effectDraft=computed<LiveEffectDraft>(()=>({name:name.value.trim(),sourceId:sourceId.value,targetId:actorId.value,kind:kind.value,scope:scope.value,amount:amount.value,stackKey:stackKey.value.trim()||`mj:${name.value.trim().toLocaleLowerCase('fr')}`,stackMode:'best',duration:duration.value==='scene'||duration.value==='manual'?{unit:duration.value}:{unit:duration.value,value:durationValue.value},...(scope.value==='skill'?{skill:skill.value}:{}),...(scope.value==='armor'&&zone.value.trim()?{zone:zone.value.trim()}:{}),...(periodic.value?{period:period.value as LiveEffectDraft['period'],delay:delay.value,...(ticks.value!==null&&String(ticks.value)!==''?{ticks:Number(ticks.value)}:{})}:{}),...(kind.value==='healing'?{healingKind:healingKind.value}:{}),...(kind.value==='damage'?{armorMode:ignoreArmor.value?'ignore':'normal',damageType:damageType.value as LiveEffectDraft['damageType']}:{} )}));
const draftValid=computed(()=>validateEffectDraft(effectDraft.value)&&actors.value.some(a=>a.id===sourceId.value));
watch(effectDraft,()=>{contextConfirmed.value=false;});

const presets=[
 {id:'maitre_des_lames',name:'Maître des lames · plaie persistante',summary:'2 PV à chaque fin de round dès le suivant, sans Armure, jusqu’à traitement. Altération avec marge ≥ 6 et au moins 1 dégât ; la cible saigne.',fields:['hit','alteration','damage','margin','bleeds']},
 {id:'khinae-serpent-vipere',name:'Khinae Vipère · venin hémotoxique',summary:'1 PV sans Armure au début des deux prochaines activations. Morsure ayant blessé, venin reçu et résistance échouée ; quota par cible et par scène.',fields:['hit','damage','exposed','resistanceFailed']},
 {id:'khinae-serpent-cobra',name:'Khinae Cobra · venin neurotoxique',summary:'1 PA physique au maximum pendant la prochaine activation. Morsure réussie, venin reçu et résistance échouée ; quota par cible et par scène.',fields:['hit','exposed','resistanceFailed']},
 {id:'extral-venin-rocreen',name:'Rocréen · venin',summary:'−3 aux tests physiques jusqu’à la fin du prochain round ; 1 PA, 1/scène. Attaque réussie, venin reçu et résistance échouée.',fields:['hit','exposed','resistanceFailed']},
 {id:'munitions-speciales-phoenix-hack',name:'Phoenix Hack · Défense Neuro',summary:'−3 en Défense Neuro jusqu’à la fin de la prochaine activation. Altération et connexion réellement affectée.',fields:['alteration','connected']},
 {id:'munitions-lourdes-consommables-grenade-flash-doorbell',name:'Flash Doorbell · vision',summary:'−3 aux tests visuels jusqu’à la fin de la prochaine activation. Altération et exposition confirmées.',fields:['alteration','exposed']},
 {id:'extral-jet-d-encre',name:'Jet d’encre · vision gênée',summary:'−3 aux tests visuels jusqu’au nettoyage ; 1 PA, 1/scène. La cible a réellement reçu l’encre.',fields:['exposed']},
 {id:'extral-ouvrir-la-cuirasse',name:'Ouvrir la cuirasse · brèche localisée',summary:'−2 à l’Armure de la zone touchée jusqu’à la fin de scène. Altération sur une arme physique, zone explicitement arbitrée.',fields:['alteration','physicalWeapon','affectedZone']}
] as const;
const presetId=ref(''),preset=computed(()=>presets.find(p=>p.id===presetId.value)),proof=ref<Record<string,any>>({hit:false,alteration:false,damage:1,margin:6,bleeds:false,exposed:false,resistanceFailed:false,connected:false,physicalWeapon:false,affectedZone:''}),sourceActionId=ref(''),presetConfirmed=ref(false);
const impulseProof=ref<Record<string,{pursues:boolean;impossible:boolean;confirmed:boolean}>>({});
const frenzyActors=computed(()=>props.room.combat?.active?actors.value.filter(a=>[actorId.value,sourceId.value].includes(a.id)&&a.frenzy?.impulseRequired):[]);
watch(()=>frenzyActors.value.map(a=>`${a.id}:${props.room.combat?.round}:${JSON.stringify(a.frenzy)}`).join('|'),()=>{for(const actor of frenzyActors.value)impulseProof.value[actor.id]={pursues:false,impossible:false,confirmed:false};},{immediate:true});
function frenzyReady(id:string){const proof=impulseProof.value[id];return !frenzyActors.value.some(a=>a.id===id)||!proof?.pursues&&!proof?.impossible||proof.confirmed;}
function frenzyPayload(id:string){if(!frenzyActors.value.some(a=>a.id===id))return {};const proof=impulseProof.value[id];return {pursuesImpulse:proof.pursues,impulseImpossibleConfirmed:proof.impossible,contextConfirmed:proof.confirmed};}
function chooseImpulse(id:string,which:'pursues'|'impossible'){const proof=impulseProof.value[id];proof.confirmed=false;if(proof[which])proof[which==='pursues'?'impossible':'pursues']=false;}
const proofLabels:Record<string,string>={hit:'Attaque réussie',alteration:'Altération obtenue et applicable',damage:'Dégâts réellement subis',margin:'Marge obtenue',bleeds:'La cible peut saigner',exposed:'Exposition à l’effet confirmée',resistanceFailed:'Test de résistance échoué',connected:'Connexion affectée',physicalWeapon:'Arme physique concernée',affectedZone:'Zone d’Armure touchée'};
const paidAttacks=computed(()=>(props.room.events??[]).filter((e:any)=>e.kind==='attack'&&e.payload?.attackerId===sourceId.value&&e.payload?.targetId===actorId.value));
watch(presetId,()=>{presetConfirmed.value=false;sourceActionId.value='';});
watch(proof,()=>{presetConfirmed.value=false;},{deep:true});
watch(sourceId,()=>{contextConfirmed.value=false;presetConfirmed.value=false;sourceActionId.value='';});

function failure(cause:unknown){
 const code=cause instanceof Error?cause.message:'',messages:Record<string,string>={frenzy_impulse_pa_required:'La Frénésie exige de garder 1 PA pour son impulsion. Confirme une action qui la poursuit, ou arbitre son impossibilité réelle.',mechanics_version_conflict:'L’état de ce personnage a changé. Il a été actualisé ; vérifie puis relance ton action.',mechanics_request_conflict:'Cette référence de requête correspond à une autre action. Actualise avant de recommencer.',pending_attacks:'Résous les attaques en attente avant de modifier les effets.',effect_source_unavailable:'Le lanceur ne possède pas cette capacité ou elle est indisponible dans son état actuel.',effect_conditions_not_met:'Les conditions de cet effet ne sont pas réunies. Vérifie l’attaque et les décisions d’arbitrage.',power_already_used:'Cette capacité a déjà atteint son quota pour cette période.',effect_does_not_stack:'Un effet exclusif identique est déjà présent. Retire-le avant de le remplacer.',effect_stacking_conflict:'Ce groupe d’effets suit déjà une autre règle de cumul. Vérifie son groupe avant de recommencer.',invalid_effect:'Vérifie la valeur, la compétence, la durée et la périodicité de l’effet.',effect_not_found:'Cet effet a déjà été retiré. L’état a été actualisé.',combat_not_started:'Les activations se suivent pendant un combat lancé.',activation_phase_conflict:'Cette phase a déjà été effectuée. L’état a été actualisé.',insufficient_pa:'Le lanceur ne dispose pas des PA requis ou ne participe pas à ce combat.',effect_source_cannot_act:'Le lanceur est incapable d’agir dans son état actuel.',invalid_paid_effect_attack:'Cette attaque ne justifie pas un coût déjà payé. Choisis une attaque récente du lanceur contre cette cible.',actor_not_found:'Ce personnage n’est plus disponible dans cette campagne.'};
 return messages[code]??(cause instanceof ApiError&&cause.status<500?'L’action a été refusée. Actualise les informations et vérifie les conditions.':'Action non confirmée. Réessaie la même action pour vérifier son enregistrement.');
}
function fromState(state:any,version:number):Snapshot{return {version,effects:state.effects??state.liveEffects??[],activation:state.activation??0,activationOpen:!!state.activationOpen,effectArmor:state.effectArmor??0};}
async function load(){
 if(!alive||!props.room.canManage||!selected.value||pending.value)return;
 const actor=selected.value,sequence=++loadSequence;loading.value=true;
 try{
  if(actor.isCharacter){const response=await api<any>(`/api/characters/${actor.id}/play`);if(alive&&sequence===loadSequence&&actorId.value===actor.id){snapshot.value=fromState(response.state,response.version);armor.value=snapshot.value.effectArmor;}}
  else if(Number.isInteger(actor.version)&&actor.version>=npcMinimumVersion){snapshot.value=fromState(actor,actor.version);armor.value=snapshot.value.effectArmor;}
  else snapshot.value=null;
 }catch(cause){if(alive&&sequence===loadSequence){snapshot.value=null;error.value='Impossible de charger l’état de ce personnage. Actualise pour réessayer.';}}
 finally{if(alive&&sequence===loadSequence)loading.value=false;}
}
watch(()=>[props.room.canManage,...actors.value.map(a=>a.id)].join('|'),()=>{if(!actors.value.some(a=>a.id===actorId.value))actorId.value=actors.value[0]?.id??'';},{immediate:true});
watch(actorId,()=>{loadSequence++;snapshot.value=null;npcMinimumVersion=0;contextConfirmed.value=false;presetConfirmed.value=false;error.value='';notice.value='';sourceId.value=actorId.value;if(!pending.value)void load();},{immediate:true});
watch(()=>[props.room.combat?.version,props.room.events?.[0]?.id,...actors.value.map(a=>`${a.id}:${a.version??''}:${a.activation??''}:${a.activationOpen??''}`)].join('|'),()=>{if(!pending.value&&!busy.value)void load();});
function refresh(){if(busy.value||pending.value)return;error.value='';notice.value='';emit('changed');void load();}
async function send(action:string,extra:Record<string,any>={}){
 if(blocked.value||!selected.value||!props.room.canManage)return;
 pending.value={requestId:crypto.randomUUID(),actorId:actorId.value,version:snapshot.value!.version,action,...extra};await retry();
}
async function retry(){
 if(busy.value||!pending.value||!props.room.canManage)return;
 busy.value=true;error.value='';notice.value='';const request=pending.value;
 try{
  const response=await api<any>(`/api/campaigns/${props.campaignId}/mechanics`,{method:'POST',body:JSON.stringify(request)});
  if(!alive)return;pending.value=null;contextConfirmed.value=false;presetConfirmed.value=false;notice.value='Enregistré. Les effets détaillés restent réservés au MJ et au personnage concerné.';
  if(selected.value&&!selected.value.isCharacter){npcMinimumVersion=response.version??request.version+1;snapshot.value=null;}
  busy.value=false;emit('changed');await load();
 }catch(cause){if(alive){error.value=failure(cause);if(cause instanceof ApiError&&cause.status<500){pending.value=null;busy.value=false;emit('changed');await load();}}}
 finally{busy.value=false;}
}
function addEffect(){if(contextConfirmed.value&&draftValid.value)void send('effect-add',{effect:effectDraft.value});}
function addPreset(){if(!preset.value||!presetConfirmed.value||!frenzyReady(sourceId.value))return;const checked:Record<string,any>={};for(const field of preset.value.fields)checked[field]=proof.value[field];void send('effect-add',{preset:preset.value.id,sourceId:sourceId.value,proof:checked,...frenzyPayload(sourceId.value),...(sourceActionId.value?{sourceActionId:sourceActionId.value}:{})});}
function expiry(effect:LiveEffect){return effect.expires.unit==='round'?`Fin du round ${effect.expires.at}`:effect.expires.unit==='activation'?`Fin de l’activation ${effect.expires.at}`:effect.expires.unit==='scene'?'Fin de scène':'Jusqu’au retrait';}
function value(effect:LiveEffect){return effect.kind==='damage'?`${effect.amount} PV perdus${effect.armorMode==='ignore'?' sans Armure':''}`:effect.kind==='healing'?`+${effect.amount} PV · ${effect.healingKind==='regeneration'?'Régénération':'Soin extérieur'}`:effect.kind==='modifier'?`${effect.amount>0?'+':''}${effect.amount} · ${effect.scope==='skill'?skills.find(s=>s.id===effect.skill)?.name??effect.skill:scopeNames[effect.scope]}`:effect.scope==='pa-physical'?`${effect.amount} PA physiques au maximum`:effect.name;}
onUnmounted(()=>{alive=false;loadSequence++;});
</script>

<template>
<details v-if="room.canManage" class="campaign-effects">
 <summary><strong>MJ · effets, blessures & activations</strong><span>Sur un PJ, PNJ ou une créature</span></summary>
 <div class="effects-content">
  <p>Attribue un effet après avoir vérifié ses conditions dans la fiction et les règles. Les valeurs, durées et retraits sont enregistrés pour la cible.</p>
  <p v-if="error" role="alert">{{error}} <button v-if="pending" :disabled="busy" @click="retry">Réessayer cette action</button></p>
  <p v-if="notice" role="status">{{notice}}</p>
  <label>Cible de l’effet<select v-model="actorId" aria-label="Cible de l’effet" :disabled="busy||!!pending"><option v-if="!actors.length" value="">Aucun personnage disponible</option><option v-for="actor in actors" :key="actor.id" :value="actor.id">{{actor.name}}{{actor.isCharacter?' · PJ':' · PNJ / créature'}}</option></select></label><button v-if="selected" :disabled="busy||loading||!!pending" @click="refresh">Actualiser l’état</button>
  <p v-if="loading">Chargement de l’état…</p><p v-else-if="selected&&!snapshot">État en attente d’actualisation.</p>
  <template v-if="snapshot">
   <div class="activation-controls"><strong>Activation {{snapshot.activation}} · {{snapshot.activationOpen?'en cours':'terminée'}}</strong><button :disabled="blocked||!room.combat?.active||snapshot.activationOpen" @click="send('activation-start')">Commencer l’activation</button><button :disabled="blocked||!room.combat?.active||!snapshot.activationOpen" @click="send('activation-end')">Terminer l’activation</button></div>
   <small>Une activation correspond au passage complet de la cible dans le combat, avec toutes ses actions. Ces commandes déclenchent les effets de début ou de fin d’activation ; elles ne dépensent pas de PA.</small>
   <form class="armor-form" @submit.prevent="send('effect-armor',{armor})"><label>Armure applicable aux dégâts périodiques<input v-model.number="armor" aria-label="Armure des effets périodiques" type="number" min="0" max="100" required /></label><button :disabled="blocked||armor===snapshot.effectArmor">Enregistrer l’Armure</button><small>Le MJ fixe l’Armure pertinente pour les effets suivis. Un effet « sans Armure » ignore cette valeur.</small></form>
   <h3>Effets sur {{selected?.name}}</h3><p v-if="!snapshot.effects.length">Aucun effet persistant.</p>
   <ul v-else class="effect-list"><li v-for="effect in snapshot.effects" :key="effect.id"><div><strong>{{effect.name}}</strong><span>{{value(effect)}} · {{expiry(effect)}}<template v-if="effect.period"> · {{periodNames[effect.period]}}<template v-if="effect.remainingTicks!==null"> · {{effect.remainingTicks}} application(s) restante(s)</template></template><template v-if="effect.startsAt"> · À partir {{effect.startsAt.unit==='round'?'du round':'de l’activation'}} {{effect.startsAt.at}}</template><template v-if="effect.zone"> · Zone {{effect.zone}}</template></span></div><button :disabled="blocked" @click="send('effect-remove',{effectId:effect.id})" :aria-label="`Retirer ${effect.name}`">Retirer · arbitrage MJ</button><button v-if="['maitre_des_lames','extral-jet-d-encre'].includes(effect.ruleId??'')" :disabled="blocked||!frenzyReady(actorId)" @click="send('effect-remove',{effectId:effect.id,treatment:true,...frenzyPayload(actorId)})">{{effect.ruleId==='maitre_des_lames'?'Traiter la plaie':'Nettoyer l’encre'}} · 1 PA en combat</button></li></ul>
   <label>Source de l’effet<select v-model="sourceId" aria-label="Source de l’effet" :disabled="blocked"><option v-for="actor in actors" :key="actor.id" :value="actor.id">{{actor.name}}</option></select></label>
   <div v-for="actor in frenzyActors" :key="actor.id" class="frenzy-ruling"><strong>Frénésie · {{actor.name}}</strong><p>{{actor.frenzy.impulse}} · garde 1 PA pour cette impulsion tant qu’elle reste à satisfaire.</p><label class="check"><input v-model="impulseProof[actor.id].pursues" :aria-label="`Action de l’impulsion de ${actor.name}`" type="checkbox" @change="chooseImpulse(actor.id,'pursues')" /> Cette action payante poursuit son impulsion.</label><label class="check"><input v-model="impulseProof[actor.id].impossible" :aria-label="`Impulsion impossible de ${actor.name}`" type="checkbox" @change="chooseImpulse(actor.id,'impossible')" /> MJ · aucune action vers cette impulsion n’est réellement possible.</label><label v-if="impulseProof[actor.id].pursues||impulseProof[actor.id].impossible" class="check"><input v-model="impulseProof[actor.id].confirmed" :aria-label="`Conditions de l’impulsion de ${actor.name}`" type="checkbox" /> Je confirme les conditions réelles de cette décision.</label></div>
   <details class="add-effect"><summary>Ajouter un effet prévu par les règles</summary><form class="preset-effect-form" @submit.prevent="addPreset"><fieldset :disabled="blocked"><label>Effet canonique<select v-model="presetId" aria-label="Effet canonique"><option value="">Choisir une capacité ou une munition…</option><option v-for="rule in presets" :key="rule.id" :value="rule.id">{{rule.name}}</option></select></label><template v-if="preset"><p>{{preset.summary}}</p><p>Le serveur vérifie la capacité du lanceur et consomme son quota ainsi que les PA éventuellement dus. Confirme les conditions qui demandent un arbitrage.</p><div class="input-grid"><label v-for="field in preset.fields" :key="field" :class="{'check':!['damage','margin','affectedZone'].includes(field)}"><input v-if="!['damage','margin','affectedZone'].includes(field)" v-model="proof[field]" type="checkbox" />{{proofLabels[field]}}<input v-if="['damage','margin'].includes(field)" v-model.number="proof[field]" type="number" min="0" max="10000" required /><input v-else-if="field==='affectedZone'" v-model="proof[field]" maxlength="100" required /></label></div><label v-if="['extral-venin-rocreen','extral-jet-d-encre'].includes(preset.id)">Action déjà payée (facultatif)<select v-model="sourceActionId" aria-label="Action de l’effet déjà payée"><option value="">Payer le PA de cette capacité</option><option v-for="attack in paidAttacks" :key="attack.id" :value="attack.id">{{attack.payload.label??'Attaque'}} · {{attack.id.slice(0,8)}}</option></select></label><label class="check"><input v-model="presetConfirmed" type="checkbox" /> J’ai vérifié les conditions et la résistance éventuelle de la cible.</label><button :disabled="!presetConfirmed||!sourceId||!frenzyReady(sourceId)">Attribuer cet effet</button></template></fieldset></form></details>
   <details class="add-effect"><summary>Ajouter un effet arbitré par le MJ</summary><form class="custom-effect-form" @submit.prevent="addEffect"><fieldset :disabled="blocked"><div class="input-grid"><label>Nom de l’effet<input v-model="name" aria-label="Nom de l’effet" maxlength="150" required /></label><label>Nature de l’effet<select v-model="kind" aria-label="Nature de l’effet"><option value="modifier">Bonus ou malus</option><option value="damage">Dégâts périodiques</option><option value="healing">Soins périodiques</option><option value="condition">Condition suivie</option></select></label><label>Application<select v-model="scope" aria-label="Application de l’effet"><option v-for="item in scopes" :key="item" :value="item">{{scopeNames[item]}}</option></select></label><label v-if="scope==='skill'">Compétence<select v-model="skill" aria-label="Compétence de l’effet"><option v-for="item in skills" :key="item.id" :value="item.id">{{item.name}}</option></select></label><label>{{kind==='condition'&&scope==='pa-physical'?'PA physiques au maximum':kind==='condition'?'Valeur de suivi':'Valeur par application'}}<input v-model.number="amount" aria-label="Valeur de l’effet" type="number" :min="kind==='modifier'?-100:periodic?1:0" :max="scope==='pa-physical'?5:100" required /></label><label v-if="scope==='armor'">Zone (facultatif)<input v-model="zone" maxlength="100" /></label><label>Durée<select v-model="duration" aria-label="Durée de l’effet"><option value="scene">Jusqu’à la fin de scène</option><option value="round">Nombre de rounds</option><option value="activation">Nombre d’activations de la cible</option><option value="manual">Jusqu’au retrait du MJ</option></select></label><label v-if="duration==='round'||duration==='activation'">{{duration==='round'?'Rounds supplémentaires':'Activations supplémentaires'}}<input v-model.number="durationValue" aria-label="Nombre pour la durée" type="number" min="0" max="1000" required /></label></div>
    <template v-if="periodic"><div class="input-grid"><label>Appliquer à chaque<select v-model="period" aria-label="Périodicité de l’effet"><option v-for="(label,id) in periodNames" :key="id" :value="id">{{label}}</option></select></label><label>Décalage avant la première application<input v-model.number="delay" aria-label="Décalage de l’effet" type="number" min="0" max="1000" required /></label><label>Nombre d’applications (vide : pendant toute la durée)<input v-model.number="ticks" aria-label="Nombre d’applications" type="number" min="1" max="1000" /></label><label v-if="kind==='healing'">Origine du soin<select v-model="healingKind" aria-label="Origine du soin"><option value="external">Soin extérieur · magie ou traitement</option><option value="regeneration">Régénération du personnage</option></select></label><label v-if="kind==='damage'">Type de dégâts<select v-model="damageType"><option value="physique">Physiques</option><option value="neuro">Neuro</option><option value="occulte">Occultes</option></select></label></div><label v-if="kind==='damage'" class="check"><input v-model="ignoreArmor" type="checkbox" /> Dégâts sans Armure</label><small v-if="kind==='healing'">Une entrave à la régénération s’applique à la régénération du personnage. Un soin extérieur garde les conditions de son propre pouvoir ou traitement.</small><small>Un décalage de 1 démarre à la prochaine occurrence ; 0 inclut l’occurrence courante si elle n’a pas encore été déclenchée. Le changement de round et les commandes d’activation appliquent les effets une seule fois.</small></template>
    <label>Groupe d’effets équivalents (facultatif)<input v-model="stackKey" aria-label="Groupe de l’effet" maxlength="150" placeholder="Ex. vision-entravee" /></label><small>Dans un même groupe, le meilleur bonus et le plus fort malus sont retenus. Utilise le même groupe pour les effets équivalents. Une condition suivie doit encore être arbitrée si aucune commande dédiée ne la résout.</small><label class="check"><input v-model="contextConfirmed" type="checkbox" /> Je confirme la cible, la valeur, la durée et les conditions de cet effet.</label><button :disabled="!draftValid||!contextConfirmed">Attribuer l’effet à {{selected?.name}}</button></fieldset></form></details>
  </template>
 </div>
</details>
</template>

<style scoped>
.frenzy-ruling{padding:12px;border:1px solid #698fa7;border-radius:6px;margin:12px 0}.frenzy-ruling p{margin:5px 0}.campaign-effects{margin:16px 0;background:#0d1b2b;border:1px solid #355267;border-radius:8px;min-width:0}.campaign-effects summary{padding:14px;cursor:pointer}.campaign-effects summary span{margin-left:12px;color:#b7c9d6;font-size:.9em}.effects-content{padding:0 16px 16px}.effects-content p,.effects-content small{line-height:1.5}.effects-content small{display:block;color:#b7c9d6}.campaign-effects label{display:grid;gap:6px;margin:10px 0}.campaign-effects input:not([type=checkbox]),.campaign-effects select{box-sizing:border-box;width:100%;min-width:0;padding:10px;background:#08131f;color:#e6eef8;border:1px solid #526c80;border-radius:5px;font:inherit}.campaign-effects .check{display:flex;align-items:center;gap:8px}.campaign-effects button{padding:10px;min-height:44px;background:#143247;color:#d5f6ff;border:1px solid #52758b;border-radius:5px;cursor:pointer}.campaign-effects button:disabled{opacity:.5;cursor:default}.input-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,180px),1fr));gap:12px}.activation-controls,.armor-form{display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin:16px 0}.armor-form label{max-width:350px;flex:1}.armor-form small{flex-basis:100%}.effect-list{list-style:none;padding:0}.effect-list li{display:flex;gap:10px;align-items:center;flex-wrap:wrap;padding:12px;border:1px solid #355267;border-radius:6px;margin:8px 0}.effect-list li div{flex:1;min-width:min(100%,200px)}.effect-list li span{display:block;line-height:1.5;color:#b7c9d6}.add-effect{margin-top:16px;border-top:1px solid #355267}.add-effect summary{padding-left:0}.campaign-effects fieldset{border:0;padding:0;margin:0;min-width:0}@media(max-width:600px){.campaign-effects summary span{display:block;margin:6px 0 0}.effects-content{padding:0 12px 12px}.activation-controls button,.effect-list button{flex:1}}
</style>
