<script setup lang="ts">
import {onMounted,onUnmounted,ref} from 'vue';
import {api} from '../lib/api';
const props=defineProps<{campaignId:string}>();
const characters=ref<any[]>([]),events=ref<any[]>([]),error=ref('');
let timer:ReturnType<typeof setInterval>|undefined,alive=true,loading=false;
async function load(){if(loading||document.visibilityState==='hidden')return;loading=true;try{const r=await api<any>(`/api/campaigns/${props.campaignId}/play`);if(alive){characters.value=r.characters;events.value=r.events;error.value='';}}catch{if(alive){characters.value=[];events.value=[];error.value='Le suivi de partie est indisponible.';}}finally{loading=false;}}
onMounted(()=>{void load();timer=setInterval(()=>void load(),3000);});onUnmounted(()=>{alive=false;clearInterval(timer);});
</script>
<template><section class="campaign-play"><h2>En jeu · le groupe</h2><p>Actualisation toutes les 3 secondes. Chaque joueur choisit de partager son apparence et son état général ; le MJ voit les ressources et les jets.</p><p v-if="error" role="alert">{{ error }}</p><div class="roster"><article v-for="c in characters" :key="c.id"><img v-if="c.portrait" :src="c.portrait" :alt="c.name" /><h3>{{ c.name }}</h3><p>{{ c.occupation }} · {{ c.sphere }}</p><strong>{{ c.health }}</strong><p v-if="c.hp!==undefined">{{ c.hp }}/{{ c.pvMax }} PV · {{ c.pa }} PA · Round {{ c.round }} · {{ ['Neutre','Tendu','Paniqué'][c.stress] }} · {{ {v:'Voilé',sr:'Semi-révélé',r:'Révélé'}[c.revelation as 'v'|'sr'|'r'] }}</p><a v-if="c.canReadSheet" :href="`/characters/${c.id}/play?campaign=${campaignId}`" target="_blank" rel="noopener">Ouvrir en jeu ↗</a></article></div><p v-if="!characters.length">Aucune fiche partagée pour le moment.</p><details open><summary>Dernières actions et jets</summary><article v-for="e in events" :key="e.id" class="event"><small>{{ new Date(e.createdAt).toLocaleTimeString('fr-FR') }}</small><strong>{{ e.characterName }} · {{ e.payload.label }}</strong><span v-if="e.payload.dice">{{ e.payload.modifier }} + {{ e.payload.dice.join(' + ') }} = {{ e.payload.total }}{{ e.payload.exploded?' · Explosion':'' }}{{ e.payload.narrativeFailure?' · ÉCHEC NARRATIF':'' }}</span><span v-if="e.payload.before!==undefined">{{ e.payload.before }} → {{ e.payload.after }} PV</span><span v-if="e.payload.recovered!==undefined">+{{ e.payload.recovered }} PV</span></article></details></section></template>
<style scoped>.campaign-play{padding:20px;border:1px solid #355267;border-radius:8px;background:#0d1b2b}.roster{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(240px,100%),1fr));gap:16px}.roster article{border:1px solid #355267;border-radius:8px;padding:15px}.roster img{width:72px;height:90px;object-fit:cover;float:right;margin:0 0 10px 10px}.roster a{display:inline-block;padding:12px 0;color:#b7efff}.event{display:flex;gap:12px;flex-wrap:wrap;border-top:1px solid #355267;padding:12px 0}.event small{color:#aec0d0}summary{padding:16px 0;cursor:pointer}</style>
