<script setup lang="ts">
import {computed,ref,onUnmounted} from 'vue';
import {npcBudgetIssues,npcTalentEligible,type NpcData,type NpcCatalog} from '../../../api/src/campaign-npc-model';
import {characterDerivedStats} from '../lib/character-sheet';
import {prepareNpcPortrait} from '../lib/npc-portrait';
const props=defineProps<{data:NpcData;catalog:NpcCatalog;editable?:boolean}>();
const emit=defineEmits<{(e:'update:data',value:NpcData):void;(e:'image-busy',value:boolean):void}>();
const imageBusy=ref(false),imageError=ref('');let imageSeq=0;
const tier=computed(()=>props.catalog.tiers.find(t=>t.id===props.data.tierId));
const totals=computed(()=>({attributes:Object.values(props.data.attributes).reduce((a,b)=>a+b,0),skills:Object.values(props.data.skills).reduce((a,b)=>a+b,0)}));
const issues=computed(()=>npcBudgetIssues(props.data));
const derived=computed(()=>characterDerivedStats(id=>props.data.attributes[id]||0,id=>props.data.skills[id]||0,[]));
const descriptionFields=[{key:'appearance',label:'Apparence',max:1000},{key:'personality',label:'Caractère et façon de parler',max:1000},{key:'motivation',label:'Motivation',max:1000},{key:'secret',label:'Secret ou accroche MJ',max:3000},{key:'equipment',label:'Équipement réellement porté',max:2000},{key:'truthNotes',label:'Vérité et pouvoirs particuliers · notes MJ',max:3000},{key:'notes',label:'Notes de campagne',max:6000}] as const;
function patch(value:Partial<NpcData>){emit('update:data',{...props.data,...value});}
const value=(e:Event)=>(e.target as HTMLInputElement).value;
function stat(group:'attributes'|'skills',id:string,e:Event){patch({[group]:{...props.data[group],[id]:Number(value(e))}});}
function talent(id:string,on:boolean){patch({talentIds:on?[...props.data.talentIds,id]:props.data.talentIds.filter(t=>t!==id)});}
async function image(event:Event){const input=event.target as HTMLInputElement,file=input.files?.[0];if(!file)return;const n=++imageSeq;imageBusy.value=true;emit('image-busy',true);imageError.value='';try{const portrait=await prepareNpcPortrait(file);if(n===imageSeq)patch({portrait});}catch(e){if(n===imageSeq)imageError.value=(e as Error).message;}finally{if(n===imageSeq){imageBusy.value=false;emit('image-busy',false);}input.value='';}}
onUnmounted(()=>{imageSeq++;});
</script>
<template>
 <div class="npc-sheet">
  <div class="identity"><div class="portrait"><img v-if="data.portrait" :src="data.portrait" :alt="`Portrait de ${data.name}`" /><span v-else>Sans portrait</span><template v-if="editable"><label>Ajouter ou remplacer l’image<input type="file" accept="image/jpeg,image/png,image/webp" :disabled="imageBusy" @change="image" /></label><small>JPG, PNG ou WebP · 12 Mo maximum. L’image est réduite avant l’enregistrement.</small><button v-if="data.portrait" type="button" :disabled="imageBusy" @click="patch({portrait:''})">Retirer l’image</button><p v-if="imageBusy" role="status">Préparation de l’image…</p><p v-if="imageError" role="alert">{{ imageError }}</p></template></div>
   <div class="identity-fields"><template v-if="editable"><label>Nom du PNJ<input :value="data.name" maxlength="120" required @input="patch({name:value($event)})" /></label><label>Rôle<input :value="data.role" maxlength="160" @input="patch({role:value($event)})" /></label><label>Faction ou groupe<input :value="data.faction" maxlength="160" @input="patch({faction:value($event)})" /></label><label>Tags du PNJ<input :value="data.tags.join(', ')" maxlength="730" placeholder="Séparés par des virgules" @change="patch({tags:value($event).split(',').map(t=>t.trim()).filter(Boolean)})" /></label></template><template v-else><h3>{{ data.name }}</h3><p>{{ data.role }}{{ data.faction?' · '+data.faction:'' }}</p><p>{{ data.tags.join(' · ') }}</p></template><strong>{{ tier?.name }} · Profil de Réalité</strong><small>{{ totals.attributes }}/{{ tier?.attributes }} attributs · {{ totals.skills }}/{{ tier?.skills }} compétences · plafond ordinaire {{ tier?.cap }}</small></div>
  </div>
  <ul v-if="issues.length" role="alert"><li v-for="issue in issues" :key="issue">{{ issue }}</li></ul>
  <div class="story"><template v-for="field in descriptionFields" :key="field.key"><label v-if="editable">{{ field.label }}<textarea :value="data[field.key]" :maxlength="field.max" rows="2" @input="patch({[field.key]:value($event)})" /></label><div v-else-if="data[field.key]"><h4>{{ field.label }}</h4><p class="prose">{{ data[field.key] }}</p></div></template></div>
  <details :open="!editable" class="mechanics"><summary>Profil statistique{{ editable?' · ajuster les valeurs':'' }}</summary>
   <h4>Attributs</h4><div class="stats"><div v-for="a in catalog.attributes" :key="a.id"><label v-if="editable">{{ a.name }}<input :value="data.attributes[a.id]" type="number" min="1" max="46" step="1" required @input="stat('attributes',a.id,$event)" /></label><template v-else><span>{{ a.name }}</span><strong>{{ data.attributes[a.id] }}</strong></template></div></div>
   <h4>Compétences</h4><div class="stats"><div v-for="s in catalog.skills.filter(s=>editable||data.skills[s.id]>0)" :key="s.id"><label v-if="editable">{{ s.name }}<input :value="data.skills[s.id]" type="number" min="0" :max="s.id===data.apexSkill?15:tier?.cap" step="1" required @input="stat('skills',s.id,$event)" /></label><template v-else><span>{{ s.name }}</span><strong>{{ data.skills[s.id] }}{{ data.apexSkill===s.id?' · Apex':'' }}</strong><small>Jet : {{ data.skills[s.id]+data.attributes[s.attribute] }} + 1d10e</small></template></div></div>
   <details v-if="editable&&['heroique','legendaire'].includes(data.tierId)"><summary>Apex · spécialité exceptionnelle</summary><label>Compétence Apex<select :value="data.apexSkill" aria-label="Compétence Apex" @change="patch({apexSkill:value($event)})"><option value="">Aucune</option><option v-for="s in catalog.skills" :key="s.id" :value="s.id">{{ s.name }}</option></select></label><label v-if="data.apexSkill">Spécialité documentée<textarea :value="data.apexReason" maxlength="1000" rows="2" @input="patch({apexReason:value($event)})" /></label><small>Monte cette compétence à 15 en ajustant les autres rangs : les points Apex restent compris dans le budget.</small></details>
   <p v-else-if="data.apexSkill">Apex : {{ data.apexReason }}</p>
  </details>
  <h4>Valeurs pour jouer</h4><dl class="derived"><div><dt>PV / seuil de Mort</dt><dd>{{ derived.pvMax }} / {{ derived.death }}</dd></div><div><dt>Défense passive / active</dt><dd>{{ derived.passiveDefense }} / {{ derived.passiveDefense }} + 1d10e</dd></div><div><dt>Défense occulte passive / active</dt><dd>{{ derived.occultDefense }} / {{ derived.occultDefense }} + 1d10e</dd></div><div><dt>Initiative / déplacement</dt><dd>{{ derived.initiative }} + 1d10e / {{ derived.movement }} m par PA</dd></div><div><dt>Intégrité / Stress augmentique max</dt><dd>{{ derived.integrity }} / {{ derived.augmentStressMax }}</dd></div><div><dt>Armure portée</dt><dd><input v-if="editable" :value="data.armor" aria-label="Armure portée" type="number" min="0" max="100" required @input="patch({armor:Number(value($event))})" /><span v-else>{{ data.armor }}</span></dd></div></dl>
  <details :open="!editable"><summary>Talents PNJ · {{ data.talentIds.length }}{{ data.apexSkill?' + Apex':'' }} · repère : {{ tier?.talents }}</summary><p>Les conditions indiquées doivent être réunies en jeu. Les appuis et l’équipement ne sont pas accordés par le palier.</p><article v-for="t in catalog.talents.filter(t=>editable||data.talentIds.includes(t.id))" :key="t.id" class="talent"><label v-if="editable" class="check"><input type="checkbox" :checked="data.talentIds.includes(t.id)" :disabled="!data.talentIds.includes(t.id)&&!npcTalentEligible(t.id,data.skills)" @change="talent(t.id,($event.target as HTMLInputElement).checked)" />{{ t.name }}</label><strong v-else>{{ t.name }}</strong><label v-if="editable&&t.id==='Expertise éprouvée'&&data.talentIds.includes(t.id)">Compétence de l’expertise<select :value="data.expertiseSkill" @change="patch({expertiseSkill:value($event)})"><option value="">Choisir une compétence</option><option v-for="s in catalog.skills.filter(s=>data.skills[s.id]>=7)" :key="s.id" :value="s.id">{{ s.name }}</option></select></label><p v-else-if="!editable&&t.id==='Expertise éprouvée'">{{ catalog.skills.find(s=>s.id===data.expertiseSkill)?.name }}</p><small>{{ t.prerequisite }}</small><p>{{ t.effect }}</p></article></details>
 </div>
</template>
<style scoped>
.npc-sheet{display:grid;gap:16px;min-width:0;overflow-wrap:anywhere}.identity{display:grid;grid-template-columns:minmax(140px,220px) 1fr;gap:20px}.portrait{display:grid;gap:10px;align-content:start}.portrait>img{width:100%;max-height:280px;object-fit:contain;background:#080f19;border-radius:6px}.portrait>span{padding:25px;text-align:center;border:1px dashed #405875;color:#a3b7cc}.identity-fields,.story{display:grid;gap:12px}.npc-sheet label{display:grid;gap:7px}.npc-sheet input:not([type=checkbox]),textarea,select{min-width:0;box-sizing:border-box;width:100%;padding:10px;min-height:44px;background:#08131f;color:#edf4ff;border:1px solid #405875;border-radius:6px;font:inherit}textarea{resize:vertical}.stats,.derived{display:grid;grid-template-columns:repeat(auto-fit,minmax(125px,1fr));gap:10px}.stats>div,.derived>div{padding:10px;background:#132536;border:1px solid #304c62;border-radius:6px}.stats strong,.stats span{display:block}.derived{margin:0}.derived dt,small{color:#a3b7cc;line-height:1.6}.derived dd{margin:6px 0 0}.prose{white-space:pre-wrap}h4{margin:8px 0}.npc-sheet p{line-height:1.65}.check{display:flex!important;gap:8px;align-items:center;min-height:44px}.check input{width:20px;height:20px}.talent{padding:10px 0;border-bottom:1px solid #304c62}.talent small{display:block}summary{cursor:pointer;min-height:44px;align-content:center}button{padding:10px;min-height:44px;background:#101e30;color:#eaf2ff;border:1px solid #405875;border-radius:6px;font:inherit;cursor:pointer}input:focus-visible,textarea:focus-visible,select:focus-visible,button:focus-visible,summary:focus-visible{outline:2px solid #a3eaff;outline-offset:3px}@media(max-width:600px){.identity{grid-template-columns:1fr}.portrait{max-width:220px}.stats,.derived{grid-template-columns:repeat(2,minmax(0,1fr))}}
</style>
