<script setup lang="ts">
import {computed,onMounted,onUnmounted,ref,shallowRef,watch} from 'vue';
import {RouterLink} from 'vue-router';
import {api,ApiError} from '../lib/api';
import type {CharacterDataV2} from '../types/character';
import {buildCharacterSheet,type SheetCore} from '../lib/character-sheet-model';
import {ensureTruthRulesPackage,type TruthRulesPackage,truthAvailableTalents,type TruthState} from '../lib/truth';
import type {RealityRulesPackage} from '../lib/reality';
type Admission={userId:string;displayName:string;version:number;status:string;characterId:string|null;name:string;characterVersion:number;data:CharacterDataV2;baseline:CharacterDataV2;sourceVersion:number;sourceName:string;sourceCampaign:string|null;messages:{kind:string;message:string;at:string;author:string|null}[]};
const props=defineProps<{campaignId:string;canManage:boolean;refreshKey?:number}>();
const emit=defineEmits<{(e:'updated'):void}>();
const rows=ref<Admission[]>([]),rules=ref(''),notes=ref<Record<string,string>>({}),busy=ref(false),loading=ref(false),error=ref(''),notice=ref(''),core=shallowRef<SheetCore|null>(null),truth=shallowRef<TruthRulesPackage|null>(null),reality=shallowRef<RealityRulesPackage|null>(null);
const labels:Record<string,string>={none:'Aucune fiche proposée',pending:'À valider',changes_requested:'Modifications demandées',rejected:'Refusée',approved:'Acceptée'};
const actionable=computed(()=>rows.value.filter(r=>r.characterId&&r.status!=='approved').length);
let seq=0;
async function load(){const n=++seq;loading.value=true;error.value='';try{
 const r=await api<{admissions:Admission[];rules:string}>(`/api/campaigns/${props.campaignId}/admissions`);if(n!==seq)return;rows.value=r.admissions;rules.value=r.rules;
 if(r.admissions.some(r=>r.characterId)&&!core.value){const [c,t,e]=await Promise.all([api<SheetCore>('/api/rulesets/terra-umbra/creation'),api<TruthRulesPackage>('/api/rulesets/terra-umbra/truth'),api<RealityRulesPackage>('/api/rulesets/terra-umbra/reality')]);if(n!==seq)return;core.value=c;truth.value=ensureTruthRulesPackage(t);reality.value=e;}
 }catch(e){if(n!==seq)return;error.value='Impossible de charger les admissions et leurs bilans.';if(e instanceof ApiError&&[401,403,404].includes(e.status))rows.value=[];}finally{if(n===seq)loading.value=false;}}
function summary(d:CharacterDataV2){if(!core.value||!truth.value||!reality.value)return null;try{const p0=d.progression||{};const ranks=[...Object.values((p0.skillRanks||{}) as Record<string,number>),...Object.values((p0.attributeRanks||{}) as Record<string,number>)];if(ranks.some(n=>!Number.isInteger(n)||n<0||n>100))return null;const known=new Set([...Object.values(truth.value.catalogs).flat().map(t=>t.id),...truthAvailableTalents(truth.value,d.truth as TruthState).map(t=>t.id),...truth.value.corruption.talents.map(t=>t.id)]);const chosen=[...(Array.isArray(d.truth.truthTalents)?d.truth.truthTalents:[]),...(Array.isArray(d.truth.corruptionTalents)?d.truth.corruptionTalents:[]),...(Array.isArray(p0.truthTalents)?p0.truthTalents:[]),...(Array.isArray(p0.corruptionTalents)?p0.corruptionTalents:[])];const unknown=chosen.some(id=>!known.has(String(id)));const s=buildCharacterSheet(d,core.value,truth.value,reality.value),p=d.progression||{},tx=Array.isArray(p.cashTransactions)?p.cashTransactions:[];return {unknown,origin:core.value.rules.origins[d.creation.origin]?.name||d.creation.origin||'Non choisie',sphere:s.sphere,nature:s.truthNature,xp:Number(p.xpEarned)||0,xpSpent:(Number(p.xpEarned)||0)-s.xpRemaining,ptv:Number(p.ptvEarned)||0,ptvSpent:truth.value.structure.ptvInitial+(Number(p.ptvEarned)||0)-s.ptvRemaining,cash:s.cash,income:tx.reduce((n:number,t:any)=>n+Math.max(0,Number(t.amount)||0),0),expenses:tx.reduce((n:number,t:any)=>n+Math.max(0,-Number(t.amount)||0),0),corruption:s.corruption,source:s.corruptionSource};}catch{return null;}}
const summaries=computed(()=>Object.fromEntries(rows.value.filter(r=>r.characterId).map(r=>[r.userId,summary(r.data)])));
async function review(r:Admission,status:string){
 if(busy.value)return;const message=notes.value[r.userId]||'';
 if(status!=='approved'&&!message.trim()){error.value='Précise ce que le joueur doit changer ou pourquoi sa fiche est refusée.';return;}
 if(!window.confirm(`${status==='approved'?'Accepter cette version et tous ses acquis actuels pour la campagne':status==='changes_requested'?'Demander une nouvelle proposition':'Refuser cette fiche'} : ${r.name} ?`))return;
 busy.value=true;error.value='';try{await api(`/api/campaigns/${props.campaignId}/admissions/${r.userId}`,{method:'PATCH',body:JSON.stringify({status,message,version:r.version,characterId:r.characterId,characterVersion:r.characterVersion})});notes.value[r.userId]='';notice.value='Décision enregistrée et visible par le joueur.';await load();emit('updated');}catch(e){error.value=e instanceof Error&&e.message==='admission_version_conflict'?'La proposition ou la fiche a changé. Actualise le bilan avant de décider. Ton commentaire est conservé.':'Impossible d’enregistrer cette décision.';}finally{busy.value=false;}
}
async function resubmit(r:Admission){if(busy.value)return;busy.value=true;error.value='';try{await api(`/api/campaigns/${props.campaignId}/membership`,{method:'PUT',body:JSON.stringify({characterId:r.characterId,message:notes.value[r.userId]||''})});notes.value[r.userId]='';notice.value='Version actuelle soumise au MJ.';await load();emit('updated');}catch{error.value='Impossible de soumettre cette fiche.';}finally{busy.value=false;}}
watch(()=>props.refreshKey,()=>void load());
function focus(){if(document.visibilityState!=='hidden'&&!busy.value&&!loading.value&&!Object.values(notes.value).some(n=>n.trim()))void load();}
onMounted(()=>{void load();window.addEventListener('focus',focus);});onUnmounted(()=>{seq++;window.removeEventListener('focus',focus);});
</script>
<template>
 <section class="admissions" aria-label="Validation des personnages">
  <div class="head"><div><h2>{{ canManage?'Admissions des personnages':'Ma proposition de personnage' }}</h2><p v-if="canManage">{{ actionable }} fiche(s) à examiner. Les gains de séance s’appliquent uniquement aux versions acceptées.</p></div><button :disabled="busy||loading" @click="load">Actualiser les admissions</button></div>
  <p v-if="rules" class="rules"><strong>Conditions de la table</strong><br />{{ rules }}</p><p v-if="error" role="alert">{{ error }}</p><p v-if="notice" role="status">{{ notice }}</p><p v-if="loading" role="status">Chargement des bilans…</p>
  <p v-if="!loading&&!rows.length">Aucun personnage proposé pour le moment.</p>
  <details v-for="r in rows" :key="r.userId" class="admission" :open="r.status!=='approved'">
   <summary><strong>{{ r.name||r.displayName }}</strong> · {{ labels[r.status]||r.status }}<small>{{ r.displayName }}</small></summary>
   <div class="body" v-if="r.characterId">
    <p>Version indépendante de cette campagne, issue de {{ r.sourceName||'la fiche source' }} · v{{ r.sourceVersion }}{{ r.sourceCampaign?` · ${r.sourceCampaign}`:' · hors campagne' }}.</p>
    <div v-if="summaries[r.userId]" class="bilan">
     <p><strong>Origine :</strong> {{ summaries[r.userId]!.origin }} · {{ summaries[r.userId]!.sphere }}<br /><strong>Nature :</strong> {{ summaries[r.userId]!.nature }}</p>
     <table><caption>Acquis de la fiche proposée · calculés depuis la fiche sauvegardée</caption><thead><tr><th>Ressource</th><th>Reçus en progression</th><th>Dépensés</th><th>Disponibles</th></tr></thead><tbody><tr><th>XP</th><td>{{ summaries[r.userId]!.xp }}</td><td>{{ summaries[r.userId]!.xpSpent }}</td><td>{{ summaries[r.userId]!.xp-summaries[r.userId]!.xpSpent }}</td></tr><tr><th>PTV</th><td>{{ summaries[r.userId]!.ptv }} + {{ truth?.structure.ptvInitial }} initiaux</td><td>{{ summaries[r.userId]!.ptvSpent }} (création incluse)</td><td>{{ (truth?.structure.ptvInitial||0)+summaries[r.userId]!.ptv-summaries[r.userId]!.ptvSpent }}</td></tr><tr><th>Argent</th><td>{{ summaries[r.userId]!.income }} $</td><td>{{ summaries[r.userId]!.expenses }} $</td><td>{{ summaries[r.userId]!.cash }} $</td></tr></tbody></table>
     <p v-if="summaries[r.userId]!.unknown" role="alert">Certaines capacités sont absentes du catalogue actuel : le coût PTV calculé peut être incomplet. Vérifie la fiche avant toute acceptation.</p><small>Les entrées et sorties d’argent couvrent les transactions enregistrées en progression ; le solde inclut aussi l’argent restant à la création.</small><p>Corruption : {{ summaries[r.userId]!.corruption }} · {{ summaries[r.userId]!.source||'Aucune Source' }}</p>
    </div><p v-else>Le bilan n’est pas disponible. Recharge les catalogues avant de valider.</p>
    <div class="actions"><RouterLink target="_blank" rel="noopener noreferrer" :to="{path:`/characters/${r.characterId}/sheet`,query:{campaign:campaignId}}">Examiner la fiche complète →</RouterLink><RouterLink target="_blank" rel="noopener noreferrer" v-if="!canManage" :to="`/characters/${r.characterId}/builder`">Modifier cette version →</RouterLink></div>
    <details v-if="r.messages.length"><summary>Échanges et décisions · {{ r.messages.length }}</summary><div v-for="(m,i) in r.messages" :key="i" class="message"><strong>{{ m.author||'Système' }} · {{ labels[m.kind]||({submitted:'Proposition du joueur',detached:'Fiche retirée',migration:'Séparation des versions'} as Record<string,string>)[m.kind]||m.kind }}</strong><p>{{ m.message||'Sans commentaire.' }}</p><small>{{ new Date(m.at).toLocaleString('fr-FR') }}</small></div></details>
    <label>{{ canManage?'Retour au joueur':'Message au MJ' }}<textarea v-model="notes[r.userId]" rows="3" maxlength="4000" :placeholder="canManage?'Ex. : cette table accepte uniquement les Crawlers. Propose une version adaptée.':'Explique tes corrections ou les acquis que tu souhaites conserver.'" /></label>
    <div class="actions" v-if="canManage"><button :disabled="busy||loading||!summaries[r.userId]" @click="review(r,'approved')">Accepter la fiche</button><button :disabled="busy" @click="review(r,'changes_requested')">Demander des modifications</button><button :disabled="busy" @click="review(r,'rejected')">Refuser la fiche</button></div><button v-else-if="r.status!=='approved'" :disabled="busy" @click="resubmit(r)">Soumettre ma version actuelle</button>
   </div><p v-else>Le joueur doit choisir une fiche.</p>
  </details>
 </section>
</template>
<style scoped>
.admissions{margin:24px 0;padding:22px;background:#0e1b2c;color:#eaf2ff;border:1px solid #405875;border-radius:10px;overflow-wrap:anywhere}.head,.actions{display:flex;gap:12px;align-items:center;justify-content:space-between;flex-wrap:wrap}.actions{justify-content:flex-start;margin:14px 0}h2{font-size:20px;margin:0}p{color:#b5c8dc;line-height:1.6}.rules,.message p{white-space:pre-wrap}.rules{border-left:2px solid #a995d4;padding:14px;background:#151d30}.admission{margin-top:16px;border:1px solid #3c4a65;border-radius:6px}.admission>summary{padding:14px}.body{padding:0 16px 16px}summary{min-height:44px;align-content:center;cursor:pointer}.admission>summary small{display:block}small{color:#a3b7cc;line-height:1.6}.bilan{overflow-x:auto}table{border-collapse:collapse;width:100%;margin:14px 0;font-size:14px}caption{text-align:left;margin:8px 0;color:#b5c8dc}td,th{padding:10px;text-align:left;border:1px solid #334b60}label{display:grid;gap:8px;margin-top:16px}textarea{box-sizing:border-box;width:100%;padding:12px;background:#08131f;color:#edf4ff;border:1px solid #405875;border-radius:6px;font:inherit;resize:vertical}button,.actions a{box-sizing:border-box;min-height:44px;padding:10px 14px;border:1px solid #405875;background:#101e30;border-radius:6px;color:#a3eaff;font:inherit;text-decoration:none;cursor:pointer}button:disabled{opacity:.5}.message{border-top:1px solid #293d52;padding:12px 0}button:focus-visible,a:focus-visible,summary:focus-visible{outline:2px solid #a3eaff;outline-offset:3px}@media(max-width:600px){.admissions{padding:14px}.body{padding-inline:10px}.actions>*{flex:1}.head{align-items:stretch;flex-direction:column}td,th{padding:7px}}
</style>
