<script setup lang="ts">
import {computed,onMounted,onUnmounted,ref} from 'vue';
import PortraitZoom from './PortraitZoom.vue';
import {api} from '../lib/api';
const props=defineProps<{campaignId:string}>();
const characters=ref<any[]>([]),events=ref<any[]>([]),error=ref('');
const latest=computed(()=>events.value.find(e=>e.payload?.dice));
let timer:ReturnType<typeof setInterval>|undefined,alive=true,loading=false;
async function load(){if(loading||document.visibilityState==='hidden')return;loading=true;try{const r=await api<any>(`/api/campaigns/${props.campaignId}/play`);if(alive){characters.value=r.characters;events.value=r.events;error.value='';}}catch{if(alive){characters.value=[];events.value=[];error.value='Le suivi de partie est indisponible.';}}finally{loading=false;}}
onMounted(()=>{void load();timer=setInterval(()=>void load(),3000);});onUnmounted(()=>{alive=false;clearInterval(timer);});
</script>
<template><section class="campaign-play"><header><div><h2>Le groupe en jeu</h2><p>État partagé des personnages.</p></div><a :href="`/campaigns/${campaignId}/play`">Ouvrir la table de jeu →</a></header><p v-if="error" role="alert">{{ error }}</p><div class="roster"><article v-for="c in characters" :key="c.id"><PortraitZoom v-if="c.portrait" :src="c.portrait" :name="c.name" /><div><h3>{{ c.name }}</h3><strong>{{ c.health }}</strong><p v-if="c.hp!==undefined">{{ c.hp }}/{{ c.pvMax }} PV · {{ c.pa }} PA</p><details><summary>Informations du personnage</summary><p>{{ [c.occupation,c.sphere].filter(Boolean).join(' · ') }}</p><p v-if="c.hp!==undefined">Round {{ c.round }} · {{ ['Neutre','Tendu','Paniqué'][c.stress] }} · {{ {v:'Voilé',sr:'Semi-révélé',r:'Révélé'}[c.revelation as 'v'|'sr'|'r'] }}</p><p v-if="c.initiative!=null">Initiative : {{ c.initiative }} · {{ c.paPerRound }} PA par round</p></details><a v-if="c.canReadSheet" :href="`/characters/${c.id}/play?campaign=${campaignId}`" target="_blank" rel="noopener">Ouvrir sa fiche ↗</a></div></article></div><p v-if="!characters.length">Aucune fiche partagée pour le moment.</p><p v-if="latest" class="latest-result">{{latest.characterName??latest.payload.characterName??'MJ'}} · {{latest.payload.label}} → <strong>{{latest.payload.total}}</strong><span v-if="latest.payload.narrativeFailure"> · Échec narratif</span></p><details class="group-history"><summary>Journal récent · {{events.length}} événements</summary><article v-for="e in events" :key="e.id" class="event"><small>{{ new Date(e.createdAt).toLocaleTimeString('fr-FR') }}</small><strong>{{ e.characterName }} · {{ e.payload.label }}</strong><span v-if="e.payload.dice">{{ e.payload.modifier }} + {{ e.payload.dice.join(' + ') }} = {{ e.payload.total }}{{ e.payload.exploded?' · Explosion':'' }}{{ e.payload.narrativeFailure?' · ÉCHEC NARRATIF':'' }}</span><span v-if="e.payload.before!==undefined">{{ e.payload.before }} → {{ e.payload.after }} PV</span><span v-if="e.payload.recovered!==undefined">+{{ e.payload.recovered }} PV</span></article></details></section></template>
<style scoped>.campaign-play>header{display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap}.campaign-play h2{margin:0}.campaign-play header p{margin:6px 0;color:#aec0d0}.roster article{display:flex;gap:12px;min-width:0}.roster article>div{min-width:0;flex:1}.roster h3{margin:0 0 6px}.latest-result{padding:10px 12px;background:#142536;border-radius:6px}.group-history:not([open]){border-top:1px solid #355267}.campaign-play :focus-visible{outline:2px solid #b7efff;outline-offset:3px}.campaign-play{padding:20px;border:1px solid #355267;border-radius:8px;background:#0d1b2b}.roster{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(240px,100%),1fr));gap:16px}.roster article{border:1px solid #355267;border-radius:8px;padding:15px}.roster img{width:72px;height:90px;object-fit:cover;float:right;margin:0 0 10px 10px}.roster a{display:inline-block;padding:12px 0;color:#b7efff}.event{display:flex;gap:12px;flex-wrap:wrap;border-top:1px solid #355267;padding:12px 0}.event small{color:#aec0d0}summary{padding:16px 0;cursor:pointer}</style>
