<script setup lang="ts">
import {computed,onMounted,onUnmounted,ref,watch} from 'vue';
import {terraUmbraCreationRules} from '../../../api/src/rules/terra-umbra-creation';
import {api,ApiError} from '../lib/api';
const props=defineProps<{campaignId:string;room:any}>(),emit=defineEmits<{changed:[];attention:[count:number]}>();
const endpoint=`/api/campaigns/${props.campaignId}/occult-resolutions`,sources=ref<any[]>([]),maintained=ref<any[]>([]),consent=ref<any[]>([]),sourceId=ref(''),targetId=ref(''),kind=ref('damage'),hostile=ref(true),defenseKind=ref('occult'),protection=ref(0),amount=ref(1),note=ref(''),confirmed=ref(false),sustain=ref(false),rollId=ref(''),error=ref(''),busy=ref(false),request=ref<any>(null);
const effectDistance=ref(0),additionalTargets=ref<string[]>([]),effectName=ref(''),scope=ref('mental'),skill=ref(''),effectAmount=ref(-3),duration=ref('scene'),rounds=ref(1);
const source=computed(()=>sources.value.find(s=>s.id===sourceId.value)),targets=computed(()=>[...(props.room.characters??[]),...(props.room.combatants??[])]),rolls=computed(()=>source.value?.rolls??[]);
const skills=terraUmbraCreationRules.skills;
const sovereignty=computed(()=>source.value?.payload.powerId==='belial_la_reine_des_dieux_facette_domination_souverainete_de_belial'),phantasm=computed(()=>source.value?.payload.powerId==='daemon_clean_oracle_tentateur_fantasmagorie_fantasmagorie');
const resolveReady=computed(()=>!busy.value&&confirmed.value&&!!targetId.value&&!!note.value.trim()&&(kind.value!=='condition'||Number.isFinite(effectDistance.value)&&effectDistance.value>=0&&(!sovereignty.value||effectDistance.value<=15))&&(!(kind.value==='effects'||kind.value==='condition'&&phantasm.value)||duration.value!=='round'||Number.isSafeInteger(rounds.value)&&rounds.value>=1&&rounds.value<=100));
let alive=true,timer:ReturnType<typeof setInterval>;
async function load(){if(!alive||document.visibilityState==='hidden')return;try{const r=await api<any>(endpoint);if(!alive)return;sources.value=r.sources??[];maintained.value=r.maintained??[];consent.value=r.consent??[];emit('attention',sources.value.length);if(!sources.value.some(s=>s.id===sourceId.value))sourceId.value=sources.value[0]?.id??'';}catch{error.value='Impossible de charger les effets à résoudre.';}}
watch([sourceId,targetId,kind,hostile,defenseKind,protection,amount,effectName,scope,skill,effectAmount,duration,rounds,rollId,effectDistance,note,sustain,()=>additionalTargets.value.join('|')],()=>{confirmed.value=false;});
watch(sourceId,()=>{rollId.value='';sustain.value=false;});
async function send(action:string,extra:any){if(busy.value)return;if(!request.value)request.value={requestId:crypto.randomUUID(),action,...extra};busy.value=true;error.value='';try{await api(endpoint,{method:'POST',body:JSON.stringify(request.value)});request.value=null;confirmed.value=false;await load();emit('changed');}catch(e){error.value=e instanceof ApiError&&e.status===409?'La cible ou cette résolution a changé. Actualise et recommence.':e instanceof ApiError?({'occult_consent_required':'Le bénéficiaire doit accepter cette intervention.','occult_defense_required':'Choisis une défense pertinente avant de résoudre.','insufficient_pa':'Pas assez de PA pour maintenir cet effet.'} as Record<string,string>)[e.message]??'Résolution non confirmée. Vérifie le jet, la cible et les conditions.':'Résolution non confirmée. Réessaie la même action.';if(e instanceof ApiError&&e.status<500)request.value=null;}finally{busy.value=false;}}
async function targetVersion(){const target=targets.value.find((t:any)=>t.id===targetId.value);if(!target)throw Error('target');if((props.room.characters??[]).some((t:any)=>t.id===targetId.value))return (await api<any>(`/api/characters/${targetId.value}/play`)).version;return target.version;}
async function resolve(){if(!resolveReady.value||!sourceId.value)return;try{const version=await targetVersion();const target:any={actorId:targetId.value,version,hostile:hostile.value,function:kind.value,defenseKind:defenseKind.value,defenseConfirmed:true,protection:protection.value,protectionConfirmed:true,protectionNote:note.value};if(kind.value==='condition'&&phantasm.value)target.duration=duration.value==='round'?{unit:'round',value:rounds.value}:{unit:'scene'};if(kind.value==='healing'){target.amount=amount.value;target.healingConfirmed=true;}if(kind.value==='effects')target.effects=[{name:effectName.value,kind:'modifier',scope:scope.value,amount:effectAmount.value,...(scope.value==='skill'?{skill:skill.value}:{}),duration:duration.value==='round'?{unit:'round',value:rounds.value}:{unit:'scene'}}];await send('resolve',{sourceEventId:sourceId.value,...(rollId.value?{rollEventId:rollId.value}:{}),confirmed:true,ruling:note.value,maintained:sustain.value,targets:[{...target,distance:effectDistance.value,contextConfirmed:confirmed.value},...await Promise.all(additionalTargets.value.filter(id=>id!==targetId.value).map(async(id)=>{const row=targets.value.find(t=>t.id===id),pc=(props.room.characters??[]).some((t:any)=>t.id===id);return {...target,actorId:id,version:pc?(await api<any>(`/api/characters/${id}/play`)).version:row.version,distance:effectDistance.value,contextConfirmed:confirmed.value};}))]});}catch{error.value='Impossible de lire la version de la cible.';}}
function requestConsent(){void send('request-consent',{sourceEventId:sourceId.value,targets:[...new Set([targetId.value,...additionalTargets.value])].map(actorId=>({actorId})),note:note.value});}
onMounted(()=>{void load();timer=setInterval(()=>void load(),5000);});onUnmounted(()=>{alive=false;clearInterval(timer);});
</script>
<template>
<section class="occult-resolutions" aria-label="Résolution des effets occultes">
 <p v-if="error" role="alert">{{error}}</p><button v-if="request&&!busy" @click="send(request.action,{})">Réessayer la résolution non confirmée</button>
 <p v-if="!sources.length">Aucun sort ou pouvoir libéré à résoudre.</p>
 <form v-else @submit.prevent="resolve">
  <label>Sort ou pouvoir libéré<select v-model="sourceId" required><option v-for="s in sources" :key="s.id" :value="s.id">{{s.sourceName}} · {{s.payload.label}}</option></select></label>
  <p v-if="source?.payload.total!=null">Jet {{source.payload.total}}<span v-if="source.payload.narrativeFailure"> · échec narratif</span></p>
  <div class="fields"><label>Cible de l’effet<select v-model="targetId" required><option value="">Choisir…</option><option v-for="t in targets" :key="t.id" :value="t.id">{{t.name}}</option></select></label><label>Conséquence retenue<select v-model="kind"><option value="damage">Dégâts du sort</option><option value="healing">Soin arbitré</option><option value="effects">Modificateur temporaire arbitré</option><option value="condition">Injonction ou illusion prévue par ce pouvoir</option></select></label></div>
  <details><summary>Autres cibles de cette même conséquence</summary><label v-for="t in targets.filter((t:any)=>t.id!==targetId)" :key="t.id" class="check"><input v-model="additionalTargets" type="checkbox" :value="t.id" /> {{t.name}}</label></details><label v-if="kind==='condition'">Distance jusqu’à chaque cible (m)<input v-model.number="effectDistance" type="number" min="0" :max="sovereignty?15:10000" /></label>
  <label class="check"><input v-model="hostile" type="checkbox" /> Intervention hostile</label>
  <template v-if="!hostile"><button type="button" :disabled="busy||!targetId||!note.trim()" @click="requestConsent">Demander l’accord du bénéficiaire</button><p v-if="consent.some(c=>c.actorId===targetId&&c.sourceEventId===sourceId)">Accord du bénéficiaire reçu.</p></template>
  <div v-if="hostile" class="fields"><label>Défense pertinente<select v-model="defenseKind"><option value="occult">Occulte · Force mentale</option><option value="physical">Physique · Esquive</option></select></label><label>Protection applicable<input v-model.number="protection" type="number" min="0" max="100" /></label></div>
  <div v-if="hostile"><button type="button" :disabled="busy||!targetId||!note.trim()" @click="send('request-defense',{sourceEventId:sourceId,defenseKind,targets:[...new Set([targetId,...additionalTargets])].map(actorId=>({actorId})),note})">Proposer le choix de défense au joueur</button></div>
  <label v-if="kind==='healing'">PV rendus avant plafond de soin<input v-model.number="amount" type="number" min="1" max="100" /></label>
  <template v-if="kind==='effects'"><label>Nom de l’effet<input v-model="effectName" maxlength="150" required /></label><div class="fields"><label>Tests affectés<select v-model="scope"><option value="physical">Physiques</option><option value="mental">Mentaux</option><option value="intellectual">Intellectuels</option><option value="social">Sociaux</option><option value="visual">Visuels</option><option value="skill">Une compétence</option><option value="defense-physical">Défense physique</option><option value="defense-occult">Défense occulte</option></select></label><label v-if="scope==='skill'">Compétence<select v-model="skill" required><option value="">Choisir…</option><option v-for="s in skills" :key="s.id" :value="s.id">{{s.name}}</option></select></label><label>Bonus ou malus<input v-model.number="effectAmount" type="number" min="-100" max="100" required /></label><label>Durée<select v-model="duration"><option value="scene">Cette scène</option><option value="round">Rounds</option></select></label><label v-if="duration==='round'">Nombre de rounds<input v-model.number="rounds" type="number" min="1" max="100" required /></label></div></template>
  <div v-if="kind==='condition'&&phantasm" class="fields"><label>Durée de l’illusion<select v-model="duration"><option value="scene">Cette scène</option><option value="round">Rounds</option></select></label><label v-if="duration==='round'">Nombre de rounds<input v-model.number="rounds" type="number" min="1" max="100" required /></label></div>
  <details><summary>Jet complémentaire et maintien</summary><label>Jet du pouvoir si absent à la libération<select v-model="rollId"><option value="">Jet de libération</option><option v-for="e in rolls" :key="e.id" :value="e.id">{{e.payload.label}} · {{e.payload.total}}</option></select></label><label class="check"><input v-model="sustain" type="checkbox" /> Maintenir cet effet selon les règles du sort</label></details>
  <button type="button" :disabled="busy||!sourceId||!note.trim()||!confirmed" @click="send('cancel',{sourceEventId:sourceId,confirmed:true,note})">Classer sans conséquence · aucun coût remboursé</button>
  <label>Arbitrage du MJ<input v-model="note" maxlength="500" required placeholder="Portée, protection, conséquence réellement possible…" /></label><label class="check"><input v-model="confirmed" type="checkbox" /> J’ai vérifié la portée, la cible et la conséquence dans les règles.</label><button :disabled="!resolveReady">Résoudre sur cette cible</button>
 </form>
 <article v-for="m in maintained" :key="m.id"><strong>{{m.payload.label??'Effet maintenu'}}</strong><button :disabled="busy" @click="send('maintain',{resolutionId:m.id,version:m.payload.sourceVersion})">Maintenir · 1 PA</button><button :disabled="busy" @click="send('end-maintenance',{resolutionId:m.id,version:m.payload.sourceVersion})">Arrêter le maintien</button></article>
</section>
</template>
<style scoped>
.occult-resolutions{min-width:0}.fields{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,180px),1fr));gap:12px}label{display:grid;gap:6px;margin:12px 0}.check{display:flex;align-items:center}input:not([type=checkbox]),select{width:100%;box-sizing:border-box;min-width:0;padding:10px;border:1px solid #55778d;border-radius:5px;background:#0b1827;color:#edf4fb;font:inherit}button{min-height:44px;padding:10px;margin:6px;border:1px solid #698fa7;border-radius:5px;background:#17394e;color:#edf4fb;cursor:pointer}button:disabled{opacity:.5}summary{cursor:pointer;padding:10px}article{padding:12px;border:1px solid #55778d;margin-top:12px}
</style>
