<script setup lang="ts">
import {computed,ref,watch} from 'vue';
import {api,ApiError} from '../lib/api';
const props=defineProps<{campaignId:string;room:any}>(),emit=defineEmits<{changed:[]}>();
const endpoint=`/api/campaigns/${props.campaignId}/lightning-effects`,open=ref(false),snapshot=ref<any>(null),sourceId=ref(''),powerId=ref(''),confirmed=ref(false),edge=ref(false),busy=ref(false),error=ref(''),notice=ref(''),pending=ref<any>(null);
const picks=ref([{actorId:'',effectId:'',distance:20,threshold:18,originalTotal:null as number|null,note:'',interruptible:false,metaphysical:false,perceived:false}]);
const source=computed(()=>snapshot.value?.sources.find((s:any)=>s.id===sourceId.value)),power=computed(()=>source.value?.powers.find((p:any)=>p.id===powerId.value));
const eclipse=computed(()=>power.value?.name==='Éclipse noire');
const target=(id:string)=>snapshot.value?.targets.find((t:any)=>t.id===id);
const selected=(pick:any)=>target(pick.actorId)?.effects.find((e:any)=>e.id===pick.effectId);
const effects=(pick:any)=>(target(pick.actorId)?.effects??[]).filter((e:any)=>power.value?.name!=='Éroder l’affliction'||e.numericMalus);
const ready=computed(()=>!!power.value&&!busy.value&&!pending.value&&confirmed.value&&picks.value.length>0&&picks.value.every(p=>selected(p)&&p.note.trim()&&p.distance>=0&&p.distance<=20&&(!eclipse.value||selected(p)?.temporary&&p.metaphysical&&p.perceived)));
watch([sourceId,powerId],()=>{confirmed.value=false;edge.value=false;picks.value=picks.value.slice(0,1);});
watch(picks,()=>{confirmed.value=false;},{deep:true});
async function load(){try{snapshot.value=await api<any>(endpoint);if(!source.value)sourceId.value=snapshot.value.sources[0]?.id??'';}catch{error.value='Impossible de charger les effets actifs.';}}
watch(open,v=>{if(v)void load();});
const messages:Record<string,string>={lightning_version_conflict:'Une fiche a changé. Actualise puis confirme à nouveau.',foudre_effect_closed:'L’effet ou le jet a expiré.',foudre_source_unavailable:'Le lanceur doit être Révélé, conscient et disposer des PA nécessaires.',foudre_effect_unavailable:'Talent indisponible : vérifie les prérequis, la Révélation et le quota.',foudre_effect_source_roll_required:'Réduire en poussière exige le même jet payé et réussi contre cet effet.',foudre_affliction_not_numeric:'Cet effet n’est pas un malus chiffré atténuable.',foudre_effect_already_weakened:'Cet effet est déjà atténué pour la scène.',foudre_effect_ruling_required:'Confirme un effet magique réellement interruptible selon la règle.',insufficient_edge:'Pas assez d’Edge.',edge_roll_resolved:'Ce jet a déjà été engagé ou forcé.'};
async function send(body:any){if(busy.value||pending.value)return;pending.value={requestId:crypto.randomUUID(),...body};await retry();}
async function retry(){if(busy.value||!pending.value)return;busy.value=true;error.value='';try{const r=await api<any>(endpoint,{method:'POST',body:JSON.stringify(pending.value)});pending.value=null;const p=r.result;notice.value=p?`${p.characterName} · ${p.label} : ${p.modifier} + ${p.dice.join(' + ')} = ${p.total}${p.narrativeFailure?' · échec narratif':''}. ${p.outcomes.map((o:any)=>`${o.targetName} : ${o.result==='destroy'?'effet détruit':o.result==='suspend-scene'?'suspendu pour la scène':o.result==='weaken-scene'?'malus atténué de 3 pour la scène':'effet inchangé'}`).join(' ; ')}`:'Action déjà enregistrée.';confirmed.value=false;edge.value=false;await load();emit('changed');}catch(e){error.value=e instanceof ApiError?messages[e.message]??'Action refusée. Vérifie les conditions puis actualise.':'Envoi non confirmé. Réessaie le même envoi.';if(e instanceof ApiError&&e.status<500){pending.value=null;await load();}}finally{busy.value=false;}}
function launch(){if(!ready.value)return;void send({action:'resolve',sourceId:sourceId.value,sourceVersion:source.value.version,powerId:powerId.value,edge:edge.value,contextConfirmed:true,targets:picks.value.map(p=>({actorId:p.actorId,effectId:p.effectId,version:target(p.actorId).version,distance:p.distance,ruling:{magical:true,note:p.note,threshold:p.threshold,...(typeof p.originalTotal==='number'&&Number.isFinite(p.originalTotal)?{originalTotal:p.originalTotal}:{}),interruptible:p.interruptible,metaphysical:p.metaphysical,perceived:p.perceived}}))});}
function extra(action:string,e:any){const s=snapshot.value.sources.find((s:any)=>s.id===e.payload.sourceId);if(!s)return;void send({action,sourceRollId:e.id,sourceVersion:s.version,targetVersions:Object.fromEntries(e.payload.input.targets.map((t:any)=>[t.actorId,t.actorId===s.id?s.version:target(t.actorId)?.version]))});}
function canDust(e:any){return snapshot.value.sources.some((s:any)=>s.id===e.payload.sourceId&&s.dust)&&!e.payload.narrativeFailure&&e.payload.outcomes.some((o:any)=>o.success&&target(o.actorId)?.effects.some((f:any)=>f.id===o.effectId));}
function canForce(e:any){return !e.payload.edgeBefore&&!e.payload.edgeForced&&e.payload.outcomes.every((o:any)=>!o.success)&&snapshot.value.sources.some((s:any)=>s.id===e.payload.sourceId&&s.edge>0)&&e.payload.input.targets.every((t:any)=>target(t.actorId)?.effects.some((f:any)=>f.id===t.effectId));}
</script>
<template>
<details v-if="room.canManage" class="lightning-effects" :open="open" @toggle="open=($event.target as HTMLDetailsElement).open">
 <summary>Dissiper ou atténuer un effet · Foudre</summary>
 <p v-if="error" role="alert">{{error}} <button v-if="pending" :disabled="busy" @click="retry">Réessayer cet envoi</button></p><p v-if="notice" role="status">{{notice}}</p>
 <template v-if="snapshot">
  <form v-if="snapshot.sources.length&&snapshot.targets.length" @submit.prevent="launch"><fieldset :disabled="busy||!!pending">
   <div class="fields"><label>Lanceur<select v-model="sourceId"><option v-for="s in snapshot.sources" :key="s.id" :value="s.id">{{s.name}}</option></select></label><label>Talent<select v-model="powerId"><option value="">Choisir…</option><option v-for="p in source?.powers??[]" :key="p.id" :value="p.id">{{p.name}} · {{p.cost}} PA en combat</option></select></label></div>
   <div v-for="(pick,index) in picks" :key="index" class="effect-pick">
    <div class="fields"><label>Porteur de l’effet<select v-model="pick.actorId" @change="pick.effectId='' "><option value="">Choisir…</option><option v-for="t in snapshot.targets" :key="t.id" :value="t.id">{{t.name}}</option></select></label><label>Effet actif<select v-model="pick.effectId"><option value="">Choisir…</option><option v-for="e in effects(pick)" :key="e.id" :value="e.id">{{e.name}}</option></select></label></div>
    <p v-if="selected(pick)">{{selected(pick).description}}</p>
    <div class="fields"><label>Distance réelle (m)<input v-model.number="pick.distance" type="number" min="0" max="20" /></label><label>Puissance sans jet connu<select v-model.number="pick.threshold"><option :value="15">15</option><option :value="18">18</option><option :value="21">21</option><option :value="25">25</option></select></label></div>
    <details><summary>Jet d’origine et conditions particulières</summary><label>Résultat de lancement connu<input v-model.number="pick.originalTotal" type="number" min="0" /></label><label class="check"><input v-model="pick.interruptible" type="checkbox" /> Effet durable réellement interruptible pour la scène.</label><template v-if="eclipse"><label class="check"><input v-model="pick.metaphysical" type="checkbox" /> Effet métaphysique temporaire.</label><label class="check"><input v-model="pick.perceived" type="checkbox" /> Effet réellement perçu par le lanceur.</label></template></details>
    <label>Arbitrage MJ<input v-model="pick.note" maxlength="400" placeholder="Pourquoi cet effet est une cible magique valide" /></label><button v-if="index" type="button" @click="picks.splice(index,1)">Retirer cette cible</button>
   </div>
   <button v-if="eclipse&&picks.length<3" type="button" @click="picks.push({actorId:'',effectId:'',distance:20,threshold:18,originalTotal:null,note:'',interruptible:false,metaphysical:false,perceived:false})">Ajouter un effet (3 maximum)</button>
   <label class="check"><input v-model="confirmed" type="checkbox" /> Je confirme les effets actifs, leur portée et leur puissance. Un jet enregistré fait foi pour son résultat d’origine.</label><label class="check"><input v-model="edge" type="checkbox" :disabled="!source?.edge" /> Forcer avant le jet · 1 Edge ({{source?.edge??0}} disponibles).</label>
   <button :disabled="!ready">Lancer et résoudre</button>
  </fieldset></form>
  <p v-else>Aucun lanceur disponible ou aucun effet actif enregistré.</p>
  <details v-if="snapshot.recent.length"><summary>Jets récents et suites possibles</summary><article v-for="e in snapshot.recent" :key="e.id"><strong>{{e.payload.characterName}} · {{e.payload.label}} · {{e.payload.total}}</strong><p>{{e.payload.modifier}} + {{e.payload.dice.join(' + ')}} · {{e.payload.narrativeFailure?'échec narratif':'résultat enregistré'}}</p><button v-if="canForce(e)" :disabled="busy||!!pending" @click="extra('force',e)">Forcer après l’échec · 1 Edge</button><button v-if="canDust(e)" :disabled="busy||!!pending" @click="extra('dust',e)">Réduire en poussière · même jet</button></article></details>
 </template>
</details>
</template>
<style scoped>
.lightning-effects{min-width:0;border:1px solid #355267;border-radius:8px;padding:12px;margin:12px 0;background:#0d1b2b}.lightning-effects summary{cursor:pointer;padding:10px}.lightning-effects fieldset{min-width:0;border:0;padding:0}.fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.lightning-effects label{display:grid;gap:6px;margin:10px 0}.lightning-effects .check{display:flex;gap:8px;align-items:start}.lightning-effects input:not([type=checkbox]),.lightning-effects select{box-sizing:border-box;width:100%;min-width:0;padding:10px;background:#08131f;color:#e6eef8;border:1px solid #526c80;border-radius:5px}.lightning-effects button{min-height:44px;margin:6px 6px 6px 0;padding:10px;background:#143247;color:#d5f6ff;border:1px solid #52758b;border-radius:5px}.lightning-effects button:disabled{opacity:.5}.effect-pick{padding:8px 0;border-top:1px solid #355267}.lightning-effects p{line-height:1.5;overflow-wrap:anywhere}@media(max-width:500px){.fields{grid-template-columns:minmax(0,1fr)}}
</style>
