<script setup lang="ts">
import {computed,ref,onUnmounted} from 'vue';
import {NPC_SEXES,npcBudgetIssues,npcTruthIssues,npcTalentEligible,type NpcData,type NpcSex,type NpcCatalog,type NpcTruth} from '../../../api/src/campaign-npc-model';
import {characterDerivedStats} from '../lib/character-sheet';
import {prepareNpcPortrait} from '../lib/npc-portrait';
const props=defineProps<{data:NpcData;catalog:NpcCatalog;editable?:boolean}>();
const emit=defineEmits<{(e:'update:data',value:NpcData):void;(e:'image-busy',value:boolean):void}>();
const imageBusy=ref(false),imageError=ref('');let imageSeq=0;
const tier=computed(()=>props.catalog.tiers.find(t=>t.id===props.data.tierId));
const ranges=computed(()=>props.catalog.ranges[`${props.data.tierId}:${props.data.presetId}`]);
const truthRanges=computed(()=>props.data.truth?props.catalog.truthRanges[`${props.data.truth.powerId}:${props.data.truth.archetypeId}`]:null);
const totals=computed(()=>({attributes:Object.values(props.data.attributes).reduce((a,b)=>a+b,0),skills:Object.values(props.data.skills).reduce((a,b)=>a+b,0)}));
const issues=computed(()=>npcBudgetIssues(props.data));
const truthIssues=computed(()=>props.data.truth?npcTruthIssues(props.data.truth,props.catalog):[]);
const derived=computed(()=>characterDerivedStats(id=>props.data.attributes[id]||0,id=>props.data.skills[id]||0,[]));
const truthDerived=computed(()=>props.data.truth?characterDerivedStats(id=>props.data.truth!.attributes[id]||0,id=>props.data.truth!.skills[id]||0,[]):null);
const descriptionFields=[{key:'appearance',label:'Apparence',max:1000},{key:'personality',label:'Caractère et façon de parler',max:1000},{key:'motivation',label:'Motivation',max:1000},{key:'secret',label:'Secret ou accroche MJ',max:3000},{key:'truthNotes',label:'Vérité et pouvoirs particuliers · notes MJ',max:3000},{key:'notes',label:'Notes de campagne',max:6000}] as const;
const equipmentPick=ref(''),truthTalentPick=ref('');
const selectedEquipment=computed(()=>(props.data.equipmentIds??[]).map(id=>props.catalog.equipment.find(item=>item.id===id)).filter((item):item is NonNullable<typeof item>=>!!item));
const equipmentGroups=computed(()=>{
 const groups=new Map<string,typeof props.catalog.equipment>();
 for(const item of props.catalog.equipment){const rows=groups.get(item.category)??[];rows.push(item);groups.set(item.category,rows);}
 return [...groups.entries()].map(([category,items])=>({category,items}));
});
function patch(value:Partial<NpcData>){emit('update:data',{...props.data,...value});}
const value=(e:Event)=>(e.target as HTMLInputElement).value;
function stat(group:'attributes'|'skills',id:string,e:Event){patch({[group]:{...props.data[group],[id]:Number(value(e))}});}
function identity(key:'firstName'|'lastName',text:string){const first=(key==='firstName'?text:props.data.firstName||'').trim(),last=(key==='lastName'?text:props.data.lastName||'').trim();const previous=[props.data.firstName,props.data.lastName].filter(Boolean).join(' ').trim();const next=[first,last].filter(Boolean).join(' ');patch({[key]:text,...(!props.data.name.trim()||props.data.name.trim()===previous?{name:next||props.data.name}:{})});}
function truthPatch(value:Partial<NpcTruth>){if(props.data.truth)patch({truth:{...props.data.truth,...value}});}
function truthStat(group:'attributes'|'skills',id:string,e:Event){if(props.data.truth)truthPatch({[group]:{...props.data.truth[group],[id]:Number(value(e))}});}
function truthTalent(name:string,on:boolean){if(!props.data.truth)return;const ids=on?[...props.data.truth.talentIds,name]:props.data.truth.talentIds.filter(id=>id!==name);const cost=ids.reduce((sum,id)=>sum+(props.catalog.truthTalents.find(t=>t.name===id)?.cost||0),0);truthPatch({talentIds:ids,ptv:Math.max(props.data.truth.ptv,cost)});}
function addTruth(){patch({truth:{natureId:'autre',powerId:'recent',archetypeId:'custom',state:'revele',attributes:{...props.data.attributes},skills:{...props.data.skills},talentIds:[],ptv:0,specialtySkill:'',secondSpecialtySkill:'',notes:'',abilities:''}});}
function talent(id:string,on:boolean){patch({talentIds:on?[...props.data.talentIds,id]:props.data.talentIds.filter(t=>t!==id)});}
function addEquipment(){
 const id=equipmentPick.value;if(!id||props.data.equipmentIds?.includes(id))return;
 const ids=[...(props.data.equipmentIds??[]),id],armor=Math.max(0,...ids.map(value=>props.catalog.equipment.find(item=>item.id===value)?.armor??0));
 patch({equipmentIds:ids,armor});equipmentPick.value='';
}
function removeEquipment(id:string){
 const ids=(props.data.equipmentIds??[]).filter(value=>value!==id),armor=Math.max(0,...ids.map(value=>props.catalog.equipment.find(item=>item.id===value)?.armor??0));
 patch({equipmentIds:ids,armor});
}
function addTruthTalent(){if(!truthTalentPick.value)return;truthTalent(truthTalentPick.value,true);truthTalentPick.value='';}
async function image(event:Event){const input=event.target as HTMLInputElement,file=input.files?.[0];if(!file)return;const n=++imageSeq;imageBusy.value=true;emit('image-busy',true);imageError.value='';try{const portrait=await prepareNpcPortrait(file);if(n===imageSeq)patch({portrait});}catch(e){if(n===imageSeq)imageError.value=(e as Error).message;}finally{if(n===imageSeq){imageBusy.value=false;emit('image-busy',false);}input.value='';}}
onUnmounted(()=>{imageSeq++;});
</script>
<template>
 <div class="npc-sheet">
  <h4>Identité et portrait</h4><div class="identity"><div class="portrait"><img v-if="data.portrait" :src="data.portrait" :alt="`Portrait de ${data.name}`" /><span v-else>Sans portrait</span><template v-if="editable"><label>Ajouter ou remplacer l’image<input type="file" accept="image/jpeg,image/png,image/webp" :disabled="imageBusy" @change="image" /></label><small>JPG, PNG ou WebP · 12 Mo maximum. L’image est réduite avant l’enregistrement.</small><button v-if="data.portrait" type="button" :disabled="imageBusy" @click="patch({portrait:''})">Retirer l’image</button><p v-if="imageBusy" role="status">Préparation de l’image…</p><p v-if="imageError" role="alert">{{ imageError }}</p></template></div>
   <div class="identity-fields"><template v-if="editable"><div class="identity-parts"><label>Prénom<input :value="data.firstName||''" maxlength="80" @input="identity('firstName',value($event))" /></label><label>Nom de famille<input :value="data.lastName||''" maxlength="80" @input="identity('lastName',value($event))" /></label></div><label>Nom affiché / alias<input :value="data.name" maxlength="120" required @input="patch({name:value($event)})" /></label><label>Nationalité d’origine<input :value="catalog.nationalities.find(n=>n.id===data.nationality)?.name||data.nationality||''" maxlength="80" list="npc-nationalities" @input="patch({nationality:value($event)})" /><datalist id="npc-nationalities"><option v-for="n in catalog.nationalities" :key="n.id" :value="n.name" /></datalist></label><label>Sexe du PNJ<select :value="data.sex||'unspecified'" aria-label="Sexe du PNJ" @change="patch({sex:value($event) as NpcSex})"><option v-for="s in NPC_SEXES" :key="s.id" :value="s.id">{{ s.name }}</option></select></label><label>Rôle<input :value="data.role" maxlength="160" @input="patch({role:value($event)})" /></label><label>Faction ou groupe<input :value="data.faction" maxlength="160" list="npc-sheet-factions" placeholder="Choisir ou saisir une faction" @input="patch({faction:value($event)})" /><datalist id="npc-sheet-factions"><option>AIDH</option><option>Crawler</option><option>Chasseurs</option><option>Xenoshield</option><option>Loges des Mages</option></datalist></label><label>Tags du PNJ<input :value="data.tags.join(', ')" maxlength="730" placeholder="Séparés par des virgules" @change="patch({tags:value($event).split(',').map(t=>t.trim()).filter(Boolean)})" /></label></template><template v-else><h3>{{ data.name }}</h3><small>{{ [data.firstName,data.lastName].filter(Boolean).join(' ') }}{{ data.nationality?' · '+(catalog.nationalities.find(n=>n.id===data.nationality)?.name||data.nationality):'' }}</small><small>Sexe : {{ NPC_SEXES.find(s=>s.id===(data.sex||'unspecified'))?.name }}</small><p>{{ data.role }}{{ data.faction?' · '+data.faction:'' }}</p><p>{{ data.tags.join(' · ') }}</p></template><strong>{{ tier?.name }} · Profil de Réalité</strong><small>{{ totals.attributes }}/{{ tier?.attributes }} attributs · {{ totals.skills }}/{{ tier?.skills }} compétences · plafond ordinaire {{ tier?.cap }}</small></div>
  </div>
  <ul v-if="issues.length" role="alert"><li v-for="issue in issues" :key="issue">{{ issue }}</li></ul>
  <div class="story"><h4>Histoire, rôle et accroches MJ</h4><template v-for="field in descriptionFields" :key="field.key"><label v-if="editable">{{ field.label }}<textarea :value="data[field.key]" :maxlength="field.max" rows="2" @input="patch({[field.key]:value($event)})" /></label><div v-else-if="data[field.key]"><h4>{{ field.label }}</h4><p class="prose">{{ data[field.key] }}</p></div></template></div>
  <section class="equipment-worn">
   <h4>Équipement réellement porté</h4>
   <template v-if="editable"><label>Ajouter depuis le catalogue<select v-model="equipmentPick" @change="addEquipment"><option value="">Choisir un équipement</option><optgroup v-for="group in equipmentGroups" :key="group.category" :label="group.category"><option v-for="item in group.items" :key="item.id" :value="item.id">{{ item.name }}</option></optgroup></select></label><div v-if="selectedEquipment.length" class="selected-items"><article v-for="item in selectedEquipment" :key="item.id"><span><strong>{{ item.name }}</strong><small>{{ item.category }}<template v-if="item.armorProfile"> · {{ item.armorProfile }}</template></small></span><button type="button" @click="removeEquipment(item.id)">Retirer</button></article></div><label>Précisions ou équipement hors catalogue<textarea :value="data.equipment" maxlength="2000" rows="2" @input="patch({equipment:value($event)})" /></label><small>Lorsqu’une armure est ajoutée, le champ « Armure portée » reprend automatiquement sa protection la plus élevée et reste ajustable.</small></template>
   <template v-else><ul v-if="selectedEquipment.length"><li v-for="item in selectedEquipment" :key="item.id">{{ item.name }}<small v-if="item.armorProfile"> · {{ item.armorProfile }}</small></li></ul><p v-if="data.equipment" class="prose">{{ data.equipment }}</p></template>
  </section>
  <details :open="!editable" class="mechanics"><summary>Carte de Réalité · statistiques{{ editable?' · ajuster les valeurs':'' }}</summary>
   <h4>Attributs</h4><small>Plages de génération par archétype ; les points restent redistribuables en création personnalisée.</small><div class="stats"><div v-for="a in catalog.attributes" :key="a.id"><label v-if="editable">{{ a.name }}<small v-if="ranges">{{ ranges.attributes[a.id].min }}–{{ ranges.attributes[a.id].max }}</small><input :value="data.attributes[a.id]" type="number" min="1" max="46" step="1" required @input="stat('attributes',a.id,$event)" /></label><template v-else><span>{{ a.name }}</span><strong>{{ data.attributes[a.id] }}</strong></template></div></div>
   <h4>Compétences</h4><div class="stats"><div v-for="s in catalog.skills.filter(s=>editable||data.skills[s.id]>0)" :key="s.id"><label v-if="editable">{{ s.name }}<small v-if="ranges">{{ ranges.skills[s.id].min }}–{{ ranges.skills[s.id].max }}</small><input :value="data.skills[s.id]" type="number" min="0" :max="s.id===data.apexSkill?15:tier?.cap" step="1" required @input="stat('skills',s.id,$event)" /></label><template v-else><span>{{ s.name }}</span><strong>{{ data.skills[s.id] }}{{ data.apexSkill===s.id?' · Apex':'' }}</strong><small>Jet : {{ data.skills[s.id]+data.attributes[s.attribute] }} + 1d10e</small></template></div></div>
   <details v-if="editable&&['heroique','legendaire'].includes(data.tierId)"><summary>Apex · spécialité exceptionnelle</summary><label>Compétence Apex<select :value="data.apexSkill" aria-label="Compétence Apex" @change="patch({apexSkill:value($event)})"><option value="">Aucune</option><option v-for="s in catalog.skills" :key="s.id" :value="s.id">{{ s.name }}</option></select></label><label v-if="data.apexSkill">Spécialité documentée<textarea :value="data.apexReason" maxlength="1000" rows="2" @input="patch({apexReason:value($event)})" /></label><small>Monte cette compétence à 15 en ajustant les autres rangs : les points Apex restent compris dans le budget.</small></details>
   <p v-else-if="data.apexSkill">Apex : {{ data.apexReason }}</p>
  </details>
  <h4>Valeurs pour jouer</h4><dl class="derived"><div><dt>PV / seuil de Mort</dt><dd>{{ derived.pvMax }} / {{ derived.death }}</dd></div><div><dt>Défense passive / active</dt><dd>{{ derived.passiveDefense }} / {{ derived.passiveDefense }} + 1d10e</dd></div><div><dt>Défense occulte passive / active</dt><dd>{{ derived.occultDefense }} / {{ derived.occultDefense }} + 1d10e</dd></div><div><dt>Initiative / déplacement</dt><dd>{{ derived.initiative }} + 1d10e / {{ derived.movement }} m par PA</dd></div><div><dt>Intégrité / Stress augmentique max</dt><dd>{{ derived.integrity }} / {{ derived.augmentStressMax }}</dd></div><div><dt>Armure portée</dt><dd><input v-if="editable" :value="data.armor" aria-label="Armure portée" type="number" min="0" max="100" required @input="patch({armor:Number(value($event))})" /><span v-else>{{ data.armor }}</span></dd></div></dl>
  <details :open="!editable"><summary>Talents PNJ · {{ data.talentIds.length }}{{ data.apexSkill?' + Apex':'' }} · repère : {{ tier?.talents }}</summary><p>Les conditions indiquées doivent être réunies en jeu. Les appuis et l’équipement ne sont pas accordés par le palier.</p><article v-for="t in catalog.talents.filter(t=>editable||data.talentIds.includes(t.id))" :key="t.id" class="talent"><label v-if="editable" class="check"><input type="checkbox" :checked="data.talentIds.includes(t.id)" :disabled="!data.talentIds.includes(t.id)&&!npcTalentEligible(t.id,data.skills)" @change="talent(t.id,($event.target as HTMLInputElement).checked)" />{{ t.name }}</label><strong v-else>{{ t.name }}</strong><label v-if="editable&&t.id==='Expertise éprouvée'&&data.talentIds.includes(t.id)">Compétence de l’expertise<select :value="data.expertiseSkill" @change="patch({expertiseSkill:value($event)})"><option value="">Choisir une compétence</option><option v-for="s in catalog.skills.filter(s=>data.skills[s.id]>=7)" :key="s.id" :value="s.id">{{ s.name }}</option></select></label><p v-else-if="!editable&&t.id==='Expertise éprouvée'">{{ catalog.skills.find(s=>s.id===data.expertiseSkill)?.name }}</p><small>{{ t.prerequisite }}</small><p>{{ t.effect }}</p></article></details>
  <button v-if="editable&&!data.truth" type="button" @click="addTruth">Ajouter un profil de Vérité indépendant</button>
  <section v-if="data.truth" class="truth-profile"><div class="truth-heading"><h4>Profil de Vérité · {{ catalog.truthNatures.find(n=>n.id===data.truth!.natureId)?.name }}</h4><button v-if="editable" type="button" @click="patch({truth:null})">Retirer le profil de Vérité</button></div><p>Ce profil est indépendant du palier de Réalité. Les valeurs indiquées sont finales pour l’état Révélé ; les bonus de Nature ne s’ajoutent pas une seconde fois.</p><ul v-if="truthIssues.length" role="alert"><li v-for="issue in truthIssues" :key="issue">{{ issue }}</li></ul>
   <div v-if="editable" class="identity-parts"><label>Nature<select :value="data.truth.natureId" @change="truthPatch({natureId:value($event)})"><option v-for="n in catalog.truthNatures" :key="n.id" :value="n.id">{{ n.name }}</option></select></label><label>Puissance de Vérité<select :value="data.truth.powerId" @change="truthPatch({powerId:value($event)})"><option v-for="p in catalog.truthPowers" :key="p.id" :value="p.id">{{ p.name }}</option></select></label><label>Archétype de Vérité<select :value="data.truth.archetypeId" @change="truthPatch({archetypeId:value($event)})"><option v-for="a in catalog.truthArchetypes" :key="a.id" :value="a.id">{{ a.name }}</option></select></label><label>État actuel<select :value="data.truth.state" @change="truthPatch({state:value($event) as NpcTruth['state']})"><option value="voile">Voilé</option><option value="semi-revele">Semi-Révélé</option><option value="revele">Révélé</option></select></label></div>
   <label v-if="data.truth.archetypeId==='custom' && editable">Nom de l’archétype personnalisé<input :value="data.truth.archetypeLabel||''" maxlength="120" placeholder="Décrire cet archétype" @input="truthPatch({archetypeLabel:value($event)})" /></label><p v-else-if="data.truth.archetypeId==='custom' && data.truth.archetypeLabel">Archétype : {{ data.truth.archetypeLabel }}</p>
   <p v-else>{{ catalog.truthPowers.find(p=>p.id===data.truth!.powerId)?.name }} · {{ catalog.truthArchetypes.find(a=>a.id===data.truth!.archetypeId)?.name }} · État : {{ data.truth.state }}</p>
   <details :open="!editable"><summary>Attributs et compétences en Révélé</summary><h4>Attributs de Vérité</h4><small>Plages du profil Révélé généré ; les valeurs sont finales et indépendantes de la Réalité.</small><div class="stats"><div v-for="a in catalog.attributes" :key="a.id"><label v-if="editable">{{ a.name }}<small v-if="truthRanges">{{ truthRanges.attributes[a.id].min }}–{{ truthRanges.attributes[a.id].max }}</small><input :value="data.truth.attributes[a.id]" type="number" min="1" max="50" @input="truthStat('attributes',a.id,$event)" /></label><template v-else><span>{{ a.name }}</span><strong>{{ data.truth.attributes[a.id] }}</strong></template></div></div><h4>Compétences de Vérité</h4><div class="stats"><div v-for="s in catalog.skills.filter(s=>editable||data.truth!.skills[s.id]>0)" :key="s.id"><label v-if="editable">{{ s.name }}<small v-if="truthRanges">{{ truthRanges.skills[s.id].min }}–{{ truthRanges.skills[s.id].max }}</small><input :value="data.truth.skills[s.id]" type="number" min="0" max="25" @input="truthStat('skills',s.id,$event)" /></label><template v-else><span>{{ s.name }}</span><strong>{{ data.truth.skills[s.id] }}</strong></template></div></div></details>
   <dl v-if="truthDerived" class="derived"><div><dt>PV / seuil de Mort en Révélé</dt><dd>{{ truthDerived.pvMax }} / {{ truthDerived.death }}</dd></div><div><dt>Défense physique / occulte</dt><dd>{{ truthDerived.passiveDefense }} / {{ truthDerived.occultDefense }}</dd></div><div><dt>Initiative / déplacement</dt><dd>{{ truthDerived.initiative }} + 1d10e / {{ truthDerived.movement }} m</dd></div></dl>
   <label v-if="editable">PTV dépensés (talents et dons détaillés)<input :value="data.truth.ptv" type="number" min="0" max="999" @input="truthPatch({ptv:Number(value($event))})" /></label><p v-else>PTV dépensés estimés : {{ data.truth.ptv }}</p><label v-if="editable">Compétence de spécialité<select :value="data.truth.specialtySkill" @change="truthPatch({specialtySkill:value($event)})"><option value="">Aucune</option><option v-for="s in catalog.skills" :key="s.id" :value="s.id">{{ s.name }}</option></select></label><label v-if="editable">Seconde spécialité<select :value="data.truth.secondSpecialtySkill||''" @change="truthPatch({secondSpecialtySkill:value($event)})"><option value="">Aucune</option><option v-for="s in catalog.skills" :key="s.id" :value="s.id">{{ s.name }}</option></select></label>
   <details :open="!editable"><summary>Pouvoirs de Vérité · {{ data.truth.talentIds.length }}</summary><div v-if="editable" class="picker-row"><label>Ajouter un pouvoir<select v-model="truthTalentPick"><option value="">Choisir dans le catalogue</option><option v-for="t in catalog.truthTalents.filter(t=>!data.truth!.talentIds.includes(t.name))" :key="t.name" :value="t.name">{{ t.name }} · {{ t.cost }} PTV</option></select></label><button type="button" :disabled="!truthTalentPick" @click="addTruthTalent">Ajouter</button></div><article v-for="t in catalog.truthTalents.filter(t=>data.truth!.talentIds.includes(t.name))" :key="t.name" class="talent"><div class="truth-talent-heading"><strong>{{ t.name }} · {{ t.cost }} PTV</strong><button v-if="editable" type="button" @click="truthTalent(t.name,false)">Retirer</button></div><small>{{ t.prerequisite }}</small><p>{{ t.effect }}</p></article></details>
   <label v-if="editable">Pouvoir particulier hors catalogue<textarea :value="data.truth.abilities" maxlength="3000" rows="3" placeholder="À utiliser seulement si le pouvoir n’existe pas dans la liste : nom, coût, effet, limites et état requis…" @input="truthPatch({abilities:value($event)})" /></label><p v-else-if="data.truth.abilities" class="prose">{{ data.truth.abilities }}</p><label v-if="editable">Notes de Vérité MJ<textarea :value="data.truth.notes" maxlength="3000" rows="3" @input="truthPatch({notes:value($event)})" /></label><p v-else-if="data.truth.notes" class="prose">{{ data.truth.notes }}</p>
  </section>
 </div>
</template>
<style scoped>
.npc-sheet{display:grid;gap:16px;min-width:0;overflow-wrap:anywhere}.identity{display:grid;grid-template-columns:minmax(140px,220px) 1fr;gap:20px}.portrait{display:grid;gap:10px;align-content:start}.portrait>img{width:100%;max-height:280px;object-fit:contain;background:#080f19;border-radius:6px}.portrait>span{padding:25px;text-align:center;border:1px dashed #405875;color:#a3b7cc}.identity-fields,.story{display:grid;gap:12px}.npc-sheet label{display:grid;gap:7px}.npc-sheet input:not([type=checkbox]),textarea,select{min-width:0;box-sizing:border-box;width:100%;padding:10px;min-height:44px;background:#08131f;color:#edf4ff;border:1px solid #405875;border-radius:6px;font:inherit}textarea{resize:vertical}.stats,.derived{display:grid;grid-template-columns:repeat(auto-fit,minmax(125px,1fr));gap:10px}.stats>div,.derived>div{padding:10px;background:#132536;border:1px solid #304c62;border-radius:6px}.stats strong,.stats span{display:block}.derived{margin:0}.derived dt,small{color:#a3b7cc;line-height:1.6}.derived dd{margin:6px 0 0}.prose{white-space:pre-wrap}h4{margin:8px 0}.npc-sheet p{line-height:1.65}.check{display:flex!important;gap:8px;align-items:center;min-height:44px}.check input{width:20px;height:20px}.talent{padding:10px 0;border-bottom:1px solid #304c62}.talent small{display:block}summary{cursor:pointer;min-height:44px;align-content:center}button{padding:10px;min-height:44px;background:#101e30;color:#eaf2ff;border:1px solid #405875;border-radius:6px;font:inherit;cursor:pointer}input:focus-visible,textarea:focus-visible,select:focus-visible,button:focus-visible,summary:focus-visible{outline:2px solid #a3eaff;outline-offset:3px}@media(max-width:600px){.identity{grid-template-columns:1fr}.portrait{max-width:220px}.stats,.derived{grid-template-columns:repeat(2,minmax(0,1fr))}}
.identity-parts{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.identity,.story,.mechanics,.equipment-worn{padding:16px;border:1px solid #405875;border-radius:7px;background:#101e30}.equipment-worn,.selected-items{display:grid;gap:12px}.selected-items article,.truth-talent-heading,.picker-row{display:flex;flex-wrap:wrap;align-items:center;justify-content:space-between;gap:10px}.selected-items article{padding:10px;border:1px solid #304c62;border-radius:6px}.selected-items article>span{display:grid;gap:4px}.picker-row>label{flex:1;min-width:220px}.truth-profile{display:grid;gap:12px;padding:16px;border:1px solid #8973af;border-radius:7px;background:#17162b}.truth-profile>p{margin:0;color:#c4b6de}.truth-profile ul{color:#ffbdad}@media(max-width:600px){.identity-parts{grid-template-columns:1fr}}
.truth-heading{display:flex;flex-wrap:wrap;align-items:center;justify-content:space-between;gap:10px}
</style>
