<script setup lang="ts">
import {computed,onMounted,onUnmounted,ref,watch} from 'vue';
import {api,ApiError} from '../lib/api';
const props=defineProps<{campaignId:string;room:any}>(),emit=defineEmits<{changed:[]}>();
const endpoint=`/api/campaigns/${props.campaignId}/combat`,pending=ref<any[]>([]),error=ref(''),busy=ref(false),request=ref<any>(null);
const weapons=ref<any[]>([]),weaponId=ref('');
const eventId=ref(''),targetId=ref(''),damage=ref(1),bonusDamage=ref(0),penetration=ref(0),damageType=ref('melee'),surprise=ref(false);
const drafts=ref<Record<string,any>>({});let alive=true,timer:ReturnType<typeof setInterval>;
const rolls=computed(()=>props.room.events.filter((e:any)=>['roll','gm-roll'].includes(e.kind)&&e.payload.total!==undefined));
const targets=computed(()=>[...props.room.characters,...props.room.combatants]);
watch(weaponId,()=>{const w=weapons.value.find(w=>w.id===weaponId.value);if(w){damage.value=w.damage;penetration.value=Number(/Perforant\s+(\d+)/i.exec(w.properties)?.[1]??0);damageType.value=w.range==='Contact'?'melee':'balistique';}});
watch(eventId,()=>{const p=rolls.value.find((e:any)=>e.id===eventId.value)?.payload;damage.value=p?.damage??1;penetration.value=p?.penetration??0;damageType.value=p?.damageType??'melee';});
async function load(){if(!alive||document.visibilityState==='hidden')return;try{const r=await api<any>(endpoint);if(!alive)return;pending.value=r.pending;weapons.value=r.weapons??[];for(const a of r.pending)drafts.value[a.id]??={protectionIds:[],armor:a.target.armor,extraArmor:0,extraReduction:0,bonus:0,defenseOverride:0};}catch{if(alive){pending.value=[];error.value='Impossible de charger les attaques en attente.';}}}
async function send(action:string,extra:any){if(busy.value)return;if(request.value){error.value='Réessaie l’action non confirmée.';return;}request.value={action,requestId:crypto.randomUUID(),...extra};await retry();}
async function retry(){if(busy.value||!request.value)return;busy.value=true;error.value='';try{await api(endpoint,{method:'POST',body:JSON.stringify(request.value)});request.value=null;await load();emit('changed');}catch(e){error.value=e instanceof ApiError&&e.status===409?'Cette attaque a déjà changé ou a déjà été traitée.':e instanceof ApiError&&e.message==='active_defense_unavailable'?'Défense active indisponible : vérifie les PA, l’initiative, la surprise et les blessures.':'Action non confirmée. Réessaie.';if(e instanceof ApiError&&e.status<500){request.value=null;await load();}}finally{busy.value=false;}}
function preview(a:any){const d=drafts.value[a.id],items=a.target.protections.filter((p:any)=>d.protectionIds.includes(p.id)),defense=a.defense?.narrativeFailure?d.defenseOverride:a.defense?.total??a.target.defense;
 const armor=['neuro','occulte'].includes(a.damageType)?0:Number(d.armor)+Number(d.extraArmor)+Math.max(0,...items.map((p:any)=>p.armor))+Math.max(0,...items.map((p:any)=>p.body)),reduction=Number(d.extraReduction)+(a.target.reductions?.[a.damageType]??0)+Math.max(0,...items.map((p:any)=>p.reductions[a.damageType]??0)),margin=Math.max(0,a.total-defense),material=Math.max(0,armor-a.penetration);
 return {defense,margin,armor,material,reduction,damage:a.narrativeFailure||margin===0?0:Math.max(0,margin+a.damage+a.bonusDamage-material-reduction)};
}
onMounted(()=>{void load();timer=setInterval(()=>void load(),3000);});onUnmounted(()=>{alive=false;clearInterval(timer);});
</script>
<template>
<section class="combat-resolution" aria-label="Résolution des attaques">
 <h2>Attaques & défenses</h2><p v-if="error" role="alert">{{ error }} <button v-if="request" :disabled="busy" @click="retry">Réessayer cette action</button></p>
 <details v-if="room.canManage"><summary>Diriger un jet d’attaque vers une cible</summary><form @submit.prevent="send('attack',{eventId,targetId,damage,bonusDamage,penetration,damageType,surprise})"><div class="combat-fields">
 <label>Jet d’attaque<select v-model="eventId" required><option value="">Choisir un jet du journal…</option><option v-for="e in rolls" :key="e.id" :value="e.id">{{ e.characterName??e.payload.characterName??'MJ' }} · {{ e.payload.label }} → {{ e.payload.total }}</option></select></label>
 <label>Cible<select v-model="targetId" required><option value="">Choisir…</option><option v-for="c in targets" :key="c.id" :value="c.id">{{ c.name }}</option></select></label>
 <label>Arme du catalogue (facultatif)<select v-model="weaponId"><option value="">Profil du jet ou saisie</option><option v-for="w in weapons" :key="w.id" :value="w.id">{{ w.name }} · DGT {{ w.damage }}</option></select></label><label>Dégâts de l’arme<input v-model.number="damage" type="number" min="0" max="100" required /></label><label>Bonus de dégâts<input v-model.number="bonusDamage" type="number" min="-100" max="100" required /></label><label>Perforant<input v-model.number="penetration" type="number" min="0" max="100" required /></label><label>Type de dégâts<select v-model="damageType"><option value="melee">Mêlée</option><option value="balistique">Balistique</option><option value="antichoc">Antichoc</option><option value="feu">Feu</option><option value="occulte">Occulte</option><option value="neuro">Neuro</option></select></label>
 <label class="check"><input v-model="surprise" type="checkbox" /> Surprise : pas de défense active</label></div><button :disabled="busy||!eventId||!targetId">Proposer l’attaque au défenseur</button><small>Vérifie les propriétés de l’arme et les bonus de dégâts avant d’envoyer. Le joueur ciblé peut choisir sa défense ici ; le MJ peut aussi la résoudre.</small></form></details>
 <p v-if="!pending.length">Aucune attaque en attente de défense.</p>
 <article v-for="a in pending" :key="a.id" class="pending-attack"><h3>{{ a.attacker }} → {{ a.target.name }} · Attaque {{ a.total }}</h3><p>DGT {{ a.damage }} + bonus {{ a.bonusDamage }} · {{ a.damageType }} · Perforant {{ a.penetration }}</p><strong v-if="a.narrativeFailure">Échec narratif de l’attaque : aucun dégât.</strong>
 <div v-if="!a.defense" class="combat-fields"><label>Bonus de défense<input v-model.number="drafts[a.id].bonus" type="number" min="-100" max="100" /></label><button :disabled="busy" @click="send('defend',{attackId:a.id,active:false,bonus:drafts[a.id].bonus})">Défense passive · 0 PA</button><button :disabled="busy||!a.target.canDefend||a.surprise||a.narrativeFailure" @click="send('defend',{attackId:a.id,active:true,bonus:drafts[a.id].bonus})">Défense active · 1 PA · d10</button><span>{{ a.target.pa }} PA disponibles</span></div>
 <form v-else @submit.prevent="send('resolve',{attackId:a.id,...drafts[a.id]})"><p>{{ a.defense.label }} : {{ a.defense.modifier }}<template v-if="a.defense.dice"> + {{ a.defense.dice.join(' + ') }}</template> = {{ a.defense.total }}</p>
 <p v-if="a.defense.narrativeFailure" role="alert">Échec narratif de la défense : le MJ doit arbitrer la défense retenue avant application.</p><label v-if="a.defense.narrativeFailure&&room.canManage">Défense retenue après arbitrage<input v-model.number="drafts[a.id].defenseOverride" type="number" min="0" max="1000" required /></label>
 <fieldset><legend>Protections applicables à cet impact</legend><p v-if="a.target.reductions?.[a.damageType]">Réduction du profil : {{ a.target.reductions[a.damageType] }}</p><label v-for="p in a.target.protections" :key="p.id" class="check"><input v-model="drafts[a.id].protectionIds" type="checkbox" :value="p.id" /> {{ p.name }} — {{ p.text }}</label><div class="combat-fields"><label>Armure du profil<input v-model.number="drafts[a.id].armor" type="number" min="0" max="100" required /></label><label>Armure supplémentaire applicable<input v-model.number="drafts[a.id].extraArmor" type="number" min="0" max="100" required /></label><label>Réduction supplémentaire applicable<input v-model.number="drafts[a.id].extraReduction" type="number" min="0" max="100" required /></label></div><small>Coche seulement les protections portées et applicables. Meilleure armure portée + meilleure armure corporelle ; pas de double cumul. Ajuste les effets conditionnels, pouvoirs, charges ablatives ou protections spéciales d’après leur texte. Neuro et Occulte n’utilisent pas l’armure matérielle dans ce calcul.</small></fieldset>
 <p class="damage-preview">Marge {{ preview(a).margin }} + arme {{ a.damage }} + bonus {{ a.bonusDamage }} − protection matérielle {{ preview(a).material }} − réduction {{ preview(a).reduction }} = <strong>{{ preview(a).damage }} dégâts</strong></p><button :disabled="busy||(a.defense.narrativeFailure&&!room.canManage)">Appliquer {{ preview(a).damage }} dégâts aux PV</button></form>
 <button v-if="room.canManage" :disabled="busy" @click="send('cancel',{attackId:a.id})">Annuler cette attaque</button></article>
</section>
</template>
<style scoped>
.combat-resolution{padding:16px;margin:0 0 24px;background:#0d1b2b;border:1px solid #355267;border-radius:8px;min-width:0}.combat-fields{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.combat-fields label{flex:1;min-width:130px}.combat-resolution label{display:grid;gap:6px;margin:10px 0}.combat-resolution .check{display:flex;align-items:center}.combat-resolution input:not([type=checkbox]),.combat-resolution select{box-sizing:border-box;width:100%;min-width:0;padding:10px;background:#08131f;color:#e6eef8;border:1px solid #526c80;border-radius:5px;font:inherit}.combat-resolution button{padding:10px;min-height:44px;margin:5px;background:#143247;color:#d5f6ff;border:1px solid #52758b;border-radius:5px;cursor:pointer}.combat-resolution button:disabled{opacity:.5;cursor:default}.combat-resolution summary{padding:12px;cursor:pointer}.combat-resolution fieldset{min-width:0;border:1px solid #355267}.pending-attack{padding:12px;border:1px solid #52758b;border-radius:6px;margin:12px 0}.combat-resolution small{display:block;color:#b7c9d6;line-height:1.5}.damage-preview{color:#b7efff}
</style>
