<script setup lang="ts">
import {ref,watch} from 'vue';
import CharacterSessionVersion from './CharacterSessionVersion.vue';
import {api,ApiError} from '../lib/api';
const props=defineProps<{campaignId:string;canManage:boolean;current:any}>(),emit=defineEmits<{changed:[]}>();
const nextBefore=ref<string|null>(null),archiveBusy=ref(false);let generation=0;
const expanded=ref<Record<string,boolean>>({});
const sessions=ref<any[]>([]),selected=ref(''),planned=ref(''),title=ref(''),label=ref('Point de sauvegarde'),versions=ref<any[]>([]),events=ref<any[]>([]),error=ref(''),busy=ref(false),request=ref<any>(null);
const url=`/api/campaigns/${props.campaignId}/play`;
async function load(){try{sessions.value=(await api<any>(url+'/sessions')).sessions;}catch{error.value='Impossible de charger les séances.';}}
async function archive(){const seq=++generation;if(!selected.value)return;try{const [v,r]=await Promise.all([api<any>(`${url}/sessions/${selected.value}/versions`),api<any>(`${url}?session=${selected.value}`)]);if(seq!==generation)return;versions.value=v.versions;events.value=r.events;nextBefore.value=r.nextBefore;}catch{error.value='Cette archive est indisponible.';}}
async function more(){if(archiveBusy.value||!nextBefore.value)return;archiveBusy.value=true;const seq=generation;try{const r=await api<any>(`${url}?session=${selected.value}&before=${encodeURIComponent(nextBefore.value)}`);if(seq===generation){events.value.push(...r.events);nextBefore.value=r.nextBefore;}}catch{error.value='Impossible de charger la suite du journal.';}finally{archiveBusy.value=false;}}
async function send(action:string){if(busy.value||request.value)return;request.value={requestId:crypto.randomUUID(),action,title:action==='start'?(planned.value?sessions.value.find(s=>s.id===planned.value)?.title:title.value):label.value,expectedSession:props.current?.id??null,...(action==='start'&&planned.value?{sessionId:planned.value}:{})};await retry();}
async function retry(){if(busy.value||!request.value)return;busy.value=true;error.value='';try{await api(url+'/sessions',{method:'POST',body:JSON.stringify(request.value)});request.value=null;title.value='';planned.value='';emit('changed');await load();if(selected.value)await archive();}catch(e){error.value=e instanceof ApiError&&e.message==='finish_combat_first'?'Résous ou annule les attaques en attente avant de changer de séance.':e instanceof ApiError&&e.status===409?'La séance a changé : actualise avant de recommencer.':'Action non confirmée. Réessaie pour vérifier son enregistrement.';if(e instanceof ApiError&&e.status<500){request.value=null;emit('changed');await load();}}finally{busy.value=false;}}
watch(selected,()=>{versions.value=[];events.value=[];nextBefore.value=null;void archive();});
</script>
<template><details class="live-sessions" @toggle="($event.target as HTMLDetailsElement).open&&load()"><summary>Séances & versions · {{current?.title??'Aucune séance ouverte'}}</summary>
<p v-if="error" role="alert">{{error}} <button v-if="request" :disabled="busy" @click="retry">Réessayer</button></p>
<template v-if="canManage"><form @submit.prevent="send('start')"><h3>Ouvrir la séance suivante</h3><label>Séance préparée<select v-model="planned"><option value="">Créer une nouvelle séance</option><option v-for="s in sessions.filter(s=>!s.startedAt)" :key="s.id" :value="s.id">{{s.title}}</option></select></label><label v-if="!planned">Nom de la séance<input v-model="title" maxlength="120" required placeholder="Séance 4 · Le rendez-vous" /></label><p>Le journal repart vide. Le précédent et les versions des fiches restent consultables ci-dessous. PV, inventaire, Edge et combat en cours sont conservés.</p><button :disabled="busy||!!request||(!planned&&!title.trim())">Ouvrir et réinitialiser le journal</button></form>
<form v-if="current" @submit.prevent="send('checkpoint')"><label>Nom de la version<input v-model="label" required maxlength="120" /></label><button :disabled="busy||!!request||!label.trim()">Enregistrer une version des fiches</button></form></template>
<label>Consulter une séance<select v-model="selected"><option value="">Choisir…</option><option v-for="s in sessions.filter(s=>s.startedAt)" :key="s.id" :value="s.id">{{s.title}}</option></select></label>
<p v-if="selected">Archives en lecture seule. Chaque joueur consulte ses propres versions ; le MJ consulte toutes les fiches.</p>
<details v-for="v in versions" :key="v.id"><summary>{{v.label}} · {{new Date(v.createdAt).toLocaleString('fr-FR')}}</summary><article v-for="c in v.snapshot.characters" :key="c.id"><h4>{{c.name}} · version {{c.version}}</h4><p>Edge {{c.edge}} · PV {{c.state.hp??'maximum'}} · {{c.state.pa}} PA · round {{c.state.round}}</p><p>XP {{c.data.progression?.xpEarned??0}} · PTV {{c.data.progression?.ptvEarned??0}}</p><details @toggle="expanded[v.id+c.id]=($event.target as HTMLDetailsElement).open"><summary>Consulter la fiche sauvegardée</summary><CharacterSessionVersion v-if="expanded[v.id+c.id]" :saved="c" /></details></article><details v-if="canManage&&v.snapshot.combatants?.length"><summary>PNJ et bestiaire sauvegardés · {{v.snapshot.combatants.length}}</summary><article v-for="c in v.snapshot.combatants" :key="c.id"><h4>{{c.name}} · {{c.hp}} / {{c.pv_max}} PV · {{c.pa}} PA</h4><p>Initiative {{c.initiative??'—'}} · {{c.pa_per_round}} PA par round</p><p v-for="a in c.data.attacks??[]" :key="a.name">{{a.name}} : {{a.score}} + d10 · {{a.damage}} dégâts</p><dl><template v-for="(value,key) in c.data.attributes??c.data.stats" :key="key"><dt>{{key}}</dt><dd>{{value}}</dd></template></dl></article></details></details>
<details v-if="selected"><summary>Journal de la séance · {{events.length}} événements chargés</summary><article v-for="e in events" :key="e.id"><strong>{{e.characterName??e.payload.characterName??'MJ'}} → {{e.payload.label}} <template v-if="e.payload.total!==undefined">→ {{e.payload.total}}</template></strong><p v-if="e.payload.dice">Dés : {{e.payload.dice.join(' + ')}} · bonus {{e.payload.modifier}} <span v-if="e.payload.edgeForced">· Forcer le Destin</span></p><p v-if="e.payload.text">{{e.payload.text}}</p><a v-if="e.payload.link" :href="e.payload.link" target="_blank" rel="noopener">Compendium ↗</a><img v-if="e.image" :src="e.image" alt="Image révélée pendant cette séance" /></article><button v-if="nextBefore" :disabled="archiveBusy" @click="more">Charger les événements précédents</button></details>
</details></template>
<style scoped>.live-sessions{padding:14px;border:1px solid #355267;border-radius:8px;background:#0d1b2b;margin-bottom:16px}summary{cursor:pointer;padding:10px}form,article{padding:12px 0;border-bottom:1px solid #355267}label{display:grid;gap:6px;margin:10px 0}input,select,button{font:inherit;padding:10px;background:#102334;border:1px solid #52758b;color:inherit;border-radius:5px;max-width:100%;box-sizing:border-box;min-height:44px}button{cursor:pointer}pre{max-height:400px;overflow:auto;white-space:pre-wrap;font-size:.85rem}img{max-width:100%;max-height:240px}p{line-height:1.5}</style>
