/** Approved Extral revisions: stable purchase IDs, no changes to other Natures. */
export type ExtralRevision={id:string;number:number;name:string;cost:number;activation:string;access:string;effect:string;details:string;status:string};
export const extralRevisions:readonly ExtralRevision[] = [
  {
    "id": "extral-rebond-d-appui",
    "number": 1,
    "name": "Rebond d’appui",
    "cost": 1,
    "activation": "Passif",
    "effect": "Vous enchaînez les rebonds sans nouvel élan et gagnez +3 aux tests d’Athlétisme pour des bonds difficiles utilisant les surfaces environnantes. La distance normale, les appuis réels et les limites d’endurance demeurent.",
    "details": "",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-zero-g-natif",
    "number": 2,
    "name": "Zéro-G natif",
    "cost": 1,
    "activation": "Passif",
    "effect": "Vous ignorez les difficultés dues à l’apesanteur, à une faible gravité ou à des repères changeants. Une surface accessible reste nécessaire pour vous accrocher et vous propulser.",
    "details": "",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-trajectoire-impossible",
    "number": 4,
    "name": "Trajectoire impossible",
    "cost": 2,
    "activation": "Lors d’un Déplacement",
    "effect": "Lors d’un Déplacement par rebonds, les murs, plafonds et franchissements ordinaires accessibles ne demandent ni PA supplémentaire ni test d’Athlétisme. Jusqu’au début de votre prochaine activation, les attaques anticipant cette trajectoire subissent −3 ; des appuis réels restent nécessaires.",
    "details": "Des surfaces réelles permettent les rebonds ; ce talent ne fonctionne pas dans un espace entièrement ouvert.",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-vision-des-fractures",
    "number": 5,
    "name": "Vision des fractures",
    "cost": 1,
    "activation": "Passif",
    "effect": "Vous distinguez une fracture dimensionnelle active d’un résidu et gagnez +3 pour en estimer l’ancienneté, la stabilité ou le danger à partir des indices perceptibles. La détection élémentaire reste innée ; ni destination ni responsable ne sont révélés sans indices.",
    "details": "Clarifier en même temps le trait gratuit, actuellement trop abrégé ; ne pas retirer au Talass la perception que sa biologie décrit.",
    "access": "SR/R",
    "status": "Refonte"
  },
  {
    "id": "extral-trame-sensible",
    "number": 6,
    "name": "Trame sensible",
    "cost": 1,
    "activation": "Préparation — quelques minutes",
    "effect": "Après quelques minutes de préparation, surveillez une trame couvrant au maximum 10 m de rayon tant que vous y restez physiquement relié. Vous localisez approximativement les perturbations, sans identifier leur auteur.",
    "details": "",
    "access": "R",
    "status": "Préciser"
  },
  {
    "id": "extral-relais-conducteur",
    "number": 7,
    "name": "Relais conducteur",
    "cost": 2,
    "activation": "Selon l’effet conduit",
    "effect": "Un fil de soie continu permet d’exercer un effet compatible du Talwa à son extrémité jusqu’à 30 m. Les PA, la puissance et les protections restent ceux de l’effet ; les autres conductions réellement compatibles restent possibles.",
    "details": "Électricité, données et contact magique approprié peuvent emprunter la soie si l’effet accepte réellement cette conduction. Un effet absent n’est jamais acquis.",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-reseau-de-soie",
    "number": 8,
    "name": "Réseau de soie",
    "cost": 2,
    "activation": "Préparation — réseau physique",
    "effect": "Vous pouvez préparer cinq nœuds de soie dans une zone de 10 m de rayon, chacun relié par un trajet de fil de 30 m maximum. Vos effets compatibles partent d’un seul nœud choisi par activation, sans attaque ou zone d’effet supplémentaire.",
    "details": "",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-lien-talwa",
    "number": 10,
    "name": "Lien Talwa",
    "cost": 1,
    "activation": "Actif — 1 PA",
    "effect": "Pour 1 PA, communiquez volontairement par mots et images simples avec une cible consentante à 20 m maximum, pour la scène. Aucune fouille de pensée ni lecture forcée des sens.",
    "details": "",
    "access": "SR/R",
    "status": "Préciser"
  },
  {
    "id": "extral-main-du-talwa",
    "number": 11,
    "name": "Main du Talwa",
    "cost": 2,
    "activation": "Actif — 1 PA par manipulation",
    "effect": "Pour 1 PA par manipulation, agissez sur un objet de 5 kg maximum situé à 10 m dans votre Talwa. Une tâche fine utilise le test approprié ; pas d’étranglement, de projection d’une créature ou de projectile offensif implicite.",
    "details": "",
    "access": "SR/R",
    "status": "Préciser"
  },
  {
    "id": "extral-champ-entropique",
    "number": 12,
    "name": "Champ entropique",
    "cost": 3,
    "activation": "Actif — 1 PA après le scan",
    "effect": "Après le scan, 1 PA maintient pour la scène une veille psychique de la zone de 10 m, sans entretien supplémentaire. Les déplacements significatifs donnent une position approximative, jamais l’identité ni les intentions ; les véritables barrières dimensionnelles bloquent la veille.",
    "details": "Une créature parfaitement immobile ne produit pas de déplacement significatif. La veille n’identifie ni individu, ni Nature, ni intention.",
    "access": "SR/R",
    "status": "Préciser"
  },
  {
    "id": "extral-reflexe-de-chasse",
    "number": 14,
    "name": "Réflexe de chasse",
    "cost": 2,
    "activation": "Réaction gratuite — 1/round",
    "effect": "Une fois par round, effectuez une Défense active physique sans PA. Le talent seul ne permet pas cette défense en Surprise, mais peut se combiner avec une permission distincte de s’y défendre.",
    "details": "",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-surpuissance",
    "number": 15,
    "name": "Surpuissance",
    "cost": 2,
    "activation": "Actif — 1 PA — scène",
    "effect": "Pour 1 PA, comptez votre Vigueur comme supérieure de 2 pour les efforts de force et les luttes de prise pendant la scène. Ni PV, dégâts ni autres valeurs dérivées ne sont augmentés.",
    "details": "Renforcement de durée proposé : à confronter au caractère explosif de la Mosenine en fiction, sans rendre toutes ses techniques durables.",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-crete-de-mosenine",
    "number": 16,
    "name": "Crête de Mosenine",
    "cost": 3,
    "activation": "Début du round — gratuit — 1/scène",
    "effect": "Une fois par scène, au début d’un round et sans PA d’activation, gagnez 1 PA réservé au Déplacement, Pugilat, Mêlée, à la Défense active ou à un effort physique significatif. Les autres techniques de Mosenine restent disponibles ensuite ; les gains directs de PA ne se cumulent pas.",
    "details": "",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-triangulation-predatrice",
    "number": 19,
    "name": "Triangulation prédatrice",
    "cost": 2,
    "activation": "Passif",
    "effect": "À 10 m, opposez votre Perception à la Furtivité grâce aux signatures sensorielles que vous pouvez réellement percevoir, même sans bonne ligne de vue. Le talent n’accorde pas à lui seul un sens non acquis ; un masquage adapté peut l’empêcher.",
    "details": "Thermovision ou Goûter l’air restent des prérequis alternatifs. Le talent ne donne pas le sens non acheté.",
    "access": "R",
    "status": "Préciser"
  },
  {
    "id": "extral-verrou-sensoriel",
    "number": 20,
    "name": "Verrou sensoriel",
    "cost": 3,
    "activation": "Après détection — scène",
    "effect": "Le verrou conserve pour la scène la position approximative d’une cible détectée à 20 m maximum. Il cesse si elle quitte cette portée ou masque effectivement les signatures employées, sans créer une ligne de tir.",
    "details": "",
    "access": "R",
    "status": "Préciser"
  },
  {
    "id": "extral-angle-de-cuirasse",
    "number": 23,
    "name": "Angle de cuirasse",
    "cost": 2,
    "activation": "Réaction gratuite — 1/round",
    "effect": "Une fois par round, lorsqu’un coup physique perçu touche une zone réellement cuirassée, réduisez de 2 les dégâts restants après l’Armure, sans PA. Cela ne couvre pas une attaque visant une partie non protégée.",
    "details": "Une attaque visant explicitement une zone peu cuirassée n’est pas réduite.",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-carapace-de-combat",
    "number": 24,
    "name": "Carapace de combat",
    "cost": 3,
    "activation": "Actif — 1 PA — scène",
    "effect": "Pour 1 PA, portez votre Armure corporelle à 3 jusqu’à la fin de la scène. Cette valeur remplace les 2 d’Ostéodermes, sans ajouter une seconde couche corporelle.",
    "details": "",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-culture-de-secours",
    "number": 25,
    "name": "Culture de secours",
    "cost": 1,
    "activation": "Préparation",
    "effect": "Vos cultures préparées remplacent le matériel de premiers soins et donnent +3 aux tests de premiers soins ou de Stabilisation qui les utilisent. Les consommations réelles, la capacité des Tardollas et les effets normaux du soin restent applicables.",
    "details": "Il faut disposer d’une préparation réelle ; les emplacements de Tardolla et ses consommations restent applicables.",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-catalyse-therapeutique",
    "number": 27,
    "name": "Catalyse thérapeutique",
    "cost": 2,
    "activation": "Traitement — dix minutes — 1/cible/scène",
    "effect": "Après dix minutes et un test de Médecine difficulté 15 réussi, rendez 4 + DR PV, une fois par cible et par scène. Aucun membre ne repousse et aucune séquelle n’est effacée.",
    "details": "",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-jet-glandulaire",
    "number": 29,
    "name": "Jet glandulaire",
    "cost": 1,
    "activation": "Actif — 1 PA",
    "effect": "Pour 1 PA, projetez avec précision une préparation à 10 m maximum : Agilité + Tir + 1d10e contre Défense physique. Le talent ne fournit pas de préparation et le simple rejet biologique reste inné.",
    "details": "",
    "access": "R",
    "status": "Préciser"
  },
  {
    "id": "extral-secretion-de-guerre",
    "number": 31,
    "name": "Sécrétion de guerre",
    "cost": 2,
    "activation": "Culture ; PA du Jet glandulaire",
    "effect": "Lors de la culture, choisissez une sécrétion corrosive (DGT 5, ignore 2 Armure) ou adhésive (membre ou objet collé ; libération : 1 PA et Vigueur + Athlétisme difficulté 15). Le choix précède le tir ; aucun jet d’attaque n’est nécessaire sur un objet immobile dans des conditions ordinaires.",
    "details": "La substance est physique : exposition, compatibilité biologique et protections hermétiques appropriées restent applicables.",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-purge-explosive",
    "number": 32,
    "name": "Purge explosive",
    "cost": 3,
    "activation": "Réaction — 1 PA — 1/scène",
    "effect": "Pour 1 PA en Réaction, une fois par scène au contact, purgez une seule préparation offensive pour exposer les créatures immédiatement proches, alliés compris. Seule cette préparation est perdue ; les protections, l’évitement matériel possible et les résistances restent applicables.",
    "details": "C’est la purge sélective et maîtrisée qui est apprise, non l’existence des glandes ; l’ancienne expulsion biologique incontrôlée n’est pas effacée.",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-coordination-independante",
    "number": 33,
    "name": "Coordination indépendante",
    "cost": 1,
    "activation": "Passif — manipulation gratuite 1/round",
    "effect": "Vos quatre mains ignorent le malus de main non dominante ; gagnez une manipulation manuelle simple gratuite par round avec vos mains libres : saisir un outil accessible, le ranger ou le passer d’une main à l’autre. Ni attaque, Défense, rechargement ni action complexe gratuite.",
    "details": "",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-rechargement-quadrimanuel",
    "number": 36,
    "name": "Rechargement quadrimanuel",
    "cost": 2,
    "activation": "Rechargement gratuit — 1/round",
    "effect": "Une fois par round, rechargez sans PA une arme ou un appareil simple avec vos mains libres et des munitions immédiatement accessibles. Les armes lourdes et les rechargements à installation ou étapes complexes restent exclus.",
    "details": "",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-regeneration-active",
    "number": 38,
    "name": "Régénération active",
    "cost": 2,
    "activation": "Actif — 1 PA — 1/round ; à 0 PV : tous les PA",
    "effect": "Au-dessus de 0 PV et avec le Noyau intact, 1 PA rend 4 PV, ou 6 en immersion ou hydratation abondante, une fois par round. À 0 PV Stabilisé, la régénération occupe toute l’activation du round suivant et consomme tous ses PA, sans autre action ; aucun membre ne repousse instantanément.",
    "details": "La condition de Noyau intact est impérative. À 0 PV Stabilisé, aucune autre action, déplacement, attaque ou second soin ne peut être effectué ce round, quel que soit le nombre de PA.",
    "access": "R",
    "status": "Préciser"
  },
  {
    "id": "extral-lien-de-banc",
    "number": 41,
    "name": "Lien de banc",
    "cost": 1,
    "activation": "Actif — 1 PA par lien",
    "effect": "Pour 1 PA, intégrez au banc un allié consentant même dépourvu de don télépathique, à 20 m maximum pour la scène. Jusqu’à cinq alliés peuvent être reliés, chaque nouveau lien étant établi séparément ; l’échange naturel entre télépathes compatibles reste inné.",
    "details": "L’ouverture aux non-télépathes est une nouvelle exception à la restriction du lore, pas une capacité gratuite déjà acquise ; elle demande une validation explicite.",
    "access": "SR/R",
    "status": "Refonte"
  },
  {
    "id": "extral-partage-sensoriel",
    "number": 42,
    "name": "Partage sensoriel",
    "cost": 2,
    "activation": "Actif — 1 PA — scène",
    "effect": "Pour 1 PA, suivez pour la scène un sens volontairement partagé par un membre du banc tout en conservant vos propres perceptions. Ignorez jusqu’à −3 dus au seul partage d’attention entre ces deux points de vue, sans action supplémentaire ni emprunt de Compétence.",
    "details": "",
    "access": "SR/R",
    "status": "Refonte"
  },
  {
    "id": "extral-relais-psychique",
    "number": 43,
    "name": "Relais psychique",
    "cost": 2,
    "activation": "Passif",
    "effect": "Étendez le banc par trois intermédiaires au maximum, avec 20 m au plus entre chaque lien. La coupure d’un lien coupe la branche concernée ; pas de liaison transcontinentale.",
    "details": "",
    "access": "SR/R",
    "status": "Préciser"
  },
  {
    "id": "extral-conscience-distribuee",
    "number": 44,
    "name": "Conscience distribuée",
    "cost": 3,
    "activation": "Passif — banc établi",
    "effect": "Les membres du banc sont avertis des menaces réellement perçues par les autres, ne sont pas Surpris par elles et gagnent +3 à leur première Défense active physique du round contre une attaque ainsi annoncée. Les défenses restent payantes, les corps doivent pouvoir réagir et aucune ligne de tir n’est créée.",
    "details": "Le banc comprend au plus cinq alliés et le Rocréen. Une seule circonstance favorable équivalente s’applique par test ; consentement et continuité du réseau restent requis.",
    "access": "SR/R",
    "status": "Refonte"
  },
  {
    "id": "extral-jet-d-encre",
    "number": 46,
    "name": "Jet d'encre",
    "cost": 1,
    "activation": "Actif — 1 PA — 1/scène",
    "effect": "Une fois par scène, pour 1 PA, projetez de l’encre sur une cible à 10 m ou une zone de 2 m maximum : la vision gênée subit −3 jusqu’au nettoyage ou à la sortie de la zone. Un nettoyage simple accessible coûte 1 PA.",
    "details": "",
    "access": "R",
    "status": "Préciser"
  },
  {
    "id": "extral-colle-organique",
    "number": 47,
    "name": "Colle organique",
    "cost": 2,
    "activation": "Actif — 1 PA",
    "effect": "Pour 1 PA, tirez votre colle à 10 m, avec Agilité + Tir + 1d10e contre la Défense applicable. Une liaison collée se rompt pour 1 PA et Vigueur + Athlétisme difficulté 15, sans immobiliser tout un corps pour un simple vêtement touché.",
    "details": "",
    "access": "R",
    "status": "Préciser"
  },
  {
    "id": "extral-venin-rocreen",
    "number": 48,
    "name": "Venin rocréen",
    "cost": 2,
    "activation": "Actif — 1 PA — 1/scène",
    "effect": "Une fois par scène, pour 1 PA, projetez votre venin sur une cible à 10 m : après une attaque réussie et une exposition effective, Vigueur + Constitution difficulté 15 évite −3 aux tests physiques jusqu’à la fin du prochain round. Une protection hermétique appropriée empêche l’exposition.",
    "details": "",
    "access": "R",
    "status": "Préciser"
  },
  {
    "id": "extral-cocktail-glandulaire",
    "number": 49,
    "name": "Cocktail glandulaire",
    "cost": 3,
    "activation": "Actif — 1 PA — compteurs des deux sécrétions",
    "effect": "Pour 1 PA, combinez deux effets glandulaires connus et applicables à la même cible dans un seul jet d’attaque. Chaque effet conserve sa résistance, ses protections et son compteur d’utilisation, tous deux consommés.",
    "details": "",
    "access": "R",
    "status": "Préciser"
  },
  {
    "id": "extral-densification-osseuse",
    "number": 51,
    "name": "Densification osseuse",
    "cost": 1,
    "activation": "Passif",
    "effect": "Votre densification vous accorde Armure corporelle 1, cumulable avec une armure portée réellement compatible. Elle ne s’ajoute pas à une autre couche d’Armure corporelle.",
    "details": "",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-muscle-tasse",
    "number": 52,
    "name": "Muscle tassé",
    "cost": 2,
    "activation": "Passif",
    "effect": "Votre Pugilat utilise DGT 4 au lieu de DGT 1. Il s’agit de la valeur de base du coup naturel, pas d’un +4 cumulé avec une autre arme.",
    "details": "",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-vieux-cuir",
    "number": 53,
    "name": "Vieux cuir",
    "cost": 3,
    "activation": "Passif",
    "effect": "Votre Armure corporelle passe à 3, en remplacement de Densification osseuse et sans cumuler plusieurs couches corporelles. Ce stade de densification n’exige pas d’avoir vécu plusieurs siècles.",
    "details": "",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-lecture-vibratoire",
    "number": 54,
    "name": "Lecture vibratoire",
    "cost": 1,
    "activation": "Passif",
    "effect": "En contact avec le milieu, gagnez +3 pour distinguer et interpréter les vibrations faibles jusqu’à 10 m : nombre approximatif de sources, direction et rythme. Le talent n’identifie ni une personne ni sa Nature sans indices supplémentaires.",
    "details": "",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-branchies-barometriques",
    "number": 55,
    "name": "Branchies barométriques",
    "cost": 1,
    "activation": "Passif",
    "effect": "À 5 m, gagnez +3 aux tests de Perception utilisant les mouvements d’air ou d’eau pour détecter une présence hors de votre champ visuel. Les milieux isolés, le vide ou l’absence de perturbation perceptible restent des limites.",
    "details": "",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-resonance-holographique",
    "number": 56,
    "name": "Résonance holographique",
    "cost": 2,
    "activation": "Passif — acclimatation terrestre",
    "effect": "Après une fluctuation ressentie, gagnez +3 pour en situer la source locale et distinguer une transition V/SR/R d’une contrainte durable ou d’un résidu perceptible. Cela ne donne pas l’espèce, ne voit pas la forme V cachée et ne force aucune Révélation.",
    "details": "L’acclimatation terrestre prolongée reste nécessaire ; le Thalsios n’identifie aucune espèce et ne voit pas une forme cachée à V.",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-cartographie-vibratoire",
    "number": 57,
    "name": "Cartographie vibratoire",
    "cost": 3,
    "activation": "Actif — 1 PA — scène",
    "effect": "Pour 1 PA, maintenez pendant la scène la carte précise des mouvements à 10 m via les milieux qui vous transmettent leurs vibrations. Les surfaces découplées et isolations adaptées la bloquent ; aucune ligne de vue ou de tir n’est créée.",
    "details": "",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-transition-en-chaine",
    "number": 65,
    "name": "Transition en chaîne",
    "cost": 3,
    "activation": "Gratuit — 1/scène",
    "effect": "Une fois par scène et sans coût d’activation, les transitions personnelles ne coûtent aucun PA jusqu’à la fin de la scène. Elles restent possibles uniquement aux fenêtres normales, sans contourner blocage, créer des actions ou soigner par changement de forme.",
    "details": "",
    "access": "V/SR/R",
    "status": "Refonte"
  },
  {
    "id": "extral-reserve-nanitique",
    "number": 67,
    "name": "Réserve nanitique",
    "cost": 2,
    "activation": "Passif — 1/scénario",
    "effect": "Une fois par scénario, le premier soin réel reçu vous rend 3 PV supplémentaires. La récupération naturelle, Cycle de réparation et toute régénération indépendante sont exclus ; cette utilisation est distincte de celle de Cycle de réparation.",
    "details": "Le bonus intervient uniquement si le soin rend effectivement des PV, sans dépasser le maximum. Rechargement de page, sauvegarde, nouveau combat et transition V/SR/R ne renouvellent pas cette utilisation. Le premier soin éligible du scénario consomme cette réserve.",
    "access": "V/SR/R",
    "status": "Refonte"
  },
  {
    "id": "extral-cycle-de-reparation",
    "number": 69,
    "name": "Cycle de réparation",
    "cost": 3,
    "activation": "Actif — 1 PA — 1/scénario",
    "effect": "Une fois par scénario, dépensez 1 PA pour récupérer 6 PV si vous êtes conscient, vivant et votre essaim fonctionnel. Votre récupération naturelle hors combat reste doublée ; Réserve nanitique ne s’applique pas à ce cycle.",
    "details": "La récupération naturelle doublée est permanente hors combat, pas une deuxième activation du soin. Nouvelle scène, sauvegarde et transition V/SR/R ne renouvellent pas l’utilisation de scénario. Aucun essaim défaillant, mort ou inconscient ne peut être soigné par cette activation.",
    "access": "V/SR/R",
    "status": "Refonte"
  },
  {
    "id": "extral-poussee-myofibrillaire",
    "number": 70,
    "name": "Poussée myofibrillaire",
    "cost": 1,
    "activation": "Lors d’un Déplacement — 1/round",
    "effect": "Une fois par round, votre Déplacement à 1 PA permet un bond horizontal jusqu’au double de sa distance normale, ou vertical jusqu’à cette distance normale. Un vrai danger exige toujours un test ; aucune suspension en vol.",
    "details": "",
    "access": "V/SR/R",
    "status": "Préciser"
  },
  {
    "id": "extral-reflexe-conditionne",
    "number": 75,
    "name": "Réflexe conditionné",
    "cost": 2,
    "activation": "Réaction gratuite — 1/scène",
    "effect": "Une fois par scène, effectuez une Défense active physique sans PA avec +3, même Surpris. Il faut rester physiquement capable de réagir ; les autres avantages de la Surprise ne sont pas effacés.",
    "details": "",
    "access": "V/SR/R",
    "status": "Refonte"
  },
  {
    "id": "extral-phasage-de-l-equipement",
    "number": 78,
    "name": "Phasage de l’équipement",
    "cost": 1,
    "activation": "Actif — 1 ou 2 PA",
    "effect": "Pour matérialiser ou déphaser l’équipement existant lié à vos patchs tatoués AIDH, dépensez 1 PA pour un objet ou 2 PA pour une tenue, une armure ou plusieurs éléments. Les mêmes coûts s’appliquent dans les deux sens ; aucun matériel ni duplicata n’est créé.",
    "details": "Intégration à contrôler/développer lors du lot ; aucune prétention à un test d’interface déjà exécuté pour les Extrals.",
    "access": "V/SR/R",
    "status": "Intégrer"
  },
  {
    "id": "extral-charge-de-rupture",
    "number": 81,
    "name": "Charge de rupture",
    "cost": 2,
    "activation": "1/scène — après Déplacement et attaque payés",
    "effect": "Une fois par scène, après un Déplacement vers une cible suivi d’une attaque de mêlée réussie qui lui inflige au moins 1 dégât dans le même round, renversez-la ou repoussez-la de 2 m + DR. Les actions restent payantes et une cible sensiblement plus massive peut opposer sa Vigueur ; aucune Altération identique n’est doublée.",
    "details": "",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-mur-vivant",
    "number": 82,
    "name": "Mur vivant",
    "cost": 2,
    "activation": "Réaction — 1 PA — 1/round",
    "effect": "Pour 1 PA en Réaction, une fois par round, barrez le passage à une créature de taille comparable ou inférieure qui traverse votre zone immédiate : Vigueur + Athlétisme contre Vigueur ou Agilité + Athlétisme. En réussite, son déplacement s’arrête à votre contact.",
    "details": "",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-saisie-ecrasante",
    "number": 83,
    "name": "Saisie écrasante",
    "cost": 1,
    "activation": "Passif",
    "effect": "Après une saisie réussie sur une cible sensiblement plus petite, maintenez son immobilisation, gagnez +3 pour conserver la prise et pouvez la transporter à demi-Déplacement. Aucune saisie, attaque ou action supplémentaire n’est créée.",
    "details": "",
    "access": "SR/R",
    "status": "Refonte"
  },
  {
    "id": "extral-projection-de-masse",
    "number": 85,
    "name": "Projection de masse",
    "cost": 3,
    "activation": "Actif — 1 PA — cible déjà saisie",
    "effect": "Pour 1 PA, projetez une cible déjà saisie, de taille comparable ou inférieure : Vigueur + Pugilat contre Vigueur + Athlétisme ; en réussite, elle recule de 2 m + DR et est renversée. Une collision réelle avec une surface solide inflige votre DGT de Pugilat + DR, Armure applicable.",
    "details": "La distance et la chute sont conservées ; le DR remplace l’ancien terme de collision, ne s’ajoute pas une deuxième fois à la marge d’une autre attaque.",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-impact-titanesque",
    "number": 86,
    "name": "Impact titanesque",
    "cost": 3,
    "activation": "1/scène — attaque normalement payée",
    "effect": "Une fois par scène, annoncez avant une attaque de Pugilat ou Mêlée un coup entièrement consacré à la puissance : +4 DGT en cas de réussite, sans pénalité à votre Défense. Une Altération réellement obtenue peut prendre la forme d’une projection ou destruction locale plausible.",
    "details": "",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-corps-pour-corps",
    "number": 88,
    "name": "Corps pour corps",
    "cost": 2,
    "activation": "Réaction — 1 PA",
    "effect": "Pour 1 PA en Réaction, remplacez un allié adjacent comme cible d’une attaque de mêlée et effectuez votre Défense active physique contre cette attaque dans ce même PA. Aucune autre attaque n’est annulée.",
    "details": "",
    "access": "V/SR/R",
    "status": "Refonte"
  },
  {
    "id": "extral-ne-pas-rompre",
    "number": 90,
    "name": "Ne pas rompre",
    "cost": 3,
    "activation": "Réaction — 1 PA — 1/scène",
    "effect": "Une fois par scène, lorsqu’une blessure impose Tendu ou Paniqué, dépensez 1 PA en Réaction pour ignorer jusqu’à la fin de la scène les conséquences de Stress dues aux seules blessures. Les causes psychologiques indépendantes, PV, Altérations, Agonie et incapacités physiques restent inchangés.",
    "details": "",
    "access": "V/SR/R",
    "status": "Refonte"
  },
  {
    "id": "extral-cercle-interieur",
    "number": 92,
    "name": "Cercle intérieur",
    "cost": 2,
    "activation": "Après Défense active — saisie gratuite — 1/round",
    "effect": "Une fois par round, après une Défense active réussie contre une attaque de mêlée, établissez une saisie sans PA ni second jet si vous avez un membre libre et une prise physiquement possible. La défense reste payante, aucune immobilisation impossible n’est créée.",
    "details": "",
    "access": "V/SR/R",
    "status": "Refonte"
  },
  {
    "id": "extral-retour-de-la-main-vide",
    "number": 94,
    "name": "Retour de la main vide",
    "cost": 3,
    "activation": "Réaction — 1 PA — 1/round",
    "effect": "Une fois par round, après une Défense active de mêlée réussie, dépensez 1 PA en Réaction pour riposter en Pugilat ou Mêlée. Cette riposte ne peut pas déclencher un autre Retour de la main vide.",
    "details": "",
    "access": "V/SR/R",
    "status": "Préciser"
  },
  {
    "id": "extral-pas-ecarlate",
    "number": 96,
    "name": "Pas écarlate",
    "cost": 2,
    "activation": "1/round",
    "effect": "Une fois par round, votre Déplacement normalement payé permet un bond jusqu’au double de sa distance normale horizontalement ou cette distance verticalement. Une réception praticable reste nécessaire ; ni vol durable ni station sur un mur.",
    "details": "",
    "access": "R",
    "status": "Préciser"
  },
  {
    "id": "extral-declassement-fonctionnel",
    "number": 99,
    "name": "Déclassement fonctionnel",
    "cost": 1,
    "activation": "Préparation technique",
    "effect": "Avec les outils et l’appareil nécessaires, sacrifiez une fonction secondaire ou réduisez les performances pour préserver sa fonction essentielle malgré une infrastructure locale insuffisante, avec +3 au test technique. Les fonctions abandonnées restent perdues jusqu’à réparation ou réadaptation ; aucune pièce n’est créée.",
    "details": "",
    "access": "",
    "status": "Refonte"
  },
  {
    "id": "extral-emulation-de-composant",
    "number": 100,
    "name": "Émulation de composant",
    "cost": 2,
    "activation": "Préparation — dix minutes",
    "effect": "Avec matériaux, outils et fonction connue, fabriquez un substitut temporaire en dix minutes avec +3 au test technique approprié. Il tient pour la scène d’utilisation et ne reproduit pas un principe physiquement impossible avec ces moyens.",
    "details": "",
    "access": "",
    "status": "Refonte"
  },
  {
    "id": "extral-procedure-encapsulee",
    "number": 104,
    "name": "Procédure encapsulée",
    "cost": 2,
    "activation": "Voir règle détaillée",
    "effect": "Après sa mise au point réelle, une procédure documentée donne +3 aux tests des techniciens qui l’exécutent avec les bons outils pendant une scène de travail. Elle ne leur transmet ni théorie générale ni compétence permanente.",
    "details": "",
    "access": "",
    "status": "Refonte"
  },
  {
    "id": "extral-industrialisation-frugale",
    "number": 106,
    "name": "Production de terrain",
    "cost": 3,
    "activation": "Préparation — temps selon le prototype",
    "effect": "Vous pouvez reproduire ou réparer une fonction d’un prototype connu et testé à l’aide d’un kit mobile réellement assemblé, sans atelier fixe pour cette fonction. Les composants, outils, temps et tests restent nécessaires ; ce savoir-faire permet aussi une petite série avec une infrastructure réelle.",
    "details": "Nom proposé : « Production de terrain » ; identifiant conservé, le talent achète le protocole, pas le kit ou les objets fabriqués.",
    "access": "",
    "status": "Refonte"
  },
  {
    "id": "extral-microclimat-de-fortune",
    "number": 107,
    "name": "Microclimat de fortune",
    "cost": 1,
    "activation": "Préparation — dix minutes",
    "effect": "En dix minutes, avec du matériel réellement approprié, aménagez une zone de 3 m de rayon pour les besoins d’une espèce connue. Elle reste viable tant que ses ressources consommables et conditions d’étanchéité le permettent ; aucune atmosphère n’apparaît sans moyen matériel.",
    "details": "",
    "access": "",
    "status": "Préciser"
  },
  {
    "id": "extral-acclimatation-transitoire",
    "number": 109,
    "name": "Acclimatation transitoire",
    "cost": 2,
    "activation": "Préparation — dix minutes",
    "effect": "Définissez un protocole pour une espèce et un milieu non instantanément létal, avec dix minutes de préparation et une scène de tolérance. Produits nécessaires, incompatibilités absolues et limites biologiques restent réels.",
    "details": "",
    "access": "",
    "status": "Préciser"
  },
  {
    "id": "extral-habitat-de-survie",
    "number": 110,
    "name": "Habitat de survie",
    "cost": 3,
    "activation": "Préparation — 1 heure pour le refuge d’urgence",
    "effect": "En une heure, aménagez avec des ressources réelles un refuge compatible pour cinq personnes pendant 24 heures. Le maintien durable d’une petite population reste possible avec une infrastructure entretenue et les consommables nécessaires.",
    "details": "",
    "access": "",
    "status": "Refonte"
  },
  {
    "id": "extral-conversion-therapeutique",
    "number": 112,
    "name": "Conversion thérapeutique",
    "cost": 2,
    "activation": "Préparation — dix minutes",
    "effect": "Après étude de la pathologie et adaptation réelle d’un traitement disponible, la cible reçoit un nouveau test de résistance à +3 contre l’affection traitée. Dix minutes de préparation ; aucun traitement universel, résurrection ou disparition des dégâts déjà subis.",
    "details": "",
    "access": "",
    "status": "Refonte"
  },
  {
    "id": "extral-stabilisation-exotique",
    "number": 113,
    "name": "Stabilisation exotique",
    "cost": 2,
    "activation": "Voir règle détaillée",
    "effect": "Tentez la Stabilisation d’une physiologie inconnue avec +3, à partir des signes vitaux réellement observables. Les moyens de soin doivent être disponibles et une destruction vitale définitive reste irréversible.",
    "details": "",
    "access": "",
    "status": "Refonte"
  },
  {
    "id": "extral-support-vital-universel",
    "number": 114,
    "name": "Support vital universel",
    "cost": 3,
    "activation": "Actif — 2 PA",
    "effect": "Avec un matériel adapté disponible, consacrez 2 PA à établir un maintien vital d’urgence d’une physiologie inconnue pendant 24 heures maximum. Les consommables restent requis, aucune guérison ou résurrection n’est donnée et une destruction vitale définitive reste fatale.",
    "details": "",
    "access": "",
    "status": "Préciser"
  },
  {
    "id": "extral-compartimentation-reptilienne",
    "number": 115,
    "name": "Compartimentation reptilienne",
    "cost": 1,
    "activation": "Voir règle détaillée",
    "effect": "Les cellules réellement compartimentées imposent −3 aux tests d’enquête cherchant à remonter de l’une à l’autre. Une preuve directe conservée reste utilisable ; aucune identité parfaite ni preuve effacée.",
    "details": "",
    "access": "",
    "status": "Refonte"
  },
  {
    "id": "extral-mandat-dormant",
    "number": 116,
    "name": "Mandat dormant",
    "cost": 2,
    "activation": "1/scène — accès antérieur réel",
    "effect": "Une fois par scène, déclarez rétroactivement un ordre conditionnel plausible laissé lors d’un accès antérieur réel à une institution infiltrée. Il ne peut contredire un fait déjà établi, créer de l’autorité ou résoudre rétroactivement une action déjà accomplie.",
    "details": "",
    "access": "",
    "status": "Refonte"
  },
  {
    "id": "extral-decision-distribuee",
    "number": 117,
    "name": "Décision distribuée",
    "cost": 2,
    "activation": "Voir règle détaillée",
    "effect": "Lorsqu’un responsable devient indisponible, les relais effectivement briefés poursuivent l’opération et gagnent +3 aux tests de coordination directement nécessaires à sa continuité pendant la scène. Aucun agent, PA ou moyen supplémentaire n’est créé.",
    "details": "",
    "access": "",
    "status": "Refonte"
  },
  {
    "id": "extral-fenetre-orbitale",
    "number": 121,
    "name": "Fenêtre de transit",
    "cost": 2,
    "activation": "Repérage et préparation du transit",
    "effect": "Identifiez un créneau réel de surveillance, de trafic ou de synchronisation pour un transit clandestin terrestre, portuaire, aérien ou orbital : +3 au premier test qui l’exploite. Ni véhicule, autorisation ni invisibilité ne sont fournis.",
    "details": "Nom proposé : « Fenêtre de transit », identifiant historique conservé.",
    "access": "",
    "status": "Refonte"
  },
  {
    "id": "extral-provenance-brouillee",
    "number": 124,
    "name": "Provenance brouillée",
    "cost": 2,
    "activation": "Voir règle détaillée",
    "effect": "Une acquisition réellement passée par les relais appropriés impose −3 aux tests visant à en reconstituer la provenance. Les preuves directes subsistent et les transferts ont des délais et coûts réels.",
    "details": "",
    "access": "",
    "status": "Refonte"
  },
  {
    "id": "extral-importation-noire",
    "number": 126,
    "name": "Importation noire",
    "cost": 3,
    "activation": "Voir règle détaillée",
    "effect": "Après vérification d’un bien rare non unique réellement disponible dans le réseau, obtenez un prix et un délai de livraison dans la zone de campagne. L’engagement de la filière est réel dans ces conditions, sauf obstacle nouveau effectivement joué ; l’objet reste payant.",
    "details": "",
    "access": "",
    "status": "Préciser"
  },
  {
    "id": "extral-relais-brule",
    "number": 128,
    "name": "Relais brûlé",
    "cost": 2,
    "activation": "1/scène — avant interception",
    "effect": "Une fois par scène, lorsqu’un relais vient d’être compromis, détournez avant interception une opération encore en cours vers une solution alternative réellement praticable. Pas d’annulation d’une arrestation ou saisie déjà résolue, ni disparition des preuves.",
    "details": "",
    "access": "",
    "status": "Refonte"
  },
  {
    "id": "extral-reseau-sans-centre",
    "number": 130,
    "name": "Réseau sans centre",
    "cost": 2,
    "activation": "Préparation — une journée",
    "effect": "Après la perte d’un relais, rétablissez en une journée une fonction locale de la filière à partir de contacts et moyens restés intacts. Cela ne libère pas les captifs, ne remplace pas le matériel perdu et ne recrée pas une organisation entièrement détruite.",
    "details": "",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-propulsion-vectorielle",
    "number": 132,
    "name": "Propulsion vectorielle",
    "cost": 2,
    "activation": "Passif — milieu liquide et propulsion adaptée",
    "effect": "Avec la nage ou une propulsion appropriée, changez brutalement de direction sans perdre d’activation et ignorez jusqu’à −3 dus aux courants ou turbulences lors d’une manœuvre, attaque adaptée ou sauvetage aquatique. Les limites du corps et du dispositif restent applicables.",
    "details": "",
    "access": "",
    "status": "Refonte"
  },
  {
    "id": "extral-poussee-d-interception",
    "number": 133,
    "name": "Poussée d’interception",
    "cost": 2,
    "activation": "Réaction — 1 PA — 1/round",
    "effect": "Pour 1 PA en Réaction, une fois par round, parcourez jusqu’à votre Déplacement aquatique normal pour intercepter une menace physiquement accessible. Si vous atteignez un allié visé, le même PA inclut une Défense active physique d’interposition contre cette seule attaque.",
    "details": "",
    "access": "",
    "status": "Refonte"
  },
  {
    "id": "extral-percee-hydrostatique",
    "number": 134,
    "name": "Percée hydrostatique",
    "cost": 2,
    "activation": "1/scène — Déplacement normalement payé",
    "effect": "Une fois par scène, lors d’un Déplacement aquatique normalement payé, franchissez un courant violent, une turbulence ou un obstacle de milieu normalement capable de vous arrêter, en entraînant une personne remorquée si votre capacité le permet. Une impossibilité physique absolue reste impossible.",
    "details": "",
    "access": "",
    "status": "Refonte"
  },
  {
    "id": "extral-partage-de-survie",
    "number": 136,
    "name": "Partage de survie",
    "cost": 1,
    "activation": "Action de partage — matériel compatible",
    "effect": "Avec une réserve, un recycleur ou une physiologie compatible, partagez temporairement le support vital d’une cible adjacente sans perdre votre propre usage. Les deux consommations sont décomptées ; aucune réserve supplémentaire n’apparaît.",
    "details": "",
    "access": "",
    "status": "Refonte"
  },
  {
    "id": "extral-sas-humain",
    "number": 137,
    "name": "Sas humain",
    "cost": 2,
    "activation": "Voir règle détaillée",
    "effect": "Avec les équipements adaptés et quelques instants de préparation, accompagnez une cible dans une transition de milieu normalement exigeante sans sas complet. Le protocole fixe avant l’action pression, température, durée et limites supportées ; les transitions physiquement mortelles ne sont pas annulées.",
    "details": "",
    "access": "",
    "status": "Préciser"
  },
  {
    "id": "extral-extraction-abyssale",
    "number": 138,
    "name": "Extraction abyssale",
    "cost": 3,
    "activation": "Actif — 1 PA — 1/scène",
    "effect": "Pour 1 PA, une fois par scène, saisissez une victime neutralisée à votre portée puis remorquez-la jusqu’à votre Déplacement aquatique normal en franchissant un obstacle de milieu réellement franchissable. Équipements, voie de sortie et survie biologique restent nécessaires.",
    "details": "",
    "access": "R",
    "status": "Préciser"
  },
  {
    "id": "extral-veille-genetique",
    "number": 139,
    "name": "Veille génétique",
    "cost": 1,
    "activation": "Réaction — 1/scène",
    "effect": "Reconnaissez le greffon en défaut et, une fois par scène, mettez-le volontairement au repos avant qu’un dysfonctionnement détecté n’entraîne une complication secondaire. Sa fonction est alors indisponible ; une lésion déjà infligée n’est pas effacée.",
    "details": "",
    "access": "",
    "status": "Refonte"
  },
  {
    "id": "extral-profil-phenotypique",
    "number": 140,
    "name": "Profil phénotypique",
    "cost": 2,
    "activation": "Actif — 1 PA",
    "effect": "Pour 1 PA, recalibrez une modification biologique compatible vers une expression alternative définie avant achat qui demanderait normalement une intervention technique. Les modes ordinaires de l’équipement restent utilisables sans le talent ; aucune fonction absente n’est inventée.",
    "details": "",
    "access": "",
    "status": "Refonte"
  },
  {
    "id": "extral-sursaut-d-expression",
    "number": 141,
    "name": "Sursaut d’expression",
    "cost": 2,
    "activation": "1/scène — selon les coûts du greffon",
    "effect": "Une fois par scène, activez le sur-régime compatible selon ses coûts normaux et gagnez +3 au premier test qui en exploite directement la fonction pendant le round. Les limites et conséquences réelles du greffon demeurent.",
    "details": "",
    "access": "",
    "status": "Refonte"
  },
  {
    "id": "extral-heritage-recombine",
    "number": 142,
    "name": "Héritage recombiné",
    "cost": 1,
    "activation": "Passif — greffe et talent spécifiques",
    "effect": "Une greffe réellement possédée reproduisant le substrat biologique requis vous ouvre l’achat d’un talent racial extral précis, utilisable en R. Ce talent, ses prérequis et la greffe restent à acquérir ; aucun arbre entier ni essaim Homo Superior n’est accordé.",
    "details": "Une fiche de greffe et un identifiant de talent autorisé sont nécessaires ; une description saisie par le joueur ne vaut pas autorisation du MJ.",
    "access": "SR/R",
    "status": "Refonte"
  },
  {
    "id": "extral-tolerance-au-greffon",
    "number": 143,
    "name": "Tolérance au greffon",
    "cost": 1,
    "activation": "Voir règle détaillée",
    "effect": "Gagnez +3 aux tests pour résister à un rejet ou conflit biologique d’une greffe xéno compatible. Les incompatibilités fondamentales ne sont pas levées.",
    "details": "",
    "access": "",
    "status": "Refonte"
  },
  {
    "id": "extral-redondance-biologique",
    "number": 144,
    "name": "Redondance biologique",
    "cost": 2,
    "activation": "1/scène — scène",
    "effect": "Une fois par scène, maintenez pendant la scène la fonction d’une modification encore partiellement intacte malgré une Altération locale qui devrait la neutraliser. Ce contournement actif ne recrée pas les parties détruites et cesse avec la destruction de l’ensemble.",
    "details": "",
    "access": "",
    "status": "Refonte"
  },
  {
    "id": "extral-architecture-quadrigenique",
    "number": 146,
    "name": "Architecture quadrigénique",
    "cost": 3,
    "activation": "Accès : Baséanh N ; Thalsios N ; Mo’sen O ; Rocréen O ; Talass R expérimental ; Ad’rak O ; Homo Superior R.",
    "effect": "Définissez un montage de deux à quatre greffes réellement possédées dont vous savez supprimer les interférences fonctionnelles corrigibles. Elles peuvent opérer ensemble sans ces interférences, mais conservent leurs coûts, fonctions, contraintes biologiques et Charge augmentique.",
    "details": "Aucune réduction de Corruption, hausse d’Intégrité ou acquisition gratuite ; montage soumis à la compatibilité réelle et au MJ.",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-mobilite-cuirassee",
    "number": 147,
    "name": "Mobilité cuirassée",
    "cost": 1,
    "activation": "Voir règle détaillée",
    "effect": "Ignorez jusqu’à −3 de malus de mobilité dus à une armure réellement adaptée à votre morphologie. Les articulations bloquées, charges impossibles et contraintes physiques restent applicables.",
    "details": "",
    "access": "",
    "status": "Refonte"
  },
  {
    "id": "extral-servomusculature",
    "number": 148,
    "name": "Servomusculature",
    "cost": 2,
    "activation": "Voir règle détaillée",
    "effect": "Avec une armure assistée adaptée, gagnez +3 aux tests d’effort exploitant réellement sa servomusculature. Ce bonus améliore la maîtrise, sans relever les limites mécaniques, les PV ou les dégâts.",
    "details": "",
    "access": "",
    "status": "Refonte"
  },
  {
    "id": "extral-verrou-inertiel",
    "number": 149,
    "name": "Verrou inertiel",
    "cost": 2,
    "activation": "Réaction — 1 PA — 1/round",
    "effect": "Une fois par round, dépensez 1 PA en Réaction pour bloquer un renversement ou déplacement physique compatible avec les appuis et capacités de l’armure. Aucun arrêt de téléportation ou de force dépassant sa résistance réelle.",
    "details": "",
    "access": "",
    "status": "Préciser"
  },
  {
    "id": "extral-armure-obstinee",
    "number": 150,
    "name": "Armure obstinée",
    "cost": 3,
    "activation": "Réaction — 1 PA — 1/scène",
    "effect": "Pour 1 PA en Réaction, une fois par scène, isolez une panne non catastrophique et maintenez les fonctions essentielles d’une armure jusqu’à la fin de la scène. Une destruction réelle ne peut pas être ignorée.",
    "details": "",
    "access": "",
    "status": "Préciser"
  },
  {
    "id": "extral-sous-le-tir",
    "number": 151,
    "name": "Sous le tir",
    "cost": 1,
    "activation": "Passif — approche sous le feu — 1/round",
    "effect": "Une fois par round, la simple pression du feu ne suffit pas à interrompre votre approche d’un adversaire sensiblement plus massif ; +3 pour résister à la suppression ou intimidation de cette approche. Les impacts, blessures et obstacles matériels restent appliqués.",
    "details": "",
    "access": "",
    "status": "Refonte"
  },
  {
    "id": "extral-ouvrir-la-cuirasse",
    "number": 152,
    "name": "Ouvrir la cuirasse",
    "cost": 2,
    "activation": "Voir règle détaillée",
    "effect": "Lorsqu’une attaque produit une Altération appropriée, remplacez-la par une brèche qui diminue de 2 l’Armure matérielle de la zone atteinte pour la scène ou jusqu’à réparation. Une même zone ne cumule pas plusieurs réductions de ce talent, et une attaque doit réellement pouvoir endommager la protection.",
    "details": "",
    "access": "",
    "status": "Refonte"
  },
  {
    "id": "extral-demantelement-methodique",
    "number": 154,
    "name": "Démantèlement méthodique",
    "cost": 3,
    "activation": "Actif — 1 PA — 1/scène",
    "effect": "Pour 1 PA, une fois par scène, désignez une brèche réelle d’une cible plus massive : jusqu’à trois alliés capables de la viser ignorent 2 Armure sur leur première attaque contre elle de chaque round pendant la scène. Ce bénéfice remplace un Exploiter la brèche équivalent, sans seconde attaque ni ligne de tir créée.",
    "details": "",
    "access": "R",
    "status": "Refonte"
  },
  {
    "id": "extral-sequence-coordonnee",
    "number": 158,
    "name": "Séquence coordonnée",
    "cost": 3,
    "activation": "1/scène — PA normaux dans chaque passe",
    "effect": "Une fois par scène, coordonnez jusqu’à deux alliés et vous-même pour agir successivement dans les passes du round où chacun peut encore agir. Les PA restent normaux, une action par participant par passe, et aucun ordre d’Initiative n’est conservé au round suivant.",
    "details": "",
    "access": "V/SR/R",
    "status": "Refonte"
  },
  {
    "id": "extral-ancrage-de-terrain",
    "number": 161,
    "name": "Ancrage de terrain",
    "cost": 2,
    "activation": "Actif — 1 PA ; opposition en Réaction — 1 PA",
    "effect": "Pour 1 PA et avec un dispositif AIDH approprié, ancrez une cible consentante à 10 m dans son état V/SR/R pour la scène, sans entretien. Pour 1 PA en Réaction face à un changement forcé, opposez Esprit + Technologie au jet adverse ; la cible peut toujours changer volontairement d’état.",
    "details": "Le jet ajoute normalement 1d10e. Si l’effet adverse possède une procédure d’opposition spécifique, celle-ci prévaut ; aucune Révélation forcée et aucun cumul de protections équivalentes.",
    "access": "V/SR/R",
    "status": "Refonte"
  },
  {
    "id": "extral-fenetre-invariante",
    "number": 162,
    "name": "Fenêtre invariante",
    "cost": 3,
    "activation": "Actif — 1 PA — scène",
    "effect": "Pour 1 PA et avec le projecteur approprié, maintenez une zone d’observation stable jusqu’à la fin de la scène, dans son périmètre réel et avec un rayon maximal de 10 m. Elle protège l’observation et ses données, sans Révélation, vision de V cachée ou extinction de l’Hologramme.",
    "details": "",
    "access": "V/SR/R",
    "status": "Refonte"
  }
];
export function applyExtralRevisions<T extends {id:string;name:string;cost:number;group:string;access:string;activation:string;effect:string;prerequisiteName:string}>(catalog:readonly T[]){
 const edits=new Map(extralRevisions.map(r=>[r.id,r]));
 const rows=catalog.map(t=>{const r=edits.get(t.id);if(!r)return t.activation.startsWith('Accès :')?{...t,access:'V/SR/R',activation:'Voir règle détaillée',learningAccess:t.activation}:t;
  // Keep the complete approved definition; compact cards use at most two sentences.
  const sentences=[...new Intl.Segmenter('fr',{granularity:'sentence'}).segment(r.effect)].map(s=>s.segment);
  const effect=sentences.slice(0,2).join('').trim();
  return {...t,name:r.name,cost:r.cost,effect,effectDetails:[r.effect,r.details].filter(Boolean).join('\n\n'),activation:r.activation.startsWith('Accès :')?'Voir règle détaillée':r.activation,access:t.activation.startsWith('Accès :')?'V/SR/R':r.access,...(t.activation.startsWith('Accès :')?{learningAccess:t.activation}:{}),
   ...(t.id==='extral-projection-de-masse'?{prerequisiteName:'',useCondition:'Cible déjà maintenue ou saisie'}:{})};
 });
 const totals=new Map<string,number>();
 for(const t of rows){const parts=t.group.split(' › ').map(p=>p.replace(/ — \d+ PTV$/,''));for(let i=0;i<parts.length;i++){const key=parts.slice(0,i+1).join(' › ');totals.set(key,(totals.get(key)??0)+t.cost);}}
 return rows.map(t=>{const parts=t.group.split(' › '),plain=parts.map(p=>p.replace(/ — \d+ PTV$/,''));return {...t,group:parts.map((p,i)=>/ — \d+ PTV$/.test(p)?plain[i]+' — '+totals.get(plain.slice(0,i+1).join(' › '))+' PTV':p).join(' › ')};});
}
