// Mage revisions approved by the authors, 2026-09-29. Canonical IDs/costs retained.
export type MageRevision={effect:string;effectDetails:string;activation:string;access?:string;prerequisiteName?:string};
const cap='capacites_et_talents_communs_talents_communs_';
const amplitudeReminder=' Chaque palier d’Amplitude possédé au-dessus de l’effet lancé réduit sa Difficulté intrinsèque d’un niveau, minimum 12 ; cela ne réduit ni la Défense adverse ni les PA ou la Tension de l’effet. Avec au moins deux paliers d’avance, l’effet est automatique seulement hors opposition, urgence et difficulté réelle de contexte.';
export const mageRevisions:Record<string,MageRevision>={
  progression_par_points_de_verite_maitrise_affinee:{effect:'Vous façonnez des effets précis et des formes complexes, et pouvez diviser simplement une même manifestation. Ce palier améliore la finesse du sort, pas son échelle.',effectDetails:'Maîtrise Affinée — 1 PTV, après Initiale dans cette Affinité. Précision élevée, formes complexes et division simple d’un effet ; les possibilités exactes dépendent de l’Affinité, l’Amplitude autorise son échelle et une fonction distincte doit être justifiée.',activation:'Progression permanente · par Affinité'},
  progression_par_points_de_verite_maitrise_superieure:{effect:'Vous combinez plusieurs paramètres dans un même sort et lui donnez des comportements élaborés ou indirects. L’Amplitude doit toujours permettre l’échelle choisie.',effectDetails:'Maîtrise Supérieure — 2 PTV après Affinée, soit 3 PTV cumulés depuis Initiale. Plusieurs paramètres simultanés, effets indirects et comportements élaborés deviennent possibles selon l’Affinité ; ce palier ouvre aussi l’accès à un Accord adjacent.',activation:'Progression permanente · par Affinité'},
  progression_par_points_de_verite_maitrise_magistrale:{effect:'Vous poussez le concept de votre Affinité jusqu’à ses applications les plus complexes. Avec l’Amplitude Majeure et le développement narratif requis, vous pouvez acheter une Œuvre personnelle.',effectDetails:'Maîtrise Magistrale — 3 PTV après Supérieure, soit 6 PTV cumulés depuis Initiale. Elle ouvre les applications extrêmes de l’Affinité mais n’accorde pas gratuitement une Œuvre personnelle, une nouvelle Affinité ou plusieurs fonctions mécaniques sans justification.',activation:'Progression permanente · par Affinité'},
  progression_par_points_de_verite_amplitude_significative:{effect:'Votre magie peut agir à l’échelle d’un petit groupe, d’un véhicule ou d’une pièce. Vos effets Mineurs deviennent aussi plus faciles à lancer : −1 niveau de Difficulté intrinsèque.',effectDetails:'Amplitude Significative — 1 PTV après Mineure. Échelle d’un petit groupe, d’un véhicule ou d’une pièce ; base d’un effet Significatif : Difficulté 18, 2 PA, +2 Tension.'+amplitudeReminder,activation:'Progression permanente · par Affinité'},
  progression_par_points_de_verite_amplitude_majeure:{effect:'Votre magie peut agir à l’échelle d’un bâtiment ou d’une grande zone. Vos effets Significatifs gagnent −1 niveau de Difficulté intrinsèque, et vos effets Mineurs −2.',effectDetails:'Amplitude Majeure — 2 PTV après Significative, soit 3 PTV cumulés depuis Mineure. Base d’un effet Majeur : Difficulté 21, 3 PA, +3 Tension.'+amplitudeReminder,activation:'Progression permanente · par Affinité'},
  progression_par_points_de_verite_amplitude_cataclysmique:{effect:'Votre magie peut transformer un quartier ou un vaste terrain. Vos effets Majeurs gagnent −1 niveau de Difficulté intrinsèque, les Significatifs −2 et les Mineurs −3, sans descendre sous 12.',effectDetails:'Amplitude Cataclysmique — 3 PTV après Majeure, soit 6 PTV cumulés depuis Mineure. Base d’un effet Cataclysmique : Difficulté 25, 4 PA, +4 Tension ; les PA peuvent être investis sur plusieurs rounds consécutifs.'+amplitudeReminder,activation:'Progression permanente · par Affinité'},
  [cap+'equilibrage_du_flux']:{effect:'La première fois par round que vous changez d’Affinité, réduisez votre Tension de 2 au lieu de 1, sans descendre sous zéro, avant d’ajouter celle du nouveau sort.',effectDetails:'La première fois par round que vous changez d’Affinité, réduisez votre Tension de 2 au lieu de 1, minimum zéro, avant d’ajouter la Tension du nouveau sort. Il faut réellement lancer le nouveau sort : changer seulement un choix ou un nom ne décharge rien et n’annule pas un Revers déjà déclenché.',activation:'Passif · premier changement du round',access:'SR/R'},
  [cap+'decharge_controlee']:{effect:'Une fois par round, dépensez 1 PA et réussissez Volonté + Maîtrise spirituelle, difficulté 15, pour réduire votre Tension de 1. Un échec narratif augmente au contraire votre Tension de 1.',effectDetails:'Une fois par round, 1 PA et Volonté + Maîtrise spirituelle + 1d10e contre 15 : réussite, −1 Tension (minimum zéro) ; échec ordinaire, aucun changement ; échec narratif, +1 Tension. La Décharge utilise le Mageius, ne compte pas comme un round de repos et n’annule pas rétroactivement un Revers ou la Dormance.',activation:'1 PA · 1/round',access:'SR/R'},
  [cap+'ancrage_du_mageius']:{effect:'Vous gagnez +3 aux tests pour conserver la concentration d’un sort en préparation ou maintenu malgré une perturbation. Ce bonus protège aussi contre les effets visant à sceller, corrompre ou séparer votre Mageius, sans se cumuler avec sa Protection innée sur le même jet.',effectDetails:'SR/R : +3 aux tests pour conserver la concentration d’un sort en préparation ou maintenu malgré une perturbation significative ; +3 pour résister aux effets visant spécifiquement à sceller, corrompre, arracher, déplacer ou désolidariser le Mageius. Une seule application sur un même jet, sans cumul avec une Protection innée ou équivalente déjà applicable. Aucun bonus aux tests de Revers, aucune réduction de Dormance, aucun PA de maintien offert et aucun bonus permanent de Compétence.',activation:'Passif · concentration ou atteinte au Mageius',access:'SR/R'},
  [cap+'resonance_heritee']:{effect:'Vous réveillez un Écho précis de votre Mageius : pour ce sort, la Difficulté intrinsèque diminue d’un niveau, minimum 12. Vous pouvez le reproduire sans posséder son Affinité, mais uniquement en Maîtrise Initiale / Amplitude Mineure.',effectDetails:'Définissez avant achat l’Écho d’un ancien porteur et ses paramètres avec le MJ. Pour cet effet exact, −1 niveau de Difficulté intrinsèque, minimum 12 ; aucune réduction de la Défense adverse, des PA ou de la Tension. Sans Affinité éveillée, seul cet Écho est disponible en Initiale / Mineure ; une fois l’Affinité apprise, il suit vos propres Maîtrise et Amplitude. L’Écho n’éveille pas toute l’Affinité. La fiche descriptive ne constitue pas une approbation du MJ.',activation:'Selon l’Écho défini',access:'SR/R',prerequisiteName:'Écho identifié et paramètres définis avec le MJ'},
  [cap+'uvre_personnelle']:{effect:'Vous créez avec le MJ une technique signature dotée d’une exception précise aux règles ordinaires de la magie. Son effet, ses coûts et ses conditions sont définis avant l’achat ; cette exception ne bénéficie qu’à cette technique.',effectDetails:'Prérequis : Maîtrise Magistrale et Amplitude Majeure dans l’Affinité principale, avec développement narratif approprié. L’Œuvre est définie avec le MJ : effet, Affinités requises, Maîtrise, Amplitude, PA, portée, Tension et exception propre. Elle doit ouvrir une possibilité distincte de l’improvisation ordinaire ; elle n’améliore pas tous vos sorts. L’achat coûte 3 PTV, en plus des paliers ; aucune exception ou autorisation MJ n’est créée par un texte saisi par le joueur.',activation:'Selon l’Œuvre définie',access:'R',prerequisiteName:'Maîtrise Magistrale + Amplitude Majeure dans l’Affinité principale, développement narratif et technique définie'},
  [cap+'heritage_familial']:{effect:'Vous apprenez une technique familiale transmise, avec son effet et ses règles particulières. Vous devez posséder les Affinités et atteindre les paliers de Maîtrise et d’Amplitude exigés par cette technique.',effectDetails:'Une technique familiale identifiée doit avoir été réellement enseignée et définie avec le MJ. Vérifiez chacune de ses Affinités, Maîtrises et Amplitudes requises, pas une progression quelconque dans un autre domaine. L’achat coûte 2 PTV et n’exige pas d’acheter Œuvre personnelle en plus ; une Affinité étrangère reste à ouvrir par la Roue sauf exception explicitement accordée par la tradition et le MJ. Le formulaire ne vaut jamais autorisation MJ.',activation:'Selon la technique transmise',access:'R',prerequisiteName:'Technique transmise définie ; ses Affinités, Maîtrises et Amplitudes requises'}
};
export function applyMageRevisions<T extends {id:string}>(catalog:readonly T[]){return catalog.map(row=>mageRevisions[row.id]?{...row,...mageRevisions[row.id]}:row);}
