// Migrated from the final V1 runtime visibility table.
// This is native V2 rule data: no runtime patching or layered override remains.
export const truthVisibilityNeedles = {
  humain:{doctrine_commune:['doctrine commune de chasse'],lavandiere:['lavandieres'],catholique:['chasseurs catholiques'],khalsa:['khalsa'],taoiste:['taoistes'],kabbale:['kabbale'],nizarite:['nizarites','asasiyun'],onmyoji:['onmyoji'],neopaien:['neopaiens'],chasse_fantastique:['chasse fantastique'],lueurs_azmenor:["lueurs d'azmenor"],xenoshield:['xenoshield'],independant:['chasseurs independants'],table_ronde:['table ronde']},
  vampire:{krovni_rytsari:['krovni rytsari'],alghul_almalakiu:['alghul almalakiu'],oru_ayeraye:['oru ayeraye'],ihuito_meztzi:['ihuito meztzi'],shi_hun_zhe:['shi hun zhe'],sang_ecarlate:['sang ecarlate'],sang_primal:['sang primal'],sang_hypocrite:['sang hypocrite'],sang_venimeux:['sang venimeux'],sang_masque:['sang masque'],sang_aveugle:['sang aveugle'],sang_traqueur:['sang traqueur'],sang_glacial:['sang glacial'],sang_ardent:['sang ardent'],sang_orageux:['sang orageux'],sang_revelateur:['sang revelateur'],sang_condamne:['sang condamne']},
  garou:{pelages_gris:['pelages gris'],pelages_noirs:['pelages noirs'],pelages_blancs:['pelages blancs'],pelages_roux:['pelages roux'],pelages_bruns:['pelages bruns'],pelages_dores:['pelages dores'],sang_naturel:['sang naturel'],sang_alpha:['sang alpha'],sang_revelateur:['sang revelateur'],sang_ecarlate:['sang ecarlate'],sang_sculpteur:['sang sculpteur'],sang_funeste:['sang funeste'],sang_primal:['sang primal'],sang_chasseur:['sang chasseur'],sang_de_sagesse:['sang de sagesse'],sang_enrage:['sang enrage'],sang_enchaine:['sang enchaine'],sang_vengeur:['sang vengeur']},
  khinae:{canides_errants:['canides errants'],renards:['renards'],grands_felins:['grands felins'],chats:['chats'],rapaces:['rapaces'],requins:['requins'],serpents:['serpents'],boudas:['boudas'],berserkirs:['berserkirs'],crocodiliens:['crocodiliens']},
  daemon:{oracle:['oracle tentateur'],tourmenteur:['chatiment tourmenteur'],legionnaire:['chevalier legionnaire'],alabor:['alabor'],astaroth:['astaroth'],belial:['belial'],diablo:['diablo'],lilith:['lilith'],mammon:['mammon'],mephisto:['mephisto'],satan:['satan'],lucifer:['lucifer'],belzebuth:['belzebuth'],abigor:['abigor'],baal:['baal'],morrighan:['morrighan']},
  angelus:{trone:['nature trone'],vertu:['nature vertu'],domination:['nature domination'],kether:['kether'],hokhma:['hokhma'],bina:['bina'],hesed:['hesed'],gueburah:['gueburah'],tiphereth:['tiph ereth','tiphereth'],nesah:['nesah'],hod:['hod'],yessod:['yessod'],malkhouth:['malkhouth']},
  aseryn:{aerilien:['aerilien neo atlante'],mulien:['mulien'],hyperboreen:['hyperboreen'],lemurian:['lemurian'],seratheen:['seratheen'],athegos:['athegos'],sundosia:['sundosia'],caendis:['caendis'],cairiah:['cairiah'],eydreas:['eydreas'],seryn:['seryn'],natyel:['natyel'],erith:['erith'],lisirast:['lisirast'],lisithas:['lisithas'],selerias:['selerias'],theana:['theana'],dratyn:['dratyn'],conseil_foudre:['conseil de la foudre']},
  exile:{elye:['elye elfes'],whurten:['whurten nains'],ashyll:['ashyll gobelins'],thulkar:['thulkar orques'],azmenorien:['azmenorien'],silcenter:['silcenters et hds'],croix_emphyrra:["croix d'emphyrra"],runes_whurten:['runes whurtennes'],atelier_clans:['atelier des clans'],iron_law:['iron law'],green_union:['green union'],quatre_empereurs:['ligue des quatre empereurs'],syndicat_jade:['syndicat de jade'],horde_divine:['horde divine'],horde_marais:['horde des marais'],horde_fantome:['horde fantome'],horde_cendres:['horde des cendres'],horde_rose:['horde de la rose'],servants_pluton:['servants de pluton'],technomagie_azmenor:['technomagie azmenorienne']},
  extral:{talass:['talass'],mosen:["mo sen"],baseanh:['baseanh'],rocreen:['rocreen'],thalsios:['thalsios'],homo_superior:['homo superior'],adrak:['ad rak'],gaac:['gaac'],ctu:['ctu'],croix_verte:['croix verte','ligue baseanne'],reptile:['reptile'],shaediri:['mafia shaediri'],hydroguard:['hydroguard','thdf'],smrc:['smrc','agi'],sra:['sra'],emeraude:['emeraude sanglante'],aidh_intervention:["doctrine d intervention aidh"],aidh_coherence:['protocoles de coherence aidh']}
} as const;

export const truthSharedHunterNatures = ["humain","vampire","exile","extral"] as const;
