import type {FastifyInstance} from 'fastify';
import {randomUUID,randomInt} from 'node:crypto';
import {isDeepStrictEqual} from 'node:util';
import {pool} from './db.js';
import {requireUser} from './auth.js';
import {frenzyActionCheck,recordFrenzyAction,recordSurvivalFuryDamage} from './rules/live-frenzy.js';
import {spendRestrictedPA} from './rules/live-action-restrictions.js';
import {blankPlayState,playProfile,rollD10} from './rules/play-state.js';
import {normalizedNatureResources} from './rules/live-nature-resources.js';
import {recoverLightningWounds} from './rules/lightning-wounds.js';
import {liveHealingMaximum} from './character-live-mechanics.js';
import {applyVampireLastSleep} from './rules/live-vampire.js';
import {edgeBalance,spendEdge,forcedDie} from './character-edge.js';
import {addLiveEffect,createLiveEffect,canSpendPhysicalPA} from './rules/live-effects.js';
import {consumeNatureTest} from './rules/live-nature-resources.js';
import {consumeRegisteredTest} from './rules/registered-power-state.js';
import {target as combatTarget} from './campaign-combat.js';
import {lockCombat,combatState,participates,recordAction,maybeAdvanceCombat} from './campaign-rounds.js';
import {occultSourceKind,occultRollSkill,occultDamage,occultEffectDrafts,occultCondition,occultPowerIds} from './rules/occult-resolution.js';
const uuid=(v:any)=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);
const integer=(v:any,min:number,max:number)=>Number.isSafeInteger(v)&&v>=min&&v<=max;
const manager=(u:any)=>['gm','editor','admin'].includes(u.role);
const text=(v:any,max=1200)=>typeof v==='string'&&!!v.trim()&&v.length<=max&&!/[\u0000-\u001f\u007f]/.test(v);
async function actor(db:any,campaign:string,id:string){
 const pc=(await db.query(`SELECT c.*,s.state,s.version AS play_version FROM characters c JOIN campaign_members m ON m.character_id=c.id AND m.user_id=c.owner_id AND m.campaign_id=c.campaign_id AND m.status='accepted' LEFT JOIN character_play_states s ON s.character_id=c.id WHERE c.id=$1 AND c.campaign_id=$2 AND c.archived_at IS NULL FOR UPDATE OF c`,[id,campaign])).rows[0];
 if(pc)return {row:pc,pc:true,state:structuredClone({...blankPlayState(),...pc.state}),version:pc.play_version??0};
 const npc=(await db.query('SELECT * FROM campaign_live_combatants WHERE id=$1 AND campaign_id=$2 AND NOT removed FOR UPDATE',[id,campaign])).rows[0];return npc?{row:npc,pc:false,state:structuredClone(npc.data),version:npc.version}:null;
}
async function save(db:any,a:any){
 if(a.pc){a.state.pa=playProfile(a.row.data,a.state).pa;await db.query(`INSERT INTO character_play_states(character_id,state,version) VALUES($1,$2::jsonb,$3) ON CONFLICT(character_id) DO UPDATE SET state=EXCLUDED.state,version=EXCLUDED.version,updated_at=now()`,[a.row.id,JSON.stringify(a.state),a.version+1]);}
 else await db.query('UPDATE campaign_live_combatants SET data=$2::jsonb,hp=$3,pa=$4,version=version+1 WHERE id=$1',[a.row.id,JSON.stringify(a.state),a.row.hp,a.row.pa]);
}
async function sourceEvent(db:any,campaign:string,id:string,acrossSessions=false){
 const e=(await db.query(`SELECT e.*,c.name,c.data FROM character_play_events e JOIN characters c ON c.id=e.character_id WHERE e.id=$1 AND e.campaign_id=$2 AND c.campaign_id=$2 AND c.archived_at IS NULL AND ($3::boolean OR e.live_session_id IS NOT DISTINCT FROM (SELECT session_id FROM campaign_live_context WHERE campaign_id=$2)) AND NOT EXISTS(SELECT 1 FROM campaign_live_events boundary WHERE boundary.campaign_id=e.campaign_id AND boundary.kind IN ('combat-scene','combat-scenario') AND boundary.created_at>e.created_at)`,[id,campaign,acrossSessions])).rows[0];
 return e&&occultSourceKind(e.kind)&&e.payload.success!==false&&!e.payload.narrativeFailure&&e.payload.spell?.forced!==true&&e.request_payload?.enabled!==false?e:null;
}
async function liveEvent(db:any,campaign:string,user:any,b:any,kind:string,payload:any){await db.query('INSERT INTO campaign_live_events(id,campaign_id,created_by,kind,payload,request_payload,public) VALUES($1,$2,$3,$4,$5::jsonb,$6::jsonb,false)',[b.requestId,campaign,user.id,kind,JSON.stringify(payload),JSON.stringify(b)]);}
const effects=(a:any)=>a.pc?a.state.effects??[]:a.state.liveEffects??[];
const setEffects=(a:any,v:any[])=>{if(a.pc)a.state.effects=v;else a.state.liveEffects=v;};
async function occultEdgeResults(db:any,campaign:string,actorIds:string[],eventId:string|null=null){
 return (await db.query(`SELECT r.*,
  source.kind AS source_kind,source.character_id AS source_actor_id,source.payload AS source_payload,source.request_payload AS source_request,
  EXISTS(SELECT 1 FROM campaign_live_events closed WHERE closed.campaign_id=$1 AND closed.kind IN ('occult-resolve','occult-cancel') AND closed.payload->>'sourceEventId'=source.id::text) AS source_closed,
  (SELECT resolved.payload FROM campaign_live_events resolved WHERE resolved.campaign_id=$1 AND resolved.kind='occult-resolve' AND resolved.payload->>'sourceEventId'=source.id::text LIMIT 1) AS decree_resolution,
  EXISTS(SELECT 1 FROM campaign_live_events later WHERE later.campaign_id=$1 AND later.kind='occult-resist-decree' AND later.payload->>'actorId'=r.payload->>'actorId' AND later.payload->>'effectId'=r.payload->>'effectId' AND (later.payload->>'resultVersion')::integer>(r.payload->>'resultVersion')::integer) AS newer_resistance
 FROM campaign_live_events r JOIN character_play_events source ON source.id=(r.payload->>'sourceEventId')::uuid
 JOIN characters caster ON caster.id=source.character_id AND caster.campaign_id=$1 AND caster.archived_at IS NULL
 WHERE r.campaign_id=$1 AND source.campaign_id=$1 AND r.kind IN ('occult-defend','occult-resist-decree') AND r.payload->>'actorId'=ANY($2::text[]) AND ($3::uuid IS NULL OR r.id=$3)
  AND r.live_session_id IS NOT DISTINCT FROM (SELECT session_id FROM campaign_live_context WHERE campaign_id=$1)
  AND (r.kind='occult-resist-decree' OR source.live_session_id IS NOT DISTINCT FROM (SELECT session_id FROM campaign_live_context WHERE campaign_id=$1))
  AND EXISTS(SELECT 1 FROM campaign_members m WHERE m.campaign_id=$1 AND m.character_id=caster.id AND m.user_id=caster.owner_id AND m.status='accepted')
  AND NOT EXISTS(SELECT 1 FROM campaign_live_events boundary WHERE boundary.campaign_id=$1 AND boundary.kind IN ('combat-scene','combat-scenario') AND boundary.created_at>source.created_at)
  AND NOT EXISTS(SELECT 1 FROM campaign_live_events boundary WHERE boundary.campaign_id=$1 AND boundary.kind IN ('combat-start','combat-stop','combat-round','combat-scene','combat-scenario') AND boundary.created_at>r.created_at)
 ORDER BY r.created_at DESC,r.id DESC LIMIT 30`,[campaign,actorIds,eventId])).rows;
}
function occultEdgeError(result:any,a:any,shared:any):string|null{
 if(!a?.pc||!result||!Array.isArray(result.payload.dice)||!Number.isFinite(result.payload.modifier))return 'edge_roll_unavailable';
 const p=result.payload,source=result.source_payload;
 if(p.edgeForced)return 'edge_already_used';
 if(!Number.isSafeInteger(p.resultVersion)||p.resultVersion!==a.version||p.round!==(shared.active?shared.round:a.state.round)||p.combatActive!==shared.active)return 'edge_roll_resolved';
 if(!occultSourceKind(result.source_kind)||source?.success===false||source?.narrativeFailure||source?.spell?.forced===true||result.source_request?.enabled===false)return 'edge_roll_resolved';
 if(result.kind==='occult-defend')return p.active===true&&!result.source_closed?null:'edge_roll_resolved';
 const effect=effects(a).find((f:any)=>f.id===p.effectId&&f.ruleId===occultPowerIds.decree&&f.sourceId===result.source_actor_id),resolution=result.decree_resolution;
 return p.success===false&&Number.isFinite(p.opposition)&&effect&&!result.newer_resistance&&resolution?.powerId===occultPowerIds.decree&&resolution.counterDifficulty===p.opposition&&resolution.targets?.some((t:any)=>t.actorId===a.row.id&&t.effectIds?.includes(p.effectId))?null:'edge_roll_resolved';
}
/** Caller holds the campaign lock. Broken concentration removes the exact source-linked effects. */
export async function pruneOccultMaintenance(db:any,campaign:string|null){
 if(!campaign)return;
 const rows=(await db.query("SELECT id,payload FROM campaign_live_events WHERE campaign_id=$1 AND kind='occult-resolve' AND payload->>'maintained'='true' AND COALESCE((payload->>'maintenanceEnded')::boolean,false)=false",[campaign])).rows;
 for(const e of rows){
  const s=await actor(db,campaign,e.payload.sourceId);if(!s?.pc){for(const t of e.payload.targets??[]){const a=await actor(db,campaign,t.actorId);if(!a)continue;const ids=new Set(t.effectIds??[]),before=effects(a),next=before.filter((f:any)=>!ids.has(f.id));if(next.length!==before.length){setEffects(a,next);await save(db,a);}}await db.query("UPDATE character_play_states SET state=jsonb_set(state,'{natureResources,mage,maintained}',COALESCE((SELECT jsonb_agg(x) FROM jsonb_array_elements(state#>'{natureResources,mage,maintained}') x WHERE x<>to_jsonb($2::text)),'[]'::jsonb)),version=version+1 WHERE character_id=$1 AND state#>'{natureResources,mage,maintained}' ? $2",[e.payload.sourceId,e.id]);await db.query("UPDATE campaign_live_events SET payload=payload||'{\"maintenanceEnded\":true}'::jsonb WHERE id=$1",[e.id]);continue;}
  const r=normalizedNatureResources(s.state.natureResources),alive=playProfile(s.row.data,s.state).hp>0&&!s.state.unconscious&&!r.mage.dormant&&s.state.revelation!=='v';
  const active=alive&&r.mage.maintained.includes(e.id),targets=[];
  for(const t of e.payload.targets??[]){const a:any=t.actorId===s.row.id?s:await actor(db,campaign,t.actorId);if(!a)continue;const ids=new Set(t.effectIds??[]),before=effects(a),next=active?before:before.filter((f:any)=>!ids.has(f.id));if(next.length!==before.length){setEffects(a,next);await save(db,a);}if(next.some((f:any)=>ids.has(f.id)))targets.push(t.actorId);}
  if(!active||!targets.length){await db.query("UPDATE campaign_live_events SET payload=payload||'{\"maintenanceEnded\":true}'::jsonb WHERE id=$1",[e.id]);const next=r.mage.maintained.filter(id=>id!==e.id);if(next.length!==r.mage.maintained.length){r.mage.maintained=next;s.state.natureResources=r;await save(db,s);}}
 }
}
export async function registerCampaignOccultResolutionRoutes(app:FastifyInstance){
 app.get<{Params:{id:string}}>('/api/campaigns/:id/occult-consents',async(req,reply)=>{
  reply.header('Cache-Control','private, no-store');const user=await requireUser(req,reply);if(!user)return;
  if(!uuid(req.params.id))return reply.code(404).send({error:'campaign_not_found'});
  const owned=(await pool.query(`SELECT c.id,c.name,c.data,s.state,s.version FROM characters c JOIN campaign_members m ON m.character_id=c.id AND m.user_id=c.owner_id AND m.campaign_id=c.campaign_id AND m.status='accepted' LEFT JOIN character_play_states s ON s.character_id=c.id WHERE c.campaign_id=$1 AND c.owner_id=$2 AND c.archived_at IS NULL`,[req.params.id,user.id])).rows;
  if(!owned.length)return {offers:[],results:[]};
  const edges=new Map(await Promise.all(owned.map(async(a:any)=>[a.id,await edgeBalance(pool,a.id,a.data)] as const)));
  const offers=(await pool.query(`SELECT e.id,e.kind,e.payload FROM campaign_live_events e WHERE e.campaign_id=$1 AND e.kind IN ('occult-consent-offer','occult-defense-offer') AND e.live_session_id IS NOT DISTINCT FROM (SELECT session_id FROM campaign_live_context WHERE campaign_id=$1) AND NOT EXISTS(SELECT 1 FROM campaign_live_events r WHERE r.campaign_id=$1 AND r.kind IN ('occult-resolve','occult-cancel') AND r.payload->>'sourceEventId'=e.payload->>'sourceEventId') AND NOT EXISTS(SELECT 1 FROM campaign_live_events b WHERE b.campaign_id=$1 AND b.kind IN ('combat-scene','combat-scenario') AND b.created_at>e.created_at) ORDER BY e.created_at DESC LIMIT 50`,[req.params.id])).rows;
  const grants=(await pool.query("SELECT kind,payload FROM campaign_live_events WHERE campaign_id=$1 AND (kind='occult-defend' OR kind='occult-consent' AND created_by=$2)",[req.params.id,user.id])).rows;
  const projected:any[]=[],seen=new Set<string>();for(const e of offers)for(const t of e.payload.targets??[]){const own=owned.find((a:any)=>a.id===t.actorId),key=e.kind+':'+e.payload.sourceEventId+':'+t.actorId;if(!own||seen.has(key)||grants.some((g:any)=>g.payload.sourceEventId===e.payload.sourceEventId&&g.payload.actorId===own.id&&(e.kind==='occult-defense-offer'||g.payload.note===e.payload.note)&&(e.kind==='occult-defense-offer'?g.kind==='occult-defend':g.kind==='occult-consent')))continue;seen.add(key);projected.push({offerId:e.id,sourceEventId:e.payload.sourceEventId,actorId:own.id,version:own.version??0,characterName:own.name,sourceName:e.payload.sourceName,label:e.kind==='occult-defense-offer'?'Choisir une défense':'Accepter l’effet proposé',type:e.kind==='occult-defense-offer'?'defense':'consent',defenseKind:e.payload.defenseKind,pa:playProfile(own.data,{...blankPlayState(),...own.state}).pa,edge:edges.get(own.id),impulse:own.state?.frenzy?.impulse??null,note:e.payload.note});}
  const decrees=(await pool.query("SELECT payload FROM campaign_live_events WHERE campaign_id=$1 AND kind='occult-resolve' AND payload->>'powerId'=$2",[req.params.id,occultPowerIds.decree])).rows;
  for(const own of owned)for(const effect of own.state?.effects??[]){if(effect.ruleId!==occultPowerIds.decree)continue;const resolution=decrees.find((r:any)=>r.payload.targets.some((t:any)=>t.actorId===own.id&&t.effectIds.includes(effect.id)));if(resolution)projected.push({sourceEventId:resolution.payload.sourceEventId,actorId:own.id,version:own.version??0,characterName:own.name,sourceName:'Décret royal',label:'Résister à l’interdit',type:'decree',effectId:effect.id,edge:edges.get(own.id),note:effect.name});}
  const shared=await combatState(pool,req.params.id),results=[];
  for(const result of await occultEdgeResults(pool,req.params.id,owned.map((a:any)=>a.id))){const own=owned.find((a:any)=>a.id===result.payload.actorId),a={pc:true,row:own,state:{...blankPlayState(),...own.state},version:own.version??0};if(occultEdgeError(result,a,shared))continue;const p=result.payload;results.push({eventId:result.id,sourceEventId:p.sourceEventId,actorId:own.id,version:p.resultVersion,characterName:own.name,label:p.label,type:result.kind==='occult-defend'?'defense':'decree',total:p.total,modifier:p.modifier,dice:p.dice,sum:p.sum,narrativeFailure:p.narrativeFailure,success:p.success,edge:edges.get(own.id)});}
  return {offers:projected,results};
 });
 app.get<{Params:{id:string}}>('/api/campaigns/:id/occult-resolutions',async(req,reply)=>{
  reply.header('Cache-Control','private, no-store');const user=await requireUser(req,reply);if(!user)return;
  if(!uuid(req.params.id)||!manager(user)||!(await pool.query('SELECT id FROM campaigns WHERE id=$1 AND owner_id=$2 AND archived_at IS NULL',[req.params.id,user.id])).rowCount)return reply.code(404).send({error:'campaign_not_found'});
  const sources=(await pool.query(`SELECT e.id,e.character_id AS "sourceId",c.name AS "sourceName",e.kind,(e.payload||jsonb_build_object('powerId',COALESCE(e.payload->>'powerId',e.request_payload->>'powerId'))) AS payload,e.created_at AS "createdAt" FROM character_play_events e JOIN characters c ON c.id=e.character_id WHERE e.campaign_id=$1 AND c.campaign_id=$1 AND c.archived_at IS NULL AND e.request_payload->>'enabled' IS DISTINCT FROM 'false' AND e.kind=ANY($2::text[]) AND e.live_session_id IS NOT DISTINCT FROM (SELECT session_id FROM campaign_live_context WHERE campaign_id=$1) AND NOT EXISTS(SELECT 1 FROM campaign_live_events r WHERE r.campaign_id=$1 AND r.kind IN ('occult-resolve','occult-cancel') AND r.payload->>'sourceEventId'=e.id::text) AND NOT EXISTS(SELECT 1 FROM campaign_live_events b WHERE b.campaign_id=$1 AND b.kind IN ('combat-scene','combat-scenario') AND b.created_at>e.created_at) ORDER BY e.created_at DESC LIMIT 30`,[req.params.id,['nature-mage-release','nature-daemon-spectrum-release','nature-power-release','power']])).rows.filter((e:any)=>e.payload.success!==false&&!e.payload.narrativeFailure&&e.payload.spell?.forced!==true&&e.request_payload?.enabled!==false);
  const maintained=(await pool.query(`SELECT e.id,e.payload,s.version AS source_version FROM campaign_live_events e JOIN character_play_states s ON s.character_id=(e.payload->>'sourceId')::uuid WHERE e.campaign_id=$1 AND e.kind='occult-resolve' AND e.payload->>'maintained'='true' AND s.state->'natureResources'->'mage'->'maintained' ? e.id::text ORDER BY e.created_at DESC`,[req.params.id])).rows;
  const consent=(await pool.query("SELECT payload FROM campaign_live_events WHERE campaign_id=$1 AND kind='occult-consent' AND live_session_id IS NOT DISTINCT FROM (SELECT session_id FROM campaign_live_context WHERE campaign_id=$1)",[req.params.id])).rows.map((e:any)=>e.payload);
  for(const s of sources)s.rolls=(await pool.query("SELECT id,payload FROM character_play_events WHERE character_id=$1 AND campaign_id=$2 AND kind='roll' AND request_payload->>'skill'=$3 AND created_at>=$4 AND live_session_id IS NOT DISTINCT FROM (SELECT session_id FROM campaign_live_context WHERE campaign_id=$2) ORDER BY created_at DESC LIMIT 15",[s.sourceId,req.params.id,occultRollSkill(s.payload.powerId??''),s.createdAt])).rows;
  return {sources,maintained:maintained.map((m:any)=>({id:m.id,payload:{...m.payload,sourceVersion:m.source_version}})),consent};
 });
 app.post<{Params:{id:string};Body:any}>('/api/campaigns/:id/occult-resolutions',async(req,reply)=>{
  reply.header('Cache-Control','private, no-store');const user=await requireUser(req,reply);if(!user)return;const b=req.body as any,campaign=req.params.id;
  if(!uuid(campaign)||!b||!uuid(b.requestId)||!['resolve','cancel','request-consent','request-defense','consent','defend','maintain','end-maintenance','resist-decree','force-defense'].includes(b.action))return reply.code(400).send({error:'invalid_occult_action'});
  if(b.edge!==undefined&&typeof b.edge!=='boolean')return reply.code(400).send({error:'invalid_edge'});
  if(b.edge&&!['defend','resist-decree'].includes(b.action))return reply.code(400).send({error:'invalid_edge_action'});
  const db=await pool.connect();try{
   await db.query('BEGIN');const fail=async(status:number,error:string)=>{await db.query('ROLLBACK');return reply.code(status).send({error});};
   const camp=(await db.query('SELECT owner_id FROM campaigns WHERE id=$1 AND archived_at IS NULL',[campaign])).rows[0],mj=camp?.owner_id===user.id&&manager(user);
   if(!camp||!mj&&!(await db.query("SELECT 1 FROM campaign_members WHERE campaign_id=$1 AND user_id=$2 AND status='accepted'",[campaign,user.id])).rowCount)return await fail(404,'campaign_not_found');
   await lockCombat(db,campaign);
   const prior=(await db.query('SELECT campaign_id,created_by,request_payload,payload FROM campaign_live_events WHERE id=$1',[b.requestId])).rows[0];if(prior){if(prior.campaign_id!==campaign||prior.created_by!==user.id||!isDeepStrictEqual(prior.request_payload,b))return await fail(409,'occult_request_conflict');await db.query('COMMIT');return {ok:true,alreadyApplied:true,...(typeof prior.payload?.total==='number'?{total:prior.payload.total}:{}),...(typeof prior.payload?.success==='boolean'?{success:prior.payload.success}:{})};}
   if((await db.query('SELECT id FROM character_play_events WHERE id=$1',[b.requestId])).rowCount)return await fail(409,'occult_request_conflict');
   const shared=await combatState(db,campaign);
   if(b.action==='force-defense'){
    if(!uuid(b.eventId)||!uuid(b.actorId))return await fail(400,'edge_roll_unavailable');
    const a=await actor(db,campaign,b.actorId);if(!a?.pc||!mj&&a.row.owner_id!==user.id)return await fail(404,'actor_not_found');if(a.version!==b.version)return await fail(409,'occult_version_conflict');
    const result=(await occultEdgeResults(db,campaign,[a.row.id],b.eventId))[0];if(!result)return await fail(400,'edge_roll_resolved');const unavailable=occultEdgeError(result,a,shared);if(unavailable)return await fail(400,unavailable);
    const error=await spendEdge(db,a.row.id,a.row.data,result.id,'force');if(error)return await fail(400,error);
    const original=result.payload,payload={...original,originalRoll:{dice:original.dice,total:original.total,narrativeFailure:original.narrativeFailure,...(result.kind==='occult-resist-decree'?{success:original.success}:{})},...forcedDie(),total:original.modifier+20};
    if(result.kind==='occult-resist-decree'){payload.success=payload.total>=original.opposition;if(payload.success)setEffects(a,effects(a).filter((f:any)=>f.id!==original.effectId));}
    await save(db,a);await db.query('UPDATE campaign_live_events SET payload=$2::jsonb WHERE id=$1',[result.id,JSON.stringify(payload)]);
    await liveEvent(db,campaign,user,b,'occult-force-defense',{...payload,label:'Forcer le Destin · '+original.label,referenceId:result.id,resultVersion:a.version+1,paSpent:0});await db.query('COMMIT');return {ok:true,total:payload.total,...(result.kind==='occult-resist-decree'?{success:payload.success}:{})};
   }
   if(b.action==='maintain'||b.action==='end-maintenance'){
    if(!uuid(b.resolutionId))return await fail(400,'invalid_occult_resolution');
    const e=(await db.query("SELECT * FROM campaign_live_events WHERE id=$1 AND campaign_id=$2 AND kind='occult-resolve' AND payload->>'maintained'='true' AND COALESCE((payload->>'maintenanceEnded')::boolean,false)=false",[b.resolutionId,campaign])).rows[0];if(!e)return await fail(404,'occult_resolution_not_found');
    const s=await actor(db,campaign,e.payload.sourceId);if(!s?.pc||!mj&&s.row.owner_id!==user.id)return await fail(404,'actor_not_found');if(s.version!==b.version)return await fail(409,'occult_version_conflict');
    const r=normalizedNatureResources(s.state.natureResources);if(!r.mage.maintained.includes(e.id))return await fail(400,'occult_maintenance_ended');
    if(b.action==='maintain'){
     if(!shared.active||!participates(shared,s.row.id)||s.state.initiative===null||playProfile(s.row.data,s.state).hp<=0||s.state.unconscious||r.mage.dormant||s.state.revelation==='v'||s.state.pa<1)return await fail(400,'occult_maintenance_unavailable');
     const paid=(await db.query("SELECT id FROM campaign_live_events WHERE campaign_id=$1 AND kind='occult-maintain' AND payload->>'resolutionId'=$2 AND (payload->>'round')::integer=$3 AND live_session_id IS NOT DISTINCT FROM (SELECT session_id FROM campaign_live_context WHERE campaign_id=$1)",[campaign,e.id,shared.round])).rowCount;
     if(paid||e.payload.createdRound===shared.round)return await fail(400,'occult_maintenance_already_paid');
     let found=0;for(const t of e.payload.targets){const a:any=t.actorId===s.row.id?s:await actor(db,campaign,t.actorId);if(!a)continue;const ids=new Set(t.effectIds);setEffects(a,effects(a).map((f:any)=>{if(ids.has(f.id)){if(f.expires.unit!=='round'||f.expires.at<shared.round)throw new Error('occult_maintenance_expired');found++;return {...f,expires:{unit:'round',at:shared.round+1}};}return f;}));if(a!==s)await save(db,a);}
     if(!found)return await fail(400,'occult_maintenance_expired');frenzyActionCheck(s.state,1,b,{manager:mj});spendRestrictedPA(s.state,1,'occult');recordFrenzyAction(s.state,1,b,{manager:mj});r.mage.usedRound=shared.round;s.state.natureResources=r;await save(db,s);await recordAction(db,campaign,s.row.id,1);await liveEvent(db,campaign,user,b,'occult-maintain',{label:'Maintien du sort · '+e.payload.label,resolutionId:e.id,sourceId:s.row.id,round:shared.round,paSpent:1});await maybeAdvanceCombat(db,campaign,user.id);
    }else{r.mage.maintained=r.mage.maintained.filter(id=>id!==e.id);s.state.natureResources=r;await save(db,s);await pruneOccultMaintenance(db,campaign);await liveEvent(db,campaign,user,b,'occult-end-maintenance',{label:'Concentration interrompue',resolutionId:e.id,sourceId:s.row.id});}
    await db.query('COMMIT');return {ok:true};
   }
   if(!uuid(b.sourceEventId))return await fail(400,'invalid_occult_source');const e=await sourceEvent(db,campaign,b.sourceEventId,b.action==='resist-decree');if(!e)return await fail(404,'occult_source_not_found');
   if((await db.query("SELECT id FROM campaign_live_events WHERE campaign_id=$1 AND kind IN ('occult-resolve','occult-cancel') AND payload->>'sourceEventId'=$2",[campaign,e.id])).rowCount&&b.action!=='resist-decree')return await fail(409,'occult_source_resolved');
   if(b.action==='cancel'){
    if(!mj&&e.created_by!==user.id)return await fail(403,'occult_resolution_mj_only');if(b.confirmed!==true||!text(b.note))return await fail(400,'occult_ruling_required');
    await liveEvent(db,campaign,user,b,'occult-cancel',{label:'Effet classé sans conséquence',sourceEventId:e.id,sourceId:e.character_id,note:b.note,paRefunded:0});await maybeAdvanceCombat(db,campaign,user.id);await db.query('COMMIT');return {ok:true};
   }
   if(b.action==='request-consent'||b.action==='request-defense'){
    if(!mj)return await fail(403,'occult_resolution_mj_only');if(!text(b.note,1200)||!Array.isArray(b.targets)||!b.targets.length||b.targets.length>12||new Set(b.targets.map((t:any)=>t.actorId)).size!==b.targets.length)return await fail(400,'invalid_occult_consent_offer');
    if(b.action==='request-defense'&&(!['physical','occult'].includes(b.defenseKind)||([occultPowerIds.injunction,occultPowerIds.decree,occultPowerIds.sovereignty,occultPowerIds.phantasm] as string[]).includes(e.payload.powerId??e.request_payload?.powerId??'')&&b.defenseKind!=='occult'))return await fail(400,'occult_defense_required');
    const targets=[];for(const t of b.targets){if(!uuid(t.actorId))return await fail(400,'invalid_occult_target');const a=await actor(db,campaign,t.actorId);if(!a?.pc)return await fail(404,'actor_not_found');targets.push({actorId:a.row.id});}
    await liveEvent(db,campaign,user,b,b.action==='request-defense'?'occult-defense-offer':'occult-consent-offer',{sourceEventId:e.id,sourceName:e.name,note:b.note,targets,defenseKind:b.action==='request-defense'?b.defenseKind:undefined,label:b.action==='request-defense'?'Choix de défense demandé':'Consentement à un effet allié demandé'});await db.query('COMMIT');return {ok:true};
   }
   if(['consent','defend','resist-decree'].includes(b.action)){
    if(!uuid(b.actorId))return await fail(400,'invalid_occult_target');const a=await actor(db,campaign,b.actorId);if(!a||!mj&&(!a.pc||a.row.owner_id!==user.id))return await fail(404,'actor_not_found');if(a.version!==b.version)return await fail(409,'occult_version_conflict');
    if(b.action==='consent'){if(!a.pc||a.row.owner_id!==user.id)return await fail(403,'occult_consent_owner_required');if(!uuid(b.offerId))return await fail(400,'occult_consent_not_offered');const offered=(await db.query("SELECT id,payload FROM campaign_live_events WHERE id=$4 AND campaign_id=$1 AND kind='occult-consent-offer' AND payload->>'sourceEventId'=$2 AND payload->'targets' @> $3::jsonb",[campaign,e.id,JSON.stringify([{actorId:a.row.id}]),b.offerId])).rows[0];if(!offered)return await fail(400,'occult_consent_not_offered');await liveEvent(db,campaign,user,b,'occult-consent',{sourceEventId:e.id,actorId:a.row.id,offerId:offered.id,note:offered.payload.note,label:'Effet allié accepté · '+e.payload.label});await db.query('COMMIT');return {ok:true};}
    if(b.action==='resist-decree'){
     if(b.edge&&!a.pc)return await fail(400,'edge_players_only');
     const effect=effects(a).find((f:any)=>f.id===b.effectId&&f.ruleId===occultPowerIds.decree&&f.sourceId===e.character_id);if(!effect||b.violationConfirmed!==true)return await fail(400,'occult_decree_not_applicable');
     const resolved=(await db.query("SELECT payload FROM campaign_live_events WHERE campaign_id=$1 AND kind IN ('occult-resolve','occult-cancel') AND payload->>'sourceEventId'=$2",[campaign,e.id])).rows[0]?.payload,opposition=resolved?.counterDifficulty;if(!Number.isFinite(opposition))return await fail(400,'occult_counter_unavailable');
     const profile=a.pc?playProfile(a.row.data,a.state):null,defenses=await combatTarget(db,campaign,a.row.id);if(!defenses||defenses.hp<=0||a.state.unconscious)return await fail(400,'actor_unavailable');if(b.edge){const error=await spendEdge(db,a.row.id,a.row.data,b.requestId,'force');if(error)return await fail(400,error);}const skill=profile?.skills.find((s:any)=>s.id==='force_mentale'),modifier=defenses.activeOccultDefense,die=b.edge?forcedDie():rollD10(defenses.stress,()=>randomInt(1,11)),total=modifier+die.sum,success=!die.narrativeFailure&&total>=opposition;if(success)setEffects(a,effects(a).filter((f:any)=>f.id!==effect.id));if(a.pc){consumeNatureTest(a.row.data,a.state,'force_mentale');consumeRegisteredTest(a.row.data,a.state,'force_mentale');}await save(db,a);await liveEvent(db,campaign,user,b,'occult-resist-decree',{label:'Résister au Décret · '+a.row.name,sourceEventId:e.id,actorId:a.row.id,effectId:effect.id,...die,modifier,total,success,opposition,paSpent:0,resultVersion:a.version+1,round:shared.active?shared.round:a.state.round,combatActive:shared.active,components:skill?{attribute:skill.attributeValue,rank:skill.rank,bonus:skill.bonus,skillName:skill.name}:{defense:modifier}});await db.query('COMMIT');return {ok:true,total,success};
    }
    if(([occultPowerIds.injunction,occultPowerIds.decree,occultPowerIds.sovereignty,occultPowerIds.phantasm] as string[]).includes(e.payload.powerId??e.request_payload?.powerId??'')&&b.defenseKind!=='occult')return await fail(400,'occult_defense_required');
    if(!['physical','occult'].includes(b.defenseKind)||typeof b.active!=='boolean'||b.contextConfirmed!==true)return await fail(400,'occult_defense_required');
    if(b.edge&&(!a.pc||!b.active))return await fail(400,'edge_players_only');
    if((await db.query("SELECT id FROM campaign_live_events WHERE campaign_id=$1 AND kind='occult-defend' AND payload->>'sourceEventId'=$2 AND payload->>'actorId'=$3",[campaign,e.id,a.row.id])).rowCount)return await fail(409,'occult_defense_already_chosen');
    const p=a.pc?playProfile(a.row.data,a.state):null,defenses=await combatTarget(db,campaign,a.row.id);if(!defenses)return await fail(404,'actor_not_found');let total=b.defenseKind==='physical'?defenses.defense:defenses.occultDefense,die:any=null,modifier=total,components:any=null,cost=0;
    if(b.active){if(defenses.hp<=0||a.state.unconscious||shared.active&&(!participates(shared,a.row.id)||defenses.initiative===null||defenses.pa<1))return await fail(400,'insufficient_pa');const skillId=b.defenseKind==='physical'?'esquive':'force_mentale',skill=p?.skills.find((s:any)=>s.id===skillId);if(shared.active&&b.defenseKind==='physical'){const physical=canSpendPhysicalPA(effects(a),a.row.id,{...a.state,round:shared.round},1);if(!physical.available)return await fail(400,'physical_pa_limit');a.state.physicalPaSpent=physical.nextSpent;}if(shared.active){if(!a.pc)a.state.pa=a.row.pa;frenzyActionCheck(a.state,1,b,{manager:mj});spendRestrictedPA(a.state,1,b.defenseKind==='physical'?'physical-defense':'occult');recordFrenzyAction(a.state,1,b,{manager:mj});if(!a.pc)a.row.pa=a.state.pa;cost=1;}if(b.edge){const error=await spendEdge(db,a.row.id,a.row.data,b.requestId,'force');if(error)return await fail(400,error);}die=b.edge?forcedDie():rollD10(defenses.stress,()=>randomInt(1,11));modifier=b.defenseKind==='physical'?defenses.activeDefense:defenses.activeOccultDefense;total=die.narrativeFailure?0:modifier+die.sum;components=skill?{attribute:skill.attributeValue,rank:skill.rank,bonus:skill.bonus,skillName:skill.name}:{defense:modifier};if(a.pc){consumeNatureTest(a.row.data,a.state,skillId);consumeRegisteredTest(a.row.data,a.state,skillId);}await save(db,a);}
    await liveEvent(db,campaign,user,b,'occult-defend',{label:'Défense '+(b.defenseKind==='physical'?'physique':'occulte')+' · '+a.row.name,sourceEventId:e.id,actorId:a.row.id,defenseKind:b.defenseKind,active:b.active,modifier,total,components,...(die??{}),paSpent:cost,resultVersion:a.version+(b.active?1:0),round:shared.active?shared.round:a.state.round,combatActive:shared.active});if(cost)await maybeAdvanceCombat(db,campaign,user.id);await db.query('COMMIT');return {ok:true,total};
   }
   if(!mj)return await fail(403,'occult_resolution_mj_only');if(b.confirmed!==true||!text(b.ruling)||!Array.isArray(b.targets)||!b.targets.length||b.targets.length>12||new Set(b.targets.map((t:any)=>t.actorId)).size!==b.targets.length)return await fail(400,'occult_ruling_required');
   const s=await actor(db,campaign,e.character_id);if(!s?.pc)return await fail(404,'actor_not_found');const powerId=e.payload.powerId??e.request_payload?.powerId??'',spell=e.payload.spell??null,canonical=(Object.values(occultPowerIds) as string[]).includes(powerId);
   if(canonical&&b.targets.some((t:any)=>t.function!=='condition'||t.hostile&&t.defenseKind!=='occult'))return await fail(400,'occult_canonical_condition_required');
   if(powerId===occultPowerIds.sovereignty&&b.targets.some((t:any)=>!Number.isFinite(t.distance)||t.distance<0||t.distance>15||t.contextConfirmed!==true))return await fail(400,'occult_sovereignty_range');
   if(canonical&&powerId!==occultPowerIds.sovereignty&&b.targets.length!==1)return await fail(400,'occult_target_count');if(b.maintained===true&&!spell)return await fail(400,'occult_maintained_spell_required');if(b.maintained===true&&(s.state.unconscious||playProfile(s.row.data,s.state).hp<=0||s.state.revelation==='v'||normalizedNatureResources(s.state.natureResources).mage.dormant))return await fail(400,'occult_maintenance_unavailable');
   let total=e.payload.total,sourceRoll=e.payload;
   if(!Number.isFinite(total)&&e.payload.spell?.automatic!==true){if(!uuid(b.rollEventId))return await fail(400,'occult_roll_required');const roll=(await db.query("SELECT * FROM character_play_events WHERE id=$1 AND character_id=$2 AND campaign_id=$3 AND kind='roll' AND request_payload->>'skill'=$4 AND created_at>=$5 AND live_session_id IS NOT DISTINCT FROM (SELECT session_id FROM campaign_live_context WHERE campaign_id=$3)",[b.rollEventId,s.row.id,campaign,occultRollSkill(powerId),e.created_at])).rows[0];if(!roll||roll.payload.narrativeFailure)return await fail(400,'occult_roll_required');if((await db.query("SELECT id FROM campaign_live_events WHERE campaign_id=$1 AND kind='occult-resolve' AND payload->>'rollEventId'=$2",[campaign,roll.id])).rowCount)return await fail(409,'occult_roll_already_resolved');total=roll.payload.total;sourceRoll=roll.payload;}
   const outcome:any[]=[];let sourceChanged=false;
   for(const t of b.targets){
    if(!uuid(t.actorId)||!integer(t.version,0,100000)||!['damage','healing','effects','condition'].includes(t.function)||typeof t.hostile!=='boolean')return await fail(400,'invalid_occult_target');const a:any=t.actorId===s.row.id?s:await actor(db,campaign,t.actorId);if(!a)return await fail(404,'actor_not_found');if(a.version!==t.version)return await fail(409,'occult_version_conflict');
    if(!t.hostile&&a.pc&&a.row.id!==s.row.id&&!(await db.query("SELECT id FROM campaign_live_events WHERE campaign_id=$1 AND kind='occult-consent' AND payload->>'sourceEventId'=$2 AND payload->>'actorId'=$3 AND created_by=$4 AND payload->>'note'=$5",[campaign,e.id,a.row.id,a.row.owner_id,b.ruling])).rowCount)return await fail(403,'occult_target_consent_required');
    if(spell?.automatic&&t.hostile)return await fail(400,'occult_automatic_cannot_oppose');
    const p=a.pc?playProfile(a.row.data,a.state):null,before=p?.hp??a.row.hp,death=p?.derived.death??a.row.death,maximum=p?liveHealingMaximum(a.row.data,a.state,p.derived.pvMax):a.row.pv_max;
    let defense=0;if(t.hostile){if(!['physical','occult'].includes(t.defenseKind)||t.defenseConfirmed!==true)return await fail(400,'occult_defense_required');const chosen=(await db.query("SELECT payload FROM campaign_live_events WHERE campaign_id=$1 AND kind='occult-defend' AND payload->>'sourceEventId'=$2 AND payload->>'actorId'=$3",[campaign,e.id,a.row.id])).rows[0]?.payload;if(chosen&&chosen.defenseKind!==t.defenseKind)return await fail(409,'occult_defense_conflict');const defenses=await combatTarget(db,campaign,a.row.id);if(!defenses)return await fail(404,'actor_not_found');defense=chosen?.total??(t.defenseKind==='physical'?defenses.defense:defenses.occultDefense);}
    const hit=!t.hostile||Number(total)>defense,summary:any={actorId:a.row.id,name:a.row.name,function:t.function,hostile:t.hostile,defense,hit,effectIds:[],before,after:before};
    if(hit){
     if(t.function==='damage'){
      if(!integer(t.protection,0,1000)||t.protection>0&&(!text(t.protectionNote,300)||t.protectionConfirmed!==true))return await fail(400,'occult_protection_required');if(!spell||!integer(spell.damage,0,100))return await fail(400,'occult_damage_requires_spell');const d=occultDamage(Number(total),t.hostile?defense:spell.difficulty,spell.damage,t.protection);summary.calculation=d;const after=Math.max(death,before-d.damage);if(a.pc){a.state.hp=after;a.state.stabilized=false;if(a.row.data.truth?.nature==='vampire'){const sleep=applyVampireLastSleep(a.row.data,{...a.state,hp:before},after,death,t.bodySurvivable!==false);if(!('error'in sleep)){a.state=sleep.state;summary.lastSleep=sleep.payload;}}}else{a.row.hp=after;if(after<=0)a.row.pa=Math.min(a.row.pa,1);}
     }else if(t.function==='healing'){
      if(t.hostile||canonical||!integer(t.amount,1,1000)||t.healingConfirmed!==true||before<=death||a.state.lightningWounds?.final)return await fail(400,'occult_healing_unavailable');if(!spell&&t.amount>100)return await fail(400,'invalid_occult_healing');if(a.pc){a.state.hp=Math.min(maximum,before+t.amount);summary.recoveredLightningWounds=recoverLightningWounds(a.state,before,a.state.hp);if(a.state.hp>0)a.state.stabilized=false;}else{a.row.hp=Math.min(maximum,before+t.amount);summary.recoveredLightningWounds=recoverLightningWounds(a.state,before,a.row.hp);}
     }else{
      const drafts=t.function==='condition'?[occultCondition(powerId,b.ruling.slice(0,500),s.row.id,a.row.id,t.duration)]:occultEffectDrafts(t.effects,{sourceId:s.row.id,targetId:a.row.id,ruleId:spell?'spell:'+spell.affinity:powerId||'table-ruling',maintained:b.maintained===true});if(canonical&&t.function!=='condition'||drafts.some(d=>!d))return await fail(400,'occult_canonical_condition_required');let next=effects(a);for(const draft of drafts){const effect=createLiveEffect(draft!,{id:randomUUID(),round:shared.active?shared.round:a.state.round??1,targetActivation:a.state.activation??0});next=addLiveEffect(next,effect);summary.effectIds.push(effect.id);}setEffects(a,next);
     }
     summary.after=a.pc?playProfile(a.row.data,a.state).hp:a.row.hp;if(a.pc&&t.function==='damage')summary.survivalFury=recordSurvivalFuryDamage(a.row.data,a.state,{beforeHp:before,afterHp:summary.after,maximum:p!.healthMaximum,realDamage:true});if(a===s)sourceChanged=true;else await save(db,a);
    }
    outcome.push(summary);
   }
   const maintained=b.maintained===true&&outcome.some(t=>t.effectIds.length);if(b.maintained===true&&outcome.some(t=>t.hit&&t.function!=='effects'))return await fail(400,'occult_maintained_effect_required');if(maintained){const r=normalizedNatureResources(s.state.natureResources);if(r.mage.maintained.length>=30)return await fail(400,'occult_maintenance_limit');r.mage.maintained.push(b.requestId);s.state.natureResources=r;sourceChanged=true;}if(sourceChanged)await save(db,s);
   const payload={label:'Résolution occulte · '+(e.payload.label??e.kind),sourceEventId:e.id,sourceId:s.row.id,sourceKind:e.kind,sourceRequestVersion:e.request_payload?.version,rollEventId:b.rollEventId??null,sourceRoll:{total,dice:sourceRoll.dice,sum:sourceRoll.sum,edgeForced:sourceRoll.edgeForced===true,narrativeFailure:sourceRoll.narrativeFailure,modifier:sourceRoll.modifier,components:sourceRoll.components},counterDifficulty:Number.isFinite(total)?total:null,spell,powerId,canonicalText:e.payload.canonicalText??null,ruling:b.ruling,arbitrated:true,maintained,createdRound:shared.active?shared.round:s.state.round,targets:outcome};
   await liveEvent(db,campaign,user,b,'occult-resolve',payload);for(const t of outcome){const target=(await db.query('SELECT id FROM characters WHERE id=$1',[t.actorId])).rows[0];if(target)await db.query('INSERT INTO character_play_events(id,character_id,campaign_id,created_by,kind,payload,request_payload) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb)',[randomUUID(),t.actorId,campaign,user.id,t.function==='damage'?'damage':'occult-effect',JSON.stringify({label:payload.label,sourceEventId:e.id,resolutionId:b.requestId,...t}),JSON.stringify({action:'occult-effect',resolutionId:b.requestId})]);}
   await maybeAdvanceCombat(db,campaign,user.id);await db.query('COMMIT');return {ok:true,resolutionId:b.requestId,targets:outcome};
  }catch(e){await db.query('ROLLBACK').catch(()=>{});if((e as Error).message.startsWith('frenzy_')||(e as Error).message.startsWith('occult_')||['physical_pa_reserved','insufficient_pa','between_states_action_forbidden','invalid_occult_effect','invalid_occult_damage','effect_does_not_stack','effect_stacking_conflict','invalid_effect'].includes((e as Error).message))return reply.code(400).send({error:(e as Error).message});throw e;}finally{db.release();}
 });
}
