import { applyNamedPnjStatProfile, type StatProfile } from "./compendium-pnj-corporate-stats.js";

type Article={id:string;dataset?:string;sections?:Array<Record<string,any>>;[key:string]:any};
type Entry=StatProfile & {id:string};

const PROFILES:Entry[]=[
  {"id":"personnages-verite-extrals-groupes-kirstyn-kjoll","tier":"elite","shape":"esprit","skills":["Commerce","Investigation","Autorité","Diplomatie"],"anchor":"Administratrice de Space Union, présentée publiquement comme la sœur d'Alladava Kjoll.","talents":["Dossier préparé — Space Union","Réseau mobilisable — administration"],"truth":"La parenté présentée ne suffit pas à fixer sa nature réelle."},
  {"id":"personnages-verite-extrals-groupes-rikardo-schenaz","tier":"heroique","shape":"esprit","skills":["Commerce","Savoirs","Autorité","Diplomatie"],"anchor":"Ancien fondateur et président d'Apexi, destitué puis professeur à Caltech, mêle ambition corporative et aide aux institutions.","talents":["Expertise éprouvée — Commerce","Réseau mobilisable — Caltech"],"truth":"N'a plus l'autorité légale de la corporation perdue."},
  {"id":"personnages-verite-extrals-groupes-jaymor-milgan","tier":"haute","shape":"social","skills":["Commerce","Autorité","Investigation","Séduction"],"anchor":"Dirige Makerking chez Yellowfood, allié de la branche Fastfood et étouffe financièrement les contestations.","talents":["Réseau mobilisable — Yellowfood","Dossier préparé — réputation"],"truth":"Sa Vérité est à traiter séparément."},
  {"id":"personnages-verite-extrals-groupes-gong-min-ju","tier":"heroique","shape":"terrain","skills":["Pilotage","Autorité","Tir","Survie"],"anchor":"Ancien pilote d'élite devenu général de division de l'insurrection nord-coréenne, recherche les combats par ego.","talents":["Chef de manœuvre — division","Terrain reconnu — aviation"],"truth":"Aucun surnaturel déduit de son sadisme."},
  {"id":"personnages-verite-extrals-groupes-katasha-barkirov","tier":"haute","shape":"esprit","skills":["Langages & Argot","Investigation","Furtivité","Autorité"],"anchor":"Russe favorable à l'occupant norco et introduite aux États-Unis sous une réputation trompeuse, parle couramment anglais.","talents":["Expertise éprouvée — Langages & Argot","Dossier préparé — couverture"],"truth":"Son passé de collaboratrice est privé tant qu'il n'est pas connu des interlocuteurs."},
  {"id":"personnages-verite-extrals-groupes-mazeeda-el-sadheen","tier":"haute","shape":"social","skills":["Représentation","Diplomatie","Survie","Commerce"],"anchor":"Insurgée anti-Wellspring du Moyen-Orient, plaide sa cause en Californie et achète du matériel hors corporations.","talents":["Réseau mobilisable — insurgés","Expertise éprouvée — Diplomatie"],"truth":"Ses contacts norcos ne sont pas une affiliation idéologique automatique."},
  {"id":"personnages-verite-extrals-groupes-sharmon-leonard","tier":"haute","shape":"terrain","skills":["Tir","Survie","Autorité","Perception"],"anchor":"Marine puis soldat Ushkoll pendant la guerre, loyal et franc malgré les sanctions de ses supérieurs.","talents":["Terrain reconnu — opérations","Chef de manœuvre — section"],"truth":"Son calme ne donne pas de résistance surnaturelle."},
  {"id":"personnages-verite-extrals-groupes-cool-blake-morrisson","tier":"elite","shape":"social","skills":["Représentation","Autorité","Commerce","Tir"],"anchor":"Neopunk autoproclamé Gigaking, mêle spectacle ostentatoire, intimidation des fans et dépenses de luxe.","talents":["Réseau mobilisable — entourage","Expertise éprouvée — Représentation"],"truth":"Son entourage n'est pas une ressource garantie hors scène."},
  {"id":"personnages-verite-extrals-groupes-wei-lin","tier":"haute","shape":"social","skills":["Commerce","Autorité","Investigation","Diplomatie"],"anchor":"Chargé des affaires extérieures de la Triade des Vingt-deux Dragons, rescapé de l'enrôlement de guerre.","talents":["Réseau mobilisable — Triade","Dossier préparé — négociation"],"truth":"Le titre exact de septième Dragon et l'identité du vingt-deuxième sont dans le dossier selon leur publicité."},
  {"id":"personnages-verite-extrals-groupes-alante-dennis","tier":"haute","shape":"terrain","skills":["Furtivité","Séduction","Commerce","Survie"],"anchor":"Jeune Sud-Africaine ayant exercé prostitution et assassinats, mobile et réputée fiable par certaines corporations.","talents":["Terrain reconnu — opérations mobiles","Expertise éprouvée — Furtivité"],"truth":"Sa richesse apparente n'est pas un équipement de combat inventorié."},
  {"id":"personnages-verite-extrals-groupes-ogum-so-yung","tier":"haute","shape":"terrain","skills":["Tir","Survie","Autorité","Athlétisme"],"anchor":"Ancienne sportive sud-coréenne devenue résistante, a obtenu des exosquelettes pour un groupe en 2023 et travaille avec des vétérans.","talents":["Chef de manœuvre — vétérans","Terrain reconnu — guérilla"],"truth":"Les exosquelettes ne sont disponibles qu'avec leur équipement effectif."},
  {"id":"personnages-verite-extrals-groupes-ernesto-hidalgo","tier":"elite","shape":"social","skills":["Séduction","Commerce","Pugilat","Perception"],"anchor":"Membre arrogant du cartel de Sinaloa, intimidant et connu pour ses avances menaçantes, sans expertise militaire attestée.","talents":["Expertise éprouvée — Séduction","Réseau mobilisable — cartel"],"truth":"Aucun réseau supérieur à son rang de simple membre."},
  {"id":"personnages-verite-extrals-groupes-noya-kagami","tier":"heroique","shape":"terrain","skills":["Mêlée","Investigation","Perception","Esquive"],"anchor":"Une des sept Lames de Fuyumi, combattante imprévisible mais surtout psychologue et profiler de sa cheffe.","talents":["Désarmement net — Mêlée","Lecture des failles — profilage"],"truth":"Ses talents de profiler sont civils, sa Vérité reste MJ."},
  {"id":"personnages-verite-extrals-groupes-axelle-monroy","tier":"haute","shape":"esprit","skills":["Soin","Commerce","Investigation","Savoirs"],"anchor":"Ancienne fondatrice de Monroy Pharma, travaille chez Sunways après conflit au PCRC et la mort de ses enfants à Tbilissi.","talents":["Dossier préparé — pharmacie","Expertise éprouvée — Soin"],"truth":"Son siège du SMRC et Nea'Aeri relèvent du MJ ; nettoyer le fragment public d'import."},
  {"id":"personnages-verite-extrals-groupes-mustafa-dzeko","tier":"haute","shape":"terrain","skills":["Investigation","Tir","Survie","Autorité"],"anchor":"Ancien policier bosnien émigré aux États-Unis, célèbre pour avoir secouru des enfants dans un incendie malgré un passé meurtrier.","talents":["Dossier préparé — enquête","Terrain reconnu — secours"],"truth":"Les cadavres de son passé ne deviennent pas des exploits policiers."},
  {"id":"personnages-verite-extrals-groupes-coral-hope","tier":"haute","shape":"terrain","skills":["Furtivité","Tir","Survie","Autorité"],"anchor":"Insurgée recherchée sur la côte Ouest et alliée de Larry Sundown, privilégie l'action clandestine.","talents":["Terrain reconnu — clandestinité","Chef de manœuvre — cellule"],"truth":"Son niveau réel dans la Vérité reste MJ."},
  {"id":"personnages-verite-extrals-groupes-sheylinn-williams","tier":"heroique","shape":"social","skills":["Autorité","Savoirs","Diplomatie","Pilotage"],"anchor":"Amirale des gardes-côtes américains opposée à l'indépendance californienne qui menacerait sa carrière.","talents":["Chef de manœuvre — garde-côtes","Réseau mobilisable — marine"],"truth":"N'a pas le commandement californien que Dina Page réclame."},
  {"id":"personnages-verite-extrals-groupes-piripi-stuart-hariwana","tier":"heroique","shape":"terrain","skills":["Autorité","Pilotage","Survie","Tir"],"anchor":"Ex-général néo-zélandais vétéran, dirige la communauté maritime indépendante du Mola Mola.","talents":["Chef de manœuvre — flotte","Terrain reconnu — mer"],"truth":"Les armes et navires dépendent des ressources présentes."},
  {"id":"personnages-verite-extrals-groupes-elsa-rys","tier":"haute","shape":"terrain","skills":["Tir","Furtivité","Survie","Perception"],"anchor":"Vétérane des forces spéciales sud-africaines, missions non publiées, tente de reconstruire sa vie en Californie.","talents":["Terrain reconnu — opérations discrètes","Expertise éprouvée — Tir"],"truth":"Pas d'exploits spécifiques inventés pour ses missions classifiées."},
  {"id":"personnages-verite-extrals-groupes-monorra-smith","tier":"entraine","shape":"social","skills":["Soin","Séduction","Perception","Commerce"],"anchor":"Sud-Africaine exerçant l'acupuncture et la domination BDSM ; aucun combat ou réseau important n'est documenté.","talents":["Expertise éprouvée — Soin"],"truth":"Arbitrage : dossier civil bref ; confirmer sa formation médicale éventuelle."},
  {"id":"personnages-verite-extrals-groupes-lisa-koenig","tier":"heroique","shape":"esprit","skills":["Neurodive","Mêlée","Investigation","Esquive"],"anchor":"Crawler Neurodiver surcharge les systèmes et gère plusieurs IA, combat aussi efficacement au corps à corps.","talents":["Expertise éprouvée — Neurodive","Désarmement net — Mêlée"],"truth":"Ses IA doivent exister dans la scène pour apporter un appui."},
  {"id":"pnj-temples-daemoniaques-branwen-crowford","tier":"haute","shape":"terrain","skills":["Tir","Autorité","Survie","Investigation"],"anchor":"Ex-sportive, officière mercenaire Black Crow puis Ushkoll, consultante ponctuelle de Raven.","talents":["Chef de manœuvre — escouade","Terrain reconnu — opérations"],"truth":"Son histoire démoniaque est séparée de la carrière civile."},
  {"id":"pnj-temples-daemoniaques-hugue-reynarsson","tier":"haute","shape":"terrain","skills":["Pugilat","Survie","Tir","Autorité"],"anchor":"Colosse norvégien devenu soldat huit ans puis mercenaire Black Crow lié à Liam Siridean.","talents":["Lutte brève — Pugilat","Terrain reconnu — missions"],"truth":"Taille visible ne signifie pas nature démoniaque publique."},
  {"id":"pnj-temples-daemoniaques-ishaa-el-jabara","tier":"elite","shape":"social","skills":["Représentation","Diplomatie","Commerce","Perception"],"anchor":"Actrice californienne née au Maroc, carrière moyenne dans l'ombre de Siobhain et rivalité persistante.","talents":["Expertise éprouvée — Représentation","Réseau mobilisable — production"],"truth":"Sa jalousie n'est pas une compétence de combat."},
  {"id":"pnj-temples-daemoniaques-bethany-griffith","tier":"haute","shape":"esprit","skills":["Investigation","Perception","Tir","Savoirs"],"anchor":"Enquêtrice anglaise naturalisée californienne, méthodes anciennes et convictions néopaïennes affichées.","talents":["Dossier préparé — enquête","Lecture des failles — indices"],"truth":"Ses croyances ne prouvent aucune magie civile."},
  {"id":"pnj-temples-daemoniaques-ciaran-lainn","tier":"haute","shape":"terrain","skills":["Mêlée","Tir","Survie","Autorité"],"anchor":"Soldat américain d'origine galloise, habitué des fronts et du corps à corps malgré les sanctions disciplinaires.","talents":["Désarmement net — Mêlée","Terrain reconnu — guerre"],"truth":"Ses sanctions restent une limite de commandement."},
  {"id":"pnj-temples-daemoniaques-demona-prince","tier":"haute","shape":"esprit","skills":["Savoirs","Investigation","Diplomatie","Commerce"],"anchor":"Avocate de First Lawyers souvent sous-estimée, gère des affaires sensibles de Belyandra Queen.","talents":["Dossier préparé — dossiers Belyandra","Expertise éprouvée — Savoirs"],"truth":"La proximité de Belyandra ne confère aucune protection d'Hologramme automatiquement."},
  {"id":"pnj-temples-daemoniaques-jane-de-march","tier":"elite","shape":"social","skills":["Commerce","Investigation","Diplomatie","Perception"],"anchor":"Fixer chargée du service après-vente et de la logistique des cabinets d'avocats corporatifs.","talents":["Dossier préparé — mandat","Expertise éprouvée — Commerce"],"truth":"Ses clients corporatifs ne sont pas ses subordonnés."},
  {"id":"pnj-temples-daemoniaques-luciano-dominelli","tier":"haute","shape":"social","skills":["Autorité","Commerce","Diplomatie","Investigation"],"anchor":"Capo italien calme et redouté dont le sang-froid déstabilise même les parrains.","talents":["Réseau mobilisable — Famille","Dossier préparé — rival"],"truth":"Sa nature de Vérité reste MJ."},
  {"id":"pnj-temples-daemoniaques-aessa-lee-love","tier":"haute","shape":"social","skills":["Commerce","Séduction","Autorité","Investigation"],"anchor":"Crawler Hooker de 26 ans et gérante du Purple Embers, nightclub à forte influence locale.","talents":["Réseau mobilisable — Purple Embers","Dossier préparé — clientèle"],"truth":"Ses talents de Vérité ne sont pas chiffrés par le succès du bar."},
  {"id":"pnj-temples-daemoniaques-syfia-gyllenhaal","tier":"haute","shape":"social","skills":["Représentation","Séduction","Diplomatie","Commerce"],"anchor":"Actrice et présentatrice Tuatha à forte popularité, persona publique froide et assurée.","talents":["Expertise éprouvée — Représentation","Réseau mobilisable — médias"],"truth":"Image de femme épanouie ne prouve pas sa situation privée."},
  {"id":"pnj-temples-daemoniaques-leonetta-cross","tier":"elite","shape":"social","skills":["Commerce","Perception","Diplomatie","Survie"],"anchor":"Tient seule un petit diner d'un quartier délaissé, accueille gangs et Crawlers.","talents":["Expertise éprouvée — Commerce","Terrain reconnu — quartier"],"truth":"Son contact avec les gangs ne fait pas d'elle une combattante."},
  {"id":"pnj-temples-daemoniaques-scott-mcfadden","tier":"elite","shape":"social","skills":["Séduction","Commerce","Investigation","Diplomatie"],"anchor":"Prostitué et Fixer occasionnel, gagne péniblement de la confiance chez les Yakuzas après rejet de la mafia irlandaise.","talents":["Dossier préparé — missions","Expertise éprouvée — Séduction"],"truth":"Ressources yakuza contestées, aucun renfort automatique."},
  {"id":"pnj-temples-daemoniaques-virginia-echis","tier":"elite","shape":"esprit","skills":["Investigation","Survie","Perception","Savoirs"],"anchor":"Agente de terrain NRMD chargée d'enquêtes littorales et maritimes.","talents":["Dossier préparé — côte","Terrain reconnu — littoral"],"truth":"Nature réelle réservée au MJ."},
  {"id":"pnj-temples-daemoniaques-sergei-makarovich","tier":"haute","shape":"social","skills":["Autorité","Commerce","Investigation","Diplomatie"],"anchor":"Vétéran des mafias moscovites récemment muté à Los Angeles, peine à s'adapter aux plus jeunes.","talents":["Réseau mobilisable — Bratva","Dossier préparé — anciennes méthodes"],"truth":"Son ancienneté n'implique pas que les cadres de Vladivostok lui obéissent."},
  {"id":"pnj-temples-daemoniaques-cheng-guanlong","tier":"elite","shape":"terrain","skills":["Tir","Survie","Mêlée","Perception"],"anchor":"Mercenaire Crawler chinois, ancien subordonné de Wei, pénalisé par un Logifate désastreux.","talents":["Terrain reconnu — missions","Expertise éprouvée — Tir"],"truth":"Mauvais Logifate limite les contrats, ne renforce pas le combat."},
  {"id":"pnj-temples-daemoniaques-mercedes-garcia","tier":"elite","shape":"social","skills":["Commerce","Diplomatie","Investigation","Perception"],"anchor":"Cadre d'Ocean Master appréciant le luxe ; aucune formation guerrière n'est mentionnée.","talents":["Expertise éprouvée — Commerce","Dossier préparé — activité"],"truth":"Fonction corporative seule ne confirme pas autorité sur une division entière."},
  {"id":"pnj-temples-daemoniaques-zedarius-harmon","tier":"haute","shape":"terrain","skills":["Autorité","Tir","Survie","Investigation"],"anchor":"Dirige un petit gang Crawler employé par les mafias pour leurs opérations compromettantes.","talents":["Chef de manœuvre — gang","Terrain reconnu — quartiers"],"truth":"Son réseau limité ne vaut pas celui de ses donneurs d'ordre."},
  {"id":"pnj-temples-daemoniaques-addison-andrews","tier":"haute","shape":"social","skills":["Commerce","Investigation","Autorité","Diplomatie"],"anchor":"Fixer influente auprès des mafias russes et irlandaises et de corporations, veut concurrencer les grands Fixers.","talents":["Dossier préparé — clients","Réseau mobilisable — fixer"],"truth":"Ambition de supplanter la Blanchisserie n'est pas réalisée."},
  {"id":"pnj-temples-daemoniaques-yalonda-reese","tier":"elite","shape":"social","skills":["Représentation","Diplomatie","Commerce","Perception"],"anchor":"Artiste Omegacoustic populaire sur des thèmes plus sombres que ses collègues.","talents":["Expertise éprouvée — Représentation","Réseau mobilisable — scène"],"truth":"Style sombre n'atteste aucun rituel occulte public."},
  {"id":"pnj-temples-daemoniaques-aseela-al-hamidi","tier":"heroique","shape":"esprit","skills":["Investigation","Commerce","Autorité","Furtivité"],"anchor":"Orpheline irakienne adoptée par une soldate américaine, Fixer majeure de la Blanchisserie aspirant au rang Whiteman.","talents":["Dossier préparé — opérations","Réseau mobilisable — Blanchisserie"],"truth":"Whiteman reste une ambition, ne pas lui accorder ce titre."},
  {"id":"pnj-temples-daemoniaques-tristan-barenton","tier":"entraine","shape":"terrain","skills":["Pugilat","Constitution","Perception","Survie"],"anchor":"Membre mineur du Milieu, sa grande carrure impressionne davantage que son poste réel.","talents":["Lutte brève — Pugilat"],"truth":"Ne pas attribuer le pouvoir du Milieu sur sa seule apparence."},
  {"id":"pnj-temples-daemoniaques-nazeem-alallih","tier":"elite","shape":"social","skills":["Séduction","Investigation","Diplomatie","Savoirs"],"anchor":"Crawler Hooker prostitué et informateur, également imam ouvert sur les réformes de l'Islam.","talents":["Dossier préparé — renseignements","Expertise éprouvée — Séduction"],"truth":"Son statut religieux et son mode de vie sont publics ; pouvoirs cachés réservés au MJ."},
  {"id":"pnj-temples-daemoniaques-amber-murphy","tier":"haute","shape":"esprit","skills":["Représentation","Autorité","Commerce","Investigation"],"anchor":"Dirige la création de Tuatha et répond directement à Siobhain, sans compétence de combat attestée.","talents":["Réseau mobilisable — Tuatha","Chef de manœuvre — studio"],"truth":"Proximité de Siobhain ne donne pas sa puissance de Vérité."},
  {"id":"pnj-temples-daemoniaques-nick-edison","tier":"heroique","shape":"esprit","skills":["Mécanique","Neurodive","Investigation","Savoirs"],"anchor":"Jeune Neurotech Crawler génial, combine bricolage, intrusion et recomposition des technologies corporatives.","talents":["Expertise éprouvée — Mécanique","Dossier préparé — sécurité"],"truth":"Ses réalisations demandent l'inventaire d'outils, aucun gadget gratuit."},
  {"id":"pnj-temples-daemoniaques-magda-galanou","tier":"heroique","shape":"esprit","skills":["Savoirs","Neurodive","Investigation","Mécanique"],"anchor":"Enseignante-chercheuse Caltech parmi les grandes mathématiciennes de 2035, travaille sur calculateurs et IA.","talents":["Expertise éprouvée — Savoirs","Dossier préparé — calculs"],"truth":"Réputation scientifique ne signifie pas aptitude martiale."},
  {"id":"pnj-temples-daemoniaques-ludovic-yersin","tier":"haute","shape":"esprit","skills":["Soin","Savoirs","Investigation","Diplomatie"],"anchor":"Médecin reconnu d'une clinique privée, soutenu par sa directrice et opposant à une insurgée biologique.","talents":["Expertise éprouvée — Soin","Dossier préparé — contagion"],"truth":"Morax et la nature de la directrice de la clinique sont des informations de Vérité privées."},
  {"id":"pnj-temples-daemoniaques-sam-george-clarkson","tier":"haute","shape":"esprit","skills":["Investigation","Perception","Tir","Furtivité"],"anchor":"Détective Voidwatcher de crimes irrésolus, pousse ses enquêtes jusqu'à la mort du responsable.","talents":["Dossier préparé — affaire","Lecture des failles — enquête"],"truth":"Son surnom ne justifie pas de talents surnaturels."},
  {"id":"pnj-temples-daemoniaques-karlyn-chamunda","tier":"heroique","shape":"terrain","skills":["Furtivité","Tir","Mêlée","Perception"],"anchor":"Assassine Voidrunner majeure de la Blanchisserie, soupçonnée sans preuve d'un massacre de tunnel.","talents":["Expertise éprouvée — Furtivité","Terrain reconnu — extraction"],"truth":"Le massacre demeure soupçonné, pas un exploit confirmé."},
  {"id":"pnj-temples-daemoniaques-shin-arata","tier":"heroique","shape":"terrain","skills":["Mêlée","Pugilat","Esquive","Survie"],"anchor":"Maître reconnu de karaté, judo, kendo, wushu et taekwondo, ancien soldat devenu restaurateur.","talents":["Désarmement net — Mêlée","Lutte brève — Pugilat"],"truth":"Ses distinctions martiales réelles justifient un haut niveau sans pouvoir occulte."},
];

export function applyPnjStatBatch08(byId:Map<string,Article>):void {
  if(PROFILES.length!==50||new Set(PROFILES.map(p=>p.id)).size!==50)throw new Error("PNJ · lot 08 incomplet ou dupliqué");
  for(const profile of PROFILES){
    const article=byId.get(profile.id);
    if(!article)throw new Error(`PNJ · fiche active introuvable : ${profile.id}`);
    repairPublicLeaks(article);
    applyNamedPnjStatProfile(article,profile);
  }
}

function repairPublicLeaks(article:Article):void {
  const corrections:Record<string,[string,string,string]>={
    "personnages-verite-extrals-groupes-axelle-monroy":["informations-realite","ième siège du SMRC ",""],
    "pnj-temples-daemoniaques-ludovic-yersin":["temples-daemoniaques-realite"," malgré le fait qu’il ne soit pas vampire",""]
  };
  const correction=corrections[article.id];
  if(!correction)return;
  const [sectionId,fragment,replacement]=correction;
  const section=article.sections?.find(item=>item.id===sectionId);
  const paragraph=section?.blocks?.find((block:Record<string,any>)=>block.type==="p");
  if(typeof paragraph?.text!=="string"||!paragraph.text.includes(fragment)||!article.sections?.some(item=>item.audience==="mj"&&item.blocks?.length))throw new Error(`PNJ · fuite à déplacer : ${article.id}`);
  paragraph.text=paragraph.text.replace(fragment,replacement);
}
