import { applyNamedPnjStatProfile, type StatProfile } from "./compendium-pnj-corporate-stats.js";

type Article={id:string;dataset?:string;sections?:Array<Record<string,any>>;[key:string]:any};
type Entry=StatProfile & {id:string};

// Fifty separate people; the multi-person entry Adam/Qigang/Carmello is held
// for editorial arbitration and never treated as a single set of attributes.
const PROFILES:Entry[]=[
  {id:"pnj-crawlers-docx-brittany-smith-cavaletty",tier:"elite",shape:"social",skills:["Diplomatie","Commerce","Investigation","Autorité"],anchor:"Mariée à un capo après s'être imposée dans son entourage, elle navigue dans les réseaux mafieux sous une apparence sous-estimée.",talents:["Réseau mobilisable — liens Cavaletty","Dossier préparé — milieu mafieux"]},
  {id:"pnj-crawlers-docx-shuren-shi",tier:"elite",shape:"social",skills:["Diplomatie","Représentation","Commerce","Investigation"],anchor:"Professionnelle de la publicité et de la persuasion, elle dépend de mafieux sans être elle-même décrite comme combattante.",talents:["Expertise éprouvée — Diplomatie","Dossier préparé — publicité"]},
  {id:"pnj-crawlers-docx-zeeka-steele",tier:"entraine",shape:"social",skills:["Représentation","Diplomatie","Commerce","Perception"],anchor:"Jeune figure réputée du milieu des Hookers de Las Vegas, connue aussi à Los Angeles ; aucune prouesse martiale n'est établie.",talents:["Expertise éprouvée — Représentation"]},
  {id:"pnj-crawlers-docx-jacob-delisle",tier:"elite",shape:"social",skills:["Séduction","Diplomatie","Représentation","Perception"],anchor:"Célébrité des Hookers dont la réputation vient du charisme et des rencontres ; son manque de concentration ne devient pas un bonus.",talents:["Expertise éprouvée — Séduction"]},
  {id:"pnj-crawlers-docx-henry-edwards",tier:"haute",shape:"esprit",skills:["Investigation","Perception","Tir","Autorité"],anchor:"Ancien policier et enquêteur très respecté, désormais sélectif dans les affaires qu'il accepte.",talents:["Lecture des failles — enquête","Dossier préparé — dossiers personnels"]},
  {id:"pnj-crawlers-docx-josefin-drescher",tier:"elite",shape:"esprit",skills:["Investigation","Perception","Diplomatie","Furtivité"],anchor:"Gunwatcher indépendante dont les contacts avec Tokala et les corporations suscitent la méfiance d'autres Crawlers.",talents:["Lecture des failles — enquête","Dossier préparé — contacts corporatifs"]},
  {id:"pnj-crawlers-docx-stella-hardin",tier:"haute",shape:"esprit",skills:["Investigation","Perception","Furtivité","Diplomatie"],anchor:"L'affaire criminelle de son père a déclenché sa passion de l'enquête, qu'elle poursuit comme Gunwatcher.",talents:["Lecture des failles — enquête","Dossier préparé — dossiers criminels"]},
  {id:"pnj-crawlers-docx-karl-henry",tier:"haute",shape:"terrain",skills:["Tir","Survie","Autorité","Athlétisme"],anchor:"Décrit comme l'un des grands héros de la guerre de Corée du Nord ; son expérience de soldat prime sur une étiquette de Deathrunner.",talents:["Terrain reconnu — guerre de Corée","Chef de manœuvre — vétérans"]},
  {id:"pnj-crawlers-docx-hailey-powell",tier:"heroique",shape:"terrain",skills:["Tir","Survie","Athlétisme","Investigation"],anchor:"Survivante de la première génération de supersoldats expérimentaux ; les modifications subies ne donnent aucun bonus chiffré sans règle d'augmentation.",talents:["Terrain reconnu — opérations militaires","Lecture des failles — observation"],truth:"Les augmentations issues des expériences du PCRC sont présentes au dossier ; les intégrer demande leur inventaire, leur intégrité et leurs coûts exacts."},
  {id:"pnj-crawlers-docx-jakeline-bates",tier:"haute",shape:"terrain",skills:["Furtivité","Survie","Investigation","Tir"],anchor:"A réussi une extraction dans une prison laboratoire subaquatique de Biosun et sait coopérer lors de missions risquées.",talents:["Terrain reconnu — infiltration","Dossier préparé — extraction"]},
  {id:"pnj-crawlers-docx-tia-reynolds",tier:"haute",shape:"terrain",skills:["Investigation","Survie","Perception","Tir"],anchor:"Chasseuse de fugitifs spécialisée dans la recherche et la traque ; ses propos sur des loups-garous restent des propos, sans tag de nature.",talents:["Lecture des failles — traque","Terrain reconnu — poursuite"]},
  {id:"pnj-crawlers-docx-carlos-saez",tier:"haute",shape:"terrain",skills:["Pugilat","Athlétisme","Esquive","Autorité"],anchor:"Sportif de combat exclu de nombreuses compétitions au Mexique, puis mercenaire employé par des cartels.",talents:["Lutte brève — Pugilat","Désarmement net — Pugilat"]},
  {id:"pnj-crawlers-docx-kiandra-price",tier:"haute",shape:"terrain",skills:["Autorité","Mêlée","Tir","Survie"],anchor:"Ancienne cheffe des Redgals, a travaillé dans la protection des commerces puis la sécurité d'Eversor tout en gardant des liens de gang.",talents:["Chef de manœuvre — Redgals","Réseau mobilisable — liens du quartier"]},
  {id:"pnj-crawlers-docx-goro-kazuma",tier:"haute",shape:"terrain",skills:["Mêlée","Furtivité","Survie","Investigation"],anchor:"Issu du clan yakuza Shinohara et survivant de blessures graves ; son parcours de Voidrunner justifie un combattant expérimenté.",talents:["Désarmement net — Mêlée","Terrain reconnu — opérations clandestines"]},
  {id:"pnj-crawlers-docx-zoya-ryukana",tier:"haute",shape:"terrain",skills:["Furtivité","Mêlée","Investigation","Tir"],anchor:"Assassine connue pour ses augmentations cruelles et ses contrats pour Drasko Vladic ; aucune arme implantée n'est fournie sans inventaire.",talents:["Désarmement net — Mêlée","Dossier préparé — cible précise"],truth:"Micro-ondes et acidité implantées sont décrites par le lore ; leurs dégâts, intégrité et stress augmentique restent à établir individuellement."},
  {id:"pnj-crawlers-docx-rayne-carter",tier:"haute",shape:"esprit",skills:["Neurodive","Investigation","Furtivité","Perception"],anchor:"Hacker parmi les plus redoutés et admirés du monde connu ; aucun pouvoir au-delà de ses pratiques numériques n'est présumé.",talents:["Expertise éprouvée — Neurodive","Lecture des failles — sécurité numérique"]},
  {id:"pnj-crawlers-docx-domingo-valerio",tier:"elite",shape:"esprit",skills:["Neurodive","Investigation","Furtivité","Diplomatie"],anchor:"Netdriller mexicain décoré pour ses actions contre les corporations, puis marqué par une opération ratée.",talents:["Expertise éprouvée — Neurodive","Dossier préparé — cible corporative"]},
  {id:"pnj-crawlers-docx-ashuna-kimble",tier:"haute",shape:"esprit",skills:["Neurodive","Mécanique","Investigation","Commerce"],anchor:"Exploite des corps connectés à des IA pour maintenir des identités actives sur l'Holonet ; possède des accords ponctuels avec le CBII.",talents:["Expertise éprouvée — Neurodive","Dossier préparé — identités numériques"]},
  {id:"pnj-crawlers-docx-khristina-yaroslavovna",tier:"haute",shape:"esprit",skills:["Neurodive","Investigation","Mécanique","Perception"],anchor:"Venue du jeu sur Holonet, devenue Neurodiver capable d'altérer des protocoles de sécurité malgré un début sans formation informatique.",talents:["Expertise éprouvée — Neurodive","Lecture des failles — protocoles"]},
  {id:"pnj-crawlers-docx-dragoslav-memic",tier:"elite",shape:"esprit",skills:["Neurodive","Furtivité","Investigation","Pilotage"],anchor:"Ancien chauffeur mafieux grièvement blessé, reconverti en Neurokiller ; le Pilotage vient de sa profession, non du dossier secret.",talents:["Expertise éprouvée — Neurodive","Dossier préparé — intrusion"]},
  {id:"pnj-crawlers-docx-zemirah-sherah",tier:"haute",shape:"esprit",skills:["Neurodive","Investigation","Perception","Mécanique"],anchor:"Hackeuse majeure dont le dossier souligne qu'elle est la moins augmentée des personnalités de ce rang ; compétence et augmentation restent distinctes.",talents:["Expertise éprouvée — Neurodive","Lecture des failles — systèmes"]},
  {id:"pnj-crawlers-docx-taishara-jibson",tier:"elite",shape:"esprit",skills:["Mécanique","Soin","Investigation","Commerce"],anchor:"Mécanicienne pour gangs et motards puis réparatrice d'augmentations, avec des bases de soin acquises au PCRC.",talents:["Expertise éprouvée — Mécanique","Dossier préparé — réparation d'implants"]},
  {id:"pnj-crawlers-docx-lenny-falk",tier:"elite",shape:"esprit",skills:["Mécanique","Neurodive","Commerce","Investigation"],anchor:"A vécu du bricolage, des réparations et du piratage après des revers économiques ; technicien adaptable.",talents:["Expertise éprouvée — Mécanique","Dossier préparé — équipement"]},
  {id:"pnj-crawlers-docx-dushane-murray",tier:"elite",shape:"esprit",skills:["Mécanique","Soin","Commerce","Investigation"],anchor:"Après une grave blessure, entretient sa propre échine mécanique puis équipe le quartier d'augmentations pour les Ivory Lion.",talents:["Expertise éprouvée — Mécanique","Dossier préparé — maintenance"],truth:"Son échine mécanique conditionne sa mobilité ; ses caractéristiques d'implant et le risque de panne doivent être consignés séparément."},
  {id:"pnj-crawlers-docx-narako-austin",tier:"haute",shape:"esprit",skills:["Mécanique","Neurodive","Savoirs","Investigation"],anchor:"Ingénieure jetée dans les bas quartiers, ayant exploité les logifates et les IA au lieu de disparaître.",talents:["Expertise éprouvée — Mécanique","Lecture des failles — technologie"]},
  {id:"pnj-crawlers-docx-aisha-white",tier:"haute",shape:"esprit",skills:["Soin","Savoirs","Mécanique","Investigation"],anchor:"Meditech capable de prodiguer des soins dépassant l'urgence.",talents:["Expertise éprouvée — Soin","Dossier préparé — soins avancés"]},
  {id:"pnj-crawlers-docx-arnstein-gill",tier:"haute",shape:"esprit",skills:["Savoirs","Soin","Investigation","Représentation"],anchor:"Chimiste et généticien médical reconnu, passé progressivement des laboratoires aux plateaux de télévision.",talents:["Expertise éprouvée — Savoirs","Lecture des failles — laboratoire"]},
  {id:"pnj-crawlers-docx-kashrim-el-khayat",tier:"elite",shape:"terrain",skills:["Pilotage","Commerce","Survie","Investigation"],anchor:"Prince passionné de vitesse et de véhicules, formé aux États-Unis ; sa catégorie Gundriver ne suffit pas à présumer une arme permanente.",talents:["Expertise éprouvée — Pilotage","Terrain reconnu — itinéraires"]},
  {id:"pnj-crawlers-docx-kendasha-roberts",tier:"haute",shape:"social",skills:["Commerce","Investigation","Autorité","Mécanique"],anchor:"Organise des équipes de charognards spécialisées dans la récupération d'augmentations rares pour d'autres Crawlers.",talents:["Réseau mobilisable — récupérateurs","Dossier préparé — pièces rares"]},
  {id:"pnj-crawlers-docx-yan-xiao",tier:"elite",shape:"terrain",skills:["Investigation","Survie","Autorité","Commerce"],anchor:"A bâti des équipes de récupération en Chine puis en Californie, arrivant après les affrontements pour fouiller les lieux.",talents:["Terrain reconnu — zones de combat","Dossier préparé — récupération"]},
  {id:"pnj-crawlers-docx-tuuwa-kolenya",tier:"elite",shape:"social",skills:["Autorité","Commerce","Investigation","Diplomatie"],anchor:"A repris très jeune le mouvement de son père Koyah ; son pouvoir est récent et discuté au sein de ses propres réseaux.",talents:["Réseau mobilisable — mouvement hérité","Dossier préparé — rivalités internes"]},
  {id:"pnj-crawlers-docx-kerlyn-sherres",tier:"elite",shape:"social",skills:["Commerce","Autorité","Investigation","Diplomatie"],anchor:"Recrute sous contrats abusifs des émigrés pour les corporations à travers des pays en crise ; réseau logistique établi.",talents:["Réseau mobilisable — convoyage","Dossier préparé — contrats"]},
  {id:"pnj-crawlers-docx-leslie-wright",tier:"heroique",shape:"esprit",skills:["Savoirs","Investigation","Mécanique","Autorité"],anchor:"Issue d'une famille ouvrière de Liverpool, scientifique du PCRC et pivot du bond technologique ; sa notoriété dépasse son groupe Crawler.",talents:["Expertise éprouvée — Savoirs","Lecture des failles — recherche"],truth:"Ses conséquences dans la Vérité et sa place historique demandent un profil révélé spécifique ; aucun PTV n'est inféré de ses découvertes scientifiques."},
  {id:"pnj-crawlers-docx-damon-harrington",tier:"entraine",shape:"social",skills:["Représentation","Diplomatie","Perception","Investigation"],anchor:"Neopunk pacifique mais très respecté, surtout connu pour une parole dure ; sa force physique réelle est explicitement incertaine.",talents:["Expertise éprouvée — Représentation"],truth:"Arbitrage : le dossier laisse ouverte une force soit très faible soit exceptionnelle ; pas de rang de combat spéculatif."},
  {id:"pnj-crawlers-docx-darielle-power",tier:"haute",shape:"social",skills:["Représentation","Séduction","Autorité","Diplomatie"],anchor:"Musicienne de The Void, sœur de Marielle, influence la scène neopunk par ses concerts ; ne pas confondre leurs groupes.",talents:["Expertise éprouvée — Représentation","Réseau mobilisable — scène neopunk"]},
  {id:"pnj-crawlers-docx-damian-escribano",tier:"haute",shape:"terrain",skills:["Tir","Survie","Autorité","Perception"],anchor:"Mène environ deux cents Enders depuis un bunker désertique, produit ses ressources et tire au sniper sur les intrus qu'il ne connaît pas.",talents:["Terrain reconnu — désert","Chef de manœuvre — Enders"]},
  {id:"pnj-crawlers-docx-gerrika-reese",tier:"elite",shape:"terrain",skills:["Survie","Perception","Autorité","Diplomatie"],anchor:"A quitté San Francisco face aux dolines et protège l'accès d'une communauté de huit cents survivalistes.",talents:["Terrain reconnu — refuge","Réseau mobilisable — communauté Enders"]},
  {id:"pnj-crawlers-docx-daft-vador-kaine-reid",tier:"haute",shape:"terrain",skills:["Furtivité","Tir","Investigation","Mêlée"],anchor:"Assassin Voidrunner associé à la Blanchisserie et réputé difficile à égaler avant l'apparition du Massacreur des égouts.",talents:["Dossier préparé — cible","Décrochage préparé — exfiltration"]},
  {id:"pnj-crawlers-docx-dan-shelong",tier:"haute",shape:"esprit",skills:["Neurodive","Investigation","Furtivité","Force Mentale"],anchor:"Expert de guerre psychologique par intrusions neurales, impliqué dans l'assassinat de Stephen Barner.",talents:["Expertise éprouvée — Neurodive","Lecture des failles — intrusion neurale"]},
  {id:"pnj-crawlers-docx-mi-yeon-ryong",tier:"haute",shape:"esprit",skills:["Savoirs","Soin","Commerce","Investigation"],anchor:"Venomer connue pour son savoir médical et son opportunisme politique ; ses interventions biomédicales restent distinctes de pouvoirs surnaturels.",talents:["Expertise éprouvée — Savoirs","Dossier préparé — biomédecine"]},
  {id:"pnj-crawlers-docx-yong-gi-mangjol",tier:"elite",shape:"social",skills:["Commerce","Investigation","Autorité","Diplomatie"],anchor:"Mandealer originaire de Séoul, actif dans les réseaux Crawler ; le dossier public ne prouve pas une spécialité au tir.",talents:["Dossier préparé — transactions","Réseau mobilisable — Mandealers"]},
  {id:"pnj-crawlers-docx-ogshaata-otto",tier:"elite",shape:"terrain",skills:["Survie","Perception","Diplomatie","Investigation"],anchor:"Évite les métropoles, vit loin des villes et évoque leurs mauvais esprits ; sa croyance ne prouve aucun don occulte.",talents:["Terrain reconnu — extérieur","Lecture des failles — observation"]},
  {id:"pnj-crawlers-antisysteme-p6-max-sharp",tier:"haute",shape:"terrain",skills:["Autorité","Tir","Survie","Investigation"],anchor:"Bras droit de Ryan Rowe, dirige des raids insurgés d'une brutalité particulière au sein de Raising Freedom.",talents:["Chef de manœuvre — raids","Réseau mobilisable — Raising Freedom"]},
  {id:"pnj-crawlers-antisysteme-p7-lyn-gordon",tier:"elite",shape:"social",skills:["Représentation","Autorité","Diplomatie","Investigation"],anchor:"Jeune figure de Raising Freedom, porte une colère militante plutôt qu'une formation martiale décrite.",talents:["Réseau mobilisable — Raising Freedom","Expertise éprouvée — Représentation"]},
  {id:"pnj-crawlers-antisysteme-p7-merlynn-bryant",tier:"elite",shape:"terrain",skills:["Survie","Autorité","Investigation","Soin"],anchor:"Ancienne pompière licenciée après avoir privilégié un incendie au lieu de protéger un conseiller ; devenue insurgée après la mort de ses enfants.",talents:["Terrain reconnu — secours","Réseau mobilisable — Raising Freedom"]},
  {id:"pnj-crawlers-antisysteme-p9-chon-hyun-sook",tier:"entraine",shape:"social",skills:["Diplomatie","Représentation","Investigation","Perception"],anchor:"Jeune recrue de Health Age attirée par l'oppression subie par les Coréens ; son engagement hésitant ne justifie pas un palier élite.",talents:["Expertise éprouvée — Diplomatie"]},
  {id:"pnj-crawlers-antisysteme-p10-karstryn-ogelgrutten",tier:"elite",shape:"esprit",skills:["Soin","Survie","Investigation","Perception"],anchor:"Intervient parmi les Corbeaux d'Asclépios dans les foyers infectieux et contre les dangers sanitaires.",talents:["Expertise éprouvée — Soin","Terrain reconnu — intervention sanitaire"]},
  {id:"pnj-crawlers-antisysteme-p10-omaar-al-bagheri",tier:"haute",shape:"terrain",skills:["Soin","Tir","Survie","Autorité"],anchor:"Médecin de guerre de retour du conflit de 2022-2028, combattant de Health Age ensuite lié aux Hell Angels.",talents:["Expertise éprouvée — Soin","Terrain reconnu — soins de guerre"]},
  {id:"pnj-crawlers-antisysteme-p12-roland-mitchell",tier:"elite",shape:"terrain",skills:["Tir","Survie","Autorité","Investigation"],anchor:"Fantassin de l'US Army tardivement déployé, survivant traumatisé devenu membre des Iron Revengers ; pas de grade héroïque inventé.",talents:["Terrain reconnu — zone de guerre","Réseau mobilisable — Iron Revengers"]},
  {id:"pnj-crawlers-antisysteme-p13-thaddeus-slabaugh",tier:"elite",shape:"social",skills:["Autorité","Représentation","Diplomatie","Survie"],anchor:"A dirigé une communauté devenue secte, a été appelé sous les armes pendant la guerre puis rejoint les Iron Revengers.",talents:["Réseau mobilisable — anciens fidèles","Expertise éprouvée — Autorité"]}
];

export function applyCrawlerStatBatch01(byId:Map<string,Article>):void {
  if(PROFILES.length!==50||new Set(PROFILES.map(p=>p.id)).size!==50)throw new Error("PNJ · lot Crawlers 01 incomplet ou dupliqué");
  for(const profile of PROFILES){
    const article=byId.get(profile.id);
    if(!article||article.dataset!=="realite-v9-crawlers-pnj")throw new Error(`PNJ · Crawler actif introuvable : ${profile.id}`);
    applyNamedPnjStatProfile(article,profile);
  }
}
