import { applyNamedPnjStatProfile, type StatProfile } from "./compendium-pnj-corporate-stats.js";

type Article={id:string;dataset?:string;sections?:Array<Record<string,any>>;[key:string]:any};
type Entry=StatProfile & {id:string};

const PROFILES:Entry[]=[
  {"id":"personnages-verite-extraterrestres-dhanuka-samara","tier":"elite","shape":"social","skills":["Représentation","Savoirs","Diplomatie","Commerce"],"anchor":"Musicien du groupe Gehenna, connu dans les cercles néopaïens pour des concerts liés à des rites.","talents":["Expertise éprouvée — Représentation"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-extraterrestres-carmen-hodges","tier":"heroique","shape":"esprit","skills":["Neurodive","Investigation","Autorité","Savoirs"],"anchor":"Assistante de Dina Page dotée d'accès gouvernementaux élevés, pilote jusqu'à vingt-cinq IA à la fois.","talents":["Expertise éprouvée — Neurodive","Dossier préparé — dossiers"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-extraterrestres-t-n","tier":"elite","shape":"terrain","skills":["Neurodive","Tir","Pilotage","Soin"],"anchor":"Crawler polyvalent augmenté, compétent dans plusieurs métiers mais sans spécialité ni rang remarquable.","talents":["Expertise éprouvée — Pilotage"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-extraterrestres-beltor-rixil","tier":"heroique","shape":"social","skills":["Commerce","Autorité","Investigation","Diplomatie"],"anchor":"Bryan Rixil organise la contrebande et les livraisons sous la couverture de la Rixil Association.","talents":["Réseau mobilisable — livreurs","Dossier préparé — itinéraire"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-especes-ming-xinya","tier":"elite","shape":"social","skills":["Commerce","Diplomatie","Investigation","Autorité"],"anchor":"Ancienne héritière chinoise exfiltrée pendant la guerre et contrainte de financer le PCRC, sans patrimoine actuel défini.","talents":["Dossier préparé — intérêts","Expertise éprouvée — Commerce"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-especes-megda-ayshin","tier":"haute","shape":"terrain","skills":["Autorité","Furtivité","Survie","Tir"],"anchor":"Dirige un groupuscule insurrectionnel hostile aux États-Unis et négocie avec les cartels mexicains.","talents":["Chef de manœuvre — cellule","Terrain reconnu — clandestinité"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-especes-neeba-ngubenani","tier":"heroique","shape":"social","skills":["Savoirs","Autorité","Diplomatie","Investigation"],"anchor":"Fondateur de Fangs et avocat intimidant, compte parmi les cadres de First Lawyers.","talents":["Réseau mobilisable — cabinet","Dossier préparé — procès"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-especes-elody-katherine-skotia","tier":"heroique","shape":"esprit","skills":["Savoirs","Soin","Autorité","Investigation"],"anchor":"Scientifique roumaine dirigeant la recherche de Sunways, obsédée par le progrès médical.","talents":["Expertise éprouvée — Savoirs","Réseau mobilisable — laboratoire"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-especes-elizabeth-mircalla-karnstein","tier":"haute","shape":"esprit","skills":["Soin","Savoirs","Commerce","Investigation"],"anchor":"Médecin austro-allemande liée à la direction de Rabbitechnologies après son mariage avec Hannes Senefelder.","talents":["Expertise éprouvée — Soin","Dossier préparé — biotechnologie"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-especes-ascanius","tier":"heroique","shape":"esprit","skills":["Savoirs","Autorité","Investigation","Diplomatie"],"anchor":"Nathan Chappelle, ancien chercheur en physique de Strasbourg engagé dans les insurrections civiles européennes.","talents":["Expertise éprouvée — Savoirs","Dossier préparé — insurrection"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-especes-koshaway-le-gris","tier":"heroique","shape":"terrain","skills":["Survie","Tir","Autorité","Perception"],"anchor":"Vétéran comanche des deux guerres mondiales et figure historique de sa tribu.","talents":["Terrain reconnu — guerre","Chef de manœuvre — anciens"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-especes-gullveig","tier":"haute","shape":"esprit","skills":["Mécanique","Savoirs","Commerce","Perception"],"anchor":"Alicia Gullveig tient un atelier de chimie des matériaux spécialisé dans les revêtements d'armes et d'augmentations.","talents":["Expertise éprouvée — Mécanique","Dossier préparé — matériaux"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-especes-circe","tier":"heroique","shape":"esprit","skills":["Savoirs","Soin","Autorité","Commerce"],"anchor":"Cylia Patra est cadre de Biosun et bras droit d'Opalia Sanders.","talents":["Réseau mobilisable — Biosun","Expertise éprouvée — Savoirs"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-especes-kalira-athegos","tier":"heroique","shape":"esprit","skills":["Savoirs","Investigation","Diplomatie","Autorité"],"anchor":"Katelyn Attenborough est une experte juridique du LAPD et proche de l'ancien enquêteur John Silver.","talents":["Dossier préparé — droit","Expertise éprouvée — Savoirs"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-especes-sagarion-nagilia","tier":"haute","shape":"social","skills":["Autorité","Diplomatie","Commerce","Investigation"],"anchor":"Collin Perez, maire de Phoenix, s'oppose aux implantations corporatives incontrôlées.","talents":["Réseau mobilisable — mairie","Dossier préparé — implantation"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-especes-kelrana-nateas","tier":"heroique","shape":"social","skills":["Commerce","Autorité","Investigation","Représentation"],"anchor":"Carolina Nates exerce aussi comme Katrin Ruthburg, directrice de la biochimie chez Wellspring et actrice occasionnelle.","talents":["Réseau mobilisable — Wellspring","Dossier préparé — concurrence"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-especes-laetheas-sundosia","tier":"heroique","shape":"social","skills":["Commerce","Autorité","Pilotage","Investigation"],"anchor":"Larry Sundown a acheté de nombreux navires de guerre et emploie le Red Captain Asgall MacArtain.","talents":["Réseau mobilisable — flotte","Dossier préparé — acquisitions"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-especes-lorinae-athegos","tier":"heroique","shape":"esprit","skills":["Investigation","Autorité","Perception","Furtivité"],"anchor":"Laurie D. Sun dirige Darksun Association, réseau d'enquêteurs, d'espions et d'anciens commandos.","talents":["Dossier préparé — enquête","Réseau mobilisable — Darksun"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-especes-iwashita-koji","tier":"heroique","shape":"terrain","skills":["Mêlée","Pugilat","Esquive","Furtivité"],"anchor":"Koji Iwashita est un tueur à gages entraîné très jeune à de nombreux arts martiaux au Japon.","talents":["Désarmement net — Mêlée","Terrain reconnu — contrats"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-especes-alice-river","tier":"haute","shape":"esprit","skills":["Savoirs","Investigation","Autorité","Diplomatie"],"anchor":"Bras droit du directeur de l'énergie du NRMD, contrôle les ressources aquatiques et surveille les corporations.","talents":["Dossier préparé — eau","Réseau mobilisable — NRMD"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-especes-athena-clyde","tier":"heroique","shape":"esprit","skills":["Mécanique","Soin","Neurodive","Investigation"],"anchor":"Athena Clyde travaille comme Meditech Crawler et possède une expertise scientifique en robotique.","talents":["Expertise éprouvée — Mécanique","Dossier préparé — réparation"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-especes-martin-guiden","tier":"haute","shape":"social","skills":["Représentation","Furtivité","Autorité","Investigation"],"anchor":"Militant néopaïen clandestin appelant à l'insurrection contre les religions monothéistes.","talents":["Réseau mobilisable — insurgés","Dossier préparé — propagande"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-especes-liliana-shera","tier":"heroique","shape":"social","skills":["Représentation","Commerce","Séduction","Autorité"],"anchor":"Actrice puis productrice majeure du divertissement pour adultes depuis les années 2010.","talents":["Expertise éprouvée — Représentation","Réseau mobilisable — production"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-especes-sigrid-jorgensen","tier":"haute","shape":"social","skills":["Savoirs","Représentation","Diplomatie","Autorité"],"anchor":"Ancienne institutrice et spécialiste des mythes, mobilise la communauté néopaïenne depuis son procès de 2034.","talents":["Réseau mobilisable — fidèles","Expertise éprouvée — Savoirs"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-especes-elysabeth-godwin","tier":"heroique","shape":"social","skills":["Représentation","Diplomatie","Perception","Commerce"],"anchor":"Animatrice du LysNight de Nextar, émission internationale de débats et divertissements.","talents":["Expertise éprouvée — Représentation","Réseau mobilisable — médias"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-especes-az-la-faucheuse-noire","tier":"entraine","shape":"terrain","skills":["Survie","Furtivité","Perception","Esquive"],"anchor":"Personne sans papiers et sans domicile des quartiers abandonnés, taciturne et sans profession attestée.","talents":["Expertise éprouvée — Survie"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-especes-svetlana-konstantinovna","tier":"heroique","shape":"terrain","skills":["Autorité","Mêlée","Survie","Savoirs"],"anchor":"Cheffe renommée formée à travers le monde, ancienne officière des forces spéciales russes.","talents":["Chef de manœuvre — anciens","Terrain reconnu — guerre"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-especes-amphitrite","tier":"haute","shape":"social","skills":["Commerce","Diplomatie","Autorité","Investigation"],"anchor":"Amalia Carson finance Underwater Nation contre l'exploitation de la mer par Ocean Master et Seawares.","talents":["Réseau mobilisable — militants","Dossier préparé — financement"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-fantastiques-tobias-dorner","tier":"haute","shape":"esprit","skills":["Représentation","Commerce","Autorité","Savoirs"],"anchor":"Cofondateur d'Omegacoustic, ancien musicien devenu directeur de la branche pop-rock.","talents":["Réseau mobilisable — label","Expertise éprouvée — Représentation"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-fantastiques-ielynnoesi-alianmar","tier":"haute","shape":"social","skills":["Représentation","Diplomatie","Savoirs","Autorité"],"anchor":"Lynda Noesi est évêquesse de San Francisco, respectée de ses fidèles et entendue à la tour Vatican.","talents":["Réseau mobilisable — diocèse","Expertise éprouvée — Diplomatie"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-fantastiques-laegeltias-alduryn","tier":"elite","shape":"esprit","skills":["Mécanique","Survie","Perception","Tir"],"anchor":"Larry Duryn, caporal vétéran souffrant de stress post-traumatique, travaille comme mécanicien Crawler.","talents":["Expertise éprouvée — Mécanique","Terrain reconnu — interventions"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-fantastiques-roberrik-reimer","tier":"heroique","shape":"social","skills":["Commerce","Autorité","Survie","Diplomatie"],"anchor":"Ancien militaire néerlandais ayant fondé MegaMeat, aujourd'hui président de Dwarfood.","talents":["Réseau mobilisable — Dwarfood","Expertise éprouvée — Commerce"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-fantastiques-motsognir","tier":"entraine","shape":"terrain","skills":["Survie","Perception","Constitution","Pugilat"],"anchor":"Bob vit sans domicile à Los Angeles ; son dossier public ne documente ni emploi ni formation particulière.","talents":["Expertise éprouvée — Survie"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-fantastiques-atreesha","tier":"haute","shape":"social","skills":["Représentation","Autorité","Diplomatie","Commerce"],"anchor":"Actrice de seconds rôles reconnue pour sa discipline et son énergie dans de nombreuses productions.","talents":["Expertise éprouvée — Représentation","Réseau mobilisable — tournage"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-fantastiques-izchara","tier":"haute","shape":"terrain","skills":["Tir","Survie","Mêlée","Perception"],"anchor":"Neekolas Hara, ancien commando sauvé par le programme Phénix, travaille dans la sécurité de Tuatha.","talents":["Terrain reconnu — opérations","Expertise éprouvée — Tir"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-fantastiques-lhizza","tier":"elite","shape":"terrain","skills":["Survie","Tir","Furtivité","Perception"],"anchor":"Lisa, orpheline des guerres de cartels, a rejoint des motards puis les insurgés californiens.","talents":["Terrain reconnu — clandestinité","Expertise éprouvée — Survie"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-fantastiques-king-frazier","tier":"haute","shape":"esprit","skills":["Autorité","Investigation","Perception","Tir"],"anchor":"King Frazier commande la surveillance et les caméras du secteur ouest du LAUS.","talents":["Chef de manœuvre — patrouilles","Dossier préparé — secteur"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-fantastiques-ashorn","tier":"heroique","shape":"terrain","skills":["Autorité","Tir","Survie","Commerce"],"anchor":"Gerald Ashorn, général des Marines pendant la guerre, exploite désormais des arènes de combat en Californie.","talents":["Chef de manœuvre — vétérans","Terrain reconnu — guerre"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-fantastiques-cassie-murdock","tier":"heroique","shape":"esprit","skills":["Commerce","Investigation","Autorité","Savoirs"],"anchor":"Cassie Murdock, gestionnaire brillante de Tala, organise les ressources et les actifs immobiliers.","talents":["Expertise éprouvée — Commerce","Dossier préparé — actifs"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-fantastiques-emilynn-marshall","tier":"elite","shape":"social","skills":["Investigation","Perception","Commerce","Diplomatie"],"anchor":"Crawler devenue Fixer, obtient des informations grâce à son réseau naissant et sa lecture des mensonges.","talents":["Dossier préparé — source","Expertise éprouvée — Perception"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-fantastiques-kristian-morales","tier":"haute","shape":"social","skills":["Représentation","Perception","Commerce","Diplomatie"],"anchor":"Batteur du groupe The Void, musicien du courant contestataire néopunk MAP.","talents":["Expertise éprouvée — Représentation","Réseau mobilisable — scène"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-fantastiques-samanthea-malanwe","tier":"heroique","shape":"social","skills":["Commerce","Autorité","Investigation","Diplomatie"],"anchor":"Samantha Maxwell domine le métier de Fixer à Las Vegas grâce à un vaste réseau.","talents":["Réseau mobilisable — Las Vegas","Dossier préparé — clients"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-fantastiques-skyler-murray","tier":"elite","shape":"terrain","skills":["Neurodive","Survie","Perception","Furtivité"],"anchor":"Crawler Neurodiver solitaire et paranoïaque, survit à de graves blessures lors de ses missions.","talents":["Terrain reconnu — isolement","Expertise éprouvée — Neurodive"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-fantastiques-silia-ellen-sky","tier":"heroique","shape":"social","skills":["Commerce","Autorité","Investigation","Diplomatie"],"anchor":"Fondatrice galloise d'une corporation exploitant les fonds marins, contrôle de vastes concessions.","talents":["Réseau mobilisable — corporation","Dossier préparé — concessions"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-chasseurs-neera-athren","tier":"entraine","shape":"terrain","skills":["Pilotage","Survie","Perception","Commerce"],"anchor":"Neera Athren est une Gundriver motarde, encore peu réputée et jugée peu fiable.","talents":["Expertise éprouvée — Pilotage"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-chasseurs-radomir-pavelov-hadjiev","tier":"haute","shape":"esprit","skills":["Investigation","Perception","Savoirs","Diplomatie"],"anchor":"Évêque bulgare expérimenté, connu publiquement pour son flair d'enquêteur.","talents":["Dossier préparé — piste","Lecture des failles — enquête"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-chasseurs-juanna-di-ferrantino-albertini","tier":"haute","shape":"social","skills":["Diplomatie","Autorité","Investigation","Commerce"],"anchor":"Juanna di Ferrantino a exercé une influence politique discrète avant de partir aux États-Unis sous une autre identité.","talents":["Dossier préparé — contact","Expertise éprouvée — Diplomatie"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-chasseurs-nhreya-kumar","tier":"entraine","shape":"social","skills":["Représentation","Commerce","Perception","Diplomatie"],"anchor":"Née à Los Angeles d'une actrice de Bollywood, sa profession personnelle n'est pas documentée.","talents":["Expertise éprouvée — Perception"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-chasseurs-sarah-smith","tier":"entraine","shape":"social","skills":["Représentation","Survie","Perception","Commerce"],"anchor":"Ancienne travailleuse du divertissement pour adultes, entrée très jeune dans la scène néopunk et la drogue.","talents":["Expertise éprouvée — Survie"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
  {"id":"personnages-verite-chasseurs-rahul-punja","tier":"entraine","shape":"terrain","skills":["Survie","Perception","Diplomatie","Commerce"],"anchor":"Rahul Punja vit modestement à Las Vegas et se déplace souvent ; aucun métier public précis n'est attesté.","talents":["Expertise éprouvée — Survie"],"truth":"Le profil de Vérité et les pouvoirs révélés se traitent dans un bloc distinct."},
];

export function applyPnjStatBatch10(byId:Map<string,Article>):void {
  if(PROFILES.length!==50||new Set(PROFILES.map(p=>p.id)).size!==50)throw new Error("PNJ · lot 10 incomplet ou dupliqué");
  for(const profile of PROFILES){
    const article=byId.get(profile.id);
    if(!article)throw new Error(`PNJ · fiche active introuvable : ${profile.id}`);
    applyNamedPnjStatProfile(article,profile);
  }
}
