import { applyNamedPnjStatProfile, type StatProfile } from "./compendium-pnj-corporate-stats.js";

type Article={id:string;dataset?:string;sections?:Array<Record<string,any>>;[key:string]:any};
type Entry=StatProfile & {id:string};

// Ancrages et compétences examinés pour chaque personnage dans son dossier.
// Les informations de Vérité ne servent jamais à augmenter le profil civil.
const PROFILES:Entry[]=[
  {id:"pnj-crawlers-antisysteme-p13-mildred-copeland",tier:"elite",shape:"esprit",skills:["Mécanique","Savoirs","Investigation","Furtivité"],anchor:"Ancienne technicienne du PCRC passée à l'insurrection, a manipulé du combustible nucléaire ; le projet Phoenix n'en fait pas une scientifique en chef.",talents:["Expertise éprouvée — Mécanique","Dossier préparé — laboratoire"]},
  {id:"pnj-crawlers-antisysteme-p15-jane-costa",tier:"elite",shape:"esprit",skills:["Soin","Survie","Furtivité","Investigation"],anchor:"Meditech qui soigne les insurgés après leurs attaques ; sa nature de louve relève exclusivement du dossier MJ.",talents:["Expertise éprouvée — Soin","Terrain reconnu — soins clandestins"],truth:"Sa nature de louve et ses liens avec Ascanius restent dans le dossier MJ ; forme révélée et PTV demandent une évaluation séparée."},
  {id:"pnj-crawlers-antisysteme-p16-isabelle-pinchon",tier:"haute",shape:"terrain",skills:["Tir","Survie","Autorité","Investigation"],anchor:"Ancienne gendarme puis légionnaire, prépare l'accueil d'insurgés fuyant la répression française.",talents:["Terrain reconnu — opération militaire","Chef de manœuvre — exfiltration"]},
  {id:"pnj-crawlers-antisysteme-p16-adalfredo-guastella",tier:"elite",shape:"terrain",skills:["Athlétisme","Survie","Mêlée","Esquive"],anchor:"Ancien sportif italien entré dans l'insurrection après les famines, garde une cicatrice d'un affrontement à la hallebarde.",talents:["Terrain reconnu — manifestations","Expertise éprouvée — Athlétisme"]},
  {id:"pnj-crawlers-antisysteme-p18-sahamena-lannis",tier:"elite",shape:"social",skills:["Autorité","Furtivité","Survie","Diplomatie"],anchor:"Dirige dans la Réalité des insurgés écologistes, impliquée dans des assassinats de cadres alimentaires ; sa filiation elfe reste MJ.",talents:["Réseau mobilisable — écologistes","Terrain reconnu — guérilla"],truth:"Origine Lanyth, conseil des Anciens et forme de Vérité restent MJ ; aucun pouvoir elfique chiffré n'est présumé."},
  {id:"pnj-crawlers-antisysteme-p19-mahkah-jones",tier:"elite",shape:"social",skills:["Diplomatie","Représentation","Savoirs","Survie"],anchor:"Militant écologiste revendiquant une action non violente, rejoint GFM après avoir été désavoué ; chaman ne suffit pas à prouver une magie.",talents:["Expertise éprouvée — Diplomatie","Expertise éprouvée — Représentation"]},
  {id:"pnj-crawlers-antisysteme-p19-kimmy-oromigna",tier:"elite",shape:"social",skills:["Représentation","Investigation","Diplomatie","Autorité"],anchor:"Militante ghanéenne devenue figure de GFM, sait dénoncer les clients riches de son ancien milieu.",talents:["Réseau mobilisable — GFM","Dossier préparé — mécènes"]},
  {id:"pnj-crawlers-antisysteme-p22-miwatani-raichoko",tier:"entraine",shape:"terrain",skills:["Pilotage","Perception","Survie","Mécanique"],anchor:"Jeune membre des Mermaid Soldiers qui n'a pas réellement combattu pendant la guerre ; aucune expérience militaire majeure n'est attestée.",talents:["Expertise éprouvée — Pilotage"]},
  {id:"pnj-crawlers-antisysteme-p25-wang-gyeong-su",tier:"heroique",shape:"social",skills:["Autorité","Savoirs","Diplomatie","Tir"],anchor:"Général nord-coréen autrefois très respecté, s'est opposé aux offensives de Kang et tente de négocier en exil.",talents:["Chef de manœuvre — troupes","Dossier préparé — commandement" ]},
  {id:"pnj-crawlers-antisysteme-p25-lang-yahui",tier:"heroique",shape:"esprit",skills:["Pilotage","Savoirs","Autorité","Mêlée"],anchor:"Officière chinoise et stratège, excellente pilote de chasse et compétente au combat rapproché selon le dossier.",talents:["Expertise éprouvée — Pilotage","Chef de manœuvre — aviation"]},
  {id:"pnj-crawlers-antisysteme-p27-ashkii-goldrain",tier:"haute",shape:"terrain",skills:["Pugilat","Athlétisme","Esquive","Autorité"],anchor:"Vétéran navajo devenu combattant d'UMA, puis soutien loyal de Talatuwa dans la réserve.",talents:["Lutte brève — Pugilat","Désarmement net — Pugilat"]},
  {id:"pnj-crawlers-antisysteme-p29-masroora-el-ashraf",tier:"haute",shape:"terrain",skills:["Tir","Survie","Autorité","Furtivité"],anchor:"Combattante de l'opposition au régime des Khayat, ancienne proche du prince Kashrim.",talents:["Terrain reconnu — insurrection","Réseau mobilisable — opposition"]},
  {id:"pnj-crawlers-antisysteme-p31-leona-ambersmith",tier:"haute",shape:"terrain",skills:["Tir","Survie","Autorité","Investigation"],anchor:"Ex-soldate puis mercenaire, forme des exécutants pour le mouvement YDYL.",talents:["Chef de manœuvre — recrues YDYL","Terrain reconnu — opérations armées"]},
  {id:"pnj-crawlers-antisysteme-p33-yegpor-karamov",tier:"entraine",shape:"esprit",skills:["Savoirs","Diplomatie","Investigation","Perception"],anchor:"Professeur de sciences discret ; les crimes d'Arkady, son frère, ne se transfèrent pas à son profil.",talents:["Expertise éprouvée — Savoirs"]},
  {id:"pnj-crawlers-antisysteme-p35-shaif-almessar",tier:"entraine",shape:"social",skills:["Diplomatie","Perception","Savoirs","Survie"],anchor:"Seule l'appartenance à l'Alhaqiqa est documentée ; les capacités opérationnelles de cette secte ne prouvent aucune compétence personnelle.",talents:["Expertise éprouvée — Diplomatie"],truth:"Arbitrage : biographie individuelle absente ; réviser le palier si une source nommée décrit sa fonction."},
  {id:"pnj-crawlers-antisysteme-p35-ameena-al-gad",tier:"elite",shape:"terrain",skills:["Perception","Furtivité","Mêlée","Survie"],anchor:"Acolyte nizarite chargée de veiller sur Hashem El'Khayat ; sa surveillance justifie la vigilance, sans exploits inventés.",talents:["Terrain reconnu — escorte","Lecture des failles — surveillance"]},
  {id:"pnj-crawlers-antisysteme-p38-janyn-yates",tier:"haute",shape:"social",skills:["Autorité","Pugilat","Diplomatie","Investigation"],anchor:"Impliquée dans la direction des Angels et s'entraîne à la boxe plusieurs heures par nuit.",talents:["Réseau mobilisable — Angels","Lutte brève — Pugilat"]},
  {id:"pnj-crawlers-antisysteme-p39-waylon-hunt",tier:"haute",shape:"terrain",skills:["Tir","Survie","Athlétisme","Soin"],anchor:"Ancien pompier puis Navy SEAL, a servi pendant la guerre sans distinctions militaires particulières attestées.",talents:["Terrain reconnu — opérations militaires","Expertise éprouvée — Soin"]},
  {id:"pnj-crawlers-antisysteme-p39-angelino-molina",tier:"elite",shape:"terrain",skills:["Pilotage","Commerce","Tir","Survie"],anchor:"Motard contrebandier redouté et impulsif ; sa réputation de brutalité ne prouve pas une maîtrise héroïque.",talents:["Expertise éprouvée — Pilotage","Expertise éprouvée — Commerce"]},
  {id:"pnj-crawlers-antisysteme-p40-stephany-lorn",tier:"haute",shape:"esprit",skills:["Autorité","Investigation","Diplomatie","Commerce"],anchor:"A réorganisé les Cruisers pendant la guerre par planification et diversification des liens plutôt que par le combat.",talents:["Chef de manœuvre — Cruisers","Réseau mobilisable — motards"]},
  {id:"pnj-crawlers-antisysteme-p41-lana-jackson",tier:"haute",shape:"terrain",skills:["Tir","Survie","Furtivité","Autorité"],anchor:"Vétérane new-yorkaise engagée en 2027, seule survivante de sa famille après la guerre.",talents:["Terrain reconnu — guerre","Expertise éprouvée — Tir"]},
  {id:"pnj-crawlers-antisysteme-p41-xander-lucas",tier:"haute",shape:"terrain",skills:["Pugilat","Constitution","Autorité","Athlétisme"],anchor:"Chef brutal des Armored Fists, revenu de détention profondément modifié physiquement ; ses implants et leurs coûts ne sont pas chiffrés sans inventaire.",talents:["Lutte brève — Pugilat","Chef de manœuvre — Armored Fists"],truth:"Arbitrage des augmentations : source décrit masse et densité osseuse, sans inventaire mécanique ; intégrité et contreparties à fixer."},
  {id:"pnj-crawlers-antisysteme-p43-addison-fockell-fox",tier:"entraine",shape:"social",skills:["Diplomatie","Commerce","Investigation","Perception"],anchor:"Fille du fondateur des Reapers, était enfant lors de leur réorganisation ; aucun exploit de commandement ou de combat personnel n'est décrit.",talents:["Expertise éprouvée — Diplomatie"]},
  {id:"pnj-crawlers-antisysteme-p43-solomon-blackburn",tier:"haute",shape:"social",skills:["Autorité","Commerce","Diplomatie","Investigation"],anchor:"Second chef des Reapers, les a ouverts à de nouveaux membres puis a fondé un autre chapitre du réseau RIP.",talents:["Réseau mobilisable — Reapers","Chef de manœuvre — motards"]},
  {id:"pnj-crawlers-antisysteme-p44-miguel-gonzalez",tier:"entraine",shape:"social",skills:["Commerce","Autorité","Perception","Diplomatie"],anchor:"Sa section publique raconte surtout l'histoire des Vagos et ne documente presque aucune aptitude personnelle de Miguel.",talents:["Réseau mobilisable — Vagos"],truth:"Arbitrage : trouver une source biographique propre à Miguel avant de hausser son profil."},
  {id:"pnj-crawlers-antisysteme-p44-adalyn-owens-peacock",tier:"haute",shape:"terrain",skills:["Pugilat","Tir","Esquive","Survie"],anchor:"A obtenu sa place chez les Vagos en se battant et en protégeant ses camarades sous le feu ; a coopéré avec Tokala.",talents:["Lutte brève — Pugilat","Terrain reconnu — affrontement de motards"]},
  {id:"pnj-crawlers-antisysteme-p45-encarnacion-miralles",tier:"haute",shape:"social",skills:["Autorité","Commerce","Tir","Investigation"],anchor:"Préside les Coyotes Locos et négocie entre le passé du cartel familial et les factions motardes mexicaines.",talents:["Chef de manœuvre — Coyotes Locos","Réseau mobilisable — cartel"]},
  {id:"pnj-crawlers-antisysteme-p45-kyle-simmons",tier:"haute",shape:"terrain",skills:["Autorité","Tir","Survie","Commerce"],anchor:"Préside un chapitre Vagos extrémiste qui soumet des villages et revend des captifs ; sa dangerosité tient aussi à ses hommes.",talents:["Chef de manœuvre — Los Einherjar","Réseau mobilisable — Vagos"]},
  {id:"pnj-crawlers-antisysteme-p46-raghnaid-peutan",tier:"heroique",shape:"terrain",skills:["Mêlée","Pugilat","Autorité","Survie"],anchor:"A imposé sa place à la tête des Sons of Silence malgré leur misogynie ; son rang d'Amazone est réservé au dossier MJ.",talents:["Chef de manœuvre — Sons of Silence","Désarmement net — Mêlée"],truth:"Amazone au service d'Angrboda : profil révélé et PTV à déduire de la source de Vérité, pas de la présidence motarde."},
  {id:"pnj-crawlers-antisysteme-p46-eamonn-mac-cearain",tier:"elite",shape:"social",skills:["Autorité","Commerce","Investigation","Pugilat"],anchor:"Violent prétendant à la direction des Sons of Silence, a monté des contacts en prison ; ses visions d'enfance ne prouvent pas un don.",talents:["Réseau mobilisable — détenus","Dossier préparé — rivalités"]},
  {id:"pnj-crawlers-antisysteme-p47-rike-kuechler",tier:"haute",shape:"terrain",skills:["Mêlée","Pilotage","Pugilat","Survie"],anchor:"S'est distinguée jeune dans les affrontements de motards avec Raghnaid, entretient un lien fort avec sa moto Miranda.",talents:["Désarmement net — Mêlée","Terrain reconnu — raids motards"]},
  {id:"pnj-crawlers-antisysteme-p47-cannon-mullins",tier:"elite",shape:"terrain",skills:["Autorité","Pilotage","Tir","Survie"],anchor:"Dirige des motards lourdement augmentés et dévoués, mais le dossier le décrit personnellement comme lâche.",talents:["Réseau mobilisable — Fils de l'Audace","Expertise éprouvée — Pilotage"],truth:"Le niveau de ses augmentations personnelles demeure non renseigné ; ne pas le confondre avec celui de ses hommes."},
  {id:"pnj-crawlers-antisysteme-p48-zaketa-harris",tier:"elite",shape:"social",skills:["Autorité","Diplomatie","Survie","Investigation"],anchor:"A rassemblé des vétérans blessés pour former les Sons of Legba ; sa section publique porte surtout sur l'histoire du club.",talents:["Réseau mobilisable — Sons of Legba","Chef de manœuvre — vétérans"]},
  {id:"pnj-crawlers-antisysteme-p48-annushka-lyninka-maxinovna",tier:"elite",shape:"esprit",skills:["Investigation","Furtivité","Diplomatie","Survie"],anchor:"Héritière survivante d'un naufrage, a vécu cachée en Russie alors que les hommes de Shuji Kashiwa la traquaient.",talents:["Expertise éprouvée — Furtivité","Dossier préparé — poursuivants"]},
  {id:"pnj-crawlers-antisysteme-p49-lemaun-cross",tier:"haute",shape:"terrain",skills:["Tir","Autorité","Pugilat","Investigation"],anchor:"Ex-policier de Washington condamné pour corruption et violence, devenu chef de motards après une mission contre Dina Page.",talents:["Chef de manœuvre — motards","Dossier préparé — surveillance"]},
  {id:"pnj-crawlers-antisysteme-p49-toxicity-norton",tier:"haute",shape:"terrain",skills:["Pugilat","Autorité","Survie","Esquive"],anchor:"Boxeuse passée par le front puis par les Sons of Legba ; son poison céleste est exclusivement une capacité de Vérité MJ.",talents:["Lutte brève — Pugilat","Réseau mobilisable — Sons of Legba"],truth:"Roshielle et le poison céleste figurent au dossier MJ ; forme révélée, dégâts et PTV à arbitrer séparément."},
  {id:"pnj-crawlers-antisysteme-p50-honda-daisuke",tier:"haute",shape:"terrain",skills:["Pilotage","Survie","Autorité","Mêlée"],anchor:"Après l'effondrement de son clan yakuza, a fui plusieurs mois à moto avant de fonder le gang Onikishi.",talents:["Terrain reconnu — fuite à moto","Chef de manœuvre — Onikishi"]},
  {id:"pnj-crawlers-antisysteme-p50-miyashiro-kamiko",tier:"haute",shape:"terrain",skills:["Mêlée","Autorité","Pilotage","Esquive"],anchor:"Dirige les Red Oni, connue pour sa brutalité et son katana de Sehdia Craft ; l'arme demande son propre équipement.",talents:["Désarmement net — Mêlée","Chef de manœuvre — Red Oni"]},
  {id:"pnj-crawlers-antisysteme-p51-shitomada-kiyoemon",tier:"heroique",shape:"terrain",skills:["Mêlée","Pugilat","Esquive","Autorité"],anchor:"Ancien Bosozoku devenu maître de son style martial, sa maîtrise au combat malgré l'âge est explicitement attestée.",talents:["Désarmement net — Mêlée","Lutte brève — Pugilat"]},
  {id:"pnj-crawlers-antisysteme-p51-yokoyama-shinobu-yo-jin-joo",tier:"haute",shape:"esprit",skills:["Langages & Argot","Autorité","Tir","Survie"],anchor:"Préside les Green Oni, son expérience militaire et sa pratique de plusieurs langues sont documentées.",talents:["Expertise éprouvée — Langages & Argot","Chef de manœuvre — Green Oni"]},
  {id:"pnj-crawlers-antisysteme-p52-wenona",tier:"haute",shape:"social",skills:["Autorité","Pilotage","Survie","Diplomatie"],anchor:"Cheffe des Last Crows, motarde et chamane ; aucune magie chiffrée ne résulte du seul titre de chamane.",talents:["Chef de manœuvre — Last Crows","Terrain reconnu — itinérance"]},
  {id:"pnj-crawlers-antisysteme-p53-meilir-yarwood",tier:"elite",shape:"terrain",skills:["Pilotage","Survie","Mêlée","Perception"],anchor:"Motard gallois des Black Crows puis proche des Last Crows, a veillé sur Ciara et brièvement tenté Ushkoll.",talents:["Terrain reconnu — itinérance","Expertise éprouvée — Pilotage"]},
  {id:"pnj-crawlers-antisysteme-p53-zack-littlebear",tier:"elite",shape:"terrain",skills:["Pilotage","Autorité","Survie","Pugilat"],anchor:"Trop jeune pour la guerre, a rejoint Wenona après une défaite puis fondé son propre chapitre des Last Crows.",talents:["Réseau mobilisable — chapitre Last Crows","Terrain reconnu — routes"]},
  {id:"pnj-crawlers-antisysteme-p56-mary-shanasti",tier:"haute",shape:"social",skills:["Autorité","Représentation","Diplomatie","Savoirs"],anchor:"Fondatrice spirituelle et dirigeante des communautés sous-marines indépendantes ; son néopaganisme ne donne pas de pouvoirs automatiques.",talents:["Réseau mobilisable — Underwater Nation","Chef de manœuvre — communautés"]},
  {id:"pnj-crawlers-antisysteme-p57-kylon-smithgerald",tier:"haute",shape:"terrain",skills:["Tir","Survie","Athlétisme","Autorité"],anchor:"Combattant et vétéran de la fin de la guerre, a quitté la sécurité de Seaware pour défendre Mary Shanasti.",talents:["Terrain reconnu — installations sous-marines","Chef de manœuvre — gardes"]},
  {id:"pnj-crawlers-antisysteme-p57-ryan-oakson",tier:"haute",shape:"terrain",skills:["Tir","Athlétisme","Survie","Autorité"],anchor:"Défenseur fanatique des colonies sous-marines, décrit comme l'un des partisans les plus puissants et violents de Mary.",talents:["Terrain reconnu — cités sous-marines","Chef de manœuvre — Enders"]},
  {id:"pnj-crawlers-antisysteme-p58-kassidy-haynes",tier:"haute",shape:"terrain",skills:["Tir","Survie","Autorité","Athlétisme"],anchor:"Ex-capitaine des Marines reconvertie dans la communauté agricole Gold Cows, s'y réfugie après sa désertion.",talents:["Chef de manœuvre — Marines","Terrain reconnu — exploitation agricole"]},
  {id:"pnj-crawlers-antisysteme-p58-diana-buck",tier:"haute",shape:"social",skills:["Autorité","Commerce","Survie","Investigation"],anchor:"Dirige les Gold Cows, communauté de fermiers indépendants qui résiste aux motards et aux mercenaires.",talents:["Réseau mobilisable — Gold Cows","Chef de manœuvre — défense des fermes"]},
  {id:"pnj-crawlers-antisysteme-p59-ethan-sheppard",tier:"haute",shape:"social",skills:["Diplomatie","Savoirs","Autorité","Représentation"],anchor:"Avocat réputé puis sénateur californien durant la guerre ; sa conversion ultérieure aux Enders ne confère pas de talent martial.",talents:["Expertise éprouvée — Diplomatie","Réseau mobilisable — anciens élus"]},
  {id:"pnj-crawlers-antisysteme-p59-jett-burris",tier:"haute",shape:"terrain",skills:["Tir","Investigation","Pilotage","Perception"],anchor:"Ex-policier texan féru de style cowboy, possède un revolver microplasma personnalisé acquis après la guerre.",talents:["Expertise éprouvée — Tir","Dossier préparé — enquête" ]}
];

export function applyCrawlerStatBatch02(byId:Map<string,Article>):void {
  if(PROFILES.length!==50||new Set(PROFILES.map(p=>p.id)).size!==50)throw new Error("PNJ · lot Crawlers 02 incomplet ou dupliqué");
  for(const profile of PROFILES){
    const article=byId.get(profile.id);
    if(!article||article.dataset!=="realite-v9-crawlers-pnj")throw new Error(`PNJ · Crawler actif introuvable : ${profile.id}`);
    repairTruthLeaks(article);
    applyNamedPnjStatProfile(article,profile);
  }
}

function repairTruthLeaks(article:Article):void {
  const sections=article.sections??[];
  const section=(id:string)=>sections.find(item=>item.id===id);
  if(article.id==="pnj-crawlers-antisysteme-p15-jane-costa"){
    const reality=section("antisysteme-p15-realite");
    const text=reality?.blocks?.find((block:Record<string,any>)=>block.type==="p")?.text;
    const marker=" En tant que louve,";
    if(typeof text!=="string"||!text.includes(marker)||!section("dossier-mj-consolide"))throw new Error("PNJ · Jane : déplacement MJ impossible");
    // Le paragraphe public sans le suffixe secret existe déjà dans pelages-realite.
    article.sections=sections.filter(item=>item!==reality);
  }
  if(article.id==="pnj-crawlers-antisysteme-p18-sahamena-lannis"){
    const reality=section("antisysteme-p18-realite");
    const text=reality?.blocks?.find((block:Record<string,any>)=>block.type==="p")?.text;
    if(typeof text!=="string"||!text.includes("origine elfes sylvains")||!section("dossier-mj-consolide"))throw new Error("PNJ · Sahamena : déplacement MJ impossible");
    // Le récit civil figure dans grands-exiles-informations-realite ; le récit elfe est déjà en MJ.
    article.sections=sections.filter(item=>item!==reality);
  }
  if(article.id==="pnj-crawlers-antisysteme-p49-toxicity-norton"){
    const reality=section("antisysteme-p49-realite");
    const block=reality?.blocks?.find((item:Record<string,any>)=>item.type==="p");
    const prefix="pouvoir angélique : le poison céleste ";
    if(typeof block?.text!=="string"||!block.text.startsWith(prefix)||!section("dossier-mj-consolide"))throw new Error("PNJ · Toxicity : secret introuvable");
    block.text=block.text.slice(prefix.length).replace(/^Statut : présidence de Motorcycle Club /,"");
  }
}
