import { applyNamedPnjStatProfile, type StatProfile } from "./compendium-pnj-corporate-stats.js";

type Article={id:string;dataset?:string;sections?:Array<Record<string,any>>;[key:string]:any};
type Entry=StatProfile & {id:string};

const PROFILES:Entry[]=[
  {"id":"pnj-temples-daemoniaques-lucia-gilliam","tier":"haute","shape":"social","skills":["Savoirs","Autorité","Perception","Diplomatie"],"anchor":"Religieuse de haut rang au service personnel de la papesse, réservée et marquée par un passé douloureux.","talents":["Réseau mobilisable — curie","Expertise éprouvée — Savoirs"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"pnj-temples-daemoniaques-evelyn-forbes","tier":"heroique","shape":"esprit","skills":["Savoirs","Investigation","Autorité","Diplomatie"],"anchor":"Haute juge de la Cour suprême californienne, réputée incorruptible et inflexible dans l'application du droit.","talents":["Dossier préparé — jurisprudence","Expertise éprouvée — Savoirs"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"pnj-temples-daemoniaques-finton-francehill","tier":"heroique","shape":"social","skills":["Représentation","Diplomatie","Autorité","Savoirs"],"anchor":"Sénateur californien et orateur redouté, ancien démocrate et soutien actif de Dina Page.","talents":["Réseau mobilisable — sénat","Expertise éprouvée — Représentation"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"pnj-temples-daemoniaques-miles-forest","tier":"heroique","shape":"terrain","skills":["Investigation","Survie","Mêlée","Perception"],"anchor":"Chasseur indépendant de sorciers et de Mages, exerce la sorcellerie sans appartenir à une association.","talents":["Dossier préparé — cible","Terrain reconnu — traque"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"pnj-temples-daemoniaques-samira-moghadam","tier":"haute","shape":"social","skills":["Représentation","Séduction","Commerce","Diplomatie"],"anchor":"Ancienne actrice et mannequin Tuatha qui a remplacé son ancienne mentor Annashadeh.","talents":["Expertise éprouvée — Représentation","Réseau mobilisable — scène"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"pnj-temples-daemoniaques-bayarmaa-jin","tier":"heroique","shape":"terrain","skills":["Autorité","Tir","Survie","Investigation"],"anchor":"Vétérane chinoise devenue mercenaire Crawler, commande sept équipes de chasseurs d'anciens soldats nord-coréens.","talents":["Chef de manœuvre — sept équipes","Terrain reconnu — poursuite"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"pnj-temples-daemoniaques-shala-stevens","tier":"haute","shape":"social","skills":["Séduction","Furtivité","Investigation","Perception"],"anchor":"Crawler d'espionnage mondain, s'introduit dans les soirées corporatives et quitte les lieux avant d'être repérée.","talents":["Dossier préparé — cible","Expertise éprouvée — Séduction"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"pnj-temples-daemoniaques-ryushi-ikazuchi","tier":"entraine","shape":"terrain","skills":["Mêlée","Pugilat","Survie","Perception"],"anchor":"Jeune Yakuza de la famille Egawa, longtemps en convalescence et sans exploits établis à ce stade.","talents":["Lutte brève — Pugilat"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"pnj-temples-daemoniaques-eres-kamal","tier":"haute","shape":"social","skills":["Commerce","Diplomatie","Investigation","Perception"],"anchor":"Commerciale d'armes chez Phoenix, négocie avec des clients allant du crime organisé aux chefs d'État.","talents":["Dossier préparé — acheteurs","Expertise éprouvée — Commerce"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"pnj-temples-daemoniaques-shin-xeong","tier":"heroique","shape":"terrain","skills":["Tir","Perception","Survie","Furtivité"],"anchor":"Ancien soldat chinois, Avant-garde de la Triade et tireur d'élite réputé même face aux Ten.","talents":["Expertise éprouvée — Tir","Terrain reconnu — positions"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"pnj-temples-daemoniaques-melindia-sticks","tier":"haute","shape":"esprit","skills":["Soin","Commerce","Investigation","Diplomatie"],"anchor":"Médecin de formation, exerce surtout comme administratrice chez Sunways auprès d'Elodie-Katherine Skotia.","talents":["Expertise éprouvée — Soin","Dossier préparé — administration"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"pnj-temples-daemoniaques-ziyad-alaydin","tier":"haute","shape":"social","skills":["Représentation","Diplomatie","Savoirs","Autorité"],"anchor":"Prêcheur néopaïen et polémiste reconnu, défend publiquement l'autonomie corporelle et la critique des monothéismes.","talents":["Expertise éprouvée — Représentation","Réseau mobilisable — fidèles"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"pnj-temples-daemoniaques-pablo-parejano","tier":"haute","shape":"terrain","skills":["Investigation","Survie","Mêlée","Perception"],"anchor":"Chasseur de l'Église unifiée et membre indépendant de l'ordre d'Arianwen, garde ses méthodes pour lui.","talents":["Dossier préparé — traque","Terrain reconnu — chasse"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"pnj-temples-daemoniaques-navati-rajamalla","tier":"haute","shape":"social","skills":["Représentation","Séduction","Commerce","Diplomatie"],"anchor":"Chanteuse et actrice Tuatha à la voix remarquable, connue pour son exigence de diva.","talents":["Expertise éprouvée — Représentation","Réseau mobilisable — spectacle"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"pnj-temples-daemoniaques-meryl-west","tier":"entraine","shape":"social","skills":["Séduction","Perception","Commerce","Diplomatie"],"anchor":"Travailleuse du sexe australienne essentiellement au service de Todd Larsen, discrète et peu influente.","talents":["Expertise éprouvée — Séduction"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"pnj-temples-daemoniaques-nina-allen","tier":"heroique","shape":"esprit","skills":["Neurodive","Investigation","Mécanique","Esquive"],"anchor":"Neurodiver indépendante parmi les cinq plus redoutées de Californie malgré une formation interrompue.","talents":["Expertise éprouvée — Neurodive","Dossier préparé — intrusion"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-walter-jefferson","tier":"heroique","shape":"esprit","skills":["Commerce","Autorité","Investigation","Diplomatie"],"anchor":"Économiste et administrateur de startups, vice-directeur du CNAD depuis 2034.","talents":["Réseau mobilisable — CNAD","Dossier préparé — administration"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-diana-maellchire","tier":"haute","shape":"social","skills":["Représentation","Savoirs","Diplomatie","Perception"],"anchor":"Prêcheuse de la CyChurch ayant surmonté de graves malformations grâce à la médecine technologique.","talents":["Expertise éprouvée — Représentation","Réseau mobilisable — fidèles"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-sunghyon-kang","tier":"heroique","shape":"terrain","skills":["Autorité","Tir","Survie","Investigation"],"anchor":"Ancien général nord-coréen redouté, dirige clandestinement une insurrection en Californie après 2030.","talents":["Chef de manœuvre — insurgés","Terrain reconnu — opérations"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-soo-kyung-yu","tier":"heroique","shape":"terrain","skills":["Tir","Survie","Athlétisme","Autorité"],"anchor":"Soldate d'élite nord-coréenne et héroïne de guerre, mène des attaques avec une armure de combat.","talents":["Terrain reconnu — assaut","Chef de manœuvre — unité"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-summer-stevenson","tier":"heroique","shape":"esprit","skills":["Savoirs","Investigation","Autorité","Soin"],"anchor":"Directrice des sciences sociales à Caltech, diplômée en astronomie, études comportementales et biochimie.","talents":["Expertise éprouvée — Savoirs","Dossier préparé — recherche"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-nikita-chernov","tier":"haute","shape":"esprit","skills":["Savoirs","Commerce","Investigation","Diplomatie"],"anchor":"Scientifique et homme d'affaires reconnu pour ses innovations et son soutien au PCRC.","talents":["Expertise éprouvée — Savoirs","Dossier préparé — innovation"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-esperanza-martinez","tier":"haute","shape":"social","skills":["Diplomatie","Autorité","Commerce","Investigation"],"anchor":"Émigrée mexicaine engagée pour les travailleurs modestes, devenue maire de San Francisco.","talents":["Réseau mobilisable — mairie","Dossier préparé — politique"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-yae-jin-ryong","tier":"heroique","shape":"terrain","skills":["Autorité","Tir","Survie","Pugilat"],"anchor":"Instructrice et résistante sud-coréenne, devenue une héroïne de guerre nationale comparable aux Ten.","talents":["Chef de manœuvre — résistance","Terrain reconnu — guerre"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-arkinas","tier":"haute","shape":"terrain","skills":["Investigation","Autorité","Tir","Perception"],"anchor":"Apollo Gaines dirige le South Bureau du LAUS et provoque parfois les gangs pour déclencher une riposte.","talents":["Dossier préparé — gangs","Chef de manœuvre — bureau"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-tiana-hawkins","tier":"heroique","shape":"esprit","skills":["Neurodive","Commerce","Autorité","Investigation"],"anchor":"Fondatrice de Monarch Systems, concurrente acharnée d'Arcanetwork dans les applications de l'Holonet.","talents":["Réseau mobilisable — Monarch","Dossier préparé — concurrence"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-kraid","tier":"haute","shape":"terrain","skills":["Tir","Constitution","Survie","Autorité"],"anchor":"Mercenaire Crawler brutal aux armes lourdes, renommé à Los Angeles pour sa force de frappe.","talents":["Terrain reconnu — interventions","Expertise éprouvée — Tir"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-nishikawa-yumia","tier":"heroique","shape":"terrain","skills":["Tir","Survie","Mêlée","Perception"],"anchor":"Ancienne policière japonaise devenue soldate pendant la guerre, membre polyvalente et loyale du Yamaguchi-gumi.","talents":["Terrain reconnu — guerre","Expertise éprouvée — Tir"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-shykrerath","tier":"heroique","shape":"terrain","skills":["Mêlée","Pugilat","Esquive","Perception"],"anchor":"Honoka voyage sans ressources et ne montre qu'une compétence exceptionnelle au combat rapproché.","talents":["Désarmement net — Mêlée","Lutte brève — Pugilat"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-eyteliana-guwundha","tier":"elite","shape":"social","skills":["Commerce","Diplomatie","Investigation","Perception"],"anchor":"Héritière indienne réfugiée en Californie, négocie des paiements de Wellspring contre son patrimoine.","talents":["Dossier préparé — patrimoine","Expertise éprouvée — Commerce"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-meira-zoegell","tier":"heroique","shape":"esprit","skills":["Savoirs","Soin","Investigation","Représentation"],"anchor":"Biologiste allemande spécialisée dans les risques génétiques, nommée à la tête d'une branche sanitaire.","talents":["Expertise éprouvée — Savoirs","Dossier préparé — génome"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-makar-kazlouski","tier":"haute","shape":"terrain","skills":["Mécanique","Tir","Survie","Perception"],"anchor":"Chimiste biélorusse clandestin devenu Crawler redouté peu après son arrivée en Californie.","talents":["Terrain reconnu — clandestinité","Expertise éprouvée — Mécanique"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-kaitlyn-alvin","tier":"heroique","shape":"esprit","skills":["Savoirs","Mécanique","Investigation","Neurodive"],"anchor":"Scientifique canadienne plusieurs fois primée, ancienne captive du programme Écaille rouge puis membre du PCRC.","talents":["Expertise éprouvée — Savoirs","Dossier préparé — armures"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-valerian-gruzinsky","tier":"heroique","shape":"terrain","skills":["Autorité","Survie","Tir","Diplomatie"],"anchor":"Chef insurgé de la coalition opposée à Wellspring pour défendre eau et ressources.","talents":["Chef de manœuvre — coalition","Terrain reconnu — résistance"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-olishia-harmon","tier":"haute","shape":"social","skills":["Commerce","Investigation","Furtivité","Séduction"],"anchor":"Ancienne cambrioleuse devenue Fixer, travaille pour les milieux clandestins de Californie.","talents":["Dossier préparé — mission","Expertise éprouvée — Commerce"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-finn-dixon","tier":"haute","shape":"social","skills":["Commerce","Autorité","Diplomatie","Investigation"],"anchor":"Directeur de compagnie chez Redwheels, enrichi par ses placements et ses contrats de studio.","talents":["Réseau mobilisable — Redwheels","Dossier préparé — contrats"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-ivanna-yevgenievna","tier":"haute","shape":"esprit","skills":["Neurodive","Autorité","Investigation","Tir"],"anchor":"Informaticienne et vétérane russe passée de l'aide au bataillon Arkhangel au rang de Kapitan de la Bratva.","talents":["Dossier préparé — systèmes","Réseau mobilisable — Bratva"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-jorun-bergland","tier":"haute","shape":"esprit","skills":["Investigation","Savoirs","Autorité","Commerce"],"anchor":"Cadre du CNAD recrutée après Byron Corporation pour sa rigueur analytique et son Logifate élevé.","talents":["Dossier préparé — dossiers","Réseau mobilisable — CNAD"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-kaine-reid","tier":"heroique","shape":"terrain","skills":["Tir","Furtivité","Survie","Mêlée"],"anchor":"Mercenaire masqué connu sous Daft Vador, tireur d'élite équipé d'un camouflage optique.","talents":["Terrain reconnu — infiltration","Expertise éprouvée — Tir"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-chesiree-armstrong","tier":"haute","shape":"esprit","skills":["Savoirs","Investigation","Commerce","Diplomatie"],"anchor":"Avocate de la mairie de San Diejuana et conseil personnel de la famille Arellano.","talents":["Dossier préparé — clientèle","Expertise éprouvée — Savoirs"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-shimamura-nobuhito","tier":"heroique","shape":"terrain","skills":["Mêlée","Esquive","Perception","Survie"],"anchor":"Une des sept Lames de Fuyumi, garde du corps et maître sabreur du Yamaguchi-gumi.","talents":["Désarmement net — Mêlée","Terrain reconnu — garde"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-leia-irving","tier":"haute","shape":"esprit","skills":["Commerce","Autorité","Investigation","Diplomatie"],"anchor":"Cadre de Redwheels et bras droit de la directrice de la production Pacifique.","talents":["Réseau mobilisable — Redwheels","Dossier préparé — production"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-donald-griffin","tier":"heroique","shape":"terrain","skills":["Pilotage","Autorité","Survie","Tir"],"anchor":"Colonel de la marine californienne, vétéran de guerre chargé de surveiller les activités des corporations sous-marines.","talents":["Chef de manœuvre — marine","Terrain reconnu — mer"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-emilie-dimont","tier":"haute","shape":"social","skills":["Commerce","Autorité","Représentation","Diplomatie"],"anchor":"Ancien mannequin Tuatha devenue directrice de branche chez Bullmotors et négociatrice impitoyable.","talents":["Réseau mobilisable — Bullmotors","Expertise éprouvée — Commerce"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-adelaide-de-cuvier","tier":"heroique","shape":"esprit","skills":["Savoirs","Perception","Commerce","Diplomatie"],"anchor":"Cuisinière française au service de Svetlana Konstantinovna, peut-être la meilleure de son restaurant après la cheffe et son frère.","talents":["Expertise éprouvée — Savoirs","Dossier préparé — cuisine"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-chin-hyung-joon","tier":"heroique","shape":"esprit","skills":["Neurodive","Furtivité","Investigation","Athlétisme"],"anchor":"Hacker sud-coréen devenu Neurodiver et Neurokiller redouté en 2035, athlétique à force de travail.","talents":["Expertise éprouvée — Neurodive","Dossier préparé — intrusion"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-amandara-barvadekar","tier":"haute","shape":"social","skills":["Commerce","Autorité","Diplomatie","Investigation"],"anchor":"Émigrée indienne âgée et importante financière du groupe armé d'Andrea Shield.","talents":["Réseau mobilisable — insurgés","Expertise éprouvée — Commerce"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-zeelthan","tier":"heroique","shape":"social","skills":["Autorité","Commerce","Survie","Investigation"],"anchor":"Jack Tang dirige la Triade de la Pieuvre d'encre et a survécu à de nombreuses tentatives d'assassinat grâce à ses augmentations.","talents":["Réseau mobilisable — Triade","Dossier préparé — sécurité"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-opalia-sanders","tier":"heroique","shape":"esprit","skills":["Savoirs","Soin","Investigation","Autorité"],"anchor":"Généticienne majeure de Biosun puis membre d'Eversor, ancienne scientifique du PCRC.","talents":["Expertise éprouvée — Savoirs","Dossier préparé — génétique"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
  {"id":"personnages-verite-extraterrestres-ariana-douglas","tier":"haute","shape":"social","skills":["Représentation","Autorité","Commerce","Diplomatie"],"anchor":"Primat discrète de la CyChurch, gère un grand centre de transformation corporelle en partenariat avec Byron.","talents":["Réseau mobilisable — CyChurch","Expertise éprouvée — Représentation"],"truth":"La Vérité et les capacités révélées restent distinctes de ce profil de Réalité."},
];

export function applyPnjStatBatch09(byId:Map<string,Article>):void {
  if(PROFILES.length!==50||new Set(PROFILES.map(p=>p.id)).size!==50)throw new Error("PNJ · lot 09 incomplet ou dupliqué");
  for(const profile of PROFILES){
    const article=byId.get(profile.id);
    if(!article)throw new Error(`PNJ · fiche active introuvable : ${profile.id}`);
    applyNamedPnjStatProfile(article,profile);
  }
}
