import { applyNamedPnjStatProfile, type StatProfile } from "./compendium-pnj-corporate-stats.js";

type Article={id:string;dataset?:string;sections?:Array<Record<string,any>>;[key:string]:any};
type Entry=StatProfile & {id:string};

// Rôles civils examinés dans chacune des cinquante biographies, sans statistiques vampiriques indues.
const PROFILES:Entry[]=[
  {"id":"personnages-verite-vampires-p08-scott-ruthven","tier":"haute","shape":"terrain","skills":["Autorité","Tir","Survie","Commerce"],"anchor":"Dirige une cellule criminelle écossaise indépendante, homme d'action impétueux souvent en conflit avec Deaman Mac Eadha.","talents":["Chef de manœuvre — cellule","Terrain reconnu — milieu criminel"],"truth":"Sa nature vampirique est réservée au dossier MJ."},
  {"id":"personnages-verite-vampires-p08-jonas-myer","tier":"haute","shape":"social","skills":["Commerce","Autorité","Investigation","Diplomatie"],"anchor":"Dirige Yellow-Revo-Meat, branche viande de Yellowfood, utilise intimidation et malversations pour sa production.","talents":["Réseau mobilisable — Yellowfood","Dossier préparé — approvisionnement"],"truth":"La Vérité de sa cour ne découle pas de sa fonction corporative."},
  {"id":"personnages-verite-vampires-p09-sieg-kent","tier":"haute","shape":"social","skills":["Séduction","Autorité","Commerce","Pugilat"],"anchor":"Bras droit de Beryx au Pinksun, supervise les Crawlers recrutés pour séduction et prostitution, avec un physique puissant.","talents":["Réseau mobilisable — Pinksun","Expertise éprouvée — Séduction"],"truth":"La séduction vampirique est distincte de ses compétences civiles."},
  {"id":"personnages-verite-vampires-p09-carmilla-stein","tier":"haute","shape":"terrain","skills":["Tir","Survie","Furtivité","Perception"],"anchor":"Mercenaire Crawler indépendante, fréquente les cliniques Karnstein et apprend auprès de Lisbeth Brunn.","talents":["Terrain reconnu — missions","Expertise éprouvée — Tir"],"truth":"Sa Chasse et son ascendance restent MJ."},
  {"id":"personnages-verite-vampires-p12-youssef-hareef","tier":"haute","shape":"social","skills":["Diplomatie","Commerce","Autorité","Survie"],"anchor":"Mafieux français aux études et affaires réussies, fait sécession après la soumission de sa patronne et se rapproche de l'insurrection.","talents":["Réseau mobilisable — dissidents","Chef de manœuvre — cellule"],"truth":"Ne déduire aucun pouvoir vampire de sa réussite sociale."},
  {"id":"personnages-verite-vampires-p13-sarah-kellington","tier":"haute","shape":"social","skills":["Autorité","Commerce","Investigation","Diplomatie"],"anchor":"Dirige l'administration des chaînes Nextar, en conflit avec Gabriella Austin et la vedette Lys.","talents":["Réseau mobilisable — Nextar","Dossier préparé — grilles"],"truth":"Son appartenance à la cour est MJ."},
  {"id":"personnages-verite-vampires-p13-nayshya-greer","tier":"haute","shape":"social","skills":["Autorité","Séduction","Investigation","Commerce"],"anchor":"Cadre violente de réseaux de prostitution, protégée par les Crips et associée à Todd Larsen.","talents":["Réseau mobilisable — Crips","Dossier préparé — rivales"],"truth":"La prédation réelle de son dossier MJ reste distincte de son réseau criminel."},
  {"id":"personnages-verite-vampires-p14-engracia-montes","tier":"heroique","shape":"terrain","skills":["Furtivité","Tir","Esquive","Investigation"],"anchor":"Assassine Black Scorpio de la Blanchisserie, agile et obsédée par la mort de ses fils au Mexique.","talents":["Dossier préparé — cible","Décrochage préparé — retrait"],"truth":"Son passé possible chez Los Antrax demeure une rumeur et sa Vérité ne détermine pas ses rangs civils."},
  {"id":"personnages-verite-vampires-p14-nadia-el-saabi","tier":"haute","shape":"social","skills":["Commerce","Représentation","Autorité","Diplomatie"],"anchor":"Actrice égyptienne reconvertie après un échec californien, a acquis le casino Luxor en deux ans.","talents":["Réseau mobilisable — Luxor","Expertise éprouvée — Commerce"],"truth":"Sa nature de Vérité est au dossier MJ."},
  {"id":"personnages-verite-vampires-p15-annashadeh-shariati","tier":"haute","shape":"social","skills":["Représentation","Séduction","Commerce","Diplomatie"],"anchor":"Ancienne mannequin internationale, devenue égérie puis salariée d'Eversor après le déclin de sa notoriété.","talents":["Expertise éprouvée — Représentation","Réseau mobilisable — mode"],"truth":"Aucune séduction surnaturelle attribuée par son métier."},
  {"id":"personnages-verite-vampires-p16-hassan-el-shadir","tier":"heroique","shape":"esprit","skills":["Commerce","Autorité","Investigation","Savoirs"],"anchor":"Préside Undertakers Incorporated et coordonne pompes funèbres, assurances, soins palliatifs et autres métiers de la mort.","talents":["Réseau mobilisable — Undertakers","Chef de manœuvre — holdings"],"truth":"Pouvoirs de la cour réservés au MJ."},
  {"id":"personnages-verite-vampires-p16-muntir-ashab","tier":"haute","shape":"terrain","skills":["Tir","Survie","Mécanique","Perception"],"anchor":"Ancien résistant irakien et mercenaire contre les forces coréennes, chez Black Crow, passionné de technologie.","talents":["Terrain reconnu — opérations","Expertise éprouvée — Tir"],"truth":"Sa Vérité n'est pas déduite de sa carrière mercenaire."},
  {"id":"personnages-verite-vampires-p17-lockart-feunos","tier":"elite","shape":"social","skills":["Commerce","Investigation","Perception","Diplomatie"],"anchor":"Milliardaire sans profession déclarée, vit reclus près de San Diejuana avec un personnel renouvelé fréquemment.","talents":["Dossier préparé — propriété","Expertise éprouvée — Commerce"],"truth":"Santé apparente et personnel restent des indices, aucune immortalité chiffrée civile."},
  {"id":"personnages-verite-vampires-p21-xicolas-morillo","tier":"haute","shape":"terrain","skills":["Autorité","Tir","Investigation","Pugilat"],"anchor":"Chef des Red Reapers, violent mais rusé derrière une allure démente, formé autrefois parmi les Grim Reapers.","talents":["Chef de manœuvre — Red Reapers","Dossier préparé — rival"],"truth":"Aucun bonus surnaturel de sa cour n'est chiffré dans le profil de gang."},
  {"id":"personnages-verite-vampires-p21-tonya-magrina","tier":"heroique","shape":"terrain","skills":["Pugilat","Esquive","Athlétisme","Perception"],"anchor":"Combattante UMA vedette de Sunways, affronte les autres champions après entraînement et augmentations biologiques.","talents":["Lutte brève — Pugilat","Désarmement net — Pugilat"],"truth":"Ses augmentations exigent inventaire et coûts, sa Vérité requiert un profil distinct."},
  {"id":"personnages-verite-vampires-p22-alfredo-necahual","tier":"haute","shape":"esprit","skills":["Soin","Savoirs","Investigation","Diplomatie"],"anchor":"Médecin dévoué formé à Las Vegas, travaille sous Keysha Richards et déteste les corporations de la santé.","talents":["Expertise éprouvée — Soin","Dossier préparé — patient"],"truth":"Les secrets de sa cour ne modifient pas sa médecine civile."},
  {"id":"personnages-verite-vampires-p22-xavio-nabarez","tier":"haute","shape":"terrain","skills":["Pilotage","Autorité","Tir","Survie"],"anchor":"Motard Blackcoatl réfugié en Californie, participe aux guerres contre Hell Angels et Cruisers.","talents":["Chef de manœuvre — Blackcoatl","Terrain reconnu — routes"],"truth":"Sa nature vampirique est MJ."},
  {"id":"personnages-verite-vampires-p23-xephia-mila-de-la-vega","tier":"haute","shape":"social","skills":["Représentation","Autorité","Savoirs","Investigation"],"anchor":"Grande prêtresse néopaïenne aztèque, organise les dons de sang rituels et est recherchée au Mexique sous une autre identité.","talents":["Réseau mobilisable — cultes","Dossier préparé — cérémonie"],"truth":"Les pouvoirs de sa cour et son identité mexicaine sont au dossier MJ."},
  {"id":"personnages-verite-vampires-p23-consuela-miralles","tier":"elite","shape":"social","skills":["Séduction","Investigation","Commerce","Perception"],"anchor":"Prostituée et informatrice du cartel au White Jungle, épargne pour ouvrir son bar malgré de multiples emplois.","talents":["Dossier préparé — renseignements","Expertise éprouvée — Séduction"],"truth":"Aucun pouvoir vampirique inféré de sa présence dans le cartel."},
  {"id":"personnages-verite-vampires-p24-river-barns","tier":"entraine","shape":"social","skills":["Représentation","Commerce","Diplomatie","Perception"],"anchor":"Jeune Neopunk dont la performance en bus blindé à travers la Décharge a fait circuler le nom.","talents":["Expertise éprouvée — Représentation"],"truth":"Sa Vérité et l'escorte payée ne constituent pas une formation militaire."},
  {"id":"personnages-verite-vampires-p24-daniella-gotz-daniel-goethe","tier":"elite","shape":"social","skills":["Savoirs","Diplomatie","Perception","Investigation"],"anchor":"Ancienne nonne des Saintes Lagunes, utilise publiquement aussi l'identité Daniel Goethe.","talents":["Expertise éprouvée — Savoirs","Dossier préparé — archives"],"truth":"Les deux identités civiles sont connues ; les secrets de Vérité restent MJ."},
  {"id":"personnages-verite-vampires-p25-saheeda-al-sahli","tier":"elite","shape":"esprit","skills":["Commerce","Investigation","Diplomatie","Autorité"],"anchor":"Cadre de Night Hotels de 22 ans, entretient les liens Shinoda et résiste aux pressions d'Eversor.","talents":["Dossier préparé — partenariats","Expertise éprouvée — Commerce"],"truth":"Répugne à la violence ; ne pas la classer combattante par son seul dossier vampirique."},
  {"id":"personnages-verite-vampires-p29-tamytrice-bishop-knowles","tier":"haute","shape":"social","skills":["Séduction","Investigation","Commerce","Autorité"],"anchor":"Belle-mère de la famille Knowles, diplômée, exerce une influence indirecte sur certains cadres d'Aces.","talents":["Dossier préparé — liens Knowles","Réseau mobilisable — Aces"],"truth":"Les manipulations imputées à Kadeena restent une hypothèse."},
  {"id":"personnages-verite-vampires-p29-morris-yama","tier":"elite","shape":"terrain","skills":["Tir","Survie","Perception","Athlétisme"],"anchor":"Mercenaire taciturne des quartiers abandonnés, accepte les missions à condition de travailler avec des Afro-Américains.","talents":["Terrain reconnu — quartiers","Expertise éprouvée — Tir"],"truth":"Son dossier MJ peut préciser ses contrats, sans capacité vampirique automatique."},
  {"id":"personnages-verite-vampires-p30-maarina-ogaufi","tier":"haute","shape":"social","skills":["Représentation","Autorité","Séduction","Tir"],"anchor":"Chanteuse et danseuse d'Omegacoustic, dirige Blood of Love ; soupçonnée d'avoir éliminé des rivales.","talents":["Réseau mobilisable — Omegacoustic","Expertise éprouvée — Représentation"],"truth":"Les meurtres restent soupçonnés, le port d'armes déclaré n'implique pas un tir de maître."},
  {"id":"personnages-verite-vampires-p30-laureen-clayton","tier":"haute","shape":"esprit","skills":["Investigation","Autorité","Diplomatie","Savoirs"],"anchor":"Commissaire de l'influence corporative, consigne les tentatives de corruption pour agir avec le CSCO.","talents":["Dossier préparé — corruption","Réseau mobilisable — Commission"],"truth":"Nature vampirique et statut de cour restent MJ."},
  {"id":"personnages-verite-vampires-p31-kanika-onyesha","tier":"haute","shape":"esprit","skills":["Mécanique","Savoirs","Tir","Investigation"],"anchor":"Ingénieure kényane en robotique, appelée à exploiter des brevets de guerre, possède aussi une couverture de combat en Californie.","talents":["Expertise éprouvée — Mécanique","Dossier préparé — robotique"],"truth":"Sa couverture auprès des Crawlers et sa nature réelle se lisent au dossier MJ."},
  {"id":"personnages-verite-vampires-p31-eliott-lock","tier":"haute","shape":"social","skills":["Commerce","Investigation","Diplomatie","Savoirs"],"anchor":"Milliardaire d'origine modeste dont la fortune et les liens sud-africains sont inconnus et soumis à enquête CBII.","talents":["Dossier préparé — investissements","Expertise éprouvée — Commerce"],"truth":"Aucun réseau mafieux confirmé : ne pas ajouter de talent de cette organisation."},
  {"id":"personnages-verite-vampires-p32-tykeim-thornton","tier":"elite","shape":"terrain","skills":["Tir","Survie","Athlétisme","Perception"],"anchor":"Ex-soldat US sans exploit notable, mercenaire fiable en solo mais conflictuel et traumatisé en équipe.","talents":["Terrain reconnu — opérations","Expertise éprouvée — Tir"],"truth":"Ses blessures psychologiques ne sont pas des bonus, sa Vérité reste MJ."},
  {"id":"personnages-verite-vampires-p32-napoleon-kukabango","tier":"heroique","shape":"terrain","skills":["Autorité","Tir","Survie","Investigation"],"anchor":"Ancien colonel camerounais puis légionnaire chez Tortoise, sait inspirer des unités avec peu de moyens.","talents":["Chef de manœuvre — détachement","Terrain reconnu — campagne"],"truth":"Le surnom de seigneur de guerre n'atteste aucun pouvoir surnaturel."},
  {"id":"personnages-verite-vampires-p33-alfonse-n-vigenza","tier":"heroique","shape":"esprit","skills":["Neurodive","Investigation","Perception","Furtivité"],"anchor":"Neurodiver Yellion décrit comme exceptionnel sur l'Holonet mais lâche sur le terrain.","talents":["Expertise éprouvée — Neurodive","Lecture des failles — sécurité"],"truth":"Les propriétés de sa Vérité et ses possessions demeurent MJ."},
  {"id":"personnages-verite-vampires-p36-zhao-xinzo","tier":"haute","shape":"social","skills":["Commerce","Autorité","Investigation","Diplomatie"],"anchor":"Fixer traditionaliste aisé mais sélectif, rémunère bien ses équipes sans travailler avec Yakuza ni Triades.","talents":["Réseau mobilisable — fixers","Dossier préparé — mission"],"truth":"Son exclusion volontaire de plusieurs communautés limite son réseau."},
  {"id":"personnages-verite-vampires-p37-rim-do-yeon","tier":"haute","shape":"esprit","skills":["Neurodive","Langages & Argot","Investigation","Perception"],"anchor":"Neurodiver coréen réputé, parle coréen, chinois et japonais après avoir grandi parmi les réfugiés de Los Angeles.","talents":["Expertise éprouvée — Neurodive","Expertise éprouvée — Langages & Argot"],"truth":"Son activité nocturne ne confirme aucune capacité occulte publique."},
  {"id":"personnages-verite-vampires-p37-ouji-nojiro","tier":"haute","shape":"terrain","skills":["Autorité","Tir","Survie","Perception"],"anchor":"Officier de Tortoise Security, ancien officier japonais et bras droit de la Sécurité urbaine, porte une armure Raven personnalisée.","talents":["Chef de manœuvre — sécurité","Terrain reconnu — opérations"],"truth":"L'armure existe comme équipement, ses valeurs doivent venir de sa fiche d'objet."},
  {"id":"personnages-verite-vampires-p38-an-nhat-khuong","tier":"haute","shape":"social","skills":["Savoirs","Diplomatie","Langages & Argot","Représentation"],"anchor":"Religieux shientaoïste vietnamien érudit, influent en Asie et parlant les langues de la région, pacifiste.","talents":["Expertise éprouvée — Savoirs","Réseau mobilisable — shientaoïsme"],"truth":"Son exil californien face aux autorités du culte reste officieux."},
  {"id":"personnages-verite-vampires-p38-maya-binti-ishak","tier":"haute","shape":"esprit","skills":["Investigation","Perception","Diplomatie","Tir"],"anchor":"A étudié et rejoint le CBII après la guerre et la recherche de ses frères disparus.","talents":["Dossier préparé — disparition","Lecture des failles — enquête"],"truth":"Sa nationalisation californienne n'est pas une preuve de capacité militaire."},
  {"id":"personnages-verite-vampires-p39-rinnah-sinubulan","tier":"haute","shape":"social","skills":["Commerce","Autorité","Investigation","Diplomatie"],"anchor":"Présidente d'Urban Technoboost chez Byron, recherche aussi le frisson au contact des criminels.","talents":["Réseau mobilisable — Byron","Chef de manœuvre — division"],"truth":"Fréquenter des Crawlers violents ne lui donne pas leurs compétences de combat."},
  {"id":"personnages-verite-vampires-p40-chettur-jagatap","tier":"haute","shape":"esprit","skills":["Savoirs","Investigation","Commerce","Diplomatie"],"anchor":"Juge californien travaillant parfois pour des corporations et soupçonné de pots-de-vin par Farah.","talents":["Dossier préparé — jurisprudence","Expertise éprouvée — Savoirs"],"truth":"La corruption reste à prouver publiquement, aucun réseau policier attribué."},
  {"id":"personnages-verite-vampires-p40-alberto-randall-mutya-bristol","tier":"haute","shape":"esprit","skills":["Investigation","Perception","Langages & Argot","Diplomatie"],"anchor":"Ancien mafieux philippin devenu détective privé en Californie pour rechercher son épouse enlevée.","talents":["Dossier préparé — enquête","Lecture des failles — filature"],"truth":"Ses contacts issus de sa recherche ne garantissent aucun soutien instantané."},
  {"id":"personnages-verite-vampires-p41-chigusa-sawako","tier":"haute","shape":"social","skills":["Autorité","Commerce","Investigation","Diplomatie"],"anchor":"Ancienne policière japonaise, dirige l'association de services Chigu et ouvre des accès aux quartiers asiatiques.","talents":["Réseau mobilisable — Chigu","Dossier préparé — quartier"],"truth":"Son passé policier n'accorde aucune autorité actuelle sur la police."},
  {"id":"personnages-verite-vampires-p41-kaeo-sriwarunyu","tier":"entraine","shape":"social","skills":["Commerce","Représentation","Perception","Diplomatie"],"anchor":"Serveuse thaïlandaise du Pinksun souvent présente dans les bars ; ses études inachevées et son réseau informel restent modestes.","talents":["Expertise éprouvée — Commerce"],"truth":"Connaitre beaucoup de fêtards n'en fait pas une cheffe de réseau."},
  {"id":"personnages-verite-vampires-p43-anna-skoheim","tier":"entraine","shape":"social","skills":["Perception","Diplomatie","Survie","Commerce"],"anchor":"Aucune profession ni activité publique connue, seulement des apparitions en ville ; profil civil volontairement prudent.","talents":["Expertise éprouvée — Perception"],"truth":"Arbitrage : insuffisance de biographie pour prétendre à des compétences spécialisées."},
  {"id":"personnages-verite-vampires-p44-thammara-jones","tier":"elite","shape":"terrain","skills":["Furtivité","Perception","Tir","Survie"],"anchor":"Assassine taciturne et peu documentée, se présente comme afro-américaine alors qu'elle est d'origine aborigène.","talents":["Terrain reconnu — traque","Expertise éprouvée — Furtivité"],"truth":"Son origine véritable doit rester dans son dossier MJ si elle est protégée."},
  {"id":"personnages-verite-vampires-p46-ruggero-bottini","tier":"elite","shape":"social","skills":["Autorité","Commerce","Investigation","Pugilat"],"anchor":"Petit chef Bottini qui se donne des airs de parrain, brutal mais sa famille pèse peu en Californie.","talents":["Réseau mobilisable — Bottini","Dossier préparé — racket"],"truth":"Kazimyr Botti est son ancien nom connu dans le dossier civil."},
  {"id":"personnages-verite-vampires-p47-sinthia-wendy","tier":"haute","shape":"social","skills":["Représentation","Savoirs","Commerce","Diplomatie"],"anchor":"Présentatrice d'émissions artistiques, devenue ultrariche par ses placements et travaillant par plaisir.","talents":["Expertise éprouvée — Représentation","Réseau mobilisable — médias"],"truth":"Sa richesse ne prouve aucune capacité martiale."},
  {"id":"personnages-verite-vampires-p47-beryx-draghici","tier":"haute","shape":"social","skills":["Commerce","Autorité","Séduction","Investigation"],"anchor":"Ancien gérant d'un réseau criminel roumain, a cédé son activité à Drasko pour tenir un bar sous sa protection.","talents":["Réseau mobilisable — bar","Dossier préparé — réseau"],"truth":"Les anciennes ressources cédées ne sont plus automatiquement disponibles."},
  {"id":"personnages-verite-vampires-p48-saama","tier":"entraine","shape":"terrain","skills":["Survie","Tir","Perception","Investigation"],"anchor":"Mercenaire Crawler cynique et paresseuse dont le dossier public ne décrit aucune opération remarquable.","talents":["Terrain reconnu — quartiers"],"truth":"Arbitrage de spécialité : le métier seul ne justifie pas un grade élite."},
  {"id":"personnages-verite-vampires-p45-dwayne-white","tier":"heroique","shape":"terrain","skills":["Furtivité","Pugilat","Langages & Argot","Perception"],"anchor":"Assassin professionnel discret, polyglotte sans accent et invaincu dans les épreuves de force rapportées.","talents":["Lutte brève — Pugilat","Terrain reconnu — infiltration"],"truth":"Sa force exceptionnelle reste attestée sans présumer sa forme vampirique."},
  {"id":"personnages-verite-extrals-groupes-shanandra-fear","tier":"entraine","shape":"social","skills":["Commerce","Diplomatie","Investigation","Perception"],"anchor":"Fixer new-yorkaise rarement active en Californie, sans autres capacités civiles décrites.","talents":["Dossier préparé — contrat"],"truth":"Réseau new-yorkais à documenter avant de l'attribuer comme talent."},
  {"id":"personnages-verite-extrals-groupes-karl-moonger","tier":"haute","shape":"terrain","skills":["Autorité","Survie","Soin","Athlétisme"],"anchor":"Chef expérimenté des pompiers de Los Angeles, collabore avec la police et porte une armure TFA en intervention.","talents":["Chef de manœuvre — pompiers","Terrain reconnu — incendies"],"truth":"L'armure TFA est un équipement à chiffrer depuis son objet, pas un trait inné."},
];

export function applyPnjStatBatch07(byId:Map<string,Article>):void {
  if(PROFILES.length!==50||new Set(PROFILES.map(p=>p.id)).size!==50)throw new Error("PNJ · lot 07 incomplet ou dupliqué");
  for(const profile of PROFILES){
    const article=byId.get(profile.id);
    if(!article)throw new Error(`PNJ · fiche active introuvable : ${profile.id}`);
    applyNamedPnjStatProfile(article,profile);
  }
}
