// Chaque ligne de cette sélection est une décision éditoriale sur un dossier MJ
// identifié, et non une déduction automatique de la Nature ou du métier public.
// Les rangs listés sont les compétences saillantes ; les autres conservent le
// profil de Réalité, sauf décision individuelle. Les achats génériques MJ
// sont chiffrés séparément des Dons et Rites canoniques.
type Block = {type:'p';text:string}|{type:'table';rows:string[][]};
import {standaloneTruthSecondary} from './compendium-pnj-truth-standalone.js';
export type TruthBatchArticle = {id:string;title?:string;sections?:Array<{id?:string;title?:string;level?:number;audience?:string;blocks?:Block[]}>;[key:string]:any};
export type TruthDecision = readonly [id:string, attributes:readonly [number,number,number,number,number], skills:readonly (readonly [string,number])[], evidence:string, limit:string];
type Article = TruthBatchArticle;
type Decision = TruthDecision;
const choices:Decision[] = [
  ['pnj-pegre-milda-tarasknovna',[10,9,10,11,10],[['Force Mentale',17],['Autorité',16],['Mêlée',15]],'Selaphielle, ancienne Archange du devoir, rivalisait avec Michel ; son incarnation est consentie et Milda conserve souvent le contrôle de son corps.','Talent signature : Devoir partagé — 1/scène, 1 PA, Selaphielle peut guider une décision ou une défense de Milda ; aucune prise de contrôle automatique contre sa volonté.'],
  ['pnj-police-casey-vaughn',[6,8,11,10,10],[['Savoirs',16],['Furtivité',15],['Représentation',13]],'Celeasa est une elfe de plusieurs siècles, magicienne autrefois, devenue pirate informatique et maîtresse des identités masquées.','Sa grande affinité magique ne signifie pas que ses sorts délaissés soient immédiatement disponibles.'],
  ['pnj-gouvernement-diego-alejandro-lasa',[9,8,8,9,8],[['Autorité',14],['Survie',12],['Pugilat',12]],'Ce meneur des pelages roux dirige encore la meute formée dans sa jeunesse, a appris à maîtriser ses instincts, mais conserve une dépendance aux drogues.','Sa dépendance reste une contrainte en scène ; la meute agit selon ses moyens propres.'],
  ['pnj-crawlers-docx-jacob-delisle',[7,8,7,8,10],[['Diplomatie',14],['Autorité',13],['Perception',11]],'Jacob s’est éveillé sans famille garou, a bâti une meute influente par son charme et évite le combat.','Sa Vérité privilégie les liens de clan ; ne pas lui attribuer la brutalité d’un alpha guerrier.'],
  ['pnj-crawlers-docx-josefin-drescher',[8,8,7,9,8],[['Autorité',13],['Survie',12],['Pugilat',11]],'Josefin a reconstitué sa meute à Los Angeles en y faisant venir progressivement son ancien clan européen.','Sa haine des pelages blancs est un parti pris tactique et une source de conflit.'],
  ['pnj-crawlers-docx-hailey-powell',[11,10,8,10,6],[['Constitution',16],['Tir',14],['Pugilat',14]],'Hailey, survivante du projet Phoenix, supporte des augmentations qui ont brisé les autres cobayes ; ses essais et sa Chasse sont documentés.','Puissance cybernétique de son corps réel : ne pas inventer des Dons surnaturels ni ignorer son logifate dégradé.'],
  ['pnj-crawlers-docx-dragoslav-memic',[5,7,13,8,7],[['Investigation',16],['Savoirs',15],['Esquive',13]],'Son cerveau artificiel calcule de nombreuses simulations d’une parole ou d’un geste avant l’action.','Les simulations demandent des données d’entrée ; une inconnue réelle peut les déjouer.'],
  ['pnj-crawlers-docx-aisha-white',[8,8,11,10,9],[['Force Mentale',16],['Perception',14],['Savoirs',13]],'Aisha est l’homoncule presque parfaite de Faust, conçue comme un piège à magie, pouvoirs et âmes, puis émancipée.','Talent signature : Réceptacle d’Aisha — sur contact effectif d’une magie hostile, 1/scène, elle peut en retenir la trace pour enquête ; aucune absorption ou réémission chiffrée sans règle vérifiée.'],
  ['pnj-crawlers-docx-leslie-wright',[6,7,14,11,8],[['Savoirs',19],['Investigation',17],['Mécanique',16]],'Leslie porte l’Attribut divin du Génie et le Mageius de Merlin ; elle n’est pas la réincarnation de Myrddin, qui demeure distinct.','Talent signature : Génie appliqué — 1/scène après étude effective, poser au MJ une question sur un mécanisme observable ; pas de connaissance automatique du secret ni de toute magie de Merlin.'],
  ['pnj-crawlers-docx-ogshaata-otto',[9,10,8,11,7],[['Survie',16],['Mêlée',15],['Tir',14]],'Ogshaata communique avec les esprits et alterne tir, hache et Okichitaw ; son corps porte de nombreuses marques de pactes.','Chaque pacte requiert son esprit et ses conditions propres ; ne pas convertir les marques en pouvoirs gratuits.'],
  ['pnj-crawlers-antisysteme-p6-max-sharp',[8,8,10,11,10],[['Autorité',16],['Diplomatie',15],['Force Mentale',14]],'Max est Focalor, ancien Robespierre et duc récent de Baal, défenseur de l’égalité des mortels et indépendant des autres Daemons.','Talent signature : Refus du joug — 1/scène, 1 PA, donner +2 à une résistance contre une intimidation qu’il a identifiée ; la dignité ne rend pas invulnérable.'],
  ['pnj-crawlers-antisysteme-p15-jane-costa',[9,8,8,9,8],[['Autorité',14],['Pugilat',13],['Survie',12]],'Jane dirige une meute sans pitié et collabore avec Faust contre la famine blanche et les autres afflictions garoues.','Son partenariat de recherche ne lui donne pas la magie de Faust.'],
  ['pnj-crawlers-antisysteme-p18-sahamena-lannis',[7,9,9,9,9],[['Survie',15],['Autorité',14],['Furtivité',14]],'Sahamena, elfe sylvaine des Lanyth, représente les siens au conseil tout en menant des actions de guérilla environnementale.','Sa rivalité avec Alayna et sa priorité aux elfes limitent ses alliances.'],
  ['pnj-crawlers-antisysteme-p35-ameena-al-gad',[9,10,8,10,7],[['Furtivité',16],['Mêlée',15],['Perception',13]],'Ghurab est une Corneille de Morrighan et Observatrice, chargée d’arrêter Hashem si Vaanesh lui échappe.','Talent signature : Vigie de Vaanesh — après observation personnelle, 1/scène, relever un signe de perte de contrôle ; ne neutralise pas le Deimon sans action et opposition.'],
  ['pnj-crawlers-antisysteme-p39-angelino-molina',[11,10,8,11,8],[['Mêlée',17],['Pugilat',16],['Survie',15]],'Apollyon, frère de Dragoy mort en l’affrontant, est devenu le duc destructeur de Mammon et traque les vampires.','Talent signature : Chasseur de l’abîme — 1/scène, 1 PA, cibler un vampire identifié : +2 à une attaque dirigée contre lui ; son passé ne supprime aucune défense.'],
  ['pnj-crawlers-antisysteme-p56-mary-shanasti',[9,9,11,10,9],[['Force Mentale',17],['Savoirs',15],['Autorité',14]],'Mary, fille d’Alabor et ancienne duchesse d’Amunghol, provoque la pluie sous la colère et peut ôter temporairement des pouvoirs aux Daemons de sa mère.','Talent signature : Orage d’Alabor — 1/scène, 1 PA, perturber pendant un tour un pouvoir d’un Daemon lié à sa mère après opposition de Force Mentale ; aucune appropriation permanente.'],
  ['pnj-crawlers-antisysteme-p58-diana-buck',[11,8,7,10,7],[['Pugilat',16],['Constitution',15],['Autorité',14]],'Diana protège son village et maîtrise le sang enragé, au point de pousser les siens vers l’éveil dans sa rage.','Talent signature : Rage du clan — 1/scène, 1 PA, un allié garou consentant à portée reçoit +2 sur un test de résistance ; aucun éveil forcé automatique.'],
  ['pnj-crawlers-antisysteme-p60-nana-nandoa',[10,9,9,10,9],[['Autorité',16],['Pugilat',15],['Force Mentale',14]],'Skenandoa, fille aînée de Quetzalcoatl, revendique une puissance comparable à Megda ou Dragoy et impose une épreuve meurtrière pour entrer dans sa maison.','Cette comparaison est son estimation personnelle ; ses achats de Sang restent inconnus.'],
  ['pnj-crawlers-antisysteme-p64-jane-moreno',[12,9,8,9,8],[['Pugilat',16],['Autorité',15],['Perception',13]],'Cette dragonne jaune indépendante a repris la direction des Faucons malachite et protège possessivement sa faction.','Sa forme draconique et ses dimensions se règlent selon les règles de Dragon ; ses alliés ne sont pas un équipement instantané.'],
  ['pnj-crawlers-antisysteme-p64-jayceon-osborn',[7,9,9,9,8],[['Furtivité',14],['Survie',13],['Force Mentale',13]],'Jacyr Oceriol porte la marque de la chaîne de V’aagor qu’il libéra il y a trois siècles après une manipulation de Frildec.','Le nom civil est Jayceon ; le dossier inverse parfois ces noms. La marque est une contrainte, non un Don confirmé.'],
  ['pnj-crawlers-antisysteme-p70-ulfric-tamer',[13,10,9,11,8],[['Pugilat',18],['Constitution',17],['Mêlée',16]],'Rulfam, dernier dragon fléau de sa lignée, a tué Siegfried et dirige Lostown tout en composant avec ses factions.','Talent signature : Terreur de Lostown — 1/scène, 1 PA, forcer une opposition de Force Mentale à une cible qui le voit se révéler ; pas de contrôle général du quartier.'],
  ['pnj-corporations-kadeena-jackson',[9,8,9,10,10],[['Autorité',16],['Pugilat',14],['Diplomatie',13]],'Kealaboga est la seule Makoko de l’Oru Ayeraye, dirige Grootslang et soutient les défis des rivaux de sa maison.','Sa descendance de Sulwana et son lien ancien avec Nayshya ne donnent aucun arbre de Sang gratuit.'],
  ['pnj-corporations-lenavah-uriel',[8,8,11,11,8],[['Savoirs',16],['Force Mentale',16],['Soin',14]],'Levanah a survécu à l’arrachement de sa part sorcière, fait ouvrir son arbre de vie et poursuit ses missions de chasseuse Sephirienne.','La perte de sa sorcellerie est effective ; les Sephiroth obtenues et leurs coûts doivent être vérifiés avant usage.'],
  ['pnj-corporations-stephania-volkov',[9,8,8,11,9],[['Mêlée',16],['Force Mentale',15],['Autorité',14]],'Stephania, ancienne sorcière dépouillée de son essence, est devenue cheffe de l’ordre de Longinus et porte la sainte Lance.','La Lance est un objet unique effectivement porté ; sa puissance n’est pas un Don inné de Stephania.'],
  ['pnj-041-gawel-prowacjesky',[11,8,8,9,9],[['Autorité',16],['Mêlée',15],['Pugilat',14]],'Gaar’Kha dirige le Syndicat de Jade, traque ses rivaux orques sous une couverture médiatique de bouffon et favorise les siens dans les forces publiques.','Talent signature : Ordre de horde — 1/scène, 1 PA, un allié du Syndicat présent gagne +2 sur une action coordonnée ; pas de renfort sans délai.'],
  ['pnj-043-keegan-foster',[13,10,10,11,9],[['Perception',18],['Pugilat',17],['Force Mentale',15]],'Kaargan est un dragon ancien du clan noir qui voit à travers l’Hologramme et sert loyalement Dina Page parce qu’elle a éveillé sa curiosité.','Talent signature : Regard de Kaargan — 1/scène, 1 PA, identifier une illusion qu’il observe réellement ; voir la tromperie ne permet pas de connaître son auteur.'],
  ['pnj-118-rosalinda-maldonado',[7,9,9,9,8],[['Furtivité',14],['Tir',13],['Investigation',12]],'Ro’Zal dissimule sa nature Mo’senne au sein de réseaux criminels et élimine parfois d’autres non humains pour protéger sa couverture.','Ses choix d’infiltration n’établissent pas une supériorité surnaturelle universelle.'],
  ['pnj-132-sylvia-rose',[6,8,10,9,10],[['Diplomatie',14],['Force Mentale',13],['Furtivité',12]],'Selravae connaît une petite magie paternelle capable d’effacer la mémoire à court terme, qu’elle a utilisée pour masquer des rencontres.','Talent signature : Souvenir effacé — 1/scène, 1 PA, cibler un souvenir immédiat après contact et opposition de Force Mentale ; ne réécrit pas toute une histoire personnelle.'],
  ['pnj-134-abigael-sky',[12,11,11,12,10],[['Force Mentale',19],['Pugilat',17],['Autorité',16]],'Abigor est une ancienne divinité des tempêtes qui rivalisa de puissance avec Belial et dont les avatars célestes sont multiples.','Talent signature : Orage d’Abigor — 1/scène, 1 PA, concentrer une manifestation climatique sur une zone visible ; ses dégâts exacts relèvent des pouvoirs élémentaires acquis, et un avatar vaincu ne tue pas la déesse.'],
  ['pnj-140-benedicte-vilhelmsen',[10,9,9,11,9],[['Autorité',17],['Pugilat',16],['Survie',15]],'Thorunn dirige les pelages blancs avec une mémoire de meneuse remontant au Xe siècle et l’héritage plus ancien des ulfhednars.','Talent signature : Mémoire de Thorunn — 1/scène, 1 PA, rappeler un précédent que sa lignée a effectivement connu ; mémoire héritée ne signifie pas omniscience.'],
  ['pnj-143-dana-obryan',[8,9,13,11,9],[['Savoirs',19],['Force Mentale',18],['Investigation',16]],'Daghain MELDEGRYN est une Mage ancienne qui participa à la guerre de la Magie et imagine des catastrophes visant des êtres inhumains.','Talent signature : Catastrophe préparée — 1/scénario, après préparation et accès aux moyens réels, établir un phénomène local à résoudre avec les règles de magie ; aucun séisme instantané gratuit.'],
  ['pnj-146-gabrielle-power',[9,9,12,12,11],[['Force Mentale',19],['Savoirs',18],['Soin',16]],'Gabriel, aussi ancienne qu’Elynea, a étudié la magie protectrice de Nathral et fut l’une de ses premières alliées.','Talent signature : Égide de Gabriel — 1/scène, 1 PA, +2 à une défense occulte d’un allié présent ; les grands miracles exigent les rites effectivement maîtrisés.'],
  ['pnj-154-nathan-prince',[11,10,12,12,12],[['Autorité',19],['Force Mentale',18],['Diplomatie',17]],'Nathan est un avatar volontairement inférieur à la puissance de Satan, ancien dieu des serments, de la justice et de l’équilibre.','Talent signature : Serment pesé — 1/scène après un engagement librement entendu, +2 à une opposition liée à sa violation ; l’avatar ne possède pas tous les pouvoirs du dieu.'],
  ['pnj-161-zabeel-albel',[11,10,12,12,11],[['Soin',19],['Survie',18],['Savoirs',17]],'Belzébuth fut une grande divinité de la chasse, de la santé et des animaux, mais l’énergie corrompue absorbée contre les Fléaux a blessé son être.','Talent signature : Vie blessée — 1/scène, 1 PA, diagnostiquer une corruption organique qu’il peut examiner ; aucune guérison universelle ni immunité à sa propre atteinte.'],
  ['pnj-131-shiloh-floyd',[11,8,8,10,8],[['Pugilat',16],['Autorité',15],['Constitution',14]],'Shi’log est un orc puissant et loyal, ancien militaire chassé par une querelle clanique, devenu capitaine dans la police.','Son honneur de clan peut créer un duel, mais son rang de policier ne lui donne pas une troupe immédiate.'],
  ['pnj-006-belyandra-queen',[13,11,14,14,13],[['Force Mentale',21],['Autorité',20],['Savoirs',20]],'Belial a vaincu des Fléaux majeurs, fondé l’essor des Mages et affronté les Titans ; la fiche publique de Belyandra ne mesure pas sa puissance divine.','Talent signature : Scellement de Belial — effet de scénario nécessitant préparation, cible et confrontation ; ne se déclenche pas librement en une action. Un avatar local reste distinct de la déesse.'],
  ['pnj-011-kareen-botha',[11,10,9,10,10],[['Commerce',17],['Pugilat',16],['Diplomatie',15]],'Jaryn est une dragonne de quelques siècles dont la recherche obstinée de richesse motive ses contrats avec des factions très diverses.','Talent signature : Contrat de Jaryn — 1/scène après accord explicite, +2 à une négociation sur une récompense matérielle ; ses trésors ne se téléportent pas.'],
  ['pnj-019-ramaesh-talavalakr',[8,8,12,10,10],[['Savoirs',18],['Mécanique',16],['Diplomatie',14]],'Gnurruda coordonne le SMRC, ses recherches de fusion génétique et des transferts illégaux d’espèces ; il porte un Holojamer.','Le Holojamer limite sa révélation tant qu’il est actif ; les créatures issues du SMRC demandent leur propre fiche.'],
  ['pnj-090-leona-elliott',[10,10,12,12,11],[['Furtivité',19],['Force Mentale',18],['Autorité',17]],'Li’loth sert secrètement Shaoggith depuis longtemps et trompe la T-ra’queen sous l’apparence de sa fidèle servante.','Talent signature : Masque de Li’loth — 1/scène, après échange réel, +2 à une tentative de dissimulation de sa loyauté ; pas de lecture des pensées.'],
  ['pnj-108-asheylinn-medira',[8,9,14,12,11],[['Représentation',19],['Force Mentale',19],['Autorité',16]],'Assy’Medira Fel, impératrice sérysse déchue de Vahan’fel, possède une voix capable de déchirer l’espace et d’ouvrir l’espace N ; ses pouvoirs psychiques ont provoqué sa captivité.','Talent signature : Voix de l’espace N — effet de scénario après manifestation et résistance appropriée, susceptible de déplacer un vaisseau ; jamais un dégât sonore ordinaire ni un portail libre et sans conséquence.'],
  ['pnj-109-atticus-sharp',[9,9,9,9,8],[['Athlétisme',15],['Survie',14],['Savoirs',13]],'Atticus, Thalsios né sur Terre, s’entraîne quotidiennement à la condition physique, à la survie et à l’étude pour atteindre un idéal de perfection.','Sa solitude et ses échecs relationnels demeurent ; entraînement varié ne veut pas dire maîtrise de tout.'],
  ['pnj-113-malcolm-moss-mammoth',[8,7,12,10,10],[['Savoirs',17],['Force Mentale',15],['Diplomatie',14]],'Ma’mo, Mo’sen peu athlétique et peu belliqueux, possède une intelligence et un sang froid remarquables.','Sa Vérité renforce sa pensée et son calme ; sa Nature ne lui impose pas le profil de brute.'],
  ['pnj-114-maximilian-marshall',[13,11,14,15,13],[['Force Mentale',21],['Savoirs',20],['Autorité',19]],'Maximilian est Shen’ryl, Stellaire et Éon ancien qui a absorbé l’essence de mondes divins ; il a vaincu Morrighan autrefois, bien qu’elle l’ait scellé. Son serviteur An’Rvey et le faux Heinrich sont des êtres distincts.','Talent signature : Présence stellaire — effet de scénario préparé sous arbitrage MJ ; sur Terre il réprime presque tous ses pouvoirs pour ne pas déranger les dieux locaux. Le corps visible ne suffit pas à mesurer son essence.'],
  ['pnj-116-rached-kelley',[13,8,11,10,7],[['Force Mentale',17],['Pugilat',16],['Savoirs',15]],'Raysh, clone génétiquement modifié de Jrash’kan’Feeshri, possède des pouvoirs psychiques et un corps rocréen presque haut de trois mètres.','Talent signature : Pression de Raysh — 1/scène, 1 PA, opposition de Force Mentale sur une cible visible pour la distraire un tour ; pas de domination permanente.'],
  ['pnj-117-renaldi-rezzini',[8,8,11,10,11],[['Autorité',17],['Commerce',16],['Investigation',15]],'Roalsh’issh dirigeait la mafia rocréenne de l’Ouest et articulait trafics galactiques et couverture criminelle italienne.','Ses réseaux sont soumis à disponibilité, loyauté et délais, surtout depuis le recul de ses affaires de Réalité.'],
  ['pnj-121-zoran-kozic',[7,8,11,10,8],[['Perception',17],['Force Mentale',15],['Savoirs',14]],'Zoran est un Talass’nioek aux yeux sensibles aux énergies mentales et magiques ; l’Hologramme lui a coûté la vue en arrivant sur Terre.','Sa sensibilité ne rend pas sa vue ordinaire : préciser les moyens effectivement employés pour percevoir une scène.'],
  ['pnj-127-martin-green',[6,9,9,9,9],[['Diplomatie',14],['Esquive',13],['Savoirs',12]],'Marr, gobelin de Gaerras rejeté par les gobelins locaux, cherche obstinément une vie humaine ordinaire.','Sa révélation n’en fait ni chef gobelin ni guerrier surnaturel.'],
  ['pnj-130-russell-vinderbeck',[8,8,10,9,11],[['Autorité',17],['Commerce',16],['Diplomatie',15]],'Russell revendique la lignée royale Belentrin et dispute à Roberrick sa place au conseil des Anciens.','L’ascendance familiale offre une revendication politique, pas une autorité acceptée par tous.'],
  ['pnj-135-alexander-zazelov',[10,9,12,11,9],[['Mécanique',19],['Savoirs',17],['Mêlée',15]],'Azazel était un forgeron et prêtre de Kanorarn parmi les plus remarquables archanges d’Aèr.','Talent signature : Forge d’Azazel — après un atelier, des matériaux et une scène de travail, +2 à une fabrication précise ; aucun arsenal instantané.'],
  ['pnj-145-ephraim-bahal',[13,11,11,12,11],[['Mêlée',19],['Autorité',18],['Savoirs',17]],'Baal est un ancien dieu de la guerre, de la tactique et de la victoire ; la disparition de son Enfer ne supprime pas ses partisans ni sa compétence martiale.','Talent signature : Victoire préparée — 1/scène après observation du terrain, +2 à une manœuvre alliée ; les commandants et les troupes doivent être présents.'],
  ['pnj-148-kai-gehrman',[7,8,13,11,9],[['Savoirs',18],['Force Mentale',17],['Investigation',15]],'Le Mage Saint Germain pratique la chronomancie, mais ses pairs ont marqué ses bras afin d’interdire les voyages physiques dans le passé et le futur.','Talent signature : Écho temporel — 1/scène, 1 PA, revoir un détail de la scène perçu personnellement ; les tatouages restent une interdiction effective de voyage.'],
  ['pnj-149-kane-riley',[11,11,10,12,10],[['Force Mentale',18],['Mêlée',17],['Autorité',16]],'Remiel fut un archange majeur des tempêtes, guerrier élémentaire réputé, rival de Michael et opposant d’Abigor.','Talent signature : Front de Remiel — 1/scène, 1 PA, imposer +2 de difficulté à un déplacement dans une zone proche par le vent ; sa déchéance demeure.'],
  ['pnj-152-kyriakos-zenos',[9,9,12,12,10],[['Survie',18],['Savoirs',17],['Autorité',16]],'Kyriak, noble atlante survivant du naufrage, refusa la stase et organisa durant des siècles des voyages vers Mû.','Talent signature : Route de Kyriak — après reconnaissance réelle, 1/scénario, réduire d’un cran un obstacle de navigation pour son groupe ; pas de trajet magique gratuit.'],
  ['pnj-153-mickael-krieg',[13,11,10,13,10],[['Mêlée',20],['Pugilat',18],['Force Mentale',17]],'Michael est le paladin exceptionnel chargé de protéger Elynea ; il s’est entraîné avec acharnement après les affronts des dieux de la Terre.','Talent signature : Rempart de Michael — 1/scène, 1 PA, intercepter une attaque visant un allié adjacent et résoudre la défense normalement ; il peut être blessé.'],
  ['pnj-156-ralph-zeiner',[9,9,13,12,10],[['Soin',19],['Savoirs',18],['Force Mentale',17]],'Raphael était un prêtre d’Astia, devenu archange de la guérison et adversaire de Belzébuth et Mammon.','Talent signature : Diagnostic de Raphael — 1/scène, 1 PA après examen, identifier une affection corporelle observable et +2 au prochain Soin approprié ; ne ressuscite pas.'],
  ['pnj-162-zebediah-jacobsen',[8,9,13,12,9],[['Savoirs',18],['Force Mentale',17],['Diplomatie',15]],'Hadaïah enseigna en Perse, voyagea après la chute de Megiddo et rassembla des Mages errants tout en rédigeant des lois pour eux.','Talent signature : Loi de Hadaïah — 1/scène après consultation d’une règle de loge connue, +2 pour plaider son interprétation ; n’oblige pas une loge étrangère.'],
  ['pnj-119-sonny-dawson',[7,8,12,10,8],[['Mécanique',16],['Savoirs',15],['Investigation',14]],'So’aul, technicien talass affecté au PCRC, découvrit la fraude de Lyamina et survécut à sa tentative de meurtre grâce à sa nature.','Sa protection par la mafia rocréenne est une ressource contingente ; il ne connaît pas automatiquement tous les projets de Lyamina.'],
  ['pnj-120-yvan-abscisse',[9,8,11,10,8],[['Savoirs',16],['Constitution',15],['Investigation',13]],'Ce Grey composite entretient des organes de plusieurs espèces et peut recombiner son organisme ; le dossier signale des capacités variables.','Ses organes et talents actifs doivent être consignés pour chaque scène : aucune liste illimitée de capacités simultanées.'],
  ['pnj-133-grim-grigoria-ravinsky',[12,9,8,11,8],[['Mêlée',18],['Pugilat',17],['Survie',15]],'Greem’Sha fut formée au combat par Ashorn puis s’émancipa et chassa les cultistes des Fléaux malgré son origine corrompue.','Talent signature : Traque des cultes — 1/scène, après découverte d’un signe véritable, +2 à une piste de Survie ou Investigation ; son ascendance fléau reste ambiguë.'],
  ['pnj-139-barret-kelvin',[8,8,11,12,9],[['Investigation',17],['Force Mentale',17],['Furtivité',15]],'Barret est Barachiel, Ange transcendé en archange majeur, Observateur et chasseur ; les versions de son passé divergent mais décrivent toutes une essence usée et un âge réel visible.','Talent signature : Bonté de Barachiel — 1/scène, 1 PA, +2 à la défense d’un allié présent qu’il protège personnellement ; son vieillissement et ses ressources limitées restent effectifs.'],
  ['pnj-141-chamunda-dhavale',[11,9,9,12,8],[['Pugilat',17],['Force Mentale',16],['Survie',15]],'Chamunda a appris jeune la sorcellerie du clan des pelages d’or et chasse les barghests pour obtenir des effets d’ombre.','Talent signature : Crocs de barghest — 1/scène seulement si un barghest effectivement asservi est présent, +2 à une attaque de mêlée ; pas de magie innée universelle.'],
  ['pnj-147-john-sandrock',[11,9,9,10,9],[['Autorité',17],['Pugilat',16],['Tir',14]],'John s’est imposé comme Alpha puis meneur des pelages roux en combinant soumission des meutes et armes anti-augmentés.','Son accession par des méthodes contestées fragilise la loyauté du clan et ne lui assure aucune obéissance automatique.'],
  ['pnj-151-kaydence-o-dalaigh',[10,10,10,11,8],[['Force Mentale',17],['Perception',15],['Mêlée',14]],'Camaelle est une archange de la foudre créée par Sil’Elaith, entraînée à transcender sa puissance face à Remiel et Abigor.','Talent signature : Pointe de foudre — 1/scène, 1 PA, désigner une cible visible pour +2 à un usage électrique effectivement acquis ; pas de pouvoir nouveau gratuit.'],
  ['pnj-religions-ciara-mcfarlane',[9,10,10,11,8],[['Survie',17],['Mêlée',16],['Perception',16]],'Ciara et l’esprit corbeau Naalnish ont mené la Chasse ; elle rejoignit Hunt15 pour vaincre Vargrunda et retrouver la lance de Brunehilde.','Talent signature : Éclaireur Naalnish — 1/scène, après envoi de l’esprit, un renseignement qu’il peut observer ; l’esprit doit pouvoir revenir et communiquer.'],
  ['pnj-110-dai-zhenya',[10,8,10,10,10],[['Autorité',17],['Tir',15],['Savoirs',14]],'Zai’ny commande des cellules de la SA et cherche des conflits où employer des armes à effets climatiques ; ses brûlures sont dissimulées par une armure.','Ses cellules et les armes climatiques demandent acheminement et préparation ; l’armure ne guérit pas ses brûlures.'],
  ['pnj-111-derek-stevenson-raptor',[11,10,8,10,8],[['Pugilat',17],['Survie',16],['Tir',14]],'Kor’rek est un Mo’sen né sur Mars, présent sur Terre depuis deux siècles et habitué aux pillages et à la survie hors des autorités.','Sa longévité explique l’expérience mais ne le rend pas discipliné ni maître de réseaux institutionnels.'],
  ['pnj-112-isidoro-berganza-le-vieux',[9,8,12,11,8],[['Mécanique',19],['Savoirs',17],['Constitution',14]],'Bwargan, Thalsios massif retraité des stations spatiales, possède une longue pratique de réparation et d’optimisation.','Talent signature : Réparation du vieux — après outils et pièces disponibles, 1/scène, +2 à une réparation mécanique précise ; aucun appareil ne revient sans matériau.'],
  ['pnj-115-myra-allan',[6,8,12,10,9],[['Mécanique',16],['Savoirs',16],['Autorité',13]],'Myra est une Humalsiosse dirigeant fonctionnellement l’YDYL malgré l’IA ; sa seule capacité physique talass documentée est l’apnée.','Aucune forme aquatique ni puissance physique talass complète ; son commandement dépend des systèmes de l’YDYL.'],
  ['pnj-122-steeve-golden-hood',[12,8,8,10,7],[['Pugilat',17],['Tir',15],['Constitution',15]],'Steeve est un chasseur baséanh de deux mètres cinquante, toujours vêtu d’une armure atypique et connu pour neutraliser des augmentés.','Ses protections viennent de l’armure portée ; sans identification des composants, ne pas fixer une RD ou un arsenal imaginaire.'],
  ['pnj-124-ciliren-faelen-flamy',[8,10,8,9,10],[['Furtivité',16],['Survie',15],['Représentation',14]],'Ciliren est un jeune elfe citadin et anarchiste qui a conservé la ténacité et les méthodes de guérilla de ses ancêtres sylvains.','La contestation et la liberté sexuelle ne constituent pas des dons magiques.'],
  ['pnj-125-daldea-fann',[9,10,10,10,8],[['Furtivité',17],['Perception',16],['Mêlée',15]],'Daldea, survivante elfe noire du duché de Dalphair, a appris la méfiance, la mobilité et parfois la trahison de ses protecteurs.','Sa paranoïa limite son aptitude à compter durablement sur une troupe.'],
  ['pnj-137-arielle-nova',[10,10,11,12,10],[['Force Mentale',18],['Savoirs',16],['Esquive',15]],'Urielle est un phénix d’Aèr transcendé par Elynea en archange de lumière plutôt qu’une ange née telle.','Talent signature : Lumière d’Urielle — 1/scène, 1 PA, éclairer une zone proche et révéler une obscurité ordinaire ; renaissance ou feu sacré exigent un pouvoir confirmé.'],
  ['pnj-158-sikya-hawkins',[11,10,9,12,10],[['Autorité',18],['Pugilat',17],['Survie',16]],'Sikya a hérité de Talatuwa en dévorant sa grand-mère ; Grande Meneuse des pelages sombres, elle porte les mémoires de ses prédécesseurs, mais Tokala l’a récemment vaincue et épargnée.','Talent signature : Mémoire de Talatuwa — 1/scène, 1 PA, invoquer une expérience attestée d’une ancienne Meneuse pour +2 à un test approprié ; sa défaite par Tokala et les loyautés de son clan restent en vigueur.'],
  ['personnages-verite-fantastiques-tobias-dorner',[10,10,12,12,11],[['Autorité',18],['Savoirs',17],['Mêlée',17]],'Cet elfe gris millénaire, surnommé roi des aulnes, a servi comme soldat, politicien et magicien pendant la guerre de la Magie.','Talent signature : Conseil du roi des aulnes — 1/scène, 1 PA, +2 à une négociation entre communautés qu’il connaît ; le titre de roi n’impose aucune sujétion universelle.'],
  ['personnages-verite-extraterrestres-walter-jefferson',[6,8,11,10,11],[['Diplomatie',17],['Autorité',15],['Savoirs',14]],'Wal, Talass non violent, siège au GAAC et s’expose volontairement à des rayons pour vieillir comme ses proches humains.','Sa non violence et sa fragilité volontaire modèrent l’écart de puissance ; ses sièges politiques ne fournissent pas un pouvoir psychique.'],
  ['personnages-verite-angelus-adriana-bienvenida',[9,9,11,12,10],[['Force Mentale',17],['Perception',15],['Savoirs',14]],'Purim, Séraphine de Remiel, manie vents et foudre et accable les âmes de leurs erreurs ; une aile de domination lui a été retirée.','Talent signature : Poids de la faute — 1/scène, 1 PA, sur une cible consciente d’une faute identifiée, opposition de Force Mentale pour imposer −2 à sa prochaine action ; pas d’arrachage d’âme automatique.'],
  ['personnages-verite-extraterrestres-diana-maellchire',[5,7,12,10,10],[['Savoirs',17],['Mécanique',16],['Diplomatie',14]],'Din est une Talass frêle, sans augmentation dans la Vérité, connue pour son engagement technologique au CTU et son admiration pour Leslie.','Sa promotion de la technique n’implique ni arme intégrée ni résistance physique supplémentaire.'],
  ['personnages-verite-humains-galactiques-lisa-eredhes',[10,10,11,12,10],[['Autorité',18],['Tir',17],['Savoirs',16]],'Lisa, seigneur général de la 783e armée de l’AIDH, a gagné de nombreuses campagnes et porte la perte de l’armée de sa sœur d’arme.','Talent signature : Ordre anticipé — 1/scène, 1 PA, après observation d’un ennemi, +2 à une manœuvre d’un soldat allié présent ; pas d’armée appelée instantanément.'],
  ['personnages-verite-humains-galactiques-alladava-kjoll',[7,8,13,11,9],[['Savoirs',18],['Investigation',17],['Autorité',15]],'Alladava a affiné le Test Ackèld et recruté Lisa, malgré l’échec de sa propre ambition de devenir seigneur général.','Talent signature : Critère Ackèld — après évaluation concrète, 1/scène, +2 pour repérer une aptitude déjà démontrée ; pas de prédiction infaillible.'],
  ['personnages-verite-especes-elizabeth-mircalla-karnstein',[8,9,10,11,11],[['Diplomatie',18],['Furtivité',17],['Autorité',16]],'Mircalla Karnstein, fille de Sang d’Hécate et concubine de Dragoy, fonda sa maison et maîtrise les intrigues de la cour vampirique ; elle recherche sa fille Carmilla.','Talent signature : Sang masqué de Mircalla — 1/scène, 1 PA, +2 à une dissimulation dont le masque est réellement préparé ; les effets du Sang Masqué restent ceux des achats vérifiés.'],
  ['personnages-verite-extraterrestres-sunghyon-kang',[11,10,11,10,8],[['Tir',17],['Mécanique',16],['Pugilat',15]],'Saoden est un Talass de plus de cinq siècles, muté et augmenté sous exosquelette au sein de l’Émeraude sanglante.','Talent signature : Exosquelette de Saoden — 1/scène, 1 PA, +2 à une poussée physique avec l’exosquelette opérationnel ; sans armure, résoudre son corps séparément.'],
  ['pnj-aseryns-terres-temples-leder-caendis-02',[9,10,11,11,10],[['Survie',17],['Mêlée',16],['Autorité',15]],'Leder, duc corsaire de Valatar depuis avant le naufrage atlante, a parcouru les mers d’Aèr et de Terre et reste fidèle à Kalira.','Le rang de Survie porte sur la navigation maritime ; sa revendication de filiation avec Laera est incertaine.'],
  ['personnages-verite-pelages-migina-evans',[9,9,8,9,9],[['Autorité',15],['Pugilat',14],['Survie',13]],'Migina mène les Neige Pattes, sert Thorunn et réagit violemment au manque de respect envers son clan.','Sa couleur de pelage n’est qu’une variation génétique et ne donne pas de pouvoirs blancs supplémentaires.'],
  ['personnages-verite-angelus-zivko-voronov',[10,9,11,12,9],[['Force Mentale',18],['Diplomatie',16],['Perception',15]],'Ce Séraphin de Remiel a perdu une aile et manipule la culpabilité de ses victimes avec l’eau, la pluie, la grêle et la foudre.','Talent signature : Pesanteur de Zivko — 1/scène, 1 PA, une cible sous pression psychologique subit après opposition de Force Mentale −2 à son prochain déplacement ; il doit la percevoir.'],
  ['pnj-aseryns-terres-temples-inigo-andreas-03',[8,8,13,11,9],[['Savoirs',18],['Force Mentale',17],['Investigation',15]],'Inigo, jeune duc formé à la tour élémentaire, a survécu à une contamination de Thul qu’il maintient contenue par magie.','Talent signature : Confinement d’Inigo — 1/scène, 1 PA, +2 à sa résistance contre la corruption qui le marque ; la plaie cachée demeure un risque.'],
  ['personnages-verite-humains-galactiques-james-zero',[10,8,13,11,7],[['Savoirs',18],['Mécanique',17],['Force Mentale',15]],'James est un CBT0 conscient construit à partir de débris et du corps mécanique de Thor’lal, auxiliaire de l’AIDH.','Sa magitech archaïque ne lui confère ni les ordres de Thor’lal ni l’allégeance des CBT2.'],
  ['personnages-verite-vampires-p05-lana-loss',[9,9,10,11,11],[['Diplomatie',17],['Force Mentale',16],['Mêlée',14]],'Thanew Lodainn est une semi corbeau et concubine ancienne de Dragoy, devenue vampire après les intrigues de la Table ronde.','Son sang Khinae et sa filiation avec Bodb demandent leurs règles distinctes : pas de cumul automatique des deux lignées.'],
  ['personnages-verite-extraterrestres-soo-kyung-yu',[11,11,10,10,8],[['Tir',17],['Pugilat',16],['Furtivité',15]],'So’ouk, Talass artificielle renforcée d’ADN humain et Ad’rak, fut conçue pour combattre mais sait infiltrer et négocier.','Talent signature : Initiative de So’ouk — 1/scène après une entrée volontaire en captivité, +2 à une tentative d’évasion préparée ; sa capture reste réelle.'],
  ['personnages-verite-pelages-tsvetomir-nickolov',[10,9,8,10,9],[['Autorité',16],['Survie',15],['Pugilat',14]],'Tsvetomir mène un clan sibérien en Alaska, mais un grand Alpha s’est imposé pendant son éloignement.','Son autorité n’est pas absolue : l’Alpha rival agit pour son propre compte.'],
  ['personnages-verite-vampires-p05-bellanessa-lorenzo',[8,9,10,10,11],[['Diplomatie',17],['Furtivité',16],['Autorité',14]],'Bianca Lancia d’Agliano, concubine de Dragoy et femme de Frédéric II, a survécu à sa claustration en feignant sa mort après vampirisation.','Les sorts utilisés pour supporter le soleil demandent dépense et préparation ; ils ne deviennent pas une immunité passive.'],
  ['personnages-verite-pelages-frederic-jackelston-jackal',[10,9,8,10,9],[['Autorité',16],['Tir',15],['Survie',14]],'Jackal dirige une branche de transport d’Eversor et garde des bikers de sa meute, mais subit des défis pour son rôle de meneur.','Ses véhicules, cargos et anciens compagnons doivent être effectivement mobilisés ; sa loyauté envers Thorunn s’est nuancée.'],
  ['pnj-aseryns-terres-temples-kyleane-natyel-04',[9,9,11,12,10],[['Furtivité',17],['Autorité',16],['Mêlée',15]],'Kyleane est revenue du Temple après la disparition des Natyel et a reconquis le duché de Shael par des assassinats ciblés.','Talent signature : Retour de Kyleane — 1/scénario après infiltration préparée, +2 à une action contre un usurpateur identifié ; n’efface pas ses anciens ennemis.'],
  ['personnages-verite-humains-galactiques-lance-goldstar',[11,10,9,11,8],[['Tir',18],['Pugilat',17],['Survie',15]],'Lance est un vétéran d’élite loyal à Lisa, infecté par un fragment d’artefact cosmique après la destruction de son escouade.','L’infection est un danger et un objet d’étude ; ne pas la convertir sans source en pouvoir maîtrisé.'],
  ['personnages-verite-fantastiques-ielynnoesi-alianmar',[9,9,12,12,10],[['Soin',18],['Force Mentale',17],['Autorité',16]],'Cette prêtresse elfe de Denilia rallia les exilés à Elynea puis fut transcendée pour poursuivre son œuvre.','Son ascension ne fournit pas automatiquement la gamme complète des pouvoirs des archanges majeurs.'],
  ['personnages-verite-humains-galactiques-chris-sunborne',[10,9,10,11,9],[['Tir',16],['Investigation',15],['Autorité',14]],'Chris, officier de contrôle des émigrés extrals, conserve sa carrière militaire malgré l’attachement vulnérable à sa famille terrienne.','La protection de sa famille peut modifier ses décisions ; son statut AIDH ne signifie pas accès illimité aux troupes.'],
  ['personnages-verite-vampires-p06-evelin-bogdan',[8,8,12,11,11],[['Diplomatie',18],['Autorité',17],['Investigation',16]],'Erzsébeth Báthory fut transformée en 1614 et se décrit comme victime d’une machination ; le dossier privilégie son génie politique dans la paix entre maisons.','Les accusations anciennes et sa version divergent : ne pas transformer les bains de sang contestés en pouvoir canonique.'],
  ['personnages-verite-extrals-groupes-shanandra-fear',[8,8,9,9,8],[['Diplomatie',12],['Perception',11],['Survie',10]],'Shram, Mo’sen née parmi des communautés mixtes, rejette le communautarisme du REPTILE sans preuve suffisante pour le condamner officiellement.','Son absence de preuve limite son action ; pas de puissance supplémentaire déduite de son ethnie.'],
  ['personnages-verite-extraterrestres-summer-stevenson',[6,8,13,10,9],[['Savoirs',18],['Mécanique',17],['Investigation',15]],'Su’Er, scientifique talass du CTU, proposa l’usage de nanites alimentaires pour modifier l’ADN humain à travers YellowFood.','Talent signature : Protocole Su’Er — après accès à un laboratoire et échantillon, 1/scénario, +2 à l’analyse d’une modification génétique ; pas de nanites apparaissant sans chaîne logistique.'],
];

export const REVIEWED_TRUTH_BATCH_001_IDS = choices.map(choice=>choice[0]);

export function applyPnjTruthDecisions(byId:Map<string,Article>, decisions:readonly Decision[]):void {
  for(const [id, values, skills, evidence, limit] of decisions){
    const article=byId.get(id);
    if(!article?.sections)throw new Error(`Fiche Vérité introuvable : ${id}`);
    const reality=article.sections.find(section=>section.id==='profil-statistique');
    if(!reality||reality.audience!=='mj')throw new Error(`Profil MJ de Réalité introuvable : ${id}`);
    const rows=[['Attribut révélé','Vigueur','Agilité','Esprit','Volonté','Charisme'],['Valeur proposée',...values.map(String)]];
    const hasRealityNumbers=Boolean(reality.blocks?.some(block=>block.type==='table'&&block.rows[0]?.[0]==='Attribut'));
    const secondary=hasRealityNumbers?undefined:standaloneTruthSecondary(id);
    if(!hasRealityNumbers&&!secondary&&id!=='personnages-verite-humains-galactiques-karina-kelack')
      throw new Error(`Compétences complémentaires de Vérité absentes : ${id}`);
    if(secondary&&new Set([...skills,...secondary].map(([name])=>name)).size!==skills.length+secondary.length)
      throw new Error(`Compétence de Vérité doublonnée : ${id}`);
    const allSkills=[...skills,...(secondary??[])];
    const blocks:Block[]=[
      {type:'p',text:`Vérité · ${article.title??id}. ${evidence} Ces caractéristiques révélées sont une estimation MJ propre à cette fiche. ${hasRealityNumbers?'Le profil de Réalité décrit le corps Voilé et ne constitue pas un plafond de puissance.':'Aucun corps Voilé chiffré n’est établi par la source.'}`},
      {type:'table',rows},
      {type:'table',rows:[['Compétence de Vérité saillante','Rang proposé'],...allSkills.map(([name,rank])=>[name,String(rank)]),...(secondary?[['Autres compétences canoniques (14)','0']]:[])]},
      {type:'p',text:`${limit} ${hasRealityNumbers?'Les autres compétences conservent leurs rangs chiffrés de Réalité pour cet état, sauf différence établie sur cette fiche.':'Les compétences non spécialisées sont à 0 dans cette estimation de scène ; le dossier de Réalité ne fournit aucun rang civil.'} Les talents de Vérité achetés par ce PNJ et leur dépense PTV figurent dans le tableau de sa fiche. Les valeurs révélées sont déjà finales pour cet état : ne pas y ajouter une seconde fois les bonus de Nature.`}
    ];
    if(hasRealityNumbers){
      const civilSkills=reality.blocks?.find(block=>block.type==='table'&&/^(Compétence|Compétences)$/.test(block.rows[0]?.[0]??''));
      if(!civilSkills||civilSkills.type!=='table')throw new Error(`Compétences de Réalité non exploitables : ${id}`);
      const rank=(name:string):number=>{
        const individual=skills.find(([skill])=>skill===name);
        if(individual)return individual[1];
        const row=civilSkills.rows.slice(1).find(([labels])=>labels.split(',').some(label=>label.trim()===name));
        return row?Number(row[1].match(/^\d+/)?.[0]??0):0;
      };
      const [vig,agi,,vol]=values;
      const con=rank('Constitution'),esq=rank('Esquive'),ath=rank('Athlétisme'),fm=rank('Force Mentale');
      blocks.splice(3,0,{type:'table',rows:[['Valeur dérivée','Résultat · état Révélé proposé, sans équipement'],
        ['PV maximum / Seuil de Mort',`${2*vig+con} / −${vig+con}`],
        ['Défense physique passive / active',`${agi+esq} / ${agi+esq} + 1d10e`],
        ['Défense occulte passive / active',`${vol+fm} / ${vol+fm} + 1d10e`],
        ['Initiative / déplacement',`${agi+ath} + 1d10e / ${5+ath} m par PA`]]});
    }
    if(secondary){
      const rank=(name:string)=>allSkills.find(([skill])=>skill===name)?.[1]??0;
      const [vig,agi,,vol]=values;
      const variableBody=/^(personnages-verite-especes-(?:lombre-pape|mloxol-vaagor|vhodhalnactru|gajh-shaoggith|cthath-vhadhi)|personnages-verite-extraterrestres-(?:rsheraag|dsherraneth|peste-des-vases)|pnj-(?:088-cthulhu|fleaux-|091-lidira)|personnages-verite-vampires-p(?:46-adinhazu|48-kragen-aagor)|personnages-verite-extrals-groupes-(?:elleth-dyx|zirine-fa-meonn))/.test(id);
      if(!variableBody){
        const con=rank('Constitution'),esq=rank('Esquive'),ath=rank('Athlétisme'),fm=rank('Force Mentale');
        blocks.splice(3,0,{type:'table',rows:[['Valeur dérivée','Résultat · corps révélé proposé, sans équipement'],
          ['PV maximum / Seuil de Mort',`${2*vig+con} / −${vig+con}`],
          ['Défense physique passive / active',`${agi+esq} / ${agi+esq} + 1d10e`],
          ['Défense occulte passive / active',`${vol+fm} / ${vol+fm} + 1d10e`],
          ['Initiative / déplacement',`${agi+ath} + 1d10e / ${5+ath} m par PA`]]});
      }else blocks.push({type:'p',text:'Corps, équipement ou manifestation variables : les PV et défenses se calculent à partir de l’incarnation effectivement rencontrée. Les attributs et compétences ci-dessus servent de repères MJ, sans attribuer une forme physique permanente.'});
    }
    article.sections.splice(article.sections.indexOf(reality),0,{
      id:`profil-verite-${id}`,title:`Profil de Vérité · ${article.title??id}`,level:2,audience:'mj',blocks
    });
  }
}
export function applyPnjTruthBatch001(byId:Map<string,Article>):void {
  applyPnjTruthDecisions(byId,choices);
}
