import { applyNamedPnjStatProfile, type StatProfile } from "./compendium-pnj-corporate-stats.js";
import { consolidateReligiousRealityCard } from "./compendium-pnj-civil-stats-04.js";

type Article={id:string;dataset?:string;sections?:Array<Record<string,any>>;[key:string]:any};
type Entry=StatProfile & {id:string};

// Identités et compétences examinées individuellement ; les capacités de Vérité demandent leur propre profil.
const PROFILES:Entry[]=[
  {"id":"pnj-religions-chretiente-luciana-saltarelli","tier":"haute","shape":"terrain","skills":["Mêlée","Esquive","Survie","Perception"],"anchor":"Sœur Lucia privilégie le corps à corps et les armes blanches dans ses missions religieuses, formée par Sœur Maria.","talents":["Désarmement net — Mêlée","Terrain reconnu — mission"],"truth":"Sa formation de chasseuse et les secrets de l'ordre sont dans le dossier MJ."},
  {"id":"pnj-religions-chretiente-nazarena-montenegro","tier":"haute","shape":"esprit","skills":["Investigation","Furtivité","Perception","Diplomatie"],"anchor":"Ancienne criminelle madrilène devenue enquêtrice de l'Église, exploite sa connaissance des réseaux clandestins.","talents":["Dossier préparé — réseau criminel","Lecture des failles — enquête"]},
  {"id":"pnj-religions-chretiente-okeenan-degath","tier":"haute","shape":"terrain","skills":["Tir","Survie","Athlétisme","Autorité"],"anchor":"Ex-Marine revenu traumatisé de la guerre, agit sur le terrain religieux plus volontiers que dans la liturgie.","talents":["Terrain reconnu — opérations","Expertise éprouvée — Tir"]},
  {"id":"pnj-religions-chretiente-pere-raphael","tier":"haute","shape":"terrain","skills":["Mêlée","Constitution","Survie","Autorité"],"anchor":"Religieux de terrain surnommé le bûcheron, affectionne épées et haches mais rejette la bureaucratie.","talents":["Désarmement net — Mêlée","Terrain reconnu — expéditions"],"truth":"Sa vie antérieure et son identité véritable sont réservées au dossier MJ."},
  {"id":"pnj-religions-chretiente-radomir-hadjiev","tier":"haute","shape":"esprit","skills":["Savoirs","Investigation","Perception","Force Mentale"],"anchor":"Prépare minutieusement les rites et protocoles de protection, évite la confrontation directe.","talents":["Dossier préparé — rites","Lecture des failles — protection"]},
  {"id":"pnj-religions-chretiente-rose-de-manegond","tier":"haute","shape":"esprit","skills":["Soin","Savoirs","Investigation","Force Mentale"],"anchor":"Psychiatre ayant rejoint l'Église après un patient traumatisant, reconnue pour les prières de bannissement et les crises.","talents":["Expertise éprouvée — Soin","Dossier préparé — intervention"],"truth":"Les rites pratiqués sont décrits dans le lore ; PTV non inventés pour des phénomènes non spécifiés."},
  {"id":"pnj-religions-chretiente-sekino-shunsho","tier":"haute","shape":"esprit","skills":["Investigation","Perception","Furtivité","Tir"],"anchor":"Ancien policier anti-yakuza obstiné, continue les enquêtes dans la structure judiciaire de l'Église.","talents":["Dossier préparé — réseau yakuza","Lecture des failles — enquête"]},
  {"id":"pnj-religions-chretiente-soeur-maria","tier":"heroique","shape":"terrain","skills":["Soin","Tir","Autorité","Investigation"],"anchor":"Formatrice religieuse des missions sanitaires et dangereuses, instruit notamment Monica di Melucci.","talents":["Chef de manœuvre — formation","Expertise éprouvée — Soin"],"truth":"Son passé ancien et la Vérité de l'ordre exigent un profil révélé distinct."},
  {"id":"pnj-religions-chretiente-thomas-harker","tier":"haute","shape":"esprit","skills":["Savoirs","Investigation","Force Mentale","Diplomatie"],"anchor":"Pasteur ayant rejoint le ministère des rites après le meurtre de sa famille, spécialiste des crises et confessions.","talents":["Dossier préparé — confession","Expertise éprouvée — Savoirs"]},
  {"id":"pnj-religions-chretiente-farah-crawn","tier":"heroique","shape":"social","skills":["Autorité","Diplomatie","Survie","Savoirs"],"anchor":"Ex-officière sud-africaine versée dans le moral, la logistique et la tenue des troupes, prélat des ordres militaires.","talents":["Chef de manœuvre — unités","Réseau mobilisable — AUC"]},
  {"id":"pnj-religions-chretiente-kagiyama-kaho","tier":"haute","shape":"terrain","skills":["Tir","Survie","Autorité","Investigation"],"anchor":"Survivante des combats d'Osaka et ancienne recrue d'Ushkoll, commande une division AUC.","talents":["Chef de manœuvre — division","Terrain reconnu — guerre"]},
  {"id":"pnj-religions-chretiente-leonard-collins","tier":"heroique","shape":"esprit","skills":["Autorité","Savoirs","Tir","Survie"],"anchor":"Général vétéran des Marines, survivant de Gwangju, rejoint l'AUC pour retrouver un commandement important.","talents":["Chef de manœuvre — régiment","Terrain reconnu — guerre"]},
  {"id":"pnj-religions-chretiente-malcom-robinson","tier":"haute","shape":"esprit","skills":["Savoirs","Investigation","Autorité","Diplomatie"],"anchor":"Cardinal-sénéchal sans expérience récente de commandement, compense par la préparation méthodique de la défense.","talents":["Dossier préparé — défense","Réseau mobilisable — recrues"]},
  {"id":"pnj-religions-chretiente-melina-moya","tier":"haute","shape":"terrain","skills":["Tir","Autorité","Survie","Commerce"],"anchor":"Officière mexicaine passée par des collusions avec les cartels, devenue sénéchale de l'AUC.","talents":["Chef de manœuvre — division","Terrain reconnu — contre-cartel"]},
  {"id":"pnj-religions-chretiente-mickael-krieg","tier":"heroique","shape":"terrain","skills":["Tir","Survie","Autorité","Perception"],"anchor":"Officier allemand capturé dans la guerre de Corée et devenu chef d'une division AUC, réputé loyal au combat.","talents":["Chef de manœuvre — division","Terrain reconnu — guerre"]},
  {"id":"pnj-religions-chretiente-zedarius-davenport","tier":"haute","shape":"terrain","skills":["Autorité","Tir","Survie","Représentation"],"anchor":"Ancien évangéliste revenu de la guerre, commande et entraîne des recrues AUC sans goût pour la cérémonie.","talents":["Chef de manœuvre — entraînement","Terrain reconnu — guerre"]},
  {"id":"personnages-points-rencontre-ma-yimu","tier":"entraine","shape":"social","skills":["Diplomatie","Perception","Commerce","Savoirs"],"anchor":"Réceptionniste de la Tour dorée à un poste prestigieux ; aucune maîtrise martiale n'est décrite publiquement.","talents":["Expertise éprouvée — Diplomatie"],"truth":"Sa condition de mage et son Mageius relèvent du dossier MJ ; niveau révélé à établir."},
  {"id":"personnages-points-rencontre-manika-rimmer","tier":"entraine","shape":"social","skills":["Diplomatie","Perception","Commerce","Représentation"],"anchor":"Seconde réceptionniste de la Tour dorée, aucun parcours de combat personnel n'est attesté.","talents":["Expertise éprouvée — Diplomatie"],"truth":"Mageius de Vérité inconnu dans la biographie civile ; profil révélé à préciser."},
  {"id":"personnages-points-rencontre-kristina-moon","tier":"haute","shape":"esprit","skills":["Soin","Savoirs","Furtivité","Investigation"],"anchor":"Ex-pharmacienne de Sunways et tueuse Crawler connue pour les poisons et acides sous le nom Frogchrist.","talents":["Expertise éprouvée — Soin","Dossier préparé — poisons"],"truth":"La magie familiale de l'Empire vert est exclusivement MJ ; amplitude et PTV à définir depuis son dossier."},
  {"id":"personnages-points-rencontre-murck-date","tier":"elite","shape":"terrain","skills":["Tir","Survie","Perception","Mêlée"],"anchor":"Jeune mercenaire Crawler élevé par Mickael Date ; le dossier civil ne décrit aucune prouesse héroïque.","talents":["Terrain reconnu — mercenariat","Expertise éprouvée — Tir"],"truth":"Mageius et projection spectrale restent MJ, sans dégâts inférés."},
  {"id":"personnages-points-rencontre-mukna","tier":"elite","shape":"terrain","skills":["Pilotage","Survie","Perception","Commerce"],"anchor":"Biker et transporteur comanche sillonnant la Grande Réserve ; son titre de sentinelle magique reste privé.","talents":["Terrain reconnu — réserve","Expertise éprouvée — Pilotage"],"truth":"Magie du sang et rôle dans la Loge : réserver les PTV à la forme révélée MJ."},
  {"id":"personnages-points-rencontre-lana-alvarez","tier":"entraine","shape":"social","skills":["Commerce","Perception","Pugilat","Diplomatie"],"anchor":"Jeune croupière de Tala dont la carrure impressionnante ne démontre pas une carrière de combat.","talents":["Expertise éprouvée — Commerce"],"truth":"Technique Tueur de Mageius et malédiction relèvent du profil de Vérité MJ."},
  {"id":"personnages-points-rencontre-tina-miller","tier":"haute","shape":"social","skills":["Autorité","Commerce","Diplomatie","Investigation"],"anchor":"Dirige le Grand Théâtre, accueille personnellement les invités des ventes prestigieuses.","talents":["Réseau mobilisable — Grand Théâtre","Chef de manœuvre — personnel"],"truth":"Sa magie éventuelle et ses liens avec Faust restent MJ."},
  {"id":"personnages-points-rencontre-rupert-sven-andersen","tier":"entraine","shape":"social","skills":["Commerce","Diplomatie","Perception","Investigation"],"anchor":"Jeune assistant du Grand Théâtre employé par Tortoise Security, décrit comme prétentieux plutôt que compétent au combat.","talents":["Expertise éprouvée — Commerce"],"truth":"Mageius et nature réelle réservés au dossier MJ."},
  {"id":"personnages-points-rencontre-margareeta-rootare","tier":"elite","shape":"social","skills":["Commerce","Perception","Diplomatie","Investigation"],"anchor":"Barmaid estonienne gérant le Sugar Eden lorsque J3 s'absente.","talents":["Dossier préparé — clientèle","Expertise éprouvée — Commerce"],"truth":"Argariel et sa nature angélique sont exclusivement MJ."},
  {"id":"personnages-points-rencontre-rosina-vyacheslavovna","tier":"haute","shape":"terrain","skills":["Perception","Tir","Autorité","Furtivité"],"anchor":"Ex-Bratva désormais responsable de sécurité au Dancing Rabbit, reste taciturne et vigilante.","talents":["Terrain reconnu — sécurité","Chef de manœuvre — gardes"],"truth":"Son nom Rosaelle et son origine de Vérité restent MJ."},
  {"id":"personnages-points-rencontre-jack-ashford","tier":"elite","shape":"esprit","skills":["Mécanique","Commerce","Savoirs","Survie"],"anchor":"Ancien biker, vétéran et prêtre, dirige un garage de pièces anciennes et soutient matériellement les chasseurs.","talents":["Expertise éprouvée — Mécanique","Expertise éprouvée — Commerce"],"truth":"Ashirel et les attributs angéliques restent MJ."},
  {"id":"personnages-points-rencontre-elisenda-ruiz","tier":"haute","shape":"terrain","skills":["Tir","Furtivité","Mécanique","Commerce"],"anchor":"Ancienne tueuse du cartel de Sinaloa, vend des armes personnalisées au garage Ashford malgré la traque de ses anciens hommes.","talents":["Expertise éprouvée — Mécanique","Expertise éprouvée — Tir"],"truth":"Erianel et pouvoirs de Vérité sont à traiter dans une forme révélée MJ."},
  {"id":"personnages-points-rencontre-amber-nichols","tier":"entraine","shape":"social","skills":["Commerce","Séduction","Perception","Diplomatie"],"anchor":"Serveuse du Purple Embers au contact aisé, plaisante de son nom et du bar, sans prouesse martiale connue.","talents":["Expertise éprouvée — Commerce"],"truth":"Son identité passée incertaine ne devient pas une vérité tranchée sans arbitrage."},
  {"id":"personnages-points-rencontre-barbara-ui-maothain","tier":"elite","shape":"social","skills":["Commerce","Diplomatie","Investigation","Perception"],"anchor":"Employée de Raven Corporation, se présente publiquement comme la sœur de Morgan Uí Maotháin.","talents":["Dossier préparé — Raven","Expertise éprouvée — Diplomatie"],"truth":"Sa parenté réelle et sa nature de Vérité appartiennent au MJ."},
  {"id":"personnages-points-rencontre-rishabha-ajagavakar","tier":"haute","shape":"esprit","skills":["Mécanique","Soin","Survie","Investigation"],"anchor":"Ingénieure devenue meditech des tanières, excelle dans les réparations improvisées et les soins de terrain.","talents":["Expertise éprouvée — Mécanique","Terrain reconnu — tanières"],"truth":"Sa nature de louve et sa forme révélée exigent un profil MJ spécifique."},
  {"id":"personnages-points-rencontre-clyde-w-mcshark","tier":"haute","shape":"terrain","skills":["Autorité","Tir","Survie","Investigation"],"anchor":"Colonel de l'armée californienne, second de Benedicte Vilhelmsen à l'académie militaire.","talents":["Chef de manœuvre — académie","Terrain reconnu — manœuvres"],"truth":"Ulfried et la nature de Vérité sont privés."},
  {"id":"personnages-points-rencontre-murton-keens","tier":"elite","shape":"terrain","skills":["Pilotage","Tir","Survie","Perception"],"anchor":"Biker criminel affilié aux Hell Angels, dossier public succinct qui ne prouve pas un palier héroïque.","talents":["Terrain reconnu — routes","Expertise éprouvée — Pilotage"],"truth":"Vérité et niveau révélé indéterminés ; les préciser depuis son dossier complet."},
  {"id":"personnages-points-rencontre-jackson-blade","tier":"haute","shape":"terrain","skills":["Tir","Perception","Survie","Autorité"],"anchor":"Agent de sécurité du Jadecenter Palameta réputé comme tireur d'élite redoutable.","talents":["Expertise éprouvée — Tir","Terrain reconnu — protection"],"truth":"Sa nature Ash relève du MJ."},
  {"id":"personnages-points-rencontre-judy-rosheen-smith","tier":"elite","shape":"terrain","skills":["Athlétisme","Soin","Survie","Perception"],"anchor":"Ancienne mercenaire blessée à la guerre, enseigne désormais le sport chez Ushkoll.","talents":["Terrain reconnu — entraînement","Expertise éprouvée — Soin"],"truth":"Ses blessures ont des conséquences à préciser ; aucun bonus de combat ne vient de sa seule profession passée."},
  {"id":"personnages-points-rencontre-anna-hetfield","tier":"haute","shape":"social","skills":["Représentation","Diplomatie","Commerce","Neurodive"],"anchor":"Musicienne polyvalente Annallica, devenue célèbre pendant la guerre dans la scène neopunk.","talents":["Expertise éprouvée — Représentation","Réseau mobilisable — scène musicale"],"truth":"Les éléments de Vérité de son dossier restent privés."},
  {"id":"personnages-points-rencontre-valentyn-solovej","tier":"haute","shape":"terrain","skills":["Tir","Survie","Autorité","Perception"],"anchor":"Officier ukrainien de la Bratva, exécute avec efficacité les missions de Grigoria Ravinsky.","talents":["Chef de manœuvre — hommes de main","Terrain reconnu — opérations"],"truth":"Sa nature Thukar reste MJ."},
  {"id":"personnages-points-rencontre-jordan-mulkenny","tier":"haute","shape":"terrain","skills":["Autorité","Tir","Survie","Investigation"],"anchor":"Vétéran officier supérieur de l'académie MNA, soumis à des accusations publiques de fascisme.","talents":["Chef de manœuvre — académie","Terrain reconnu — guerre"],"truth":"Sheorrn'kay est un nom de Vérité MJ."},
  {"id":"personnages-points-rencontre-james-hopper","tier":"elite","shape":"esprit","skills":["Investigation","Perception","Tir","Diplomatie"],"anchor":"Agent enquêteur du CBII proche de Cole Gallagher et habitué aux dossiers de détectives du LAUS.","talents":["Dossier préparé — enquête","Lecture des failles — indices"],"truth":"Origine clonale rocréenne, Dusharam'Feeshri et réseaux Feeshri restent exclusivement MJ."},
  {"id":"personnages-points-rencontre-racheyl-rosemann","tier":"elite","shape":"esprit","skills":["Investigation","Savoirs","Perception","Autorité"],"anchor":"Assistante de direction chez Raven, réputée pour sa mémoire exceptionnelle et sa maîtrise des dossiers.","talents":["Dossier préparé — dossiers Raven","Expertise éprouvée — Savoirs"],"truth":"Ashmyn k'Na et sa nature artificielle restent strictement privés."},
  {"id":"personnages-verite-chasseurs-kaleem-nash","tier":"elite","shape":"social","skills":["Commerce","Investigation","Autorité","Perception"],"anchor":"Ancien trafiquant de Crash dont le réseau fut détruit par la Bratva en 2029.","talents":["Dossier préparé — circuits du Crash","Réseau mobilisable — anciens contacts"],"truth":"Son parcours de chasse et toute nature cachée demandent lecture du dossier MJ."},
  {"id":"personnages-verite-chasseurs-kenneth-chanington","tier":"haute","shape":"terrain","skills":["Mêlée","Esquive","Soin","Perception"],"anchor":"Médecin d'une vieille famille anglaise et escrimeur remarquable, à distinguer des exploits de ses ancêtres chasseurs.","talents":["Désarmement net — Mêlée","Expertise éprouvée — Soin"],"truth":"Sa lignée de chasseurs est MJ ; éventuels talents de Chasse à définir selon sa formation."},
  {"id":"personnages-verite-chasseurs-monica-di-melucci","tier":"elite","shape":"social","skills":["Représentation","Séduction","Diplomatie","Perception"],"anchor":"Jeune mannequin et actrice de Tuatha, adoptée par sa tante Clemenzia Rossini avant son installation californienne.","talents":["Expertise éprouvée — Représentation","Expertise éprouvée — Séduction"],"truth":"Sa filiation avec Paladia et sa formation secrète de chasseuse restent MJ."},
  {"id":"personnages-verite-chasseurs-jimmy-brazier","tier":"haute","shape":"social","skills":["Séduction","Investigation","Diplomatie","Perception"],"anchor":"Crawler Hooker rémunéré pour charmer et piéger ses cibles, fréquente le Purple Embers.","talents":["Expertise éprouvée — Séduction","Dossier préparé — cible"],"truth":"Le nom Moloch et sa véritable puissance démoniaque sont au dossier MJ ; forme révélée inatteignable par simple extrapolation civile."},
  {"id":"personnages-verite-chasseurs-drew-knight","tier":"heroique","shape":"terrain","skills":["Pugilat","Esquive","Athlétisme","Perception"],"anchor":"Champion légendaire de MMA réputé invulnérable avant ses défaites contre Senan Greene puis la chaîne d'adversaires.","talents":["Lutte brève — Pugilat","Désarmement net — Pugilat"],"truth":"Sa nature cachée et ses limites physiques requièrent une lecture MJ distincte."},
  {"id":"personnages-verite-chasseurs-shaneene-mabble","tier":"elite","shape":"social","skills":["Représentation","Diplomatie","Survie","Perception"],"anchor":"Militante afro-américaine après une jeunesse traumatique, a tenté police et armée sans carrière martiale confirmée.","talents":["Expertise éprouvée — Représentation","Terrain reconnu — quartier"],"truth":"Sa Vérité et tout talent de Chasse ne se déduisent pas de ce parcours public."},
  {"id":"personnages-verite-chasseurs-magyar-vilmos","tier":"elite","shape":"esprit","skills":["Soin","Perception","Investigation","Survie"],"anchor":"Infirmier hongrois aux urgences lors de l'attentat de 2022, sans antécédent physique professionnel.","talents":["Expertise éprouvée — Soin","Dossier préparé — urgence"],"truth":"Son dossier MJ peut justifier un profil de chasse séparé."},
  {"id":"personnages-verite-chasseurs-shanara-zafrani","tier":"haute","shape":"social","skills":["Représentation","Diplomatie","Savoirs","Perception"],"anchor":"Chanteuse californienne majeure issue de parents artistes marocain et afro-américain.","talents":["Expertise éprouvée — Représentation","Réseau mobilisable — scène"],"truth":"Son accès à l'ésotérisme aïssawa relève du dossier MJ."},
  {"id":"personnages-verite-chasseurs-hashem-el-khayat","tier":"elite","shape":"social","skills":["Diplomatie","Savoirs","Perception","Survie"],"anchor":"Issu d'une famille riche, évite sa cupidité et ses querelles, cherche publiquement à mener une vie juste.","talents":["Expertise éprouvée — Diplomatie","Terrain reconnu — itinérance"],"truth":"Haahdar'Vaanesh et le rôle de prince chasseur appartiennent au MJ ; palier révélé à arbitrer."},
  {"id":"personnages-verite-chasseurs-stephen-fushen","tier":"haute","shape":"social","skills":["Commerce","Autorité","Savoirs","Diplomatie"],"anchor":"Économiste fortuné ayant créé associations et compétitions d'arts martiaux chinois.","talents":["Réseau mobilisable — compétitions","Chef de manœuvre — associations"],"truth":"Son expérience de chasse se traite séparément de sa fortune et de ses concours."},
];

export function applyPnjStatBatch05(byId:Map<string,Article>):void {
  if(PROFILES.length!==50||new Set(PROFILES.map(p=>p.id)).size!==50)throw new Error("PNJ · lot 05 incomplet ou dupliqué");
  for(const profile of PROFILES){
    const article=byId.get(profile.id);
    if(!article)throw new Error(`PNJ · fiche active introuvable : ${profile.id}`);
    if(article.dataset==="realite-v9-christianity-pnj")consolidateReligiousRealityCard(article);
    if(article.dataset==="points-rencontre-pnj")repairMeetingPointSecrets(article);
    applyNamedPnjStatProfile(article,profile);
  }
}

function repairMeetingPointSecrets(article:Article):void {
  const replacements:Record<string,[string,string]>={
    "personnages-points-rencontre-kristina-moon":["Kristina Moon, dite « Frogchrist », est une Venomer et ancienne pharmacienne de Sunways. Elle est connue comme une assassine utilisant poisons et acides ; ses capacités magiques et la magie familiale de l’Empire vert restent MJ.","Kristina Moon, dite « Frogchrist », est une Venomer et ancienne pharmacienne de Sunways. Elle est connue comme une assassine utilisant poisons et acides."],
    "personnages-points-rencontre-murck-date":["Murck Date est un Crawler mercenaire élevé par Mickael Date. Son histoire familiale et sa loyauté envers celui qui l’a élevé appartiennent à sa biographie de Réalité ; son Mageius et ses techniques de projection spectrale restent MJ.","Murck Date est un Crawler mercenaire élevé par Mickael Date. Il reste loyal à celui qui l’a élevé."],
    "personnages-points-rencontre-mukna":["Mukna est un biker et gundriver comanche qui sillonne la Grande Réserve comme transporteur. Son rôle de sentinelle de Loge et sa magie du sang restent MJ.","Mukna est un biker et gundriver comanche qui sillonne la Grande Réserve comme transporteur."],
    "personnages-points-rencontre-lana-alvarez":["Lana Alvarez est une jeune croupière de Tala, connue aussi pour sa carrure de combattante. Sa magie de malédiction et la technique du « Tueur de Mageius » restent MJ.","Lana Alvarez est une jeune croupière de Tala, connue aussi pour sa carrure de combattante."],
    "personnages-points-rencontre-james-hopper":["James Hopper est un agent prometteur du CBII, enquêteur proche de Cole Gallagher et habitué à travailler avec les détectives du LAUS. Sa nature rocréenne, son origine clonale et son rôle dans les réseaux Feeshri restent MJ.","James Hopper est un agent prometteur du CBII, enquêteur proche de Cole Gallagher et habitué à travailler avec les détectives du LAUS."]
  };
  const entry=replacements[article.id];
  if(!entry)return;
  const section=article.sections?.find(item=>item.id==="reparation-biographie-realite");
  const block=section?.blocks?.find((item:Record<string,any>)=>item.type==="p");
  if(block?.text!==entry[0]||!article.sections?.some(item=>item.audience==="mj"&&item.blocks?.length))throw new Error(`PNJ · secret MJ à préserver : ${article.id}`);
  block.text=entry[1];
}
