import { applyNamedPnjStatProfile, type StatProfile } from "./compendium-pnj-corporate-stats.js";

type Article={id:string;dataset?:string;sections?:Array<Record<string,any>>;[key:string]:any};
type Entry=StatProfile & {id:string};

const PROFILES:Entry[]=[
  {"id":"personnages-verite-angelus-adriana-bienvenida","tier":"haute","shape":"esprit","skills":["Neurodive","Investigation","Perception","Pilotage"],"anchor":"Neurodiver itinérante spécialisée dans la surveillance de l'Holonet, travaille avec la tireuse Nyoko Myabe.","talents":["Dossier préparé — piste","Expertise éprouvée — Neurodive"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-zivko-voronov","tier":"heroique","shape":"social","skills":["Savoirs","Commerce","Autorité","Diplomatie"],"anchor":"Avocat dirigeant les cabinets Bratchov, riche et charmeur, surnommé Whiteman par sa garde-robe blanche.","talents":["Réseau mobilisable — cabinets","Dossier préparé — procès"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-mickael-lorn","tier":"haute","shape":"social","skills":["Représentation","Savoirs","Diplomatie","Autorité"],"anchor":"Ancien athlète olympique paralysé devenu prêtre, dirigeait un orphelinat détruit en 2035.","talents":["Expertise éprouvée — Représentation","Expertise éprouvée — Savoirs"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-anna-lynn-kimber","tier":"heroique","shape":"esprit","skills":["Mécanique","Savoirs","Autorité","Investigation"],"anchor":"Architecte majeure de Byron Industries, supervise chantiers et projets de navires géants.","talents":["Expertise éprouvée — Mécanique","Dossier préparé — chantier"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-brandon-smith","tier":"entraine","shape":"terrain","skills":["Constitution","Athlétisme","Survie","Mécanique"],"anchor":"Ouvrier de chantier ayant subi plusieurs pertes familiales, travaille pour soutenir une jeune proche hospitalisée.","talents":["Expertise éprouvée — Constitution"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-ragnil-sundstrom","tier":"heroique","shape":"terrain","skills":["Athlétisme","Esquive","Survie","Pugilat"],"anchor":"Athlète suédoise de course et de saut à la perche devenue sujet volontaire du programme Phoenix III.","talents":["Expertise éprouvée — Athlétisme","Terrain reconnu — compétition"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-harmony-melinda-mannan","tier":"haute","shape":"terrain","skills":["Survie","Investigation","Tir","Autorité"],"anchor":"Ancienne agente de la CIA devenue dirigeante d'une ferme Ender autonome.","talents":["Terrain reconnu — campagne","Dossier préparé — renseignement"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-cylia-vecellio","tier":"heroique","shape":"terrain","skills":["Athlétisme","Pugilat","Esquive","Survie"],"anchor":"Athlète Ushkoll passée de la sécurité à l'UMA, à la natation et à l'escalade de compétition.","talents":["Expertise éprouvée — Athlétisme","Terrain reconnu — compétition"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-stephania-lawrence","tier":"heroique","shape":"esprit","skills":["Neurodive","Commerce","Autorité","Investigation"],"anchor":"Directrice de System chez Monarch Systems, stratège de sa croissance sur le marché informatique.","talents":["Réseau mobilisable — Monarch","Dossier préparé — marché"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-zamari-wilkerson","tier":"haute","shape":"social","skills":["Diplomatie","Autorité","Commerce","Représentation"],"anchor":"Ancien ouvrier et livreur de Compton devenu organisateur d'associations après le handicap de son fils.","talents":["Réseau mobilisable — associations","Expertise éprouvée — Diplomatie"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-ariana-lenitz","tier":"haute","shape":"terrain","skills":["Investigation","Furtivité","Neurodive","Tir"],"anchor":"Agente de renseignement de la Blanchisserie, formée à l'observation et à l'infiltration.","talents":["Dossier préparé — cible","Expertise éprouvée — Furtivité"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-jason-fraguenaud","tier":"haute","shape":"esprit","skills":["Savoirs","Investigation","Diplomatie","Survie"],"anchor":"Prêtre issu d'une famille de vignerons ruinée, remarqué par l'ordre des Inquisiteurs.","talents":["Dossier préparé — enquête","Expertise éprouvée — Savoirs"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-hazel-salz","tier":"haute","shape":"esprit","skills":["Investigation","Perception","Commerce","Diplomatie"],"anchor":"Informateur des Crawlers surnommé Omnichiant, accumule des renseignements malgré une santé fragile.","talents":["Dossier préparé — informateur","Lecture des failles — source"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-scarlet-macbride","tier":"heroique","shape":"social","skills":["Représentation","Commerce","Diplomatie","Investigation"],"anchor":"Présentatrice de Nextar devenue créatrice de concepts d'émissions après avoir soutenu Lys.","talents":["Expertise éprouvée — Représentation","Réseau mobilisable — Nextar"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-tshaddy-el-sharif","tier":"haute","shape":"esprit","skills":["Neurodive","Représentation","Diplomatie","Savoirs"],"anchor":"Étudiant Neurodiver et figure médiatique des communautés musulmanes en ligne.","talents":["Expertise éprouvée — Neurodive","Expertise éprouvée — Représentation"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-rubino-esterranzo","tier":"elite","shape":"social","skills":["Diplomatie","Savoirs","Représentation","Perception"],"anchor":"Prêtre de San Diejuana, progressiste et père de famille, soutient les réformes de Neovatican.","talents":["Expertise éprouvée — Diplomatie","Expertise éprouvée — Savoirs"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-shayna-arc","tier":"haute","shape":"social","skills":["Représentation","Savoirs","Diplomatie","Autorité"],"anchor":"Prêtresse de traditions aztèques à New York, ancienne aspirante à une carrière politique.","talents":["Réseau mobilisable — fidèles","Expertise éprouvée — Savoirs"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-dragomir-mikhailovich","tier":"heroique","shape":"terrain","skills":["Mêlée","Autorité","Survie","Perception"],"anchor":"Ancien bras armé du chef de la mafia de Vladivostok, réputé pour son impassibilité terrifiante.","talents":["Désarmement net — Mêlée","Terrain reconnu — affrontements"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-brandon-shark","tier":"haute","shape":"terrain","skills":["Tir","Survie","Pilotage","Autorité"],"anchor":"Ancien marin de la flotte australienne devenu mercenaire de l'Unité Corneille chez Ushkoll.","talents":["Terrain reconnu — opérations","Chef de manœuvre — équipe"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-jamal-jace-jayson","tier":"haute","shape":"social","skills":["Représentation","Séduction","Commerce","Diplomatie"],"anchor":"Acteur Redwheels et propriétaire du Sugar Eden, anime aussi des publicités et événements.","talents":["Expertise éprouvée — Représentation","Réseau mobilisable — club"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-shihoko-baisho","tier":"heroique","shape":"social","skills":["Commerce","Autorité","Diplomatie","Investigation"],"anchor":"Entrepreneuse de mode et d'hôtellerie passée sous l'influence des Yakuzas de Shinoda.","talents":["Réseau mobilisable — hôtels","Expertise éprouvée — Commerce"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-sasha-novogvna","tier":"haute","shape":"social","skills":["Savoirs","Autorité","Diplomatie","Perception"],"anchor":"Mère supérieure d'une petite communauté religieuse de Las Vegas, peu connue au-delà.","talents":["Réseau mobilisable — couvent","Expertise éprouvée — Savoirs"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-chinyu-dao","tier":"entraine","shape":"terrain","skills":["Survie","Perception","Constitution","Diplomatie"],"anchor":"Sans-abri discret de Chinatown, fréquemment aperçu avec une bière mais sans profession attestée.","talents":["Expertise éprouvée — Survie"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-nei-helm","tier":"elite","shape":"terrain","skills":["Survie","Investigation","Commerce","Perception"],"anchor":"Rescapée de Floringtown après le rachat de la ville par Yellowfood ; parcours ultérieur à préciser.","talents":["Expertise éprouvée — Survie","Dossier préparé — Yellowfood"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-shaheed-el-kabir","tier":"elite","shape":"terrain","skills":["Tir","Survie","Mêlée","Perception"],"anchor":"Mercenaire Crawler sans papiers, travaille dans les quartiers abandonnés au contact de la pègre.","talents":["Terrain reconnu — quartiers","Expertise éprouvée — Tir"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-hannah-lee-flegton","tier":"haute","shape":"social","skills":["Séduction","Diplomatie","Commerce","Perception"],"anchor":"Travailleuse du sexe populaire associée à Vladic, proche de plusieurs gangs et du maire Hamilton.","talents":["Expertise éprouvée — Séduction","Réseau mobilisable — clientèle"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-min-kyung-ra","tier":"haute","shape":"social","skills":["Représentation","Commerce","Autorité","Diplomatie"],"anchor":"Ancienne artiste K-pop de Black Angel, forme désormais de jeunes chanteuses chez Omegacoustic.","talents":["Expertise éprouvée — Représentation","Réseau mobilisable — label"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-daniel-melton","tier":"haute","shape":"terrain","skills":["Athlétisme","Survie","Autorité","Soin"],"anchor":"Ancienne combattante blessée devenue officière des pompiers de Los Angeles.","talents":["Terrain reconnu — secours","Chef de manœuvre — pompiers"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-hans-griever","tier":"haute","shape":"social","skills":["Représentation","Séduction","Commerce","Investigation"],"anchor":"Acteur Tuatha et Fixer disposant d'un vaste carnet d'adresses après des années de recrutement.","talents":["Expertise éprouvée — Représentation","Dossier préparé — contact"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-angel-graff","tier":"entraine","shape":"social","skills":["Séduction","Perception","Survie","Diplomatie"],"anchor":"Fils du révérend Graff, revenu de plusieurs cures avec un changement de comportement soudain.","talents":["Expertise éprouvée — Séduction"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-jack-ken","tier":"heroique","shape":"social","skills":["Représentation","Savoirs","Commerce","Perception"],"anchor":"DJ majeur des quartiers abandonnés, connu pour des compositions MAP à dix-sept pistes.","talents":["Expertise éprouvée — Représentation","Réseau mobilisable — scène"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-jaquina-morales","tier":"haute","shape":"terrain","skills":["Tir","Furtivité","Survie","Perception"],"anchor":"Crawler mexicaine travaillant principalement pour Sinaloa, accepte aussi des contrats indépendants.","talents":["Terrain reconnu — clandestinité","Expertise éprouvée — Tir"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-kurt-kriemenschneider","tier":"elite","shape":"terrain","skills":["Pugilat","Esquive","Survie","Perception"],"anchor":"Combattant d'UMA de niveau moyen et Crawler sans arme, connu pour sa tenue minimaliste.","talents":["Lutte brève — Pugilat","Expertise éprouvée — Esquive"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-melias-abel","tier":"heroique","shape":"esprit","skills":["Mécanique","Investigation","Tir","Survie"],"anchor":"Chasseur Hunt100, ancien ingénieur Byron, s'appuie sur la technologie transportée dans son camion.","talents":["Dossier préparé — cible","Expertise éprouvée — Mécanique"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-henna-vatryov","tier":"elite","shape":"social","skills":["Séduction","Perception","Diplomatie","Commerce"],"anchor":"Escort itinérante régulièrement présente aux soirées de Jesus Jack, réputée pour ses conseils.","talents":["Expertise éprouvée — Séduction","Réseau mobilisable — soirées"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-barbara-amble","tier":"haute","shape":"social","skills":["Représentation","Investigation","Perception","Commerce"],"anchor":"Batteuse néopunk dont le groupe fut décimé, enquête sur les auteurs d'un assaut en concert.","talents":["Expertise éprouvée — Représentation","Dossier préparé — assaut"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-rei-shinkai","tier":"heroique","shape":"terrain","skills":["Investigation","Mêlée","Survie","Perception"],"anchor":"Chasseur indépendant errant, traque et renvoie des créatures sans appartenir à une organisation.","talents":["Dossier préparé — créature","Terrain reconnu — traque"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-kyu-bok-nura","tier":"elite","shape":"terrain","skills":["Tir","Survie","Perception","Investigation"],"anchor":"Ancien policier sud-coréen et Ranger, aujourd'hui agent de sécurité chez Tortoise Security.","talents":["Terrain reconnu — surveillance","Expertise éprouvée — Tir"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-angelus-lex-huria","tier":"haute","shape":"esprit","skills":["Commerce","Investigation","Représentation","Autorité"],"anchor":"Assistante de production chez Nextar sur des émissions populaires, notamment culinaires.","talents":["Dossier préparé — production","Expertise éprouvée — Commerce"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-humains-galactiques-lisa-eredhes","tier":"heroique","shape":"terrain","skills":["Pilotage","Survie","Autorité","Savoirs"],"anchor":"Ancienne nageuse et biologiste mexicaine recrutée par l'armée de l'air puis responsable de missions spatiales.","talents":["Chef de manœuvre — équipage","Terrain reconnu — vol"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-humains-galactiques-alladava-kjoll","tier":"heroique","shape":"esprit","skills":["Mécanique","Savoirs","Autorité","Commerce"],"anchor":"Ingénieure sud-africaine et dirigeante de Space Union, spécialiste des programmes spatiaux.","talents":["Réseau mobilisable — Space Union","Dossier préparé — programme"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-humains-galactiques-james-zero","tier":"elite","shape":"terrain","skills":["Pilotage","Perception","Survie","Autorité"],"anchor":"Officier discret de la Space Force Union, calme et attentif à ses équipiers.","talents":["Expertise éprouvée — Pilotage","Terrain reconnu — station"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-humains-galactiques-lance-goldstar","tier":"heroique","shape":"terrain","skills":["Pilotage","Autorité","Survie","Perception"],"anchor":"Haut gradé de la Space Force Union, coordonne les équipages entre la Terre et la Lune.","talents":["Chef de manœuvre — équipage","Terrain reconnu — espace"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-humains-galactiques-chris-sunborne","tier":"haute","shape":"social","skills":["Diplomatie","Autorité","Représentation","Commerce"],"anchor":"Haut cadre sud-africain de la Space Force Union, milite contre le racisme.","talents":["Réseau mobilisable — SFU","Expertise éprouvée — Diplomatie"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-humains-galactiques-sigmund-vandendriessche","tier":"entraine","shape":"social","skills":["Commerce","Autorité","Perception","Diplomatie"],"anchor":"Ancien gérant texan d'un petit restaurant rapide, père de Stanley Vandendriessche.","talents":["Expertise éprouvée — Commerce"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-humains-galactiques-lois-xavier","tier":"heroique","shape":"social","skills":["Autorité","Commerce","Diplomatie","Investigation"],"anchor":"Vice-présidente autoritaire d'Owl Corporation, sait imposer ses ordres malgré son impopularité.","talents":["Réseau mobilisable — Owl","Dossier préparé — direction"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-humains-galactiques-sally-melia-goom","tier":"haute","shape":"esprit","skills":["Commerce","Autorité","Investigation","Savoirs"],"anchor":"Cadre de Byron Industries, adepte des technologies esthétiques et d'augmentations fréquentes.","talents":["Réseau mobilisable — Byron","Expertise éprouvée — Commerce"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-humains-galactiques-kassim-heirdaen-castanelli","tier":"haute","shape":"social","skills":["Commerce","Autorité","Investigation","Diplomatie"],"anchor":"Entré dans la mafia italo-californienne par mariage avec Bella Castanelli.","talents":["Réseau mobilisable — Famille","Dossier préparé — alliance"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-humains-galactiques-christopher-zaakdu","tier":"elite","shape":"social","skills":["Commerce","Autorité","Savoirs","Perception"],"anchor":"Riche cadre de Wellspring sans branche à diriger, souffre d'une grave dégénérescence musculaire.","talents":["Expertise éprouvée — Commerce","Réseau mobilisable — siège"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
  {"id":"personnages-verite-humains-galactiques-ogum-mi-yeon","tier":"elite","shape":"social","skills":["Représentation","Investigation","Commerce","Perception"],"anchor":"Journaliste coréenne employée par Nextar, carrière moyenne et addiction aux jeux.","talents":["Expertise éprouvée — Représentation"],"truth":"La Vérité et les pouvoirs révélés sont évalués dans un profil distinct."},
];

export function applyPnjStatBatch11(byId:Map<string,Article>):void {
  if(PROFILES.length!==50||new Set(PROFILES.map(p=>p.id)).size!==50)throw new Error("PNJ · lot 11 incomplet ou dupliqué");
  for(const profile of PROFILES){
    const article=byId.get(profile.id);
    if(!article)throw new Error(`PNJ · fiche active introuvable : ${profile.id}`);
    applyNamedPnjStatProfile(article,profile);
  }
}
