import {applyPnjTruthDecisions,type TruthBatchArticle,type TruthDecision} from './compendium-pnj-truth-batch-001.js';

// Each estimate is anchored in the named MJ dossier. The numbers describe the
// character in a playable scene, not the full cosmological reach of a deity.
const choices:TruthDecision[]=[
  ['pnj-police-catalina-de-la-caza',[14,12,19,20,15],[['Force Mentale',27],['Autorité',22],['Pugilat',20]],'V’Aagor fusionne avec Catalina sans effacer sa volonté ; elle devient le point d’incarnation du Roi des Fléaux et détruit le corps de Lucifer.','Sa forme et ses défenses dépendent de la manifestation jouée. La disparition du corps de Lucifer ne signifie pas la destruction de son âme ni un pouvoir utilisable sans opposition.'],
  ['pnj-agences-makana-keahi',[15,13,13,14,10],[['Mêlée',24],['Pugilat',21],['Force Mentale',20]],'Makana incarne Sumarbrander, affronte Surtr et reprend le contrôle de l’épée après avoir déchiré l’espace-temps au large de Los Angeles.','L’épée incarnée et le phénomène de l’île Keahi restent des événements singuliers ; ni arme séparée toujours disponible ni déchirure spatiotemporelle gratuite.'],
  ['pnj-gouvernement-farah-el-arshad',[12,11,14,15,14],[['Force Mentale',23],['Autorité',21],['Survie',18]],'Héritière d’Akvan et de Gaïa, Farah devient Akva’Farah et assume les couronnes des Dives et des Nymphes.','Sa coalition de Dives, Djinns et Nymphes exige des alliés présents et du temps ; les dons de Nymphe et de Djinn ne sont pas tous acquis sans règle.'],
  ['pnj-crawlers-docx-tia-reynolds',[9,10,9,10,7],[['Survie',16],['Investigation',15],['Force Mentale',13]],'Tia, sorcière traqueuse de la famille Kelly, a une affinité pour les garous et a déjoué un complot impliquant des Pelages Sombres.','Son potentiel de sorcière et son lien aux garous ne lui donnent pas le Mageius ni la totalité des formes garoues.'],
  ['pnj-corporations-siobhain-nic-siridean',[11,10,17,16,14],[['Force Mentale',24],['Autorité',20],['Représentation',18]],'Héritière de Morrighan, Siobhain incarne temporairement le Sidh lors de sa poursuite de Mordred et reçoit la puissance de la fratrie liée à cette dimension.','L’incarnation du Sidh est temporaire et dépend de son ouverture ; elle ne cumule pas en permanence les pouvoirs de tous les membres de la fratrie.'],
  ['pnj-corporations-wei-shi',[10,12,18,17,12],[['Force Mentale',25],['Mêlée',22],['Savoirs',20]],'Wei représente le clan Shi au tournoi, puis arrache au Légionnaire du Néant la puissance de l’Œuf de l’Apocalypse et en sort transformée.','Son état de Légionnaire est accidentel ; les effets de l’Œuf et de la maîtrise du Vide doivent être résolus en scène, sans accès automatique à tous les pouvoirs du Néant.'],
  ['pnj-truth-alayna-daewynn',[12,12,11,11,8],[['Mêlée',19],['Survie',18],['Force Mentale',16]],'Alayna est une elfe sylvaine très ancienne, guerrière et protectrice du Cercle de Chêne ; elle parle aux esprits de la nature et demeure souvent révélée.','Elle a été recalée de la Chasse fantastique ; ses esprits et sa communauté ne deviennent pas des combattants mobilisés instantanément.'],
  ['pnj-truth-alexander-shorolth',[17,12,17,16,10],[['Force Mentale',25],['Constitution',24],['Autorité',21]],'Shorolth est le fondateur Blanc des dragons d’Aèr, héritier d’une part de l’âme et du savoir de Rethia ; ses sommeils durent parfois des millénaires.','Son corps draconique dépend de la forme présente ; ses cycles de sommeil et ses anciennes blessures limitent la disponibilité de toute sa puissance.'],
  ['pnj-truth-andrea-shield',[14,12,13,14,10],[['Autorité',22],['Mêlée',21],['Survie',19]],'Andrea Shelden fonda l’empire de Meltanéa et survécut à ses siècles de conquêtes avant de parcourir Gaerras et la Terre.','Ses conquêtes et son immortalité de hauts faits ne lui confèrent ni les armées actuelles de Meltanéa ni les pouvoirs de Morrighan.'],
  ['pnj-truth-beatrix-kruger',[6,6,12,9,7],[['Savoirs',16],['Diplomatie',15],['Mécanique',14]],'Beatrix, naine née au XIXe siècle, connaît les communautés expatriées et défend leur appartenance à une humanité élargie.','Son expérience historique ne prouve aucun Don de forge, immortalité supplémentaire ou magie des Whurtens.'],
  ['pnj-truth-cassandra-helen',[7,7,11,10,10],[['Investigation',18],['Autorité',17],['Diplomatie',16]],'Malcaiah est une azménorienne ancienne du conseil des Anciens ; elle consacre ses ressources à traquer les Flammes Indicibles.','Ses équipes et ses millions investis sont des ressources à mobiliser, pas une attaque personnelle ni le soutien acquis de tout le conseil.'],
  ['pnj-truth-helmi-liikanen',[8,7,15,13,9],[['Mécanique',22],['Savoirs',20],['Force Mentale',18]],'Helmi, forgeronne whurten ancienne au service de Morrighan, a créé Balmung et des pièces légendaires ; elle dirige les traditionalistes nains.','Les œuvres légendaires exigent atelier, matériaux et temps ; sa survie supposée liée à Morrighan est une rumeur, pas une immunité chiffrée.'],
  ['pnj-truth-jay-bentley',[11,10,8,10,7],[['Tir',17],['Mêlée',17],['Survie',15]],'Jaylan est un azménorien âgé de plusieurs siècles et un guerrier reconnu, qui simule le vieillissement puis change d’apparence pour reprendre une vie humaine.','Sa longue expérience ne lui donne pas l’armée de Dina ; le changement de couverture demande la mise en scène de sa mort civile.'],
  ['pnj-truth-kerys',[15,13,9,13,7],[['Mêlée',22],['Constitution',21],['Investigation',18]],'Kerys, dragonne d’Inryase élevée comme assassine, supporte des blessures physiques et magiques extrêmes et touche l’immatériel par sa faux singulière.','La faux doit être portée pour atteindre l’immatériel ; son insensibilité documentée n’est pas une invulnérabilité absolue ni un Mageius.'],
  ['pnj-truth-kevin-eckker',[13,10,9,11,7],[['Survie',19],['Constitution',19],['Autorité',17]],'Aarvyn est un vieux dragon d’Aèr, vétéran de la guerre des dragons et des Archanges, qui a transféré son goût du vol à la nage.','Ses ailes anciennes ne lui permettent plus de voler ; son trésor et sa flotte ne sont pas présents sans préparation.'],
  ['pnj-truth-morgan-nic-brandubh',[12,11,19,18,18],[['Force Mentale',27],['Autorité',25],['Savoirs',23]],'Morgan est Morrighan, ancienne reine divine kelta liée à la guerre, à la mort et à la magie ; elle entretient des lignées et des cultes sur plusieurs mondes.','La puissance des cultes et de ses descendants dépend de leur présence et de leurs alliances ; le profil de scène ne chiffre pas tout son domaine divin.'],
  ['pnj-truth-neals-corvo',[13,14,10,11,7],[['Furtivité',21],['Mêlée',20],['Survie',18]],'Nerediath dirigeait une confrérie d’assassins elfes noirs et a survécu à la purge de Titania après un appel à V’Aagor.','Son pacte et sa mutilation restent des contraintes ; la confrérie doit être reconstituée et n’est pas une équipe automatique.'],
  ['pnj-truth-phoebe-edgar',[7,8,13,11,8],[['Mécanique',18],['Neurodive',15],['Investigation',15]],'Phoebe est une jeune Ashyll gobeline au génie mécanique précoce, consciente de sa nature mais rarement révélée volontairement.','Son talent requiert outils, composants et délai ; son jeune âge et sa transformation involontaire ne justifient pas des pouvoirs de guerre.'],
  ['pnj-truth-yun',[9,11,7,8,6],[['Furtivité',16],['Mêlée',15],['Perception',13]],'Yun Yura est un Ashyll gobelin formé à l’espionnage et à l’assassinat par la lignée des Ryong, sans connaître le nom de son espèce.','Sa surveillance et ses ordres familiaux ne sont pas des Dons ; il ne contrôle pas à lui seul tous les gobelins Yun.'],
  ['pnj-crawlers-antisysteme-p13-thaddeus-slabaugh',[7,7,9,9,10],[['Autorité',16],['Force Mentale',14],['Diplomatie',13]],'Thaddeus est un vampire mimétique transformé par Daniella, dont le Sang reproduit les pouvoirs de sa maîtresse avec son consentement.','Les pouvoirs copiés cessent ou changent si Daniella retire son accord ; aucun arbre de Sang personnel complet n’est supposé.'],
  ['pnj-crawlers-antisysteme-p19-mahkah-jones',[9,9,10,11,10],[['Force Mentale',18],['Autorité',16],['Survie',15]],'Mahkah mène un clan loup-garou et agit en chaman auprès des spectres et des esprits naturels.','Parler aux esprits ne les commande pas automatiquement ; le clan suit ses propres contraintes et ses liens à Talatuwa.'],
  ['pnj-crawlers-antisysteme-p19-kimmy-oromigna',[8,8,10,11,11],[['Force Mentale',17],['Diplomatie',16],['Autorité',14]],'Erytheia est une Hespéride et une dryade, esprit de la nature servant Gaïa ; son écorce devient rouge sang sous forme révélée.','Son inconstance gêne son commandement ; les esprits naturels terriens ne sont pas ceux importés d’Aèr.'],
  ['pnj-crawlers-antisysteme-p27-ashkii-goldrain',[17,13,13,15,9],[['Pugilat',23],['Constitution',22],['Autorité',20]],'Ashkii est Quinametli, Dive de la seconde ère et fils de Tartare, survivant des guerres qui ont déchiré son peuple.','Sa filiation ne lui confère pas le Mageius de son frère Typhon ni le contrôle immédiat de ses anciennes amazones.'],
  ['pnj-crawlers-antisysteme-p33-yegpor-karamov',[6,6,15,13,8],[['Savoirs',20],['Mécanique',18],['Soin',17]],'Yegpor a éveillé les yeux d’or et développé le projet Phoenix en combinant réanimation et robotisation de soldats.','Lydia n’a pas été ressuscitée ; chaque retour exige corps, procédure et moyens techniques, et ne devient jamais un sort sans condition.'],
  ['pnj-crawlers-antisysteme-p44-adalyn-owens-peacock',[9,9,11,12,10],[['Diplomatie',18],['Force Mentale',17],['Pugilat',15]],'Adalyn est un Angelus de Gabrielle qui sème la discorde par des indices et des manipulations entre proches.','Son influence a échoué sur Bartram : une volonté résistante et un lien éprouvé imposent une opposition réelle.'],
  ['pnj-crawlers-antisysteme-p48-zaketa-harris',[9,9,11,12,11],[['Force Mentale',18],['Survie',17],['Autorité',16]],'Zaketa est le Baron Moteur, Guédé psychopompe qui recueille les âmes des morts de la route.','Sa moto et son corbillard doivent être disponibles ; le passage des âmes relève de sa charge et ne vaut pas domination de tous les morts.'],
  ['pnj-crawlers-antisysteme-p49-toxicity-norton',[10,10,12,13,9],[['Pugilat',19],['Force Mentale',19],['Survie',17]],'Roshielle, séraphine d’Azrael, possède Toxicity ; son poison céleste atteint l’âme après une blessure suffisamment grave.','Le poison exige une blessure et une résistance ; il ne neutralise ni les pouvoirs ni les ennemis au simple contact.'],
  ['pnj-crawlers-antisysteme-p50-miyashiro-kamiko',[11,10,14,13,12],[['Autorité',20],['Force Mentale',19],['Mêlée',18]],'Kamiko porte Bune, duchesse daemon de Belial, qui exalte le courage et l’éloquence de ceux qu’elle bénit.','Les bénédictions supposent une cible et une scène ; Bune ne possède pas les domaines de Belial ni un dragon permanent à trois têtes.'],
  ['pnj-crawlers-antisysteme-p53-meilir-yarwood',[9,10,14,12,8],[['Savoirs',20],['Perception',18],['Pilotage',16]],'Meilir est Munin, très ancien kelta corbeau voué à Morrighan, dont la mémoire ordonnée lui permet de préparer ses confrontations.','Sa mémoire dépend de ce qu’il a appris ; elle ne révèle ni les secrets futurs ni l’emplacement instantané d’une cible.'],
  ['pnj-crawlers-antisysteme-p57-kylon-smithgerald',[11,10,9,10,7],[['Survie',17],['Tir',16],['Athlétisme',15]],'Kylon est Tritorson, triton guerrier d’Amphitrite, lié aux peuples aquatiques et à leurs règles de nom.','Sa parenté aquatique n’offre pas l’autorité d’Amphitrite ni une armée de nymphes en dehors de leur milieu.'],
  ['pnj-crawlers-antisysteme-p57-ryan-oakson',[11,10,10,11,7],[['Tir',18],['Survie',18],['Autorité',16]],'Ryan est Naasif, janissaire vampirisé au XVIIe siècle et chevalier de l’Alghul chargé de protection et de conquête.','La défense des cités sous-marines demande un lieu et des moyens ; il ne commande pas toute la cour Alghul.'],
  ['pnj-crawlers-antisysteme-p58-kassidy-haynes',[11,10,8,10,7],[['Survie',17],['Pugilat',16],['Tir',15]],'Kassidy est une garoue puissante qui préfère sa vie de fermière aux conflits de meute.','Sa Nature ne prouve ni rang de chef ni pouvoir chamanique ; la ferme et ses proches limitent sa disponibilité.'],
  ['pnj-crawlers-antisysteme-p60-niichad-tenford',[12,11,11,12,8],[['Tir',19],['Survie',18],['Force Mentale',17]],'Niichad est Ask-we-da-eed, lampade associée aux comètes, météores, incendies et cratères ; il est aussi un vétéran de guerre décoré.','Son domaine igné n’appelle pas automatiquement une météorite ; ses liens à Nana et les vétérans demandent leur propre mobilisation.'],
  ['pnj-crawlers-antisysteme-p61-lyric-harvey',[8,8,16,14,11],[['Force Mentale',22],['Savoirs',20],['Furtivité',18]],'Lyric est une mage skinwalker qui greffe des parties de son corps et conserve son Mageius lors d’un transfert de cerveau.','Le transfert est douloureux et irréversible pour le cerveau ; il exige des corps accessibles et ne copie pas le Mageius du donneur.'],
  ['pnj-crawlers-antisysteme-p61-kono-mc-larson',[7,7,7,8,8],[['Force Mentale',15],['Survie',14],['Autorité',12]],'Kono est un dhampire de Skenandoa, catalyseur qui amplifie brièvement ses Dons et ceux des vampires proches après activation par le Sang.','Sans boire de Sang, il a presque aucun Don ; amplification brève ne signifie ni autonomie ni puissance illimitée.'],
  ['pnj-crawlers-antisysteme-p62-shaynida-kean',[12,11,13,14,9],[['Force Mentale',19],['Pugilat',18],['Diplomatie',17]],'Shaynida est une fille de Gaïa, nymphe pacifiste que le dossier présente comme redoutable en combat malgré son refus du conflit.','Sa force ne change pas son pacifisme ; son emprise sur Alayna repose sur un chantage, pas un contrôle surnaturel automatique.'],
  ['pnj-crawlers-antisysteme-p63-sim-hyun-ki',[9,10,10,10,7],[['Survie',17],['Perception',16],['Tir',15]],'Sim est un Talass Ki-49 qui a survécu à la guerre et s’oppose aujourd’hui au REPTILE et aux altérations climatiques.','Son origine talass n’implique pas les modifications les plus agressives de l’Émeraude sanglante.'],
  ['pnj-crawlers-antisysteme-p66-grace-drusilla-mannan',[10,10,11,12,8],[['Pugilat',18],['Force Mentale',17],['Survie',16]],'Grace est une Nephilim de Manakielle qui chasse dans sa communauté et peut contrer des pouvoirs d’Angelus simples, surtout ceux de Gabrielle.','L’annulation demande une opposition et ne supprime pas par défaut les pouvoirs d’un Archange ou de tous les Angelus.'],
  ['pnj-crawlers-antisysteme-p67-delicacy-jarah-mannan',[13,10,12,13,11],[['Pugilat',20],['Force Mentale',19],['Diplomatie',18]],'Delicacy est une autre Nephilim de Manakielle, manipulatrice et dotée d’une force physique considérable ; elle contrarie des Angelus simples.','Sa puissance physique ne remplace pas l’opposition de leurs pouvoirs ; son ascendance ne donne pas les prérogatives complètes de Manakielle.'],
  ['pnj-crawlers-antisysteme-p69-pakanga-pikari',[9,10,17,14,10],[['Savoirs',22],['Force Mentale',21],['Mécanique',19]],'Pakanga est un mage arthropodomancien majeur de Nouvelle-Zélande qui fabrique des exosquelettes animés à partir de minéraux et altère son corps.','Créer une carapace exige matière et magie en scène ; ses Amazones et les sorciers Mola mola ne sont pas un équipement personnel.'],
  ['pnj-crawlers-antisysteme-p70-saurona-maxima-drakontos',[13,12,10,11,12],[['Autorité',20],['Pugilat',19],['Diplomatie',18]],'Saurona est une matriarche Xewenne athlétique et guerrière qui entretient l’Alliance rouge et contrôle la branche du Dragon des étoiles.','La vénération de Shaoggith et le nom de sa branche ne la transforment pas en dragon ; son augmentation supposée reste non confirmée.'],
  ['pnj-crawlers-antisysteme-p71-apepia-xii-white',[9,10,18,16,11],[['Savoirs',24],['Force Mentale',23],['Investigation',20]],'Apepia est la douzième incarnation d’Apep, mage de la loge capable de préparer un corps et d’y transférer souvenirs et Mageius.','La survie par réincarnation demande corps préparé et rite ; elle n’est ni instantanée ni sans coût pour l’hôte.'],
  ['pnj-crawlers-antisysteme-p71-zigmars-vilks',[13,11,11,13,8],[['Mêlée',20],['Survie',19],['Force Mentale',18]],'Zigmars, héritier sauroctone rejeté, porte une marque de corruption et une mue de Rulfam ; il sert Shaoggith et traque les Fléaux.','Il ne possède pas Nahfr, l’armure qu’il convoitait ; la mue et le sceau ne lui donnent pas tous les pouvoirs de Shaoggith.'],
];

export const REVIEWED_TRUTH_BATCH_007_IDS=choices.map(choice=>choice[0]);
export function applyPnjTruthBatch007(byId:Map<string,TruthBatchArticle>):void {
  applyPnjTruthDecisions(byId,choices);
}
