<script setup lang="ts">
import {builderPurchaseAllowed} from "../../../../api/src/rules/builder-equipment-policy";
import {computed,ref} from 'vue';
import {cloneJson} from '../../lib/json';
import {ensureRealityState,realityItemMap,realityPriceSpec,type RealityRulesPackage} from '../../lib/reality';
import {activeBenefit,benefitSettings,setBenefitSettings,benefitProblems,grantLoan,returnLoan,loanLabel,loanBudget,loanSpent,loanItemReason,loanAvailabilityReason,grantAdditionalSupport,clearAdditionalSupport,grantReligiousHousing,clearGrant,isHousing,isLoan,referencePrice} from '../../lib/reality-benefits';
const props=defineProps<{modelValue:Record<string,unknown>;rules:RealityRulesPackage;talentIds:string[];sphereId:string;campaign?:boolean;disadvantages?:string[]}>();
const emit=defineEmits<{'update:modelValue':[value:Record<string,unknown>]}>();
const state=computed(()=>ensureRealityState(cloneJson(props.modelValue)));
const settings=computed(()=>benefitSettings(state.value));
const map=computed(()=>realityItemMap(props.rules));
const loanIds=computed(()=>['dotation_standard','dotation_de_service','armurier_du_milieu','programme_pilote'].filter(id=>activeBenefit(id,props.talentIds,props.sphereId)));
const canExtra=computed(()=>activeBenefit('avantages_salaries',props.talentIds,props.sphereId));
const canInsure=computed(()=>activeBenefit('assurance_corporative',props.talentIds,props.sphereId));
const canHouse=computed(()=>activeBenefit('hebergement_religieux',props.talentIds,props.sphereId));
const warnings=computed(()=>benefitProblems(state.value,props.rules,props.talentIds,props.sphereId));
const picks=ref<Record<string,string>>({}),searches=ref<Record<string,string>>({}),authorized=ref<Record<string,boolean>>({});
const error=ref(''),prototype=ref(''),housing=ref(''),housingConfirmed=ref(false);
const supportType=ref<'housing'|'vehicle'>('housing'),supportItem=ref('');
const show=computed(()=>loanIds.value.length||canExtra.value||canInsure.value||canHouse.value);
const assets=computed(()=>[...state.value.equipment,...state.value.augmentations].filter(p=>!isLoan(p)));
const housingOptions=computed(()=>props.rules.recurring.filter(isHousing).sort((a,b)=>a.name.localeCompare(b.name,'fr')));
const supportOptions=computed(()=>(supportType.value==='housing'?housingOptions.value:props.rules.equipment.filter(i=>i.vehicle)).filter(i=>i.id!==state.value.sphereSupportItemId).sort((a,b)=>a.name.localeCompare(b.name,'fr')));
function options(id:string){const q=(searches.value[id]??'').toLocaleLowerCase('fr');return props.rules.equipment.filter(i=>builderPurchaseAllowed(i)&&!loanItemReason(i,id)&&(loanBudget(id)===null||(realityPriceSpec(i).defaultCost??Infinity)<=Number(loanBudget(id))-loanSpent(state.value,props.rules,id))&&!(i.neuro&&props.disadvantages?.includes('unsinkable'))&&(!q||`${i.name} ${i.category}`.toLocaleLowerCase('fr').includes(q))).sort((a,b)=>a.name.localeCompare(b.name,'fr'));}
function commit(fn:(value:ReturnType<typeof ensureRealityState>)=>void){try{const next=ensureRealityState(cloneJson(props.modelValue));fn(next);error.value='';emit('update:modelValue',next as unknown as Record<string,unknown>);}catch(e){error.value=e instanceof Error?e.message:'Modification impossible.';}}
function blocked(id:string){const item=props.rules.equipment.find(i=>i.id===picks.value[id]);return item?loanAvailabilityReason(state.value,props.rules,id,item):'Choisir un modèle.';}
function add(id:string){if(!authorized.value[id]||blocked(id))return;commit(s=>{const selected=options(id).find(i=>i.id===picks.value[id]);if(!selected)throw new Error('Matériel incompatible.');grantLoan(s,props.rules,id,selected.id,props.talentIds,props.sphereId,!!props.campaign,prototype.value||settings.value.prototypeEffect);if(id==='programme_pilote')setBenefitSettings(s,{prototypeEffect:prototype.value||settings.value.prototypeEffect});});}
function remove(uid:string){commit(s=>{returnLoan(s,uid);});}
function support(){commit(s=>grantAdditionalSupport(s,props.rules,supportType.value,supportItem.value,props.talentIds,props.sphereId,!!props.campaign));}
function insure(value:string){if(value&&!assets.value.some(p=>p.uid===value))return;commit(s=>setBenefitSettings(s,{insuredAssetUid:value}));}
function religiousHousing(){if(!housingConfirmed.value)return;commit(s=>grantReligiousHousing(s,props.rules,housing.value,props.talentIds,props.sphereId,!!props.campaign));}
function money(value:number|null){return value===null?'fiche expérimentale':new Intl.NumberFormat('fr-FR').format(value)+' $';}
</script>
<template>
  <details v-if="show" class="benefits-panel" open data-reality-benefits>
    <summary><strong>Avantages matériels des Talents</strong><span>{{ warnings.length ? 'Choix à compléter' : 'Choix enregistrés' }}</span></summary>
    <p>Ces moyens sont distincts de vos achats. Les prêts coûtent 0 $, restent restituables et ne peuvent pas être revendus. Les accréditations fictionnelles ne changent aucun droit joueur ou MJ du site.</p>
    <p v-if="error" class="benefit-warning" role="alert">{{ error }}</p>
    <p v-for="warning in warnings" :key="warning" class="benefit-warning">{{ warning }}</p>
    <section v-for="id in loanIds" :key="id" class="benefit-block" :data-loan="id">
      <h3>{{ loanLabel(id) }}</h3><p v-if="loanBudget(id)!==null">Valeur confiée : {{ money(loanSpent(state,rules,id)) }} / {{ money(loanBudget(id)) }}.</p>
      <p v-else>Un prototype prêté, une fonction expérimentale approuvée avec le MJ. Les contraintes d’utilisation du modèle restent applicables.</p>
      <div class="benefit-grid"><label>Rechercher le matériel<input v-model="searches[id]" type="search" placeholder="Nom ou catégorie" /></label><label>Modèle confié<select v-model="picks[id]"><option value="">— Choisir —</option><option v-for="item in options(id)" :key="item.id" :value="item.id">{{ item.name }} · {{ money(realityPriceSpec(item).defaultCost) }}</option></select></label></div>
      <label v-if="id==='programme_pilote'">Fonction expérimentale, limites et validation MJ<textarea v-model="prototype" :placeholder="settings.prototypeEffect || 'Modèle et programme ; une fonction précise (+2 ciblé, fonction spécifique…) ; limites validées.'" rows="3"></textarea></label>
      <label class="benefit-confirm"><input v-model="authorized[id]" type="checkbox" /> Ce matériel est autorisé par ma fonction et par les conditions du prêt convenues avec le MJ.</label>
      <button type="button" class="secondary compact" :disabled="!picks[id]||!authorized[id]||!!blocked(id)" @click="add(id)">Recevoir le prêt · 0 $</button><p v-if="picks[id] && blocked(id)" role="status">{{ blocked(id) }}</p>
      <div v-for="p in state.equipment.filter(p=>p.talentGrant===id)" :key="p.uid" class="benefit-owned"><div><strong>{{ map.get(p.itemId)?.name || p.itemId }}</strong><span>Prêt non revendable · valeur {{ money(referencePrice(p,map.get(p.itemId))) }}</span><p v-if="p.loanEffect">{{ p.loanEffect }}</p></div><button type="button" class="ghost compact" @click="remove(p.uid)">Restituer</button></div>
    </section>
    <section v-if="canExtra" class="benefit-block" data-additional-support><h3>Avantages salariés · deuxième Appui</h3><p>Une deuxième prestation de même régime que le premier Appui, sans facturer deux fois un logement ni rembourser rétroactivement un véhicule acheté.</p><div class="benefit-grid"><label>Type du deuxième Appui<select v-model="supportType" @change="supportItem=''"><option value="housing">Logement de fonction</option><option value="vehicle">Véhicule de fonction</option></select></label><label>Prestation supplémentaire<select v-model="supportItem"><option value="">— Choisir —</option><option v-for="item in supportOptions" :key="item.id" :value="item.id">{{ item.name }} · {{ item.priceLabel }}</option></select></label></div><button type="button" class="secondary compact" :disabled="!supportItem" @click="support">Affecter le deuxième Appui</button><div v-if="settings.additionalSupportItemId" class="benefit-owned"><span>{{ map.get(settings.additionalSupportItemId)?.name || rules.recurring.find(i=>i.id===settings.additionalSupportItemId)?.name || settings.additionalSupportItemId }} · pris en charge</span><button type="button" class="ghost compact" @click="commit(clearAdditionalSupport)">Retirer cet Appui</button></div></section>
    <section v-if="canInsure" class="benefit-block" data-insured-asset><h3>Assurance corporative · bien garanti</h3><label>Bien personnel assuré<select :value="settings.insuredAssetUid" @change="insure(($event.target as HTMLSelectElement).value)"><option value="">— Choisir un bien réellement possédé —</option><option v-if="settings.insuredAssetUid&&!assets.some(p=>p.uid===settings.insuredAssetUid)" :value="settings.insuredAssetUid" disabled>Ancien bien indisponible · couverture à revoir</option><option v-for="p in assets" :key="p.uid" :value="p.uid">{{ map.get(p.itemId)?.name || p.itemId }} · {{ p.kind==='augmentation'?'augmentation':'équipement' }} · {{ p.uid.slice(-6) }}</option></select></label><p>Une remise en état ou un remplacement à fonction et gamme équivalentes par scénario, après dommages opérationnels. Choix préalable aux dommages ; aucun paiement ni duplicata automatique.</p></section>
    <section v-if="canHouse" class="benefit-block" data-religious-housing><h3>Hébergement religieux · base permanente</h3><label>Logement simple mis à disposition<select v-model="housing"><option value="">— Choisir —</option><option v-for="item in housingOptions" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><label class="benefit-confirm"><input v-model="housingConfirmed" type="checkbox" /> Hébergement simple réellement fourni par l’implantation, pour moi et jusqu’à deux compagnons.</label><button type="button" class="secondary compact" :disabled="!housing||!housingConfirmed" @click="religiousHousing">Prendre en charge ce logement</button><div v-if="settings.religiousHousingId" class="benefit-owned"><span>{{ rules.recurring.find(i=>i.id===settings.religiousHousingId)?.name || settings.religiousHousingId }} · 0 $/mois</span><button type="button" class="ghost compact" @click="commit(s=>{clearGrant(s,'hebergement_religieux');setBenefitSettings(s,{religiousHousingId:''});})">Retirer l’hébergement</button></div></section>
  </details>
</template>
<style scoped>
.benefits-panel{min-width:0;padding:18px;border:1px solid #36536b;border-radius:8px;background:#101e30;color:#edf4ff;margin:16px 0}.benefits-panel summary{display:flex;justify-content:space-between;gap:16px;cursor:pointer;min-height:44px;align-items:center}.benefits-panel p,.benefit-owned span{color:#b3c5d9;line-height:1.6;font-size:14px}.benefit-block{border-top:1px solid #36536b;margin-top:18px;padding-top:14px}.benefit-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.benefit-block label{display:grid;gap:8px;margin:10px 0}.benefit-block input,.benefit-block select,.benefit-block textarea{box-sizing:border-box;width:100%;min-width:0;min-height:44px;padding:10px;background:#08131f;color:#edf4ff;border:1px solid #36536b;border-radius:6px;font:inherit}.benefit-block .benefit-confirm{display:flex;align-items:center;gap:12px}.benefit-confirm input{width:22px;flex:0 0 22px}.benefit-owned{display:flex;justify-content:space-between;gap:14px;align-items:center;margin:12px 0;padding:12px;border:1px solid #36536b;border-radius:6px}.benefit-owned>div{display:grid;gap:6px;min-width:0;overflow-wrap:anywhere}.benefits-panel .benefit-warning{color:#f1c38b}.benefit-block button{min-height:44px;margin:8px 0}@media(max-width:650px){.benefit-grid{grid-template-columns:1fr}.benefit-owned{align-items:stretch;flex-direction:column}}
</style>
