// Alias de lecture du Compendium V2 : les cibles doivent appartenir au corpus actif.
// Le linker vérifie leur présence dans l’index filtré selon les droits du lecteur.

export const WIKI_EXPLICIT_TARGETS = {
  'Réalité': 'realite-v9-grande-californie-2035',
  'Guide de la Réalité': 'realite-v9-grande-californie-2035',
  'Réalité — Guide du nouveau joueur': 'realite-v9-grande-californie-2035',
  'Grande Californie': 'realite-v9-grande-californie-2035',
  'Vérité': 'verite-v7-derriere-le-voile',
  'Guide de la Vérité': 'verite-v7-derriere-le-voile',
  'Vérité — Guide du nouveau joueur': 'verite-v7-derriere-le-voile',
  'Entrer dans la Vérité': 'verite-v7-derriere-le-voile',
  'se révéler à la Vérité': 'verite-v7-derriere-le-voile',
  'Se révéler': 'verite-v7-derriere-le-voile',
  'Éveil': 'verite-v7-derriere-le-voile',
  'Voir sous le Voile': 'verite-v7-voile-hologramme',
  'Voilé': 'verite-v7-voile-hologramme',
  'Semi-Révélé': 'verite-v7-voile-hologramme',
  'Semi-Révélée': 'verite-v7-voile-hologramme',
  'Révélé': 'verite-v7-voile-hologramme',
  'Révélée': 'verite-v7-voile-hologramme',
  'Semi-Révélation': 'verite-v7-voile-hologramme',
  'Révélation': 'verite-v7-voile-hologramme',
  'Révéler sa Nature': 'verite-v7-voile-hologramme',
  'Voile': 'verite-v7-voile-hologramme',
  'Hologramme': 'verite-v7-voile-hologramme',
  'Divinité': 'verite-v7-daemons-divinites-maisonnees-temples',
  'Divinités': 'verite-v7-daemons-divinites-maisonnees-temples',
  'Anciennes Divinités': 'verite-v7-daemons-divinites-maisonnees-temples',
  'Vampire': 'verite-v7-vampires-civilisation-cours-sangs',
  'Vampires': 'verite-v7-vampires-civilisation-cours-sangs',
  'Garou': 'verite-v7-garous-khinae-meutes-pelages',
  'Garous': 'verite-v7-garous-khinae-meutes-pelages',
  'Loups-garous': 'verite-v7-garous-khinae-meutes-pelages',
  'loups garous': 'verite-v7-garous-khinae-meutes-pelages',
  'Descendant de Khinae': 'verite-v7-descendants-khinae',
  'Descendants de Khinae': 'verite-v7-descendants-khinae',
  'Khinae': 'verite-v7-descendants-khinae',
  'Khinae corrompus': 'verite-v7-descendants-khinae',
  'Loups descendants de Khinae': 'verite-v7-garous-khinae-meutes-pelages',
  'Autres descendants de Khinae': 'verite-v7-descendants-khinae',
  'Mage': 'verite-v7-mages-mageius-roue-loges',
  'Mages': 'verite-v7-mages-mageius-roue-loges',
  'Daemon': 'verite-v7-daemons-divinites-maisonnees-temples',
  'Daemons': 'verite-v7-daemons-divinites-maisonnees-temples',
  'Angelus': 'verite-v7-angelus-elynea-arbre-vie',
  'Aseryn': 'verite-v7-aseryns-serathe-atlantide-treize',
  'Aseryns': 'verite-v7-aseryns-serathe-atlantide-treize',
  'Exilé': 'verite-v7-exiles-peuples-silcenters-traditions',
  'Exilés': 'verite-v7-exiles-peuples-silcenters-traditions',
  'Extral': 'verite-v7-extrals-gaac-aidh-diasporas',
  'Extrals': 'verite-v7-extrals-gaac-aidh-diasporas',
  'Homo Superior': 'verite-v7-homo-superior-adrak-profils-rares',
  'Aèr': 'verite-v7-exiles-peuples-silcenters-traditions',
  'Aër': 'verite-v7-exiles-peuples-silcenters-traditions',
  'AIDH': 'verite-humanite-galactique-aidh',
  'Néant': 'verite-v7-cycle-neant-ombremonde-histoire-cachee',
  'Cycle': 'verite-v7-cycle-neant-ombremonde-histoire-cachee',
  'Neant': 'verite-v7-cycle-neant-ombremonde-histoire-cachee',
  'Cycle & Néant': 'verite-v7-cycle-neant-ombremonde-histoire-cachee',
  'Cycle et Néant': 'verite-v7-cycle-neant-ombremonde-histoire-cachee',
  'Cycle, le Néant': 'verite-v7-cycle-neant-ombremonde-histoire-cachee',
  'Magitech': 'verite-v7-cycle-neant-ombremonde-histoire-cachee',
  'Calamitechnologie': 'verite-catalogue-229-equipement-corrompu-et-calamitechnologie-principes',
  'Ad’rak': 'verite-v7-homo-superior-adrak-profils-rares',
  "Ad'rak": 'verite-v7-homo-superior-adrak-profils-rares',
  'Chasseur': 'verite-v7-chasseurs-doctrine-association-traditions',
  'Chasseurs': 'verite-v7-chasseurs-doctrine-association-traditions',
  'Sang Chasseur': 'regles-verite-v7-garou-sangs-vifs',
  'Fléau': 'verite-v7-six-fleaux-sources-rupture',
  'Fléaux': 'verite-v7-six-fleaux-sources-rupture',
  'Corruption': 'verite-v7-six-fleaux-sources-rupture',
  'Souillure': 'verite-v7-six-fleaux-sources-rupture',
  'Temples Daemoniaques': 'verite-v7-daemons-divinites-maisonnees-temples',
  'Cours vampiriques': 'verite-v7-vampires-civilisation-cours-sangs',
  'Pelages': 'verite-v7-garous-khinae-meutes-pelages',
  'Loges des Mages': 'verite-v7-mages-mageius-roue-loges',
  'Arbre de Vie': 'verite-v7-angelus-elynea-arbre-vie',
  'Temples Aseryns': 'verite-v7-aseryns-serathe-atlantide-treize',
  'Grands Exilés': 'verite-v7-exiles-peuples-silcenters-traditions',
  'Abigor': 'verite-v7-daemons-divinites-maisonnees-temples',
  'Alabor': 'verite-v7-daemons-divinites-maisonnees-temples',
  'Astaroth': 'verite-v7-daemons-divinites-maisonnees-temples',
  'Baal': 'verite-v7-daemons-divinites-maisonnees-temples',
  'Belial': 'verite-v7-daemons-divinites-maisonnees-temples',
  'Bélial': 'verite-v7-daemons-divinites-maisonnees-temples',
  'Belzébuth': 'verite-v7-daemons-divinites-maisonnees-temples',
  'Belzebuth': 'verite-v7-daemons-divinites-maisonnees-temples',
  'Beelzebuth': 'verite-v7-daemons-divinites-maisonnees-temples',
  'Diablo': 'verite-v7-daemons-divinites-maisonnees-temples',
  'Lilith': 'verite-v7-daemons-divinites-maisonnees-temples',
  'Lucifer': 'verite-v7-daemons-divinites-maisonnees-temples',
  'Mammon': 'verite-v7-daemons-divinites-maisonnees-temples',
  'Méphisto': 'verite-v7-daemons-divinites-maisonnees-temples',
  'Mephisto': 'verite-v7-daemons-divinites-maisonnees-temples',
  'Morrighan': 'verite-v7-daemons-divinites-maisonnees-temples',
  'Satan': 'verite-v7-daemons-divinites-maisonnees-temples',
  'Los Angeles': 'realite-v9-los-angeles-laus-securites',
  'LAUS': 'realite-v9-los-angeles-laus-securites',
  'Pègre': 'realite-v9-pegre-mafias-gangs',
  'Crawlers': 'realite-v9-crawlers-underlife',
  'Underlife': 'realite-v9-crawlers-underlife',
  'Vladivostokskaïa': 'realite-v9-vladivostokskaia',
  'Vladivostokskaia': 'realite-v9-vladivostokskaia',
  'Neurodive': 'regles-realite-v9-neurodive-principes-rang',
  'Ombremonde': 'verite-v7-cycle-neant-ombremonde-histoire-cachee',
  "L'Ombremonde": 'verite-v7-cycle-neant-ombremonde-histoire-cachee',
  'L’Ombremonde': 'verite-v7-cycle-neant-ombremonde-histoire-cachee',
  'GAAC': 'verite-extrals-gaac'
};

export const WIKI_SEARCH_FALLBACKS=['Revenants','Katanja'];

export const WIKI_STRICT_SURFACE_ALIASES=['Réalité','Vérité','Voilé','Semi-Révélé','Semi-Révélée','Révélé','Révélée','Semi-Révélation','Révélation','Corruption'];
export const WIKI_CASE_SENSITIVE_ALIASES=['Réalité','Vérité','Voile','Hologramme','Voilé','Semi-Révélé','Semi-Révélée','Révélé','Révélée','Semi-Révélation','Révélation','Éveil','Corruption','Chasseur','Chasseurs','Fléau','Fléaux','Cycle'];
